#!/usr/bin/env python
"""
seed_coa_related_parties.py — extend the chart of accounts with entity-
prefixed accounts for the 10 group subsidiaries' Trial Balances.

Each row has a code like "QIH-101401" — namespacing by entity prevents
collisions where the same numeric code means different things in
different sets of books (e.g. Quantum's 201002 = WHT Payable vs ADIC's
201002 = Receivable from Risk SW).

Run:
    python manage.py shell < ops/seeds/seed_coa_related_parties.py

Idempotent.
"""
from django.db import transaction
from ledger.models import Account
from core.models import Currency

# (code, name, account_type, sub_type, is_bank_account)
ACCOUNTS_RP = [
    ('QIH-101401', '[QIH] QIHL FNB Current Account', 'asset', 'bank', True),
    ('QIH-101402', '[QIH] QIHL FNB Call AC', 'asset', 'bank', True),
    ('QIH-110301', '[QIH] Loan to Shareholders', 'asset', 'current_asset', False),
    ('QIH-121000', '[QIH] Account Receivable', 'asset', 'current_asset', False),
    ('QIH-121001', '[QIH] Investment In Alpha Direct', 'asset', 'fixed_asset', False),
    ('QIH-121002', '[QIH] Investment In Veritas', 'asset', 'fixed_asset', False),
    ('QIH-121003', '[QIH] Investment In Risk Software', 'asset', 'fixed_asset', False),
    ('QIH-121004', '[QIH] Investment In Alpha Direct South Africa', 'asset', 'fixed_asset', False),
    ('QIH-121006', '[QIH] Investment In Gabs Coin Exchange', 'asset', 'fixed_asset', False),
    ('QIH-121007', '[QIH] Investment In Alpha Direct Life', 'asset', 'fixed_asset', False),
    ('QIH-121008', '[QIH] Investment In ADRisk Global Solutions', 'asset', 'fixed_asset', False),
    ('QIH-121100', '[QIH] Receivable From Alpha Singapore', 'asset', 'current_asset', False),
    ('QIH-121200', '[QIH] Receivable from Alpha Botswana', 'asset', 'current_asset', False),
    ('QIH-121300', '[QIH] Receivable From Alpha Direct South Africa', 'asset', 'current_asset', False),
    ('QIH-121500', '[QIH] Receivable from Risk Software', 'asset', 'current_asset', False),
    ('QIH-121600', '[QIH] Receivable from GCE', 'asset', 'current_asset', False),
    ('QIH-121700', '[QIH] Receivable from Alpha Life', 'asset', 'current_asset', False),
    ('QIH-131000', '[QIH] Tax Paid', 'asset', 'current_asset', False),
    ('QIH-1330011', '[QIH] Loan given to Alpha Life', 'asset', 'current_asset', False),
    ('QIH-133002', '[QIH] Loans given to Risk Software', 'asset', 'current_asset', False),
    ('QIH-133005', '[QIH] Loans given to Gaborone Coin Exchange', 'asset', 'current_asset', False),
    ('QIH-133007', '[QIH] Payable to Alpha Direct Botswana', 'liability', 'current_liability', False),
    ('QIH-133008', '[QIH] Payable to Risk Software Africa', 'liability', 'current_liability', False),
    ('QIH-133011', '[QIH] Payable to Alpha Singapore', 'liability', 'current_liability', False),
    ('QIH-201002', '[QIH] WHT Payable', 'liability', 'current_liability', False),
    ('QIH-202001', '[QIH] Loan from Singapore', 'liability', 'long_term_liability', False),
    ('QIH-211000', '[QIH] Account Payable', 'liability', 'current_liability', False),
    ('QIH-211001', '[QIH] Interest Payable', 'liability', 'current_liability', False),
    ('QIH-251000', '[QIH] Tax Received', 'asset', 'current_asset', False),
    ('QIH-252000', '[QIH] Tax Payable', 'liability', 'current_liability', False),
    ('QIH-252001', '[QIH] Expense Provision', 'liability', 'provision', False),
    ('QIH-291001', "[QIH] Shareholder's Loans", 'liability', 'long_term_liability', False),
    ('QIH-301000', '[QIH] Capital', 'equity', 'equity', False),
    ('QIH-303000', '[QIH] Retained Earnings', 'equity', 'equity', False),
    ('QIH-400000', '[QIH] Product Sales', 'revenue', 'operating_revenue', False),
    ('QIH-440000', '[QIH] Interest Income', 'revenue', 'other_revenue', False),
    ('QIH-440001', '[QIH] Interest Income from Bank', 'revenue', 'other_revenue', False),
    ('QIH-440002', '[QIH] Interest Income from Related Party', 'revenue', 'other_revenue', False),
    ('QIH-441000', '[QIH] Foreign Exchange Gain', 'revenue', 'other_revenue', False),
    ('QIH-450000', '[QIH] Other Income', 'revenue', 'other_revenue', False),
    ('QIH-600010', '[QIH] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('QIH-613000', '[QIH] Professional Fees', 'expense', 'operating_expense', False),
    ('QIH-613001', '[QIH] Tax Expense', 'expense', 'operating_expense', False),
    ('QIH-613002', '[QIH] Consultancy Fees', 'expense', 'operating_expense', False),
    ('QIH-613010', '[QIH] Legal Fees', 'expense', 'operating_expense', False),
    ('QIH-620000', '[QIH] Bank Fees', 'expense', 'operating_expense', False),
    ('QIH-630000', '[QIH] Salary Expenses', 'expense', 'operating_expense', False),
    ('QIH-642001', '[QIH] Interest Expenses', 'expense', 'operating_expense', False),
    ('VCM-101401', '[VCM] Veritas FNB Current', 'asset', 'bank', True),
    ('VCM-101403', '[VCM] Outstanding Receipts', 'asset', 'current_asset', False),
    ('VCM-101404', '[VCM] Outstanding Payments', 'asset', 'current_asset', False),
    ('VCM-101502', '[VCM] Outstanding Receipts', 'asset', 'current_asset', False),
    ('VCM-102001', '[VCM] Tax Penalties', 'asset', 'current_asset', False),
    ('VCM-110110', '[VCM] Stock - Salvage Vehicle', 'asset', 'current_asset', False),
    ('VCM-110200', '[VCM] Stock Interim (Received)', 'asset', 'current_asset', False),
    ('VCM-110300', '[VCM] Stock Interim (Delivered)', 'asset', 'current_asset', False),
    ('VCM-121000', '[VCM] Account Receivable', 'asset', 'current_asset', False),
    ('VCM-131000', '[VCM] Deferred Tax Assets', 'asset', 'current_asset', False),
    ('VCM-151010', '[VCM] Fixed Asset - Motor Vehicle', 'asset', 'current_asset', False),
    ('VCM-151020', '[VCM] Fixed Asset - Computer', 'asset', 'current_asset', False),
    ('VCM-151030', '[VCM] Fixed Asset - Equipments & Furniture', 'asset', 'current_asset', False),
    ('VCM-152010', '[VCM] Accumulated Depreciation - Motor Vehicle', 'asset', 'fixed_asset', False),
    ('VCM-152020', '[VCM] Accumulated Depreciation - Computer', 'asset', 'fixed_asset', False),
    ('VCM-152030', '[VCM] Accumulated Depreciation - Equipments & Furniture', 'asset', 'fixed_asset', False),
    ('VCM-201010', '[VCM] VAT Control Account', 'liability', 'current_liability', False),
    ('VCM-211000', '[VCM] Account Payable', 'liability', 'current_liability', False),
    ('VCM-253000', '[VCM] Directors Current Liability', 'liability', 'current_liability', False),
    ('VCM-291100', '[VCM] Loan from FNB', 'liability', 'long_term_liability', True),
    ('VCM-301000', '[VCM] Capital', 'equity', 'equity', False),
    ('VCM-303000', '[VCM] Retained Earnings', 'equity', 'equity', False),
    ('VCM-400000', '[VCM] Non-Motor Sales', 'revenue', 'operating_revenue', False),
    ('VCM-400010', '[VCM] Sale of Salvage Vehicles', 'revenue', 'other_revenue', False),
    ('VCM-400020', '[VCM] Sale of Salvage Parts', 'revenue', 'other_revenue', False),
    ('VCM-450000', '[VCM] Other Income', 'revenue', 'other_revenue', False),
    ('VCM-450010', '[VCM] Management Fee', 'revenue', 'other_revenue', False),
    ('VCM-500000', '[VCM] Cost of Goods Sold', 'expense', 'operating_expense', False),
    ('VCM-500010', '[VCM] COGS - Salvage Vehicle', 'expense', 'operating_expense', False),
    ('VCM-500011', '[VCM] COGS - Salvage Adjustments', 'expense', 'operating_expense', False),
    ('VCM-500015', '[VCM] COGS - Provision for Obsolete Stock', 'expense', 'operating_expense', False),
    ('VCM-500030', '[VCM] COGS - Towing Charges', 'expense', 'operating_expense', False),
    ('VCM-600000', '[VCM] General Expenses', 'expense', 'operating_expense', False),
    ('VCM-600010', '[VCM] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('VCM-600020', '[VCM] Bank Charges', 'expense', 'operating_expense', False),
    ('VCM-600040', '[VCM] Depreciation', 'expense', 'operating_expense', False),
    ('VCM-600045', '[VCM] Depreciation (ROU)', 'expense', 'operating_expense', False),
    ('VCM-600050', '[VCM] Motor Vehicle Expenses', 'expense', 'operating_expense', False),
    ('VCM-600060', '[VCM] Printing & Stationary', 'expense', 'operating_expense', False),
    ('VCM-600070', '[VCM] Professional Fees', 'expense', 'operating_expense', False),
    ('VCM-600080', '[VCM] Rent & Rates', 'expense', 'operating_expense', False),
    ('VCM-600081', '[VCM] Rent & Rates - IFRS 16', 'expense', 'operating_expense', False),
    ('VCM-600090', '[VCM] Repairs & Maintenance', 'expense', 'operating_expense', False),
    ('VCM-600100', '[VCM] Salaries', 'expense', 'operating_expense', False),
    ('VCM-600110', '[VCM] Wages', 'expense', 'operating_expense', False),
    ('VCM-600120', '[VCM] Security Expenses', 'expense', 'operating_expense', False),
    ('VCM-600130', '[VCM] Training Levy', 'expense', 'operating_expense', False),
    ('VCM-600140', '[VCM] Telephone', 'expense', 'operating_expense', False),
    ('VCM-600150', '[VCM] Utilities', 'expense', 'operating_expense', False),
    ('VCM-600160', '[VCM] Fuel Usage', 'expense', 'operating_expense', False),
    ('VCM-600170', '[VCM] Fines & Penalties', 'expense', 'operating_expense', False),
    ('VCM-600190', '[VCM] Pick UP truck Rental', 'expense', 'operating_expense', False),
    ('VCM-600200', '[VCM] Garbage Disposal', 'expense', 'operating_expense', False),
    ('VCM-600230', '[VCM] Staff Welfare', 'expense', 'operating_expense', False),
    ('VCM-600240', '[VCM] Disposal Account', 'expense', 'operating_expense', False),
    ('VCM-600250', '[VCM] Loss on Disposal', 'expense', 'operating_expense', False),
    ('VCM-600260', '[VCM] Severance', 'expense', 'operating_expense', False),
    ('VCM-611000', '[VCM] Purchase of Equipments', 'expense', 'operating_expense', False),
    ('VCM-620000', '[VCM] Bank Fees', 'expense', 'operating_expense', False),
    ('VCM-630000', '[VCM] Sales Commissions Expense', 'expense', 'operating_expense', False),
    ('VCM-642000', '[VCM] Cash Difference Loss', 'expense', 'operating_expense', False),
    ('VCM-700000', '[VCM] Interest on FNB Loan', 'expense', 'operating_expense', True),
    ('VCM-700001', '[VCM] Interest on lease - IFRS16', 'expense', 'operating_expense', False),
    ('VCM-700010', '[VCM] Insurance Expense', 'expense', 'operating_expense', False),
    ('VCM-800002', '[VCM] Advance Tax', 'expense', 'operating_expense', False),
    ('VCM-800008', '[VCM] Deferred Tax Expense', 'expense', 'operating_expense', False),
    ('VCM-999999', '[VCM] Undistributed Profits/Losses', 'expense', 'operating_expense', False),
    ('RSA-101401', '[RSA] USD Bank Account', 'asset', 'bank', False),
    ('RSA-101502', '[RSA] FNB Current Account', 'asset', 'bank', True),
    ('RSA-101601', '[RSA] Deposit', 'asset', 'current_asset', False),
    ('RSA-121000', '[RSA] Account Receivable', 'asset', 'current_asset', False),
    ('RSA-121001', '[RSA] Receivable from Alpha Direct', 'asset', 'current_asset', False),
    ('RSA-121002', '[RSA] Investments in Alpha Insurtech Zambia', 'asset', 'current_asset', False),
    ('RSA-121003', '[RSA] Receivable from Alpha Zambia', 'asset', 'current_asset', False),
    ('RSA-121004', '[RSA] Receivable from Quantum', 'asset', 'current_asset', False),
    ('RSA-121005', '[RSA] Receivable from Alpha South Africa', 'asset', 'current_asset', False),
    ('RSA-121006', '[RSA] Receivable from Unicoin', 'asset', 'current_asset', False),
    ('RSA-121007', '[RSA] Receivable from Alpha Singapore', 'asset', 'current_asset', False),
    ('RSA-121009', '[RSA] Receivable from Alpha Life', 'asset', 'current_asset', False),
    ('RSA-121010', '[RSA] Staff Loan', 'asset', 'current_asset', False),
    ('RSA-121011', '[RSA] WHT Receivable', 'asset', 'current_asset', False),
    ('RSA-151002', '[RSA] Computers and Networks', 'asset', 'current_asset', False),
    ('RSA-151002.01', '[RSA] Accumulated Depreciation - Computers and Networks', 'asset', 'fixed_asset', False),
    ('RSA-151003', '[RSA] Risk Software Property', 'asset', 'current_asset', False),
    ('RSA-151004', '[RSA] Display Racks', 'asset', 'current_asset', False),
    ('RSA-151004.01', '[RSA] Accumulated Depreciation - Display Rack', 'asset', 'fixed_asset', False),
    ('RSA-151005', '[RSA] Furniture & Fittings', 'asset', 'current_asset', False),
    ('RSA-151005.01', '[RSA] Accumulated Depreciation - Furniture & Fittings', 'asset', 'fixed_asset', False),
    ('RSA-191001', '[RSA] Graphite Software - Asset', 'asset', 'current_asset', False),
    ('RSA-201001', '[RSA] Deferred Tax Liability', 'liability', 'current_liability', False),
    ('RSA-211000', '[RSA] Account Payable', 'liability', 'current_liability', False),
    ('RSA-211001', '[RSA] Payable to Alpha Singapore', 'liability', 'current_liability', False),
    ('RSA-211002', '[RSA] Payable to Quantum Insurance Holdings', 'liability', 'current_liability', False),
    ('RSA-211003', '[RSA] Payable to Alpha Direct', 'liability', 'current_liability', False),
    ('RSA-211004', '[RSA] Payable to Unicoin', 'liability', 'current_liability', False),
    ('RSA-211006', '[RSA] Severance Payable', 'liability', 'current_liability', False),
    ('RSA-216004', '[RSA] Audit Fees', 'liability', 'current_liability', False),
    ('RSA-251000', '[RSA] Tax Received', 'asset', 'current_asset', False),
    ('RSA-252000', '[RSA] Tax Payable', 'liability', 'current_liability', False),
    ('RSA-252001', '[RSA] WHT Payable', 'liability', 'current_liability', False),
    ('RSA-252002', '[RSA] Payee Payable', 'liability', 'current_liability', False),
    ('RSA-252100', '[RSA] VAT Control AC', 'liability', 'current_liability', False),
    ('RSA-291100', '[RSA] Loan from Related Company', 'liability', 'long_term_liability', False),
    ('RSA-291101', '[RSA] Loan from Alpha Direct Insurance', 'liability', 'long_term_liability', False),
    ('RSA-291102', '[RSA] Loan from Quantum Insurance Holdings', 'liability', 'long_term_liability', False),
    ('RSA-291103', '[RSA] Loan to Alpha Zimbabwe', 'liability', 'current_liability', False),
    ('RSA-301000', '[RSA] Capital', 'equity', 'equity', False),
    ('RSA-303000', '[RSA] Retained Earnings', 'equity', 'equity', False),
    ('RSA-400000', '[RSA] Product Sales', 'revenue', 'operating_revenue', False),
    ('RSA-400010', '[RSA] Software Maintenance Income - GFS', 'revenue', 'other_revenue', False),
    ('RSA-450000', '[RSA] Other Income', 'revenue', 'other_revenue', False),
    ('RSA-450001', '[RSA] Fixed Asset Disposal', 'revenue', 'other_revenue', False),
    ('RSA-500000', '[RSA] Cost of Goods Sold', 'expense', 'operating_expense', False),
    ('RSA-500010', '[RSA] Software Maintenance Expenses - Avatar', 'expense', 'operating_expense', False),
    ('RSA-600000', '[RSA] Expenses', 'expense', 'operating_expense', False),
    ('RSA-600001', '[RSA] Cell Phone Expenses', 'expense', 'operating_expense', False),
    ('RSA-600002', '[RSA] Cellphone Usage', 'expense', 'operating_expense', False),
    ('RSA-600003', '[RSA] Deferred Tax Expenses', 'expense', 'operating_expense', False),
    ('RSA-600004', '[RSA] Petty Cash Transfer to Unicoin', 'expense', 'operating_expense', True),
    ('RSA-600010', '[RSA] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('RSA-611000', '[RSA] Purchase of Equipments', 'expense', 'operating_expense', False),
    ('RSA-611001', '[RSA] Risk Software IT Equipment Purchases', 'expense', 'operating_expense', False),
    ('RSA-612000', '[RSA] Rent', 'expense', 'operating_expense', False),
    ('RSA-612001', '[RSA] Utilities', 'expense', 'operating_expense', False),
    ('RSA-612002', '[RSA] Printing, Postage & Stationary', 'expense', 'operating_expense', False),
    ('RSA-612003', '[RSA] Office Expenses', 'expense', 'operating_expense', False),
    ('RSA-612004', '[RSA] Training Levy Expense', 'expense', 'operating_expense', False),
    ('RSA-613000', '[RSA] Promotional Expenses', 'expense', 'operating_expense', False),
    ('RSA-613001', '[RSA] Donations & Charity', 'expense', 'operating_expense', False),
    ('RSA-614000', '[RSA] Salary Expenses', 'expense', 'operating_expense', False),
    ('RSA-614001', '[RSA] Consultancy Fees', 'expense', 'operating_expense', False),
    ('RSA-615000', '[RSA] Travel Expenses', 'expense', 'operating_expense', False),
    ('RSA-615001', '[RSA] Transportation Costs', 'expense', 'operating_expense', False),
    ('RSA-615002', '[RSA] Motor Vehicle Expenses', 'expense', 'operating_expense', False),
    ('RSA-620000', '[RSA] Bank Fees', 'expense', 'operating_expense', False),
    ('RSA-620001', '[RSA] Professional Fee', 'expense', 'operating_expense', False),
    ('RSA-620002', '[RSA] Subscriptions', 'expense', 'operating_expense', False),
    ('RSA-620002.01', '[RSA] Licensing Fee Expense', 'expense', 'operating_expense', False),
    ('RSA-620003', '[RSA] Training & Professional Development', 'expense', 'operating_expense', False),
    ('RSA-620004', '[RSA] Security Services', 'expense', 'operating_expense', False),
    ('RSA-620005', '[RSA] Customer Entertainment', 'expense', 'operating_expense', False),
    ('RSA-641000', '[RSA] Foreign Exchange Loss', 'expense', 'operating_expense', False),
    ('RSA-643000', '[RSA] Taxation', 'expense', 'operating_expense', False),
    ('RSA-644000', '[RSA] Staff Welfare', 'expense', 'operating_expense', False),
    ('RSA-644001', '[RSA] Medical Aid Expenses', 'expense', 'operating_expense', False),
    ('RSA-65000', '[RSA] Finance Costs', 'expense', 'operating_expense', False),
    ('RSA-65001', '[RSA] Finance Income', 'expense', 'operating_expense', False),
    ('RSA-65002', '[RSA] Interest to Quantum', 'expense', 'operating_expense', False),
    ('RSA-65003', '[RSA] Interest to Alpha Insurtech', 'expense', 'operating_expense', False),
    ('RSA-70020', "[RSA] Instant Insurance - Shoes for Reddy's", 'expense', 'operating_expense', False),
    ('RSA-800000', '[RSA] Depreciation Expense', 'expense', 'operating_expense', False),
    ('RSA-960000', '[RSA] Software Development Costs', 'expense', 'operating_expense', False),
    ('RSA-961000', '[RSA] Software Maintenance Costs', 'expense', 'operating_expense', False),
    ('RSA-961200', '[RSA] Repairs and Maintenance', 'expense', 'operating_expense', False),
    ('RSA-962000', '[RSA] Sales Expenses', 'expense', 'operating_expense', False),
    ('RSA-999999', '[RSA] Undistributed Profits/Losses', 'expense', 'operating_expense', False),
    ('ADSA-101001', '[ADSA] Display Racks', 'asset', 'current_asset', False),
    ('ADSA-101001.1', '[ADSA] Accumulated Depreciation - Display Rack', 'asset', 'fixed_asset', False),
    ('ADSA-101401', '[ADSA] Bank', 'asset', 'bank', False),
    ('ADSA-101402', '[ADSA] Bank - Premium Account', 'asset', 'bank', False),
    ('ADSA-101601', '[ADSA] Deposit', 'asset', 'current_asset', False),
    ('ADSA-102001', '[ADSA] Petty Cash', 'asset', 'bank', True),
    ('ADSA-102004', '[ADSA] Subscriptions', 'asset', 'current_asset', False),
    ('ADSA-102005', '[ADSA] Motor Vehicle Expenses', 'asset', 'current_asset', False),
    ('ADSA-121000', '[ADSA] Account Receivable', 'asset', 'current_asset', False),
    ('ADSA-121001', '[ADSA] Receivable from Unicoin', 'asset', 'current_asset', False),
    ('ADSA-151002', '[ADSA] Laptops & Computers', 'asset', 'current_asset', False),
    ('ADSA-151002.1', '[ADSA] Accumulated Depreciation Laptops & Computers', 'asset', 'fixed_asset', False),
    ('ADSA-211000', '[ADSA] Account Payable', 'liability', 'current_liability', False),
    ('ADSA-211001', '[ADSA] Payable to Alpha Direct Botswana', 'liability', 'current_liability', False),
    ('ADSA-211002', '[ADSA] Payable to Quantum Insurance Holdings', 'liability', 'current_liability', False),
    ('ADSA-211003', '[ADSA] Payable to Risk Software', 'liability', 'current_liability', False),
    ('ADSA-211004', '[ADSA] Payable to Unicoin', 'liability', 'current_liability', False),
    ('ADSA-251000', '[ADSA] Tax Received', 'asset', 'current_asset', False),
    ('ADSA-301000', '[ADSA] Capital', 'equity', 'equity', False),
    ('ADSA-401000', '[ADSA] Staff Welfare', 'revenue', 'other_revenue', False),
    ('ADSA-445000', '[ADSA] NMI Binder fee', 'revenue', 'other_revenue', False),
    ('ADSA-445001', '[ADSA] Commission Income', 'revenue', 'other_revenue', False),
    ('ADSA-450000', '[ADSA] Other Income', 'revenue', 'other_revenue', False),
    ('ADSA-500000', '[ADSA] Cost of Goods Sold', 'expense', 'operating_expense', False),
    ('ADSA-600001', '[ADSA] Fines & Penalties', 'expense', 'operating_expense', False),
    ('ADSA-600002', '[ADSA] Transportation Costs', 'expense', 'operating_expense', False),
    ('ADSA-600003', '[ADSA] Telephone Costs', 'expense', 'operating_expense', False),
    ('ADSA-600004', '[ADSA] Promotional Expenses', 'expense', 'operating_expense', False),
    ('ADSA-600005', '[ADSA] Training and Professional Development', 'expense', 'operating_expense', False),
    ('ADSA-600006', '[ADSA] Office Expenses', 'expense', 'operating_expense', False),
    ('ADSA-600010', '[ADSA] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('ADSA-600011', '[ADSA] Insurance Expense', 'expense', 'operating_expense', False),
    ('ADSA-600012', '[ADSA] Production cost', 'expense', 'operating_expense', False),
    ('ADSA-600070', '[ADSA] Professional Fees', 'expense', 'operating_expense', False),
    ('ADSA-600080', '[ADSA] Rent & Rates', 'expense', 'operating_expense', False),
    ('ADSA-600090', '[ADSA] Travel Expenses', 'expense', 'operating_expense', False),
    ('ADSA-600091', '[ADSA] Fuel', 'expense', 'operating_expense', False),
    ('ADSA-600092', '[ADSA] Depreciation Expense', 'expense', 'operating_expense', False),
    ('ADSA-612000', '[ADSA] General', 'expense', 'operating_expense', False),
    ('ADSA-612001', '[ADSA] Import Duty', 'expense', 'operating_expense', False),
    ('ADSA-612002', '[ADSA] Printing, Postage and Stationary', 'expense', 'operating_expense', False),
    ('ADSA-620000', '[ADSA] Bank Fees', 'expense', 'operating_expense', False),
    ('ADSA-630000', '[ADSA] Salary Expenses', 'expense', 'operating_expense', False),
    ('ADSA-641000', '[ADSA] Foreign Exchange Loss / (Gain)', 'expense', 'operating_expense', False),
    ('ADSA-650000', '[ADSA] Finance Costs', 'expense', 'operating_expense', False),
    ('ADSA-962001', '[ADSA] Commission Expense', 'expense', 'operating_expense', False),
    ('GCX-101300', '[GCX] Account Receivable - Alpha Direct', 'asset', 'current_asset', False),
    ('GCX-101401', '[GCX] Bank', 'asset', 'bank', False),
    ('GCX-105000', '[GCX] Severance Benefits Payable', 'asset', 'current_asset', False),
    ('GCX-191001', '[GCX] Loan to Shareholders', 'asset', 'current_asset', False),
    ('GCX-201002', '[GCX] WHT Payable', 'liability', 'current_liability', False),
    ('GCX-201003', '[GCX] Income tax payable', 'liability', 'current_liability', False),
    ('GCX-211000', '[GCX] Account Payable', 'liability', 'current_liability', False),
    ('GCX-211001', '[GCX] Interest Payable', 'liability', 'current_liability', False),
    ('GCX-211002', '[GCX] Payable to Quantum Insurance Holdings', 'liability', 'current_liability', False),
    ('GCX-211003', '[GCX] Payable to Alpha Direct', 'liability', 'current_liability', False),
    ('GCX-291002', '[GCX] Loan from Quantum Insurance Holdings', 'liability', 'long_term_liability', False),
    ('GCX-301000', '[GCX] Capital', 'equity', 'equity', False),
    ('GCX-400000', '[GCX] Revenue - Discounts Obtained', 'revenue', 'other_revenue', False),
    ('GCX-450000', '[GCX] Other Income', 'revenue', 'other_revenue', False),
    ('GCX-500000', '[GCX] Cost of Sales - Interest on Borrowings', 'expense', 'operating_expense', False),
    ('GCX-500001', '[GCX] Cost of Sales - Commission Expenses', 'expense', 'operating_expense', False),
    ('GCX-580000', '[GCX] Salaries Payable', 'expense', 'operating_expense', False),
    ('GCX-600000', '[GCX] Expenses', 'expense', 'operating_expense', False),
    ('GCX-600010', '[GCX] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('GCX-600011', '[GCX] Income tax expense', 'expense', 'operating_expense', False),
    ('GCX-620000', '[GCX] Bank Fees', 'expense', 'operating_expense', False),
    ('GCX-620010', '[GCX] Professional Fees', 'expense', 'operating_expense', False),
    ('GCX-630000', '[GCX] Salary Expenses', 'expense', 'operating_expense', False),
    ('GCX-640000', '[GCX] Severance Benefits Expense', 'expense', 'operating_expense', False),
    ('GCX-642001', '[GCX] Interest Expenses', 'expense', 'operating_expense', False),
    ('UNI-101200', '[UNI] Receivable from South Africa', 'asset', 'current_asset', False),
    ('UNI-101401', '[UNI] Bank', 'asset', 'bank', False),
    ('UNI-101405', '[UNI] Petty Cash', 'asset', 'bank', True),
    ('UNI-101406', '[UNI] Deposit', 'asset', 'current_asset', False),
    ('UNI-101422', '[UNI] Lease Liability - Short Term', 'asset', 'current_asset', False),
    ('UNI-101502', '[UNI] Outstanding Receipts', 'asset', 'current_asset', False),
    ('UNI-101504', '[UNI] Motor Vehicle', 'asset', 'current_asset', False),
    ('UNI-110301', '[UNI] Right of Use Asset', 'asset', 'current_asset', False),
    ('UNI-110301.01', '[UNI] Right of Use Asset Depreciation', 'asset', 'fixed_asset', False),
    ('UNI-110301.02', '[UNI] Accumulated Depreciation- Right of Use Assets', 'asset', 'fixed_asset', False),
    ('UNI-110400', "[UNI] Furniture's & Fittings", 'asset', 'current_asset', False),
    ('UNI-110400.01', "[UNI] Accumulated depreciation - Furniture's & Fittings", 'asset', 'fixed_asset', False),
    ('UNI-110401', '[UNI] Laptops & Computers', 'asset', 'current_asset', False),
    ('UNI-110401.01', '[UNI] Accumulated Depreciation - Laptops & Computers', 'asset', 'fixed_asset', False),
    ('UNI-121000', '[UNI] Account Receivable', 'asset', 'current_asset', False),
    ('UNI-121001', '[UNI] Account Receivable from Alpha Direct', 'asset', 'current_asset', False),
    ('UNI-121002', '[UNI] Receivable from Risk Software', 'asset', 'current_asset', False),
    ('UNI-133006', '[UNI] Staff Loan', 'asset', 'current_asset', False),
    ('UNI-191000', '[UNI] Non-current assets', 'asset', 'current_asset', False),
    ('UNI-200110', '[UNI] Tax Expense', 'liability', 'current_liability', False),
    ('UNI-201001', '[UNI] Unidentified Income', 'liability', 'current_liability', False),
    ('UNI-201102', '[UNI] Deferred Tax Asset', 'liability', 'current_liability', False),
    ('UNI-201103', '[UNI] Deferred Tax Income', 'liability', 'current_liability', False),
    ('UNI-201104', '[UNI] Deferred Tax Expense', 'liability', 'current_liability', False),
    ('UNI-202000', '[UNI] Loan from Related Company', 'liability', 'long_term_liability', False),
    ('UNI-202001', '[UNI] Loan from Alpha Direct', 'liability', 'long_term_liability', False),
    ('UNI-202002', '[UNI] Lease Liability', 'liability', 'current_liability', False),
    ('UNI-211000', '[UNI] Account Payable', 'liability', 'current_liability', False),
    ('UNI-211001', '[UNI] Payable to Risk Software Africa', 'liability', 'current_liability', False),
    ('UNI-211002', '[UNI] Payable to South Africa', 'liability', 'current_liability', False),
    ('UNI-211003', '[UNI] Salary Payable', 'liability', 'current_liability', False),
    ('UNI-211011', '[UNI] Payable to Alpha Direct', 'liability', 'current_liability', False),
    ('UNI-211012', '[UNI] Commission Payable to Instant Insurance Agents', 'liability', 'current_liability', False),
    ('UNI-252000', '[UNI] Tax Payable', 'liability', 'current_liability', False),
    ('UNI-252001', '[UNI] VAT Control Account', 'liability', 'current_liability', False),
    ('UNI-291001', '[UNI] Shareholders Loan', 'liability', 'long_term_liability', False),
    ('UNI-301000', '[UNI] Capital', 'equity', 'equity', False),
    ('UNI-443000', '[UNI] Commission Income - Instant Insurance', 'revenue', 'other_revenue', False),
    ('UNI-443001', '[UNI] Commission Income - Direct Book', 'revenue', 'other_revenue', False),
    ('UNI-443003', '[UNI] Liberty Revenues', 'revenue', 'other_revenue', False),
    ('UNI-450000', '[UNI] Other Income', 'revenue', 'other_revenue', False),
    ('UNI-600010', '[UNI] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('UNI-600011', '[UNI] Insurance Expense', 'expense', 'operating_expense', False),
    ('UNI-600012', '[UNI] Audit Fees', 'expense', 'operating_expense', False),
    ('UNI-600013', '[UNI] Adminstration Fees', 'expense', 'operating_expense', False),
    ('UNI-600014', '[UNI] Printing, Postage & Stationery', 'expense', 'operating_expense', False),
    ('UNI-600015', '[UNI] Transport Costs', 'expense', 'operating_expense', False),
    ('UNI-600016', '[UNI] Advertising & Promotions', 'expense', 'operating_expense', False),
    ('UNI-600017', '[UNI] Software Maintenance', 'expense', 'operating_expense', False),
    ('UNI-600018', '[UNI] Repairs & Maintenance', 'expense', 'operating_expense', False),
    ('UNI-600019', '[UNI] Training & Professional Development', 'expense', 'operating_expense', False),
    ('UNI-600020', '[UNI] Subscriptions', 'expense', 'operating_expense', False),
    ('UNI-600021', '[UNI] Consultancy Fees', 'expense', 'operating_expense', False),
    ('UNI-600022', '[UNI] Training Levy Expense', 'expense', 'operating_expense', False),
    ('UNI-600070', '[UNI] Professional Fees', 'expense', 'operating_expense', False),
    ('UNI-600071', '[UNI] NBFIRA Expenses', 'expense', 'operating_expense', False),
    ('UNI-600072', '[UNI] Motor Vehicle Expenses', 'expense', 'operating_expense', False),
    ('UNI-600073', '[UNI] Interest Expense', 'expense', 'operating_expense', False),
    ('UNI-611000', '[UNI] Purchase of Equipments', 'expense', 'operating_expense', False),
    ('UNI-612000', '[UNI] Rent', 'expense', 'operating_expense', False),
    ('UNI-612001', '[UNI] Utilities', 'expense', 'operating_expense', False),
    ('UNI-612002', '[UNI] Security Services', 'expense', 'operating_expense', False),
    ('UNI-612003', '[UNI] Bad debts expense', 'expense', 'operating_expense', False),
    ('UNI-620000', '[UNI] Bank Fees', 'expense', 'operating_expense', False),
    ('UNI-620001', '[UNI] Commission Expense Instant Insurance Agents', 'expense', 'operating_expense', False),
    ('UNI-620002', '[UNI] Commission Expense Direct Book', 'expense', 'operating_expense', False),
    ('UNI-620003', '[UNI] Commission Expense AD HOC Agents', 'expense', 'operating_expense', False),
    ('UNI-620004', '[UNI] Staff Welfare', 'expense', 'operating_expense', False),
    ('UNI-620006', '[UNI] Commission Expense Motor Comprehensive', 'expense', 'operating_expense', False),
    ('UNI-620007', '[UNI] Support Staff Commission', 'expense', 'operating_expense', False),
    ('UNI-630000', '[UNI] Salary Expenses', 'expense', 'operating_expense', False),
    ('UNI-631000', '[UNI] Sales Expenses', 'expense', 'operating_expense', False),
    ('UNI-800000', '[UNI] Depreciation', 'expense', 'operating_expense', False),
    ('UNI-999999', '[UNI] Undistributed Profits/Losses', 'expense', 'operating_expense', False),
    ('ADIIC-101001', '[ADIIC] Loan to Related Company', 'asset', 'current_asset', False),
    ('ADIIC-101402', '[ADIIC] TransferWise Bank Account', 'asset', 'bank', False),
    ('ADIIC-101403', '[ADIIC] Aspire SGD Bank Account', 'asset', 'bank', False),
    ('ADIIC-101404', '[ADIIC] Aspire USD Bank Account', 'asset', 'bank', False),
    ('ADIIC-101701', '[ADIIC] Liquidity Transfer', 'asset', 'current_asset', False),
    ('ADIIC-121000', '[ADIIC] Accounts Receivable', 'asset', 'current_asset', False),
    ('ADIIC-121001', "[ADIIC] Director's Liabilities", 'asset', 'current_asset', False),
    ('ADIIC-121002', '[ADIIC] Receivable from Risk Software', 'asset', 'current_asset', False),
    ('ADIIC-121003', '[ADIIC] Receivable from Alpha Zambia', 'asset', 'current_asset', False),
    ('ADIIC-121004', '[ADIIC] Receivable from Quantum', 'asset', 'current_asset', False),
    ('ADIIC-133002', '[ADIIC] Loans given to Risk Software', 'asset', 'current_asset', False),
    ('ADIIC-133006', '[ADIIC] Loans given to Quantum', 'asset', 'current_asset', False),
    ('ADIIC-133007', '[ADIIC] Loans given to Alpha Zambia', 'asset', 'current_asset', False),
    ('ADIIC-171000', '[ADIIC] Investment in Quantum', 'asset', 'fixed_asset', False),
    ('ADIIC-201000', '[ADIIC] Related Party Payable', 'liability', 'current_liability', False),
    ('ADIIC-202001', '[ADIIC] Payable to Quantum Insurance Holdings', 'liability', 'current_liability', False),
    ('ADIIC-202002', '[ADIIC] Payable to Risk Software Africa', 'liability', 'current_liability', False),
    ('ADIIC-211000', '[ADIIC] Accounts Payable', 'liability', 'current_liability', False),
    ('ADIIC-301000', '[ADIIC] Capital', 'equity', 'equity', False),
    ('ADIIC-301001', '[ADIIC] Preference Shares Issued', 'equity', 'equity', False),
    ('ADIIC-304000', '[ADIIC] Reserve - Valuation', 'equity', 'equity', False),
    ('ADIIC-307000', '[ADIIC] Share Equity', 'equity', 'equity', False),
    ('ADIIC-400000', '[ADIIC] Product Sales', 'revenue', 'operating_revenue', False),
    ('ADIIC-440000', '[ADIIC] Interest Income', 'revenue', 'other_revenue', False),
    ('ADIIC-441000', '[ADIIC] Foreign Exchange Gain', 'revenue', 'other_revenue', False),
    ('ADIIC-460000', '[ADIIC] Bank Cashbacks', 'revenue', 'other_revenue', False),
    ('ADIIC-600001', '[ADIIC] Travel Expenses', 'expense', 'operating_expense', False),
    ('ADIIC-600010', '[ADIIC] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('ADIIC-600020', '[ADIIC] Professional Fees', 'expense', 'operating_expense', False),
    ('ADIIC-600030', '[ADIIC] Licensing & Software Fees', 'expense', 'operating_expense', False),
    ('ADIIC-600040', '[ADIIC] Legal Fees', 'expense', 'operating_expense', False),
    ('ADIIC-613000', '[ADIIC] Subscriptions', 'expense', 'operating_expense', False),
    ('ADIIC-614000', '[ADIIC] Advertising and Promotions', 'expense', 'operating_expense', False),
    ('ADIIC-620000', '[ADIIC] Bank Fees', 'expense', 'operating_expense', False),
    ('ADIIC-641000', '[ADIIC] Foreign Exchange Loss', 'expense', 'operating_expense', False),
    ('ADIIC-642002', '[ADIIC] Software Maintenance', 'expense', 'operating_expense', False),
    ('ADIIC-700000', "[ADIIC] Director's Fees", 'expense', 'operating_expense', False),
    ('AIZ-101001', '[AIZ] Display Racks', 'asset', 'current_asset', False),
    ('AIZ-101001.1', '[AIZ] Accumulated Depreciation  -  Display Racks', 'asset', 'fixed_asset', False),
    ('AIZ-101300', '[AIZ] Account Receivable (PoS)', 'asset', 'current_asset', False),
    ('AIZ-101502', '[AIZ] FNB Kwacha Account', 'asset', 'bank', True),
    ('AIZ-101503', '[AIZ] FNB USD Account', 'asset', 'bank', True),
    ('AIZ-101504', '[AIZ] Petty Cash', 'asset', 'bank', True),
    ('AIZ-110200', '[AIZ] Stock Interim (Received)', 'asset', 'current_asset', False),
    ('AIZ-151002', '[AIZ] Laptops & Computers', 'asset', 'current_asset', False),
    ('AIZ-191001', '[AIZ] Motor Vehicle', 'asset', 'current_asset', False),
    ('AIZ-191001.1', '[AIZ] Accumulated Depreciation - Motor Vehicle', 'asset', 'fixed_asset', False),
    ('AIZ-211000', '[AIZ] Account Payable', 'liability', 'current_liability', False),
    ('AIZ-211001', '[AIZ] Related Party Payable', 'liability', 'current_liability', False),
    ('AIZ-211002', '[AIZ] Payable to Alpha Singapore', 'liability', 'current_liability', False),
    ('AIZ-211004', '[AIZ] Payable to General Alliance', 'liability', 'current_liability', False),
    ('AIZ-251000', '[AIZ] Tax Payable', 'liability', 'current_liability', False),
    ('AIZ-291100', '[AIZ] Loan from Related Company', 'liability', 'long_term_liability', False),
    ('AIZ-291101', '[AIZ] Loan From Alpha Direct Insurtech', 'liability', 'long_term_liability', False),
    ('AIZ-301000', '[AIZ] Capital', 'equity', 'equity', False),
    ('AIZ-400000', '[AIZ] Sales Revenue', 'revenue', 'operating_revenue', False),
    ('AIZ-441000', '[AIZ] Foreign Exchange Gain', 'revenue', 'other_revenue', False),
    ('AIZ-450000', '[AIZ] Other Income', 'revenue', 'other_revenue', False),
    ('AIZ-500000', '[AIZ] Cost of Goods Sold', 'expense', 'operating_expense', False),
    ('AIZ-500020', '[AIZ] Collection Charges', 'expense', 'operating_expense', False),
    ('AIZ-600000', '[AIZ] Expenses', 'expense', 'operating_expense', False),
    ('AIZ-600001', '[AIZ] IT Expenses', 'expense', 'operating_expense', False),
    ('AIZ-600002', '[AIZ] Motor Vehicle Expenses', 'expense', 'operating_expense', False),
    ('AIZ-600003', '[AIZ] Insurance Expense', 'expense', 'operating_expense', False),
    ('AIZ-600004', '[AIZ] Fuel Expense', 'expense', 'operating_expense', False),
    ('AIZ-600010', '[AIZ] Accounting & Secretarial', 'expense', 'operating_expense', False),
    ('AIZ-611000', '[AIZ] Purchase of Equipments', 'expense', 'operating_expense', False),
    ('AIZ-612000', '[AIZ] Rent', 'expense', 'operating_expense', False),
    ('AIZ-612001', '[AIZ] Utilities', 'expense', 'operating_expense', False),
    ('AIZ-612002', '[AIZ] Subscriptions', 'expense', 'operating_expense', False),
    ('AIZ-613000', '[AIZ] Promotional Expenses', 'expense', 'operating_expense', False),
    ('AIZ-614000', '[AIZ] Salary Expenses', 'expense', 'operating_expense', False),
    ('AIZ-614001', '[AIZ] Leave and Severence', 'expense', 'operating_expense', False),
    ('AIZ-615000', '[AIZ] Travel Expenses', 'expense', 'operating_expense', False),
    ('AIZ-616000', '[AIZ] Transportation Costs', 'expense', 'operating_expense', False),
    ('AIZ-617000', '[AIZ] Agency Training Cost', 'expense', 'operating_expense', False),
    ('AIZ-620000', '[AIZ] Bank Fees', 'expense', 'operating_expense', False),
    ('AIZ-620002', '[AIZ] Printing & Stationery', 'expense', 'operating_expense', False),
    ('AIZ-620003', '[AIZ] Training & Professional Development', 'expense', 'operating_expense', False),
    ('AIZ-620004', '[AIZ] Consultation Fee Expense', 'expense', 'operating_expense', False),
    ('AIZ-641000', '[AIZ] Foreign Exchange Loss', 'expense', 'operating_expense', False),
    ('AIZ-644000', '[AIZ] Staff Welfare', 'expense', 'operating_expense', False),
    ('AIZ-645000', '[AIZ] Licensing Fees', 'expense', 'operating_expense', False),
    ('AIZ-65000', '[AIZ] Finance Costs', 'expense', 'operating_expense', False),
    ('AIZ-800000', '[AIZ] Depreciation Expense', 'expense', 'operating_expense', False),
    ('AIZ-960000', '[AIZ] Software Development Costs', 'expense', 'operating_expense', False),
    ('AIZ-962000', '[AIZ] Sales Expenses', 'expense', 'operating_expense', False),
    ('ADIL-101404', '[ADIL] FNB Account', 'asset', 'bank', True),
    ('ADIL-102000', '[ADIL] Accounting & Secretarial', 'asset', 'current_asset', False),
    ('ADIL-121000', '[ADIL] Account Receivable', 'asset', 'current_asset', False),
    ('ADIL-191001', "[ADIL] Director's Liabilities", 'asset', 'current_asset', False),
    ('ADIL-211000', '[ADIL] Account Payable', 'liability', 'current_liability', False),
    ('ADIL-212000', '[ADIL] Payable to Quantum', 'liability', 'current_liability', False),
    ('ADIL-213000', '[ADIL] Payable to Risk Software', 'liability', 'current_liability', False),
    ('ADIL-301000', '[ADIL] Capital', 'equity', 'equity', False),
    ('ADIL-400000', '[ADIL] Product Sales', 'revenue', 'operating_revenue', False),
    ('ADIL-613000', '[ADIL] Interest Expenses', 'expense', 'operating_expense', False),
    ('ADIL-614000', '[ADIL] General Expenses', 'expense', 'operating_expense', False),
    ('ADIL-620000', '[ADIL] Bank Fees', 'expense', 'operating_expense', False),
    ('ADRG-101404', '[ADRG] Bank', 'asset', 'bank', False),
    ('ADRG-131000', '[ADRG] Tax Paid', 'asset', 'current_asset', False),
    ('ADRG-211000', '[ADRG] Account Payable', 'liability', 'current_liability', False),
    ('ADRG-252000', '[ADRG] Tax Payable', 'liability', 'current_liability', False),
    ('ADRG-301000', '[ADRG] Capital', 'equity', 'equity', False),
    ('ADRG-400000', '[ADRG] Product Sales', 'revenue', 'operating_revenue', False),
    ('ADRG-600000', '[ADRG] Expenses', 'expense', 'operating_expense', False),
    ('ADRG-600001', '[ADRG] Staff Welfare', 'expense', 'operating_expense', False),
    ('ADRG-600002', '[ADRG] Travel Expenses', 'expense', 'operating_expense', False),
    ('ADRG-612000', '[ADRG] Rent', 'expense', 'operating_expense', False),
    ('ADRG-620000', '[ADRG] Bank Fees', 'expense', 'operating_expense', False),
    ('ADRG-630000', '[ADRG] Salary Expenses', 'expense', 'operating_expense', False),
    ('ADRG-630001', '[ADRG] Contractor Fees', 'expense', 'operating_expense', False),
    ('ADRG-630002', '[ADRG] Recruitment Service Fees', 'expense', 'operating_expense', False),
    ('ADRG-630003', '[ADRG] Lease payments', 'expense', 'operating_expense', False),
    ('ADRG-630004', '[ADRG] RBI Filing', 'expense', 'operating_expense', False),
    ('ADRG-63005', '[ADRG] Accounting and Secretarial Fees', 'expense', 'operating_expense', False),
    ('ADRG-641000', '[ADRG] Foreign Exchange Loss', 'expense', 'operating_expense', False),
    ('ADRG-999999', '[ADRG] Undistributed Profits/Losses', 'expense', 'operating_expense', False),
]


def main():
    Currency.objects.get_or_create(code='BWP', defaults={'name': 'Botswana Pula'})
    with transaction.atomic():
        created = updated = 0
        for code, name, acct_type, sub_type, is_bank in ACCOUNTS_RP:
            obj, was_created = Account.objects.update_or_create(
                code=code,
                defaults={
                    'name': name,
                    'account_type': acct_type,
                    'sub_type': sub_type,
                    'is_bank_account': is_bank,
                    'is_active': True,
                },
            )
            if was_created: created += 1
            else: updated += 1
        print(f'  CoA related-party accounts: {created} created, {updated} updated, '
              f'{len(ACCOUNTS_RP)} total.')


main()
