# Generated by Django — aligns hand-written 0001 index names with the model.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_rewards', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffsubmission',
            new_name='staff_rewar_status_f0ed7e_idx',
            old_name='staff_rewar_status_3f8c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='staffsubmission',
            new_name='staff_rewar_employe_fe4f30_idx',
            old_name='staff_rewar_employe_7b1d4e_idx',
        ),
    ]
