# Generated by Django 5.2 on 2026-03-24 05:58

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
        ('ledger', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent')], max_length=10)),
                ('payment_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_bwp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('debit_order', 'Debit Order'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('gateway', 'Payment Gateway')], max_length=15)),
                ('reference', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ledger.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('currency_code', models.ForeignKey(default='BWP', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.currency')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ledger.journalentry')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithholdingTaxRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('wht_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wht_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_year_start', models.DateField()),
                ('cumulative_paid_ytd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remitted_to_burs', models.BooleanField(default=False)),
                ('remittance_date', models.DateField(blank=True, null=True)),
                ('burs_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wht_records', to='billing.contact')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wht_record', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Withholding Tax Record',
                'verbose_name_plural': 'Withholding Tax Records',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
