# Generated by Django 5.2 on 2026-05-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_company'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vendor_bank_account',
            field=models.ForeignKey(blank=True, help_text='Required for outbound electronic payments. Must be ACTIVE and belong to the same vendor as this payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='procurement.vendorbankaccount'),
        ),
    ]
