# Generated by Django 5.2 on 2026-05-10 17:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_vendor_bank_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='secondary_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='secondary_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_secondary_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OutboundPaymentPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dual_auth_threshold', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='BWP amount above which a second approver is required.', max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_payment_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outbound Payment Policy',
                'verbose_name_plural': 'Outbound Payment Policy',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
