# Generated by Django 5.2 on 2026-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_beneficiary_name',
            field=models.CharField(blank=True, default='', help_text='Who the bank shows as the beneficiary. Blank = the vendor or payee name we hold.', max_length=140),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_narration',
            field=models.CharField(blank=True, default='', help_text='What the payee sees on their statement. Blank = the description, then the reference, then the payment number.', max_length=140),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_our_reference',
            field=models.CharField(blank=True, default='', help_text='Our own reference for this payment, for matching it back. Blank = the payment number. Max 35 characters.', max_length=35),
        ),
    ]

