# Generated by Django 5.2 on 2026-08-22 11:59

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_bank_facing_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remittance_email',
            field=models.EmailField(blank=True, default=payments.models.default_pop_email, help_text='Where FNB sends the proof of payment. Defaults to Accounts; change it per payment. Blank = no POP email requested.', max_length=254),
        ),
    ]
