# Generated by Django 5.2 on 2026-03-23 15:44

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('broker', 'Broker'), ('reinsurer', 'Reinsurer'), ('employee', 'Employee')], max_length=15)),
                ('name', models.CharField(max_length=300)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('is_resident', models.BooleanField(default=True)),
                ('wht_exempt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('graphite_id', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_code', models.ForeignKey(default='BWP', on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='core.currency')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('invoice_type', models.CharField(choices=[('customer_invoice', 'Customer Invoice'), ('credit_note', 'Credit Note'), ('vendor_bill', 'Vendor Bill'), ('vendor_credit', 'Vendor Credit')], max_length=20)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='draft', max_length=15)),
                ('source_type', models.CharField(default='manual', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('currency_code', models.ForeignKey(default='BWP', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.currency')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='ledger.journalentry')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='ledger.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.taxrate')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
