# Generated by Django 5.2 on 2026-05-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_contact_related_party'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Required for vendor bills. Bill cannot be posted without a referenced approved PO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='procurement.purchaseorder'),
        ),
    ]
