# Generated by Django 5.2 on 2026-05-10 17:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_purchase_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approval_tier',
            field=models.CharField(blank=True, default='', help_text='Snapshot of which BillApprovalPolicy tier applied.', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitted_for_approval_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='BillApprovalPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_approve_ceiling', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Bills at or below this BWP amount auto-approve.', max_digits=18)),
                ('manager_ceiling', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Above auto-approve and at or below this — Finance Manager / Controller / CFO can approve.', max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_approval_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Approval Policy',
                'verbose_name_plural': 'Bill Approval Policy',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
