# Generated by Django 5.2 on 2026-07-22 06:03

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_perf_indexes"),
        # Pinned to the actual current latest core migration. Django's
        # autodetector proposes depending on a NEW core migration
        # (0045_rename_...) that would bundle unrelated, pre-existing core
        # drift (ChatMessage/EmailLoginCode index renames + UserProfile
        # .title choices) into this billing-only feature. That drift predates
        # this branch's ReverseChargeEntry work and is out of scope here — it
        # belongs in its own migration/PR. This FK only needs core.Company to
        # exist, which 0044 already provides.
        ("core", "0044_datasubjectrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="billapprovalpolicy",
            name="tier2_ceiling",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="PLACEHOLDER — CFO to set. Above tier1 and at/below this → Tier 2 (Head of Finance). Above this → Tier 3 (CFO only).",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ReverseChargeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.CharField(
                        help_text='Free-text vendor name, e.g. "Amazon Web Services".',
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cloud", "Cloud hosting & compute (e.g. AWS)"),
                            (
                                "ai_saas",
                                "AI / SaaS subscriptions (e.g. Anthropic, Google, OpenAI)",
                            ),
                            (
                                "productivity",
                                "Productivity & automation (e.g. Microsoft 365, n8n, Power Automate)",
                            ),
                            ("design", "Design & content tools (e.g. Canva, Gamma)"),
                            ("devtools", "Dev tooling (e.g. GitHub, Cursor)"),
                            ("hris", "HRIS / monitoring (e.g. Time Doctor)"),
                            ("email_api", "Email / messaging API (e.g. Mailgun)"),
                            ("other", "Other imported remote service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField()),
                (
                    "foreign_currency",
                    models.CharField(
                        help_text="ISO 4217 currency code the foreign invoice was billed in, e.g. USD.",
                        max_length=3,
                    ),
                ),
                (
                    "foreign_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount on the foreign invoice, in foreign_currency.",
                        max_digits=18,
                    ),
                ),
                (
                    "bwp_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The BWP amount actually paid. Entered directly — NOT auto-converted from foreign_amount.",
                        max_digits=18,
                    ),
                ),
                (
                    "reverse_charge_applies",
                    models.BooleanField(
                        default=True,
                        help_text="True for non-resident/foreign remote services only. Local suppliers (e.g. RealPay) are never reverse-charge.",
                    ),
                ),
                (
                    "output_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="= bwp_amount * RC_VAT_RATE. Computed in save(); read-only.",
                        max_digits=18,
                    ),
                ),
                (
                    "input_vat_recoverable",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Defaults to full recovery (= output_vat) and stays pinned to it on every save. Set input_recovery_overridden (via an explicit edit) to lower it for entries behind VAT-exempt income.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "input_recovery_overridden",
                    models.BooleanField(
                        default=False,
                        help_text="True once a caller has explicitly supplied input_vat_recoverable. While False, save() keeps input_vat_recoverable pinned to full recovery (= output_vat) on every save.",
                    ),
                ),
                (
                    "net_vat_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="= output_vat - input_vat_recoverable. Computed in save(); read-only.",
                        max_digits=18,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Mandatory when category is "Other imported remote service".',
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning legal entity. Filters apply per-company in the topbar switcher.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reverse_charge_entries",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverse_charge_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverse_charge_entries_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reverse-Charge VAT Entry",
                "verbose_name_plural": "Reverse-Charge VAT Entries",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["company", "invoice_date"],
                        name="rc_entry_company_date_idx",
                    )
                ],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
