# Generated by Django 5.2 on 2026-09-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_alter_billapprovalpolicy_tier2_ceiling_and_more"),
        ("ledger", "0027_sync_model_state_2026_07_26"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="receivable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the receivable account this invoice posts to. Blank = premium receivable.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices_receivable_override",
                to="ledger.account",
            ),
        ),
    ]
