# Generated by Django 5.2 on 2026-05-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_title_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('cfo', 'Chief Financial Officer'), ('finance_manager', 'Finance Manager'), ('financial_controller', 'Financial Controller'), ('claims_manager', 'Claims Manager'), ('operations_manager', 'Operations Manager'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('finance_analyst', 'Finance Analyst'), ('auditor', 'Auditor (read-only)'), ('executive', 'Executive (read-only)'), ('operations', 'Operations Staff'), ('system_api', 'System / API')], default='accountant', help_text='Job title — drives approval permissions.', max_length=30),
        ),
    ]
