# Generated by Django 5.2 on 2026-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payroll_password_hash',
            field=models.CharField(blank=True, default='', help_text='PBKDF2 hash of the per-company payroll gate password. Empty = no gate (open). Set via `python manage.py set_payroll_password <code>`.', max_length=255),
        ),
    ]
