# Generated by Django 5.2 on 2026-05-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_payroll_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='If set, this Company is an agency / branch whose books consolidate INTO the parent. Null = independent legal entity.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='core.company'),
        ),
    ]
