# Generated by Django 5.2 on 2026-06-09 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_seed_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Label, e.g. "HRIS unlock password" or "RealPay 16244 login".', max_length=160, unique=True)),
                ('category', models.CharField(choices=[('hris', 'HRIS'), ('portal', 'Portal / Paygate'), ('api', 'API / Integration'), ('database', 'Database'), ('email', 'Email / M365'), ('cloud', 'Cloud / Infra'), ('other', 'Other')], default='other', max_length=12)),
                ('username', models.CharField(blank=True, default='', help_text='Optional username / account (not secret).', max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('secret_ciphertext', models.TextField(blank=True, default='', help_text='Fernet-encrypted secret value. Never plaintext.')),
                ('last_revealed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vault Secret',
                'verbose_name_plural': 'Vault Secrets',
                'ordering': ['category', 'name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='onlinepresence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Online presence', 'verbose_name_plural': 'Online presence'},
        ),
        migrations.RenameIndex(
            model_name='ariaconversation',
            new_name='core_ariaco_user_id_775f90_idx',
            old_name='core_aria_conv_user_idx',
        ),
        migrations.RenameIndex(
            model_name='ariamessage',
            new_name='core_ariame_convers_8315b1_idx',
            old_name='core_aria_msg_conv_idx',
        ),
        migrations.RenameIndex(
            model_name='omnitask',
            new_name='core_omnita_assigne_49cbcd_idx',
            old_name='core_omnit_assigne_a_idx',
        ),
        migrations.RenameIndex(
            model_name='omnitask',
            new_name='core_omnita_assigne_fca46e_idx',
            old_name='core_omnit_assigne_b_idx',
        ),
        migrations.RenameIndex(
            model_name='usercompanyaccess',
            new_name='core_userco_user_id_b4244f_idx',
            old_name='core_userco_user_id_e1f8b8_idx',
        ),
        migrations.RenameIndex(
            model_name='userroleassignment',
            new_name='core_userro_user_id_25526d_idx',
            old_name='core_uras_user_revoked_idx',
        ),
        migrations.RenameIndex(
            model_name='userroleassignment',
            new_name='core_userro_role_id_499ce5_idx',
            old_name='core_uras_role_revoked_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Optional dict — directors, FSP, CIPC, VAT state, etc. Read via Company.meta(key).'),
        ),
        migrations.AlterField(
            model_name='intercompanyaccountpolicy',
            name='payable_account_code',
            field=models.CharField(blank=True, default='', help_text='GL code for "Due to related companies" — credited in the receiver JE of an intercompany asset transfer.', max_length=20),
        ),
        migrations.AlterField(
            model_name='intercompanyaccountpolicy',
            name='receivable_account_code',
            field=models.CharField(blank=True, default='', help_text='GL code for "Due from related companies" — debited in the sender JE of an intercompany asset transfer.', max_length=20),
        ),
        migrations.AlterField(
            model_name='omnitaskcomment',
            name='new_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('partial', 'Partially complete'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='', help_text='If set, this comment also transitions the task.', max_length=15),
        ),
        migrations.AddField(
            model_name='vaultsecret',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_secrets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaultsecret',
            name='last_revealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_secrets_revealed', to=settings.AUTH_USER_MODEL),
        ),
    ]
