# Generated by Django 5.2 on 2026-07-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_manual_feature_entry'),
    ]

    operations = [
        # NOTE: makemigrations also proposed a RenameIndex on chatmessage
        # (core_chatme_room_3a6dd2_idx -> ..._805631_idx). It was REMOVED
        # 2026-07-02: prod's actual index name differs (pre-existing migration
        # -state drift), so the rename raised "relation ... does not exist" and
        # crash-looped the backend on deploy. It is unrelated to this feature.
        # On prod 0031 was recorded via --fake after that crash; this file now
        # matches what effectively applied (the title AlterField only). A
        # separate migration should reconcile the chatmessage index drift.
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('cfo', 'Chief Financial Officer'), ('finance_manager', 'Finance Manager'), ('financial_controller', 'Financial Controller'), ('claims_manager', 'Claims Manager'), ('operations_manager', 'Operations Manager'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('senior_accountant', 'Senior Accountant'), ('bookkeeper', 'Bookkeeper'), ('finance_analyst', 'Finance Analyst'), ('auditor', 'Auditor (read-only)'), ('executive', 'Executive (read-only)'), ('operations', 'Operations Staff'), ('system_api', 'System / API')], default='accountant', help_text='Job title — drives approval permissions.', max_length=30),
        ),
    ]
