# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_notebookpage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='core_chatme_room_805631_idx',
            old_name='core_chatme_room_3a6dd2_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillogincode',
            new_name='core_emaill_email_b4146e_idx',
            old_name='core_emaill_email_5c9d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='core_outbou_created_228e51_idx',
            old_name='core_outbou_created_1e8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='core_outbou_status_868448_idx',
            old_name='core_outbou_status_7c31b9_idx',
        ),
        migrations.AlterField(
            model_name='emaillogincode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('cfo', 'Chief Financial Officer'), ('finance_manager', 'Finance Manager'), ('financial_controller', 'Financial Controller'), ('claims_manager', 'Claims Manager'), ('operations_manager', 'Operations Manager'), ('hr_manager', 'HR Manager'), ('claims_team_leader', 'Claims Team Leader'), ('senior_claims_associate', 'Senior Claims Associate'), ('junior_claims_associate', 'Junior Claims Associate'), ('claims_intern', 'Claims Intern'), ('accountant', 'Accountant'), ('senior_accountant', 'Senior Accountant'), ('bookkeeper', 'Bookkeeper'), ('finance_analyst', 'Finance Analyst'), ('auditor', 'Auditor (read-only)'), ('executive', 'Executive (read-only)'), ('operations', 'Operations Staff'), ('system_api', 'System / API')], default='accountant', help_text='Job title — drives approval permissions.', max_length=30),
        ),
    ]
