# Generated by Django 5.2 on 2026-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_processordpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processordpa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
