# Generated by Django 5.2 on 2026-08-03 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_rowcountsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_slug', models.SlugField(max_length=60)),
                ('pain_ratings', models.JSONField(default=dict)),
                ('biggest_question', models.TextField(blank=True)),
                ('wish_ai_did', models.TextField(blank=True)),
                ('tried_already', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('respondent_role', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('headcount_band', models.CharField(blank=True, max_length=40)),
                ('may_quote', models.BooleanField(default=False)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'speaker audience feedback',
                'verbose_name_plural': 'speaker audience feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
