# Generated by Django 5.2 on 2026-08-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_senior_operations_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='qc_picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='qc_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='qc_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='qc_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports_qc_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='qc_result_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='qc_result_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='qc_result_pr_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
