# Generated by Django 5.2 on 2026-09-03 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_staffdevicesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=200)),
                ('surface', models.CharField(choices=[('app', 'Phone app'), ('m', 'Nexus'), ('desktop', 'Desktop')], max_length=10)),
                ('minute', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screen view',
                'verbose_name_plural': 'Screen views',
                'unique_together': {('user', 'screen', 'minute')},
            },
        ),
    ]
