# Generated by Django 5.2 on 2026-09-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_screenview'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnitask',
            name='client_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Client idempotency key (Quick Task); blank = not set.', max_length=64),
        ),
    ]
