# Generated by Django 5.2 on 2026-09-08 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_omnitask_client_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarInviteLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organiser_upn",
                    models.CharField(
                        db_index=True,
                        help_text="The only calendar written to.",
                        max_length=255,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which Omni feature asked for it.",
                        max_length=64,
                    ),
                ),
                ("starts_at", models.CharField(blank=True, default="", max_length=64)),
                ("attendee_count", models.PositiveIntegerField(default=0)),
                (
                    "attendees",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Invited addresses, comma separated.",
                    ),
                ),
                (
                    "graph_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("refused", "Refused (mailbox not allowed)"),
                            ("failed", "Failed (Microsoft error)"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Invite Log",
                "verbose_name_plural": "Calendar Invite Log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_calend_created_f369b1_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_calend_status_c65621_idx"
                    ),
                ],
            },
        ),
    ]
