# Generated by Django 5.2 on 2026-09-10 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_calendar_invite_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('ceo', 'CEO morning brief'), ('cfo', 'CFO morning brief')], db_index=True, max_length=3)),
                ('body', models.CharField(max_length=400)),
                ('for_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued for the next brief'), ('sent', 'Delivered in the brief'), ('withdrawn', 'Withdrawn before sending')], db_index=True, default='queued', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brief_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brief note',
                'verbose_name_plural': 'Brief notes',
                'ordering': ['-for_date', 'created_at'],
                'indexes': [models.Index(fields=['audience', 'for_date', 'status'], name='core_briefn_audienc_8df21b_idx')],
                'constraints': [models.UniqueConstraint(fields=('audience', 'author', 'for_date'), name='one_brief_note_per_person_per_morning')],
            },
        ),
    ]
