# Generated by Django 5.2 on 2026-09-15 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ariapopup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_access_delegate',
            field=models.BooleanField(default=False, help_text='Limited access administrator (CFO directive 2026-09-15). Can grant and revoke only the titles in core.access_delegate.delegable_titles() — never payroll, manager-level, financial or administrator access, never their own profile, and never another administrator.'),
        ),
        migrations.CreateModel(
            name='NamedModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('bonu', 'BONU'), ('bonu_intake', 'BONU claim intake (no financials)')], max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module', 'email'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('module', 'email'), name='uniq_named_module_access')],
            },
        ),
    ]
