# Generated by Django 5.2 on 2026-09-21 14:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_access_delegate_and_module_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('recipient', models.CharField(blank=True, default='', help_text='Who the link was made for (audit trail only).', max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('opened_from', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_share_links_created', to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='core.vaultsecret')),
            ],
            options={
                'verbose_name': 'Vault Share Link',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
