"""reporting/instant_admin_fees_report.py — the workbook and the covering email.

Separated from ``instant_admin_fees.py`` (which only reads and calculates) so the
figures can be tested without building a spreadsheet, and so the monthly command
is a thin caller. Same three-file shape as ``realpay/failed_debits*``.

The workbook is built with ``aware.reporting._wb``, the branded Navy/Orange builder
Graphite Aware's reports already use. Imported, never copied: a second table
builder would drift from the first the week anyone changed a column width, and
Finance would start receiving two house styles.
"""
from __future__ import annotations

from decimal import Decimal
from typing import Any, Dict, List

from aware.reporting import NAVY, ORANGE, _wb

from reporting.instant_admin_fees import MERCHANTS

COLUMNS = [
    'Store', 'Product', 'Product plan', 'Policies', 'Premium (BWP)',
    'Commission 40% (BWP)', 'VAT stripped (BWP)', 'Fee excl. VAT (BWP)',
    'OWHT 10% (BWP)', 'Payable (BWP)',
]

NOTES = [
    'Read live from Graphite on the morning it was sent — not a hand export.',
    'Period runs from the 27th of the previous month to the 26th of this one.',
    'Active policies only, inception inside the period, the five Instant '
    'Insurance products only — the same rules the Instant Insurance summary '
    'screen applies.',
    'Calculation, in order: commission is 40% of premium; the VAT is then '
    'divided out at the rate held in Omni settings; OWHT of 10% is deducted '
    'from the VAT-EXCLUSIVE fee, because the VAT is not our income. '
    '(CFO decision 13 September 2026.)',
    'Every figure is rounded to the thebe, half up.',
    'A store total is worked out on that store\'s own premium — which is what '
    'the partner will check with a calculator — so the product lines beneath '
    'it can land a thebe away from it. The store totals, and the grand total '
    'that sums them, are the amounts.',
    'A store with no business is listed with a nil line, never left out.',
    'NO GL POSTING. This is submitted to Finance for review and posting. Omni '
    'raises no journal, no payment, and moves no money.',
]


def _f(v) -> float:
    """Money as a float for the cell, so Excel gets a number it can total.

    Rounded to the thebe, never truncated: a report whose rows sum to a different
    total than its own headline is the fastest way to lose the reader.
    """
    return float(Decimal(str(v or 0)).quantize(Decimal('0.01')))


def _gl_note() -> str:
    codes = ', '.join(f'{m.name} {m.gl_account}' for m in MERCHANTS)
    return f'Chart of accounts, for Finance to post against by hand: {codes}.'


def build_xlsx(data: Dict[str, Any]):
    """The attachment. Returns a BytesIO positioned at the start."""
    kpis = [
        ('Period', data['label']),
        ('Policies written', f"{data['policies']:,}"),
        ('Premium', f"P {_f(data['premium']):,.2f}"),
        ('Commission at 40%', f"P {_f(data['commission']):,.2f}"),
        ('VAT stripped out', f"P {_f(data['vat']):,.2f}"),
        ('Fee excluding VAT', f"P {_f(data['net_of_vat']):,.2f}"),
        ('OWHT at 10%', f"P {_f(data['owht']):,.2f}"),
        ('Payable to stores', f"P {_f(data['payable']):,.2f}"),
    ]

    body: List[List[Any]] = []
    for block in data['blocks']:
        if block['nil']:
            # The whole point. A store with nothing says so, by name, on its own
            # row — it is never simply absent from the sheet.
            body.append([block['merchant'], block['nil_message'], '', 0,
                         0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
            continue
        for r in block['rows']:
            body.append([
                block['merchant'], r['product'], r['plan'], r['policies'],
                _f(r['premium']), _f(r['commission']), _f(r['vat']),
                _f(r['net_of_vat']), _f(r['owht']), _f(r['payable']),
            ])
        body.append([
            f"Total — {block['merchant']}", f"GL {block['gl_account']}", '',
            block['policies'], _f(block['premium']), _f(block['commission']),
            _f(block['vat']), _f(block['net_of_vat']), _f(block['owht']),
            _f(block['payable']),
        ])

    notes = list(NOTES) + [_gl_note()]
    if not data['plan_available']:
        notes.append('Product plan could not be read from Graphite on this run — '
                     'the plan column shows a dash. The premium, the counts and '
                     'every fee figure are unaffected.')
    if data['unmatched']:
        names = ', '.join(sorted(data['unmatched']))
        notes.append(f'Premium was found against stores that match no merchant '
                     f'and is NOT in any total above: {names}.')

    return _wb(
        title='Alpha Direct — Instant Insurance Admin Fees',
        subtitle=f"{data['label']} · generated by Omni",
        kpis=kpis,
        columns=COLUMNS,
        rows=body,
        notes=notes,
        # money_cols is DELIBERATELY NOT PASSED. aware.reporting._wb formats a
        # money column as '#,##0' — whole pula. These figures are thebe-accurate
        # and are a fee note; a 987.47 shown as 987 beside a KPI reading
        # P 987.47 is an argument with a partner waiting to happen.
    )


def filename(data: Dict[str, Any]) -> str:
    return f"Alpha Direct Instant Insurance Admin Fees {data['end']:%Y-%m}.xlsx"


def subject(data: Dict[str, Any]) -> str:
    return f"Instant insurance admin fees — {data['label']}"


def build_html(data: Dict[str, Any]) -> str:
    """The covering email.

    The per-store table is in the BODY on purpose. Finance have to read four
    numbers and act; making them open an attachment to see whether a store had
    anything is how a monthly report stops being read.
    """
    rows_html = []
    for block in data['blocks']:
        if block['nil']:
            rows_html.append(
                f'<tr><td style="padding:6px 10px;border-bottom:1px solid #eee">'
                f'<strong>{block["merchant"]}</strong></td>'
                f'<td colspan="4" style="padding:6px 10px;border-bottom:1px solid #eee;'
                f'color:#666;font-style:italic">{block["nil_message"]}</td></tr>')
            continue
        rows_html.append(
            f'<tr><td style="padding:6px 10px;border-bottom:1px solid #eee">'
            f'<strong>{block["merchant"]}</strong></td>'
            f'<td align="right" style="padding:6px 10px;border-bottom:1px solid #eee">'
            f'{block["policies"]:,}</td>'
            f'<td align="right" style="padding:6px 10px;border-bottom:1px solid #eee">'
            f'{_f(block["premium"]):,.2f}</td>'
            f'<td align="right" style="padding:6px 10px;border-bottom:1px solid #eee">'
            f'{_f(block["owht"]):,.2f}</td>'
            f'<td align="right" style="padding:6px 10px;border-bottom:1px solid #eee">'
            f'<strong>{_f(block["payable"]):,.2f}</strong></td></tr>')

    caveats = ''
    if not data['plan_available']:
        caveats += ('<p style="color:#8a6d3b">The product plan could not be read '
                    'from Graphite on this run. Premium, counts and fees are '
                    'unaffected.</p>')
    if data['unmatched']:
        names = ', '.join(sorted(data['unmatched']))
        caveats += (f'<p style="color:#a94442">Premium was found against stores '
                    f'that match none of the four merchants and is not in the '
                    f'totals: {names}. Worth a look before this is paid.</p>')

    return f"""
<div style="font-family:Segoe UI,Arial,sans-serif;color:#222;font-size:14px">
  <h2 style="color:#{NAVY};margin:0 0 4px">Instant insurance admin fees</h2>
  <p style="color:#666;margin:0 0 16px">{data['label']}</p>

  <p>Admin fees due to the four Instant Insurance retail partners for the period.
  Read live from Graphite. <strong>Nothing has been posted and nothing has been
  paid</strong> — this is for your review and for posting by hand.</p>

  <table cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:100%;
         font-size:13px;margin:12px 0">
    <tr style="background:#{NAVY};color:#fff">
      <th align="left"  style="padding:8px 10px">Store</th>
      <th align="right" style="padding:8px 10px">Policies</th>
      <th align="right" style="padding:8px 10px">Premium</th>
      <th align="right" style="padding:8px 10px">OWHT 10%</th>
      <th align="right" style="padding:8px 10px">Payable</th>
    </tr>
    {''.join(rows_html)}
    <tr style="background:#f2f4f8;font-weight:bold">
      <td style="padding:8px 10px;border-top:2px solid #{ORANGE}">All stores</td>
      <td align="right" style="padding:8px 10px;border-top:2px solid #{ORANGE}">
        {data['policies']:,}</td>
      <td align="right" style="padding:8px 10px;border-top:2px solid #{ORANGE}">
        {_f(data['premium']):,.2f}</td>
      <td align="right" style="padding:8px 10px;border-top:2px solid #{ORANGE}">
        {_f(data['owht']):,.2f}</td>
      <td align="right" style="padding:8px 10px;border-top:2px solid #{ORANGE}">
        {_f(data['payable']):,.2f}</td>
    </tr>
  </table>

  {caveats}

  <p style="color:#555;font-size:13px">How each figure is worked out: commission is
  40% of premium; the VAT is divided out of that at the rate held in Omni settings;
  then 10% withholding tax comes off the <em>VAT-exclusive</em> fee, because the VAT
  is not our income. The attached workbook shows every product and plan behind
  these totals.</p>

  <p style="color:#555;font-size:13px">A store with no business in the period is
  listed above saying so, rather than left out.</p>
</div>
"""
