# Generated by Django 5.2 on 2026-07-26 04:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        ('ledger', '0027_sync_model_state_2026_07_26'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investment',
            new_name='investments_classif_49936a_idx',
            old_name='inv_classif_idx',
        ),
        migrations.RenameIndex(
            model_name='investment',
            new_name='investments_status_8a7490_idx',
            old_name='inv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='investmenttransaction',
            new_name='investments_transac_f5d4fa_idx',
            old_name='invtx_type_idx',
        ),
        migrations.RenameIndex(
            model_name='investmenttransaction',
            new_name='investments_investm_bf02bc_idx',
            old_name='invtx_inv_status_idx',
        ),
        migrations.AlterField(
            model_name='investment',
            name='classification',
            field=models.CharField(choices=[('fvtpl', 'Fair Value Through P&L'), ('fvoci', 'Fair Value Through OCI'), ('amortised_cost', 'Amortised Cost')], help_text='IFRS 9 classification — drives FV mechanics.', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Initial acquisition cost (clean price + fees).', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='coupon_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Annual coupon (debt only).', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_fair_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Latest mark-to-market — moved by FV adjustment transactions.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='investment',
            name='custodian',
            field=models.CharField(blank=True, help_text='Bank or broker holding the instrument on our behalf.', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment',
            name='face_value',
            field=models.DecimalField(decimal_places=2, help_text='Nominal value (e.g. P1,000,000 face for a T-bill).', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_account',
            field=models.ForeignKey(help_text='Balance-sheet asset GL account that carries this position.', on_delete=django.db.models.deletion.PROTECT, related_name='investments_carried', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='isin_or_ref',
            field=models.CharField(blank=True, help_text='ISIN, ticker, or any external reference.', max_length=80),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Cash side of the transaction. For FV adjustments, the unrealised gain (positive) or loss (negative).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text='Bank account for cash side. Not required for fair-value adjustments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_cash_legs', to='ledger.account'),
        ),
    ]
