# Generated by Django 5.2 on 2026-08-12 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_sync_model_state_2026_07_26'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
