# Generated by Django 5.2 on 2026-07-11 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to="recruitment/cvs/"
                    ),
                ),
                ("cv_text", models.TextField(blank=True, default="")),
                ("skills", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="JobRequisition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("department", models.CharField(blank=True, default="", max_length=80)),
                ("company_id", models.UUIDField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed_term", "Fixed term"),
                            ("casual", "Casual"),
                            ("intern", "Intern"),
                        ],
                        default="permanent",
                        max_length=12,
                    ),
                ),
                ("headcount", models.PositiveSmallIntegerField(default=1)),
                ("jd_text", models.TextField(blank=True, default="")),
                ("required_skills", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open — accepting candidates"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisitions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Requisition",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interview_1", "First interview"),
                            ("interview_2", "Second interview"),
                            ("offer", "Offer"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=12,
                    ),
                ),
                ("match_score", models.PositiveSmallIntegerField(default=0)),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("human_reviewed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruitment.jobrequisition",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("requisition", "candidate"), name="uniq_req_candidate"
                    )
                ],
            },
        ),
    ]
