# Generated by Django 5.2 on 2026-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ai_analysed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_gaps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="ai_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
