# Generated by Django 5.2 on 2026-08-03 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_ai_analysed_application_ai_gaps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityToRecruit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('recruit', 'Authority to Recruit — external appointment'), ('regrade', 'Authority to Regrade — existing employee')], db_index=True, default='recruit', max_length=8)),
                ('person_name', models.CharField(max_length=120)),
                ('entity', models.CharField(default='Alpha Direct Insurance Company', max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('level', models.CharField(blank=True, default='', max_length=24)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed term'), ('casual', 'Casual'), ('intern', 'Intern')], default='permanent', max_length=12)),
                ('headcount', models.PositiveSmallIntegerField(default=1)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('salary_lines', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='BWP', max_length=3)),
                ('quoted_ctc_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quoted_ctc_annual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending signatures'), ('approved', 'Approved — all five signed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=10)),
                ('approvals', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorities_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruit_authorities', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorities', to='recruitment.jobrequisition')),
            ],
            options={
                'verbose_name': 'Authority to Recruit',
                'verbose_name_plural': 'Authorities to Recruit',
                'ordering': ['-created_at'],
            },
        ),
    ]
