# Generated by Django 5.2 on 2026-08-26 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0021_employee_archive"),
        ("recruitment", "0003_authoritytorecruit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="authoritytorecruit",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorities",
                to="recruitment.application",
            ),
        ),
        migrations.AddField(
            model_name="authoritytorecruit",
            name="converted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authoritytorecruit",
            name="converted_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hired_from_authorities",
                to="payroll.employee",
            ),
        ),
        migrations.CreateModel(
            name="InterviewScorecard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interviewer_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "round",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("interview_1", "First interview"),
                            ("interview_2", "Second interview"),
                        ],
                        default="interview_1",
                        max_length=12,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("strong_yes", "Strong yes"),
                            ("yes", "Yes"),
                            ("maybe", "Maybe / on the fence"),
                            ("no", "No"),
                            ("strong_no", "Strong no"),
                        ],
                        default="maybe",
                        max_length=10,
                    ),
                ),
                ("strengths", models.TextField(blank=True, default="")),
                ("concerns", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="recruitment.application",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_scorecards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "interviewer", "round"),
                        name="uniq_scorecard_per_interviewer_round",
                    )
                ],
            },
        ),
    ]
