# Generated by Django 5.2 on 2026-09-02 08:51

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

# Unami Hiring-SOP tier names (CFO 2026-09-02). Bands left blank for Human
# Capital to fill; Financial Controller anchors Tier 3.
TIER_NAMES = {
    1: 'Junior Associate',
    2: 'Senior Associate / Specialist / Team Lead',
    3: 'Controller',
    4: 'Manager & Senior Manager',
    5: 'C-suite',
}


def seed(apps, schema_editor):
    PositionTier = apps.get_model('recruitment', 'PositionTier')
    JobTitleTier = apps.get_model('recruitment', 'JobTitleTier')
    for n, label in TIER_NAMES.items():
        PositionTier.objects.update_or_create(tier=n, defaults={'name': label})
    t3 = PositionTier.objects.filter(tier=3).first()
    if t3 and not JobTitleTier.objects.filter(title__iexact='Financial Controller').exists():
        JobTitleTier.objects.create(title='Financial Controller', tier=t3)


def unseed(apps, schema_editor):
    JobTitleTier = apps.get_model('recruitment', 'JobTitleTier')
    PositionTier = apps.get_model('recruitment', 'PositionTier')
    JobTitleTier.objects.all().delete()
    PositionTier.objects.filter(tier__in=list(TIER_NAMES)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_email_unique_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('basic_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('basic_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position Tier',
                'verbose_name_plural': 'Position Tiers',
                'ordering': ['tier'],
            },
        ),
        migrations.AddField(
            model_name='authoritytorecruit',
            name='hiring_manager_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='authoritytorecruit',
            name='hiring_manager_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='authoritytorecruit',
            name='proposed_basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='authoritytorecruit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending signatures'), ('approved', 'Approved — all signatories signed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='authoritytorecruit',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorities', to='recruitment.positiontier'),
        ),
        migrations.CreateModel(
            name='JobTitleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='recruitment.positiontier')),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='uniq_jobtitletier_title_ci')],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
