# Generated by Django 5.2 on 2026-05-10 05:52

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_userprofile_title'),
        ('ledger', '0007_alter_journalentry_is_related_party_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FXRevaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_gain_bwp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_loss_bwp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_bwp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluations', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluations_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_revaluations', to='ledger.journalentry')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_revaluations', to='ledger.fiscalperiod')),
            ],
            options={
                'verbose_name': 'FX Revaluation',
                'verbose_name_plural': 'FX Revaluations',
                'ordering': ['-run_date'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FXRevaluationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_foreign', models.DecimalField(decimal_places=2, help_text='Net balance in original currency.', max_digits=18)),
                ('closing_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('book_bwp', models.DecimalField(decimal_places=2, help_text='BWP value currently in the GL.', max_digits=18)),
                ('revalued_bwp', models.DecimalField(decimal_places=2, help_text='BWP value at the closing rate.', max_digits=18)),
                ('revaluation_amount', models.DecimalField(decimal_places=2, help_text='Positive = gain (BWP up), Negative = loss (BWP down).', max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_reval_lines', to='ledger.account')),
                ('currency_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_reval_lines', to='core.currency')),
                ('revaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fx.fxrevaluation')),
            ],
            options={
                'verbose_name': 'FX Revaluation Line',
                'verbose_name_plural': 'FX Revaluation Lines',
                'ordering': ['account__code'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='fxrevaluation',
            constraint=models.UniqueConstraint(fields=('period', 'company'), name='uq_fxreval_period_company'),
        ),
    ]
