# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_fxrevaluationrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fxrevaluationrun',
            new_name='fx_fxrevalu_company_082be0_idx',
            old_name='fx_fxrevalu_company_8a1c1f_idx',
        ),
    ]
