# Generated by Django 5.2 on 2026-05-10 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_journalentry_is_related_party_and_more'),
        ('petty_cash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pettycashvoucher',
            new_name='petty_cash__status_497290_idx',
            old_name='petty_cash_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pettycashvoucher',
            new_name='petty_cash__locatio_6efbde_idx',
            old_name='petty_cash_loc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pettycashvoucher',
            new_name='petty_cash__voucher_e8e266_idx',
            old_name='petty_cash_date_idx',
        ),
        migrations.AlterField(
            model_name='pettycashlocation',
            name='address',
            field=models.TextField(blank=True, help_text='Where the cash physically sits (e.g. "Boardroom safe, 2nd Floor BAC Two, BIH").'),
        ),
        migrations.AlterField(
            model_name='pettycashlocation',
            name='custodian',
            field=models.ForeignKey(blank=True, help_text='Person responsible for the physical cash + voucher pad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashlocation',
            name='petty_cash_account',
            field=models.ForeignKey(help_text='GL account that represents this float (default: 1160).', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_float_for', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='pettycashlocation',
            name='reimbursing_bank_account',
            field=models.ForeignKey(help_text='Bank GL the reimbursement comes out of (default: 1110).', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_reimburses_from', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='pettycashreimbursement',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Optional — FiscalPeriod the reimbursement is anchored to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_reimbursements', to='ledger.fiscalperiod'),
        ),
        migrations.AlterField(
            model_name='pettycashreimbursement',
            name='period_end',
            field=models.DateField(help_text='Last voucher_date eligible for inclusion (inclusive).'),
        ),
        migrations.AlterField(
            model_name='pettycashreimbursement',
            name='period_start',
            field=models.DateField(help_text='First voucher_date eligible for inclusion (inclusive).'),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='description',
            field=models.TextField(help_text='What the cash was for. Required.'),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='expense_account',
            field=models.ForeignKey(help_text='GL expense account this disbursement is charged to.', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_vouchers', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='journal_entry',
            field=models.OneToOneField(blank=True, help_text='DR expense / CR petty cash JE created on approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_voucher', to='ledger.journalentry'),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='payee',
            field=models.CharField(help_text='Who received the cash (free text — staff name, supplier, etc.).', max_length=200),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='receipt_attached',
            field=models.BooleanField(default=False, help_text='Tick when the physical receipt is filed with the voucher.'),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='receipt_reference',
            field=models.CharField(blank=True, help_text='Till slip / invoice number / receipt ref. Optional below P50.', max_length=120),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='reimbursement',
            field=models.ForeignKey(blank=True, help_text='The monthly reimbursement that swept this voucher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='petty_cash.pettycashreimbursement'),
        ),
    ]
