# Generated by Django 5.2 on 2026-07-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_omnitask_performance_points'),
        ('petty_cash', '0002_rename_petty_cash_status_idx_petty_cash__status_497290_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashlocation',
            name='company',
            field=models.ForeignKey(blank=True, help_text="Entity that owns this float. Every petty-cash journal entry is stamped with it, so the expense rolls up into the correct company's books and the historical FY lock applies to backdated vouchers.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_locations', to='core.company'),
        ),
    ]
