# Generated by Django 5.2 on 2026-07-15 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0003_pettycashlocation_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashreimbursement',
            name='fm_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashreimbursement',
            name='fm_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_reimbursements_fm_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashreimbursement',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pettycashreimbursement',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashreimbursement',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_reimbursements_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashreimbursement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_fm', 'Pending FM Review'), ('pending_cfo', 'Pending CFO Approval'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='draft', max_length=12),
        ),
    ]
