# Generated by Django 5.2 on 2026-07-15 12:49

import core.models
import django.db.models.deletion
import petty_cash.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0004_pettycashreimbursement_fm_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashVoucherReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=petty_cash.models._voucher_receipt_path)),
                ('filename', models.CharField(help_text='Original filename as uploaded.', max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_receipts_uploaded', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='petty_cash.pettycashvoucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
