# Generated by Django 5.2 on 2026-08-12 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0008_voucher_expense_account_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashreimbursement',
            name='reimbursement_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='voucher_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
