# Generated by Django 5.2 on 2026-03-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='billing.contact'),
        ),
    ]
