# Generated by Django 5.2 on 2026-05-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_related_party_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='is_related_party',
            field=models.BooleanField(blank=True, default=None, help_text='IAS 24 classification: True if any line on this entry transacts with a related party (director, subsidiary, KMP family etc.). MUST be set before the entry can be submitted for approval — no default, no implicit answer.', null=True),
        ),
        migrations.AlterField(
            model_name='recurringjournalentry',
            name='day_of_period',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month (1-28, use 28 for safe end-of-month) the JE should be dated. Quarterly/annual templates use the same day in the relevant period.'),
        ),
        migrations.AlterField(
            model_name='recurringjournalentry',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional — stop generating after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='recurringjournalentry',
            name='last_generated_for',
            field=models.DateField(blank=True, help_text='High-water mark — date of the last JE generated by this template, prevents duplicate generation.', null=True),
        ),
        migrations.AlterField(
            model_name='recurringjournalentry',
            name='start_date',
            field=models.DateField(help_text='First period that should generate a JE.'),
        ),
    ]
