# Generated by Claude for issue #57 / #58 — adds PAYROLL, COMMITMENT, and
# COMMITMENT_REVERSAL to JournalEntry.JournalType so payroll and procurement
# commitments can post to the GL.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_journalentry_is_related_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(
                choices=[
                    ('sales', 'Sales'),
                    ('purchases', 'Purchases'),
                    ('cash_receipts', 'Cash Receipts'),
                    ('cash_payments', 'Cash Payments'),
                    ('bank', 'Bank'),
                    ('general', 'General'),
                    ('payroll', 'Payroll'),
                    ('commitment', 'PO Commitment'),
                    ('commitment_reversal', 'PO Commitment Reversal'),
                ],
                max_length=25,
            ),
        ),
    ]
