# Generated by Django 5.2 on 2026-07-26 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_posted_je_immutable_triggers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fiscalyear',
            new_name='ledger_fisc_company_8d408f_idx',
            old_name='fiscalyear_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalyear',
            new_name='ledger_fisc_start_d_c2aaff_idx',
            old_name='fiscalyear_date_range_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('current_asset', 'Current Asset'), ('bank', 'Bank'), ('fixed_asset', 'Fixed Asset'), ('accumulated_depreciation', 'Accumulated Depreciation'), ('mid_term_asset', 'Mid-Term Asset'), ('other_asset', 'Other Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long-Term Liability'), ('provision', 'Provision'), ('tax_liability', 'Tax Liability'), ('equity', 'Equity'), ('retained_earnings', 'Retained Earnings'), ('share_capital', 'Share Capital'), ('operating_revenue', 'Operating Revenue'), ('other_revenue', 'Other Revenue'), ('operating_expense', 'Operating Expense'), ('cogs', 'Cost of Goods Sold'), ('expense_depreciation', 'Depreciation Expense'), ('expense_direct_cost', 'Direct Cost'), ('finance_cost', 'Finance Cost'), ('taxation', 'Taxation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='auto_lock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jeclearingrequest',
            name='reason',
            field=models.TextField(help_text='Why this JE / period should be cleared.'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(help_text='Single-date semantics: the end date of the period this JE represents. Use period_start to capture multi-month JEs (e.g. TB imports).'),
        ),
    ]
