# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salvage', '0005_auction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bid',
            new_name='salvage_bid_auction_82b1d7_idx',
            old_name='salv_bid_auction_idx',
        ),
        migrations.RenameIndex(
            model_name='bid',
            new_name='salvage_bid_withdra_77afa7_idx',
            old_name='salv_bid_withdrawn_idx',
        ),
        migrations.RenameIndex(
            model_name='buyerquote',
            new_name='salvage_buy_status_f2b717_idx',
            old_name='salv_bq_status_idx',
        ),
        migrations.RenameIndex(
            model_name='buyerquote',
            new_name='salvage_buy_item_id_c6b5cd_idx',
            old_name='salv_bq_item_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='salvage_sal_sale_da_ec4fcb_idx',
            old_name='salv_sale_date_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='salvage_sal_item_id_574099_idx',
            old_name='salv_sale_item_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageapproval',
            new_name='salvage_sal_status_73204e_idx',
            old_name='salv_appr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageapproval',
            new_name='salvage_sal_kind_3f7164_idx',
            old_name='salv_appr_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageauction',
            new_name='salvage_sal_status_cc6c22_idx',
            old_name='salv_auc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageauction',
            new_name='salvage_sal_item_id_a2879b_idx',
            old_name='salv_auc_item_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageauction',
            new_name='salvage_sal_closes__09863e_idx',
            old_name='salv_auc_closes_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageinspection',
            new_name='salvage_sal_item_id_997651_idx',
            old_name='salv_insp_item_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageinspection',
            new_name='salvage_sal_inspect_c3dd83_idx',
            old_name='salv_insp_at_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageitem',
            new_name='salvage_sal_status_a94985_idx',
            old_name='salvage_sal_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageitem',
            new_name='salvage_sal_conditi_75a40b_idx',
            old_name='salvage_sal_cond_idx',
        ),
        migrations.RenameIndex(
            model_name='salvageitem',
            new_name='salvage_sal_company_0a7cca_idx',
            old_name='salvage_sal_co_idx',
        ),
    ]
