# Generated by Django 5.2 on 2026-09-10 14:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salvage", "0006_sync_model_state_2026_07_26"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ASSESSMENT", "Assessment savings report"),
                            ("PARTS", "Parts purchase summary"),
                        ],
                        max_length=12,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "periods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Month starts (ISO) found in the workbook.",
                    ),
                ),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "reconciliation",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stated-vs-computed lines, as parsed.",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parts_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartsSpend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DEALERSHIP", "Dealership"),
                            ("AFTERMARKET", "Aftermarket"),
                            ("WINDSCREEN", "Windscreen / glass"),
                        ],
                        max_length=12,
                    ),
                ),
                ("supplier", models.CharField(max_length=120)),
                ("month", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spend_rows",
                        to="salvage.partsupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "category", "supplier"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartsHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fy_label", models.CharField(max_length=8)),
                ("month_number", models.PositiveSmallIntegerField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_rows",
                        to="salvage.partsupload",
                    ),
                ),
            ],
            options={
                "ordering": ["fy_label", "month_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartsContractPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_rows",
                        to="salvage.partsupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssessmentSaving",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.DateField(
                        help_text="First day of the month the job was authorised in."
                    ),
                ),
                ("assessment_id", models.CharField(max_length=40)),
                ("reg_no", models.CharField(blank=True, default="", max_length=32)),
                ("vehicle", models.CharField(blank=True, default="", max_length=120)),
                ("repairer", models.CharField(blank=True, default="", max_length=120)),
                ("req_auth_date", models.DateField(blank=True, null=True)),
                (
                    "quote_parts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "quote_labour",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "quote_paint",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "quote_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "report_parts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "report_labour",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "report_paint",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "report_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "saving_parts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "saving_labour",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "saving_paint",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "saving_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "file_saving_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "savings_variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_rows",
                        to="salvage.partsupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "assessment_id"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="partsupload",
            index=models.Index(
                fields=["kind", "-created_at"], name="salvage_par_kind_d84f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partsspend",
            index=models.Index(fields=["month"], name="salvage_par_month_b8f795_idx"),
        ),
        migrations.AddIndex(
            model_name="partsspend",
            index=models.Index(
                fields=["category", "month"], name="salvage_par_categor_518ca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partsspend",
            index=models.Index(
                fields=["supplier"], name="salvage_par_supplie_ab9290_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partshistory",
            index=models.Index(
                fields=["fy_label"], name="salvage_par_fy_labe_ec1652_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partscontractpricing",
            index=models.Index(fields=["month"], name="salvage_par_month_e7378d_idx"),
        ),
        migrations.AddIndex(
            model_name="assessmentsaving",
            index=models.Index(fields=["period"], name="salvage_ass_period_9c3b87_idx"),
        ),
        migrations.AddIndex(
            model_name="assessmentsaving",
            index=models.Index(
                fields=["repairer"], name="salvage_ass_repaire_75f3d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentsaving",
            index=models.Index(
                fields=["assessment_id"], name="salvage_ass_assessm_42645c_idx"
            ),
        ),
    ]
