# Generated by Django 5.2 on 2026-09-10 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_rows_as_uploaded(apps, schema_editor):
    """Everything already in the register got here from a workbook.

    `source` defaults to MANUAL so a typed row is right by default, which
    would otherwise relabel every uploaded row as typed — and then the next
    upload of that month would refuse to replace it.
    """
    for name in ('AssessmentSaving', 'PartsSpend', 'PartsContractPricing'):
        model = apps.get_model('salvage', name)
        model.objects.filter(upload__isnull=False).update(source='UPLOAD')


class Migration(migrations.Migration):

    dependencies = [
        ("salvage", "0007_veritas_parts_savings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsaving",
            name="entered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_savings_entered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmentsaving",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentsaving",
            name="source",
            field=models.CharField(
                choices=[("UPLOAD", "From a workbook"), ("MANUAL", "Typed in")],
                default="MANUAL",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="partscontractpricing",
            name="entered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_pricing_entered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partscontractpricing",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="partscontractpricing",
            name="source",
            field=models.CharField(
                choices=[("UPLOAD", "From a workbook"), ("MANUAL", "Typed in")],
                default="MANUAL",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="partsspend",
            name="entered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts_spend_entered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partsspend",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="partsspend",
            name="source",
            field=models.CharField(
                choices=[("UPLOAD", "From a workbook"), ("MANUAL", "Typed in")],
                default="MANUAL",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="assessmentsaving",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_rows",
                to="salvage.partsupload",
            ),
        ),
        migrations.AlterField(
            model_name="partscontractpricing",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_rows",
                to="salvage.partsupload",
            ),
        ),
        migrations.AlterField(
            model_name="partshistory",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_rows",
                to="salvage.partsupload",
            ),
        ),
        migrations.AlterField(
            model_name="partsspend",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spend_rows",
                to="salvage.partsupload",
            ),
        ),
        migrations.RunPython(mark_existing_rows_as_uploaded,
                             migrations.RunPython.noop),
    ]
