"""Add VOIDED status for salvage items — data-entry correction path.

Kgosi Seboko requested (2026-09-18) an edit + delete facility on the Salvage
Inventory to fix mistakes. Rather than hard-delete rows that have already
posted an intake JE, we void: the row stays for audit, a reversing JE is
posted, and reports exclude status='voided'.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvage', '0009_item_code_autogenerated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salvageitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('available',   'Available'),
                    ('quoted',      'Quoted (offer received)'),
                    ('reserved',    'Reserved'),
                    ('sold',        'Sold'),
                    ('written_off', 'Written off'),
                    ('disposed',    'Disposed'),
                    ('scrapped',    'Scrapped'),
                    ('on_hold',     'On hold'),
                    ('voided',      'Voided (data-entry correction)'),
                ],
                default='available',
                max_length=15,
            ),
        ),
    ]
