# Generated by Django 5.2 on 2026-09-11 19:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0070_ariapopup'),
        ('taskboard', '0030_alter_paymentrequest_graphite_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LargePaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=48, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='What this run is called, e.g. "Claims Payments 10 September 2026".', max_length=200)),
                ('status', models.CharField(choices=[('enriching', 'Collecting claim details'), ('enrich_failed', 'Could not collect claim details'), ('pending_cfo', 'Pending CFO approval'), ('approved', 'Approved by the CFO'), ('rejected', 'Rejected by the CFO'), ('cancelled', 'Cancelled')], db_index=True, default='enriching', max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('progress_note', models.CharField(blank=True, default='', max_length=160)),
                ('enrich_error', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('cfo_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='large_payment_requests', to='core.omnitask')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='large_payment_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='large_payment_requests_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Large payment authorisation request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LargePaymentLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=48)),
                ('payee', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('claim_number', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('enrich_status', models.CharField(choices=[('pending', 'Not collected yet'), ('ok', 'Found in Graphite'), ('not_found', 'No such claim in Graphite'), ('no_claim', 'No claim number on the payment'), ('error', 'Lookup failed')], default='pending', max_length=12)),
                ('insured_name', models.CharField(blank=True, default='', max_length=200)),
                ('policy_number', models.CharField(blank=True, default='', max_length=60)),
                ('claim_status', models.CharField(blank=True, default='', max_length=60)),
                ('claim_sub_status', models.CharField(blank=True, default='', max_length=60)),
                ('date_of_loss', models.DateField(blank=True, null=True)),
                ('loss_description', models.TextField(blank=True, default='')),
                ('reserve_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='large_payment_lines', to='taskboard.paymentrequest')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='large_payments.largepaymentrequest')),
            ],
            options={
                'ordering': ['-amount'],
                'constraints': [models.UniqueConstraint(fields=('request', 'payment_request'), name='uniq_large_payment_line_per_request')],
            },
        ),
    ]
