# Generated by Django 5.2 on 2026-09-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ariapopup'),
        ('large_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='largepaymentrequest',
            name='ceo_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largepaymentrequest',
            name='ceo_decision_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='largepaymentrequest',
            name='ceo_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='largepaymentrequest',
            name='ceo_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='large_payment_ceo_requests', to='core.omnitask'),
        ),
        migrations.AddField(
            model_name='largepaymentrequest',
            name='send_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='largepaymentrequest',
            name='sent_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='largepaymentrequest',
            name='sent_to_ceo_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='largepaymentrequest',
            name='status',
            field=models.CharField(choices=[('enriching', 'Collecting claim details'), ('enrich_failed', 'Could not collect claim details'), ('pending_cfo', 'Pending CFO approval'), ('approved', 'Approved by the CFO'), ('rejected', 'Rejected by the CFO'), ('sent_to_ceo', 'With the CEO for authorisation'), ('question', 'CEO has asked a question'), ('ceo_approved', 'Authorised by the CEO'), ('ceo_rejected', 'Refused by the CEO'), ('cancelled', 'Cancelled')], db_index=True, default='enriching', max_length=20),
        ),
    ]
