# Generated by Django 5.2 on 2026-07-24 08:50

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('engagement_type', models.CharField(choices=[('assurance', 'Assurance'), ('advisory', 'Advisory'), ('investigation', 'Investigation')], default='assurance', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('planning', 'Planning'), ('fieldwork', 'Fieldwork'), ('reporting', 'Reporting'), ('follow_up', 'Follow-up'), ('closed', 'Closed')], default='planning', max_length=20)),
                ('lead_auditor', models.CharField(blank=True, default='', max_length=120)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, default='', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('criteria', models.TextField(help_text='The standard / policy / expectation.')),
                ('condition', models.TextField(help_text='What was found. Must cite supporting evidence.')),
                ('evidence_reference', models.CharField(blank=True, default='', help_text='Workpaper / evidence reference backing the condition.', max_length=200)),
                ('root_cause', models.CharField(choices=[('control_design', 'Control design failure'), ('missing_control', 'Missing control'), ('training_gap', 'Training gap'), ('system_limitation', 'System limitation'), ('tone_at_the_top', 'Tone-at-the-top'), ('resource_constraint', 'Resource constraint'), ('other', 'Other (justify)')], max_length=30)),
                ('root_cause_justification', models.TextField(blank=True, default='', help_text="Required when root cause is 'Other'.")),
                ('effect_category', models.CharField(choices=[('financial', 'Financial'), ('regulatory', 'Regulatory'), ('reputational', 'Reputational'), ('operational', 'Operational'), ('fraud', 'Fraud exposure')], max_length=20)),
                ('effect_detail', models.TextField(help_text='Stated in specific terms — BWP amount/range, regulatory, etc.')),
                ('likelihood', models.PositiveSmallIntegerField(default=1)),
                ('impact', models.PositiveSmallIntegerField(default=1)),
                ('rating', models.CharField(blank=True, default='', max_length=10)),
                ('rating_justification', models.TextField()),
                ('fraud_flag', models.BooleanField(default=False)),
                ('regulatory_tag', models.BooleanField(default=False)),
                ('nbfira_reference', models.CharField(blank=True, default='', help_text='NBFIRA return line item affected, if regulatory.', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('agreed', 'Agreed with management'), ('issued', 'Issued'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='internal_audit.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('risk_accepted', 'Risk accepted')], default='not_started', max_length=20)),
                ('evidence_reference', models.TextField(blank=True, default='', help_text='Evidence of implementation — required to close as Implemented.')),
                ('next_retest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='internal_audit.finding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ManagementResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_text', models.TextField()),
                ('action', models.TextField(help_text='The remediation action management commits to.')),
                ('owner', models.CharField(help_text='Responsible manager.', max_length=120)),
                ('target_date', models.DateField()),
                ('agreed', models.BooleanField(default=False)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='internal_audit.finding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status'], name='internal_au_status_8d9287_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['rating'], name='internal_au_rating_83864f_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['fraud_flag'], name='internal_au_fraud_f_493eee_idx'),
        ),
    ]
