# Generated by Django 5.2 on 2026-09-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0021_employee_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('entity', 'Entity')], default='individual', max_length=12)),
                ('email', models.EmailField(blank=True, help_text='Used to match a login when no staff record is linked.', max_length=254)),
                ('is_current', models.BooleanField(default=True, help_text='Uncheck for a former holder whose shares and grants have fully exited.')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_stakeholders', to='payroll.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShareHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.CharField(help_text='Share class label, e.g. ORB, ORA, PA, ORB+ORA.', max_length=40)),
                ('shares', models.BigIntegerField(default=0)),
                ('usd_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='equity.stakeholder')),
            ],
            options={
                'ordering': ['-shares'],
            },
        ),
        migrations.CreateModel(
            name='EsopGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('exercise_price_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pct_pool', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pct_fd', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lapsed', 'Lapsed'), ('exercised', 'Exercised'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('letter_ref', models.CharField(blank=True, help_text='Letter of Grant reference.', max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='equity.stakeholder')),
            ],
            options={
                'ordering': ['-units'],
            },
        ),
        migrations.CreateModel(
            name='VestingTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vest_date', models.DateField()),
                ('units', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='equity.esopgrant')),
            ],
            options={
                'ordering': ['vest_date'],
            },
        ),
    ]
