# Generated by Django 5.2 on 2026-09-13 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0006_bankstatementline_dedupe_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenricPackRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('complete', 'Complete'), ('partial', 'Complete with blocked reports'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('policy_source', models.CharField(blank=True, help_text='graphite_export | graphite_ro', max_length=40)),
                ('policy_export_name', models.CharField(blank=True, max_length=255)),
                ('prior_export_name', models.CharField(blank=True, max_length=255)),
                ('collection_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('confirmed_gwp_incl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_reinsurance_premium_due', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice_number', models.CharField(blank=True, max_length=30)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('blocked_notes', models.JSONField(blank=True, default=list)),
                ('bank_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genric_pack_runs', to='banking.bankstatement')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genric_pack_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month', '-generated_at'],
                'indexes': [models.Index(fields=['period_year', 'period_month'], name='genric_genr_period__5a7251_idx')],
            },
        ),
    ]
