# Generated by Django 5.2 on 2026-09-13 22:39

import uuid
from django.db import migrations, models


def seed_settings(apps, schema_editor):
    """Write the seed rows at migrate time, not on first read.

    genric.config seeds lazily too, so this is not what makes the code work —
    it is what makes the SCREEN work. Without it the GENRIC Settings admin is
    empty until somebody happens to open the GENRIC page or generate a pack,
    and Add is deliberately disabled, so the person who owns the setting cannot
    populate their own screen. get_or_create, so re-running never overwrites a
    value Finance has edited.
    """
    from genric.config import _DEFAULTS, _DESCRIPTIONS
    GenricSetting = apps.get_model('genric', 'GenricSetting')
    for key, value in _DEFAULTS.items():
        GenricSetting.objects.get_or_create(
            key=key,
            defaults={'value': value, 'description': _DESCRIPTIONS.get(key, '')},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('genric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenricSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'GENRIC Setting',
                'verbose_name_plural': 'GENRIC Settings',
                'ordering': ['key'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_settings, migrations.RunPython.noop),
    ]
