# Generated by Django 5.2 on 2026-07-15 14:40

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0026_posted_je_immutable_triggers"),
        ("payroll", "0011_bank_details_import"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLoanApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[("staff", "Staff Loan"), ("vehicle", "Vehicle Loan")],
                        max_length=10,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "term_months_requested",
                    models.PositiveIntegerField(
                        help_text="Requested number of monthly repayments."
                    ),
                ),
                ("reason", models.TextField(help_text="What the loan is for.")),
                (
                    "monthly_salary_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "vehicle_description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "vehicle_reg",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "blue_book_holder",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alpha_direct", "Alpha Direct"),
                            ("veritas", "Veritas"),
                        ],
                        default="",
                        help_text="Whose name the blue book is held under until the loan clears.",
                        max_length=20,
                    ),
                ),
                (
                    "blue_book_received",
                    models.BooleanField(
                        default=False,
                        help_text="HR confirms the blue book is physically held before disbursing.",
                    ),
                ),
                ("blue_book_returned", models.BooleanField(default=False)),
                ("blue_book_returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_cfo", "Pending CFO approval"),
                            ("approved", "Approved — awaiting signature"),
                            ("signed", "Signed — awaiting HR disbursement"),
                            ("active", "Disbursed — repaying"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cfo_decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_notes", models.TextField(blank=True, default="")),
                ("decline_reason", models.TextField(blank=True, default="")),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "approved_term_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "annual_rate_pct",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("15.5"),
                        help_text="Annual interest rate applied. Pre-filled with the scheme default; the CFO may change it per loan.",
                        max_digits=6,
                    ),
                ),
                ("signature_data_url", models.TextField(blank=True, default="")),
                (
                    "signatory_full_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_ip", models.CharField(blank=True, default="", max_length=45)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disbursement_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Payment / PACOTO reference for the pay-out.",
                        max_length=80,
                    ),
                ),
                (
                    "disbursement_bank_code",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "cfo_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_loans_cfo_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who filled in the application (usually the employee).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_loans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disbursed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_loans_disbursed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_loan_applications",
                        to="payroll.employee",
                    ),
                ),
                (
                    "employee_loan",
                    models.OneToOneField(
                        blank=True,
                        help_text="The live amortising loan created on disbursement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_loan_application",
                        to="payroll.employeeloan",
                    ),
                ),
                (
                    "issuance_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GL entry posted when the loan was issued.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Loan Application",
                "verbose_name_plural": "Staff Loan Applications",
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
