# Generated by Django 5.2 on 2026-07-15 18:39

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLoanRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date this rate takes effect for new loans."
                    ),
                ),
                (
                    "annual_rate_pct",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="The scheme rate applied to new loans = reference + spread.",
                        max_digits=6,
                    ),
                ),
                (
                    "reference_name",
                    models.CharField(
                        default="Bank of Botswana Monetary Policy Rate", max_length=120
                    ),
                ),
                (
                    "reference_rate_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="The public rate this was built from (e.g. the MoPR).",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "spread_pct",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("10.0"),
                        help_text="Margin added to the public reference rate.",
                        max_digits=6,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (Bank of Botswana)"),
                            ("manual", "Manual (set by CFO/Finance)"),
                            ("seed", "Seed (initial value)"),
                        ],
                        default="auto",
                        max_length=8,
                    ),
                ),
                (
                    "source_url",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_loan_rates_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Loan Rate",
                "verbose_name_plural": "Staff Loan Rates",
                "ordering": ["-effective_from", "-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
