# Generated by Django 5.2 on 2026-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_loans", "0003_seed_staff_loan_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffloanapplication",
            name="no_other_loans_declared",
            field=models.BooleanField(
                default=False,
                help_text="Applicant confirms they have no other loans with any bank or financial institution.",
            ),
        ),
        migrations.AddField(
            model_name="staffloanapplication",
            name="purchased_via_veritas",
            field=models.BooleanField(
                default=False,
                help_text="Vehicle loans only: the vehicle was purchased through the Veritas salvage yard.",
            ),
        ),
    ]
