# Generated by Django 5.2 on 2026-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_loans", "0004_staffloanapplication_no_other_loans_declared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffloanapplication",
            name="payment_request_error",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Set when the payment request could NOT be raised, so the loan is not silently disbursed with nobody paying it.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="staffloanapplication",
            name="payment_request_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Omni payment request raised to pay this loan.",
                max_length=48,
            ),
        ),
    ]
