# Generated by Django 5.2 on 2026-09-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_loans", "0005_staffloanapplication_payment_request_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffloanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_cfo", "Pending CFO approval"),
                    ("approved", "Approved — awaiting signature"),
                    ("signed", "Signed — awaiting Finance release"),
                    ("active", "Disbursed — repaying"),
                    ("declined", "Declined"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
    ]
