# Generated by Django 5.2 on 2026-05-10 05:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_dual_authorization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salvage',
            new_name='claims_salv_claim_r_b07a8f_idx',
            old_name='claims_sal_claim_r_idx',
        ),
        migrations.RenameIndex(
            model_name='salvage',
            new_name='claims_salv_status_312965_idx',
            old_name='claims_sal_status_idx',
        ),
        migrations.RenameIndex(
            model_name='subrogation',
            new_name='claims_subr_claim_r_b51089_idx',
            old_name='claims_sub_claim_r_idx',
        ),
        migrations.RenameIndex(
            model_name='subrogation',
            new_name='claims_subr_status_1386df_idx',
            old_name='claims_sub_status_idx',
        ),
        migrations.AlterField(
            model_name='recoveryimportbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (preview)'), ('partially_approved', 'Awaiting second approval'), ('approved', 'Fully approved — ready to commit'), ('committed', 'Committed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='salvage',
            name='asset_description',
            field=models.CharField(help_text='What was salvaged — e.g. "2018 Toyota Hilux 2.4D, reg B-123-ABC"', max_length=300),
        ),
        migrations.AlterField(
            model_name='salvage',
            name='claim_reference',
            field=models.CharField(help_text='Graphite claim reference, e.g. CLM-2026-001234', max_length=80),
        ),
        migrations.AlterField(
            model_name='salvage',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pre-sale estimate of recoverable value.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='subrogation',
            name='actual_recovery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative cash actually recovered to date.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='subrogation',
            name='claim_paid_amount',
            field=models.DecimalField(decimal_places=2, help_text='How much we paid out on the original claim.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='subrogation',
            name='claim_reference',
            field=models.CharField(help_text='Graphite claim reference, e.g. CLM-2026-001234', max_length=80),
        ),
        migrations.AlterField(
            model_name='subrogation',
            name='expected_recovery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Best estimate of recoverable amount.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='subrogation',
            name='third_party_name',
            field=models.CharField(help_text='Person or organisation we are recovering from.', max_length=200),
        ),
    ]
