# Generated by Django 5.2 on 2026-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_rename_claims_sal_claim_r_idx_claims_salv_claim_r_b07a8f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryimportbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (preview)'), ('partially_approved', 'Awaiting second approval'), ('approved', 'Fully approved — ready to commit'), ('committed', 'Committed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
