# Generated by Django 5.2 on 2026-08-17 12:27

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_billapprovalpolicy_tier2_ceiling_and_more'),
        ('claims', '0006_claimform_vault'),
        ('core', '0059_bugreport_status_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubrogationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('received_date', models.DateField()),
                ('method', models.CharField(choices=[('realpay', 'RealPay collection'), ('cash', 'Cash'), ('eft', 'EFT'), ('pos', 'Card / POS'), ('other', 'Other')], default='other', max_length=12)),
                ('reference', models.CharField(blank=True, default='', help_text='Bank / RealPay / receipt reference.', max_length=200)),
                ('realpay_txn_id', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Subrogation Receipt',
                'verbose_name_plural': 'Subrogation Receipts',
                'ordering': ['-received_date', '-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='assessor_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('motor_accident', 'Motor Accident'), ('buildings_combined', 'Buildings Combined'), ('fire_special_perils', 'Fire and Special Perils'), ('money_fidelity', 'Money and Fidelity'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='client_excess',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='date_appointed',
            field=models.DateField(blank=True, help_text='When the lawyer / collector was appointed. Drives ageing.', null=True),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='legal_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='repair_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='salvage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='towing_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='SubrogationPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('external_lawyer', 'External lawyer'), ('internal_lawyer', 'Internal lawyer'), ('debt_collector', 'Debt collector'), ('internal_accountant', 'Internal accountant')], max_length=24)),
                ('contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive panel members cannot be newly appointed, but stay linked to existing cases for history.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subrogation_panel_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subrogation Panel Member',
                'verbose_name_plural': 'Subrogation Panel',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subrogation',
            name='appointed_to',
            field=models.ForeignKey(blank=True, help_text='Who is monitoring / collecting this recovery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subrogations', to='claims.subrogationpanel'),
        ),
        migrations.AddIndex(
            model_name='subrogation',
            index=models.Index(fields=['date_appointed'], name='claims_subr_date_ap_cec2e6_idx'),
        ),
        migrations.AddField(
            model_name='subrogationreceipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subrogation_receipts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subrogationreceipt',
            name='subrogation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='claims.subrogation'),
        ),
        migrations.AddIndex(
            model_name='subrogationpanel',
            index=models.Index(fields=['kind'], name='claims_subr_kind_bd9184_idx'),
        ),
        migrations.AddIndex(
            model_name='subrogationpanel',
            index=models.Index(fields=['is_active'], name='claims_subr_is_acti_551ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='subrogationreceipt',
            index=models.Index(fields=['subrogation', 'received_date'], name='claims_subr_subroga_211192_idx'),
        ),
        migrations.AddConstraint(
            model_name='subrogationreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('realpay_txn_id__gt', '')), fields=('realpay_txn_id',), name='uniq_subrogation_realpay_txn'),
        ),
    ]
