# Generated by Django 5.2 on 2026-08-17 14:33

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_subrogationreceipt_subrogation_assessor_fees_and_more'),
        ('ledger', '0027_sync_model_state_2026_07_26'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubrogationGLConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_income_account', models.ForeignKey(blank=True, help_text='Revenue account that subrogation recoveries credit. Unset = GL posting stays blocked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subrogation_gl_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subrogation GL Configuration',
                'verbose_name_plural': 'Subrogation GL Configuration',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
