# Generated by Django 5.2 on 2026-09-12 12:57

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_subrogationglconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(db_index=True, max_length=24)),
                ('vat_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('opening_claims_payable', models.DecimalField(decimal_places=2, max_digits=18)),
                ('closing_claims_payable', models.DecimalField(decimal_places=2, max_digits=18)),
                ('claims_paid_gross', models.DecimalField(decimal_places=2, max_digits=18)),
                ('claims_paid_excl_vat', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_on_claims_paid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('incurred_claims', models.DecimalField(decimal_places=2, max_digits=18)),
                ('retention_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_ri_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('claim_results', models.JSONField(blank=True, default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_recon_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claims Reconciliation Run',
                'verbose_name_plural': 'Claims Reconciliation Runs',
                'ordering': ['-computed_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
