# Generated by Django 5.2 on 2026-05-10 15:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_disposal_approval'),
    ]

    operations = [
        # State-only since 2026-06-05 audit: 0001_initial was regenerated and
        # now creates these indexes under their final (new) names, so the old
        # names these RenameIndex ops expect never exist on a fresh build
        # ("no such index: assets_aso_kind_status_idx"). Production already
        # applied 0006. Keep the rename in migration STATE only; emit no SQL.
        migrations.SeparateDatabaseAndState(database_operations=[], state_operations=[
            migrations.RenameIndex(
                model_name='assetsignoff',
                new_name='assets_asse_kind_0cf58b_idx',
                old_name='assets_aso_kind_status_idx',
            ),
            migrations.RenameIndex(
                model_name='assetsignoff',
                new_name='assets_asse_due_dat_c92166_idx',
                old_name='assets_aso_due_idx',
            ),
        ]),
        migrations.AlterField(
            model_name='asset',
            name='capital_allowance_method',
            field=models.CharField(choices=[('straight_line', 'Straight-line'), ('reducing_balance', 'Reducing balance')], default='reducing_balance', help_text='Method used for BURS capital allowance computation. Independent from the accounting depreciation method above.', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='capital_allowance_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Annual % rate for capital allowances.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT charged on the original purchase. Informational only when vat_treatment=denied (the VAT is already inside cost).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tax_cost_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, the cost recognised for tax (capital allowance) purposes is capped at this value. BURS sets P 175,000 for passenger motor vehicles.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vat_treatment',
            field=models.CharField(choices=[('standard', 'Standard — input VAT recoverable, cost is net of VAT'), ('denied', 'Denied — VAT capitalised into cost (luxury / passenger vehicle)'), ('zero_exempt', 'Zero-rated or exempt — no VAT')], default='standard', help_text='Standard: VAT is reclaimed via the VAT return and is NOT in cost. Denied: VAT is capitalised into cost (luxury / passenger motor vehicles per VAT Act s.20).', max_length=15),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_capital_allowance_method',
            field=models.CharField(choices=[('straight_line', 'Straight-line'), ('reducing_balance', 'Reducing balance'), ('full_year_one', '100% in year of acquisition')], default='reducing_balance', help_text='Capital allowance method per BURS Income Tax Act.', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_capital_allowance_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Annual rate (% of opening tax NBV for reducing balance, % of cost for straight-line). 25 for plant/vehicles, 2.5 for buildings.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_tax_cost_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, the asset cost is capped at this value for tax purposes. P 175,000 for passenger motor vehicles per BURS.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='is_passenger_vehicle',
            field=models.BooleanField(default=False, help_text='Triggers BURS passenger-vehicle treatment: cost cap P 175,000 for capital allowances + input VAT denial (capitalised into cost).'),
        ),
        migrations.AlterField(
            model_name='assetsignoff',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Set for FULLY_DEPRECIATED_REVIEW. NULL for company-wide SEMI_ANNUAL_COUNT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signoffs', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetsignoff',
            name='counted_assets',
            field=models.PositiveIntegerField(default=0, help_text='Number of assets physically inspected during this count.'),
        ),
        migrations.AlterField(
            model_name='assetsignoff',
            name='discrepancies_text',
            field=models.TextField(blank=True, default='', help_text='Free-text description of any discrepancies found (missing, damaged, location mismatch).'),
        ),
        migrations.AlterField(
            model_name='assetsignoff',
            name='period_label',
            field=models.CharField(help_text='e.g. "H1-2026" for half-year count, or asset tag for fully-depreciated reviews.', max_length=40),
        ),
    ]
