# Generated by Django 5.2 on 2026-07-26 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_custodian_transfer'),
        ('core', '0051_sync_model_state_2026_07_26'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='custodian',
            field=models.CharField(blank=True, default='', help_text='Person or department responsible for the asset (free-text display; mirrors custodian_employee name).', max_length=200),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='recipient_company',
            field=models.ForeignKey(blank=True, help_text='Receiving company on a TRANSFER disposal. Required when disposal_type=transfer and intercompany.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposals_received', to='core.company'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='transfer_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override transfer value for intercompany transfers. NULL = transfer at NBV (no gain/loss). When set, the variance vs NBV posts as gain or loss.', max_digits=18, null=True),
        ),
    ]
