# Generated by Django 5.2 on 2026-09-02 11:58

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_custody_status(apps, schema_editor):
    """Map the EXISTING register onto the new custody control (CFO 2026-09-02).

    Without this, every legacy asset defaults to 'in_stock' — the offboarding
    gate would be blind to assets people already hold, and a legacy asset a
    person holds would pass the 'in_stock' check in create_handover and be
    issued to a second person. Mapping:
      - already held (custodian_employee set)      -> in_use
      - disposed / written off / transferred       -> retired
      - everything else                            -> in_stock (the default)
    """
    Asset = apps.get_model("assets", "Asset")
    Asset.objects.filter(custodian_employee__isnull=False).update(custody_status="in_use")
    Asset.objects.filter(
        status__in=["disposed", "written_off", "transferred", "migrated_duplicate"]
    ).update(custody_status="retired")


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_sync_model_state_2026_07_26"),
        ("core", "0064_unicoinreconexception"),
        ("payroll", "0021_employee_archive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetControlPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material_threshold_bwp",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1500.00"),
                        help_text="Estimated value at or above which a requisition needs the full CFO + Finance-Manager approval. Below it, a single approver signs off. Everything is still registered and logged.",
                        max_digits=18,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Asset Control Policy",
                "verbose_name_plural": "Asset Control Policy",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="custody_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("issued", "Issued — awaiting signed handover"),
                    ("in_use", "In use"),
                    ("returned_spare", "Returned / spare"),
                    ("retired", "Written off / retired"),
                ],
                db_index=True,
                default="in_stock",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_custody_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name="AssetRequisition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requisition_number", models.CharField(max_length=30, unique=True)),
                (
                    "req_type",
                    models.CharField(
                        choices=[
                            ("new_purchase", "New purchase"),
                            ("reissue", "Reissue of a spare"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Make / model / spec of the asset requested.",
                        max_length=300,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Best estimate of value — drives the approval tier.",
                        max_digits=18,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Why the asset is needed.", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_fm_approval", "Awaiting Finance Manager"),
                            ("pending_cfo_approval", "Awaiting CFO"),
                            ("approved", "Approved — ready to hand over"),
                            ("fulfilled", "Fulfilled (handed over)"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=25,
                    ),
                ),
                (
                    "requires_full_gate",
                    models.BooleanField(
                        default=True,
                        help_text="True when value ≥ the material threshold: needs both FM and CFO. False: single sign-off.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("fm_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fm_comment",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("cfo_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cfo_comment",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Type of asset requested.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "cfo_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_requisitions_cfo_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_requisitions",
                        to="core.company",
                    ),
                ),
                (
                    "fm_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_requisitions_fm_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Staff member the asset is for. Picked from the directory, never typed. [Rule 2]",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_requisitions_received",
                        to="payroll.employee",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_requisitions_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_requisitions_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resulting_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issuing_requisitions",
                        to="assets.asset",
                    ),
                ),
                (
                    "spare_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="The returned/spare asset being reissued. Set only when req_type = reissue. [Rule 1]",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reissue_requisitions",
                        to="assets.asset",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_requisitions_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Requisition",
                "verbose_name_plural": "Asset Requisitions",
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AssetHandover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handover_number", models.CharField(max_length=30, unique=True)),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting IT release"),
                            ("it_released", "Released by IT — awaiting Finance"),
                            (
                                "finance_recorded",
                                "Recorded by Finance — awaiting employee",
                            ),
                            ("accepted", "Accepted — asset in use"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "condition_on_issue",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "accessories",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Charger, bag, mouse, etc. included.",
                        max_length=300,
                    ),
                ),
                ("it_released_at", models.DateTimeField(blank=True, null=True)),
                ("it_signature", models.TextField(blank=True, default="")),
                ("finance_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("finance_signature", models.TextField(blank=True, default="")),
                ("employee_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("employee_signature", models.TextField(blank=True, default="")),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handovers",
                        to="assets.asset",
                    ),
                ),
                (
                    "employee_accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_handovers_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_handovers_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "it_released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_handovers_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_handovers_received",
                        to="payroll.employee",
                    ),
                ),
                (
                    "requisition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover",
                        to="assets.assetrequisition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Handover Note",
                "verbose_name_plural": "Asset Handover Notes",
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="assetrequisition",
            index=models.Index(fields=["status"], name="assets_asse_status_407ed3_idx"),
        ),
        migrations.AddIndex(
            model_name="assetrequisition",
            index=models.Index(
                fields=["req_type", "status"], name="assets_asse_req_typ_94f2c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetrequisition",
            index=models.Index(
                fields=["recipient"], name="assets_asse_recipie_0c70f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assethandover",
            index=models.Index(fields=["status"], name="assets_asse_status_9ef042_idx"),
        ),
    ]
