# Generated by Django 5.2 on 2026-09-02 12:58

from decimal import Decimal
from django.db import migrations, models


def bump_default_threshold(apps, schema_editor):
    """CFO 2026-09-02: the gate targets laptop + vehicle movements — assets
    above P5,000. Move any policy row still on the original P1,500 default up to
    P5,000. Idempotent + non-destructive: a threshold the CFO has already set to
    some other value is left untouched."""
    Policy = apps.get_model("assets", "AssetControlPolicy")
    Policy.objects.filter(material_threshold_bwp=Decimal("1500.00")).update(
        material_threshold_bwp=Decimal("5000.00")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_assetcontrolpolicy_asset_custody_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetcontrolpolicy",
            name="material_threshold_bwp",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5000.00"),
                help_text="Estimated value at or above which a requisition needs the full CFO + Finance-Manager approval. Below it, a single approver signs off. Everything is still registered and logged.",
                max_digits=18,
            ),
        ),
        migrations.RunPython(bump_default_threshold, migrations.RunPython.noop),
    ]
