# Generated by Django 5.2 on 2026-09-02 13:17

import assets.control_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_alter_assetcontrolpolicy_material_threshold_bwp"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcontrolpolicy",
            name="it_officer_emails",
            field=models.JSONField(
                default=assets.control_models.default_it_officer_emails,
                help_text="Named IT Asset Officers (by email) who may raise a requisition and sign the IT-release. Superusers / omni administrators are always included.",
            ),
        ),
    ]
