# Generated by Django 5.2 on 2026-07-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_feeds', '0001_initial'),
        ('ledger', '0027_sync_model_state_2026_07_26'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankfeedrun',
            new_name='bank_feeds__outcome_765f0f_idx',
            old_name='bank_feed_outcome_idx',
        ),
        migrations.RenameIndex(
            model_name='bankfeedrun',
            new_name='bank_feeds__config__3b14c0_idx',
            old_name='bank_feed_cfg_start_idx',
        ),
        migrations.AlterField(
            model_name='bankfeedconfig',
            name='bank_account',
            field=models.ForeignKey(help_text='Which GL bank account this feed populates.', on_delete=django.db.models.deletion.PROTECT, related_name='bank_feed_configs', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='bankfeedconfig',
            name='env_prefix',
            field=models.CharField(help_text='Env-var prefix that holds the credentials. E.g. "BANK_FEED_FNB_BWP" reads BANK_FEED_FNB_BWP_HOST, _USERNAME, _PASSWORD or _PRIVATE_KEY_PATH.', max_length=40),
        ),
        migrations.AlterField(
            model_name='bankfeedconfig',
            name='file_pattern',
            field=models.CharField(blank=True, default='*.csv', help_text='Glob to match statement files in remote_path.', max_length=120),
        ),
        migrations.AlterField(
            model_name='bankfeedconfig',
            name='last_run_status',
            field=models.CharField(blank=True, help_text='Outcome of the most recent run.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankfeedconfig',
            name='name',
            field=models.CharField(help_text='Friendly label, e.g. "FNB BWP operating — daily 06:00".', max_length=120),
        ),
        migrations.AlterField(
            model_name='bankfeedconfig',
            name='remote_path',
            field=models.CharField(blank=True, help_text='SFTP folder or API path to pull from.', max_length=240),
        ),
        migrations.AlterField(
            model_name='bankfeedconfig',
            name='schedule_cron',
            field=models.CharField(blank=True, default='0 6 * * *', help_text='Cron expression for the scheduler. Default 06:00 daily.', max_length=60),
        ),
        migrations.AlterField(
            model_name='bankfeedrun',
            name='file_hashes',
            field=models.JSONField(blank=True, default=list, help_text='SHA-256 of every processed file — gives idempotency.'),
        ),
        migrations.AlterField(
            model_name='bankfeedrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='User who manually triggered this run, or null for cron.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_feed_runs_triggered', to=settings.AUTH_USER_MODEL),
        ),
    ]
