import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoAControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause', models.CharField(max_length=20, unique=True,
                    help_text='e.g. A.5.15 — must match ISO 27001:2022.')),
                ('title', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=20,
                    choices=[
                        ('organisational', 'Organisational (A.5)'),
                        ('people', 'People (A.6)'),
                        ('physical', 'Physical (A.7)'),
                        ('technological', 'Technological (A.8)'),
                    ])),
                ('control_type', models.CharField(max_length=20, default='preventive',
                    choices=[
                        ('preventive', 'Preventive'),
                        ('detective', 'Detective'),
                        ('corrective', 'Corrective'),
                    ])),
                ('description', models.TextField(blank=True, default='')),
                ('applicable', models.BooleanField(default=True)),
                ('justification', models.TextField(blank=True, default='',
                    help_text='Why applicable / why excluded. Required by ISO 27001 6.1.3 d).')),
                ('status', models.CharField(default='planned', max_length=20,
                    choices=[
                        ('implemented', 'Implemented'),
                        ('partial', 'Partial'),
                        ('planned', 'Planned'),
                        ('not_implemented', 'Not implemented'),
                        ('excluded', 'Excluded'),
                    ])),
                ('owner', models.CharField(blank=True, default='', max_length=80)),
                ('evidence_ref', models.TextField(blank=True, default='',
                    help_text='Link / path / doc reference.')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('commandment', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='soa_controls', to='iso_compliance.commandment')),
            ],
            options={'ordering': ['clause']},
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('asset', models.CharField(blank=True, default='', max_length=120)),
                ('threat', models.CharField(blank=True, default='', max_length=200)),
                ('vulnerability', models.CharField(blank=True, default='', max_length=200)),
                ('likelihood', models.PositiveSmallIntegerField(default=3)),
                ('impact', models.PositiveSmallIntegerField(default=3)),
                ('treatment', models.CharField(default='reduce', max_length=20,
                    choices=[
                        ('reduce', 'Reduce — implement controls'),
                        ('transfer', 'Transfer — insure / outsource'),
                        ('avoid', 'Avoid — stop the activity'),
                        ('accept', 'Accept — sign off the residual'),
                    ])),
                ('treatment_plan', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(default='open', max_length=20,
                    choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('closed', 'Closed')])),
                ('residual_likelihood', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_impact', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('controls', models.ManyToManyField(blank=True, related_name='risks',
                    to='iso_compliance.soacontrol')),
            ],
            options={'ordering': ['ref']},
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('nonconformity', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('preventive_action', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=80)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('verifier', models.CharField(blank=True, default='', max_length=80)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20,
                    choices=[
                        ('draft', 'Draft'),
                        ('open', 'Open'),
                        ('in_progress', 'In progress'),
                        ('verification', 'Pending verification'),
                        ('closed', 'Closed'),
                    ])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commandment', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='capas', to='iso_compliance.commandment')),
                ('finding', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='capas', to='iso_compliance.auditfinding')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('document_url', models.URLField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=80)),
                ('approver', models.CharField(blank=True, default='', max_length=80)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20,
                    choices=[
                        ('draft', 'Draft'),
                        ('review', 'Under review'),
                        ('approved', 'Approved'),
                        ('retired', 'Retired'),
                    ])),
                ('controls', models.ManyToManyField(blank=True, related_name='policies',
                    to='iso_compliance.soacontrol')),
            ],
            options={'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('captured_by', models.CharField(blank=True, default='', max_length=80)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commandment', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='evidence_items', to='iso_compliance.commandment')),
                ('control', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='evidence_items', to='iso_compliance.soacontrol')),
                ('finding', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='evidence_items', to='iso_compliance.auditfinding')),
            ],
            options={'ordering': ['-captured_at']},
        ),
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('scope', models.TextField(help_text='Scope of this audit (sites, processes, controls).')),
                ('lead_auditor', models.CharField(blank=True, default='', max_length=80)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=20,
                    choices=[
                        ('planned', 'Planned'),
                        ('in_progress', 'In progress'),
                        ('complete', 'Complete'),
                    ])),
                ('summary', models.TextField(blank=True, default='')),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('report_url', models.URLField(blank=True, default='')),
            ],
            options={'ordering': ['-scheduled_for', 'ref']},
        ),
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_date', models.DateField()),
                ('chair', models.CharField(blank=True, default='CFO', max_length=80)),
                ('attendees', models.TextField(blank=True, default='')),
                ('inputs_considered', models.TextField(blank=True, default='')),
                ('decisions', models.TextField(blank=True, default='')),
                ('action_items', models.TextField(blank=True, default='')),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('minutes_url', models.URLField(blank=True, default='')),
            ],
            options={'ordering': ['-review_date']},
        ),
    ]
