# Generated by Django 5.2 on 2026-06-10 15:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0002_soa_risk_capa_policy_evidence_audits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='SOPDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(db_index=True, max_length=80)),
                ('sop_number', models.CharField(blank=True, default='', help_text='Mastersheet reference number where known.', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, default='', max_length=80)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('iso_compliant', models.BooleanField(blank=True, help_text='Mastersheet "ISO 9001:2015 Compliant" flag. NULL = not assessed.', null=True)),
                ('file', models.FileField(max_length=400, upload_to='sop_bank/%Y/')),
                ('file_type', models.CharField(blank=True, default='', max_length=10)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_text', models.TextField(blank=True, default='', help_text='Extracted plain text (docx) - powers search. Empty for video/pdf.')),
                ('source_path', models.CharField(blank=True, default='', help_text='Original Data Room relative path, for traceability.', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft - pending owner approval'), ('obsolete', 'Obsolete')], db_index=True, default='active', max_length=10)),
                ('omni_fit', models.CharField(choices=[('ok', 'Aligned with omni'), ('gap', 'Gap - references replaced process'), ('na', 'Not applicable to omni'), ('unreviewed', 'Not yet reviewed')], default='unreviewed', max_length=12)),
                ('omni_fit_notes', models.TextField(blank=True, default='', help_text='What the omni-alignment review flagged (legacy system refs etc.).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SOP document',
                'ordering': ['department', 'sop_number', 'title'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditfinding',
            new_name='iso_complia_command_c0d57c_idx',
            old_name='iso_finding_cmd_state_idx',
        ),
        migrations.RenameIndex(
            model_name='auditfinding',
            new_name='iso_complia_severit_a6b2ab_idx',
            old_name='iso_finding_sev_state_idx',
        ),
        migrations.AlterField(
            model_name='capa',
            name='nonconformity',
            field=models.TextField(blank=True, default='', help_text='The deviation found.'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='ref',
            field=models.CharField(help_text='Stable reference e.g. CAPA-001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='root_cause',
            field=models.TextField(blank=True, default='', help_text='5-whys / fishbone result.'),
        ),
        migrations.AlterField(
            model_name='commandment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internalaudit',
            name='ref',
            field=models.CharField(help_text='e.g. IA-2026-Q3', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='managementreview',
            name='inputs_considered',
            field=models.TextField(blank=True, default='', help_text='Status of actions; changes; performance; nonconformities; audit results; risks.'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='code',
            field=models.CharField(help_text='e.g. POL-INFOSEC-001', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='ref',
            field=models.CharField(help_text='Stable reference e.g. R-001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='soacontrol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='sopacknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_acknowledgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sopdocument',
            index=models.Index(fields=['department', 'status'], name='iso_complia_departm_095c02_idx'),
        ),
        migrations.AddField(
            model_name='sopacknowledgement',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='iso_compliance.sopdocument'),
        ),
        migrations.AddConstraint(
            model_name='sopacknowledgement',
            constraint=models.UniqueConstraint(fields=('sop', 'user'), name='uniq_sop_ack_per_user'),
        ),
    ]
