# Generated by Django 5.2 on 2026-08-13 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0004_sopdocument_doc_type_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('data_types', models.TextField(blank=True, default='')),
                ('special_category', models.BooleanField(default=False)),
                ('risk_rating', models.CharField(choices=[('P1', 'P1 — High risk'), ('P2', 'P2 — Medium risk'), ('P3', 'P3 — Low risk')], default='P3', max_length=2)),
                ('residual_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('conditions_open', 'Conditions open'), ('approved', 'Approved'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('dpo_reviewer', models.CharField(blank=True, default='', max_length=120)),
                ('dpo_signed', models.BooleanField(default=False)),
                ('dpo_signed_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_officer', models.CharField(blank=True, default='', max_length=120)),
                ('compliance_signed', models.BooleanField(default=False)),
                ('compliance_signed_at', models.DateTimeField(blank=True, null=True)),
                ('cfo_signed', models.BooleanField(default=False)),
                ('cfo_signed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DPIACondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('pilot', 'Pilot (current scope)'), ('rollout', 'Before customer rollout')], default='pilot', max_length=8)),
                ('text', models.CharField(max_length=400)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('dpia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='iso_compliance.dpia')),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
    ]
