# Generated by Django 5.2 on 2026-08-13 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0005_dpia_dpiacondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpia',
            name='cross_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpia',
            name='cross_border_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='data_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dpia',
            name='data_other',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='data_subjects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='date_opened',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpia',
            name='decision',
            field=models.CharField(blank=True, choices=[('proceed', 'Proceed'), ('proceed_conditions', 'Proceed with conditions'), ('do_not_proceed', 'Do not proceed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dpia',
            name='department',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='dpia',
            name='disposal_method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='dpia_ref',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dpia',
            name='dpo_review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='external_vendors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='how_informed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='how_rights',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='internal_sharing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='lawful_basis',
            field=models.CharField(blank=True, choices=[('contract', 'Contract'), ('legal_obligation', 'Legal obligation'), ('legitimate_interests', 'Legitimate interests'), ('consent', 'Consent'), ('vital_interests', 'Vital interests'), ('public_task', 'Public task')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='dpia',
            name='lawful_basis_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='new_change_existing',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('change', 'Change'), ('existing', 'Existing')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dpia',
            name='planned_go_live',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dpia',
            name='process_owner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dpia',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='retention_period',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='retention_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='security_controls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dpia',
            name='security_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='special_category_basis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='special_category_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='statement_of_alignment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='system_used',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dpia',
            name='triggers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dpia',
            name='vendor_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpia',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dpia',
            name='vulnerable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpia',
            name='vulnerable_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DPIARisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('what_could_go_wrong', models.TextField(blank=True, default='')),
                ('controls', models.TextField(blank=True, default='')),
                ('likelihood', models.PositiveSmallIntegerField(default=1)),
                ('impact', models.PositiveSmallIntegerField(default=1)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('residual_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_band', models.CharField(blank=True, default='', max_length=40)),
                ('dpia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='iso_compliance.dpia')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
