# Generated by Django 5.2 on 2026-09-09 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0006_dpia_cross_border_dpia_cross_border_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkRequirement',
            fields=[
                ('requirement_code', models.CharField(help_text="e.g. 'S48.1' — matches the DPO spreadsheet", max_length=30, primary_key=True, serialize=False)),
                ('requirement_name', models.TextField(help_text='The actual DPA 2024 clause text')),
                ('plain_description', models.TextField(blank=True, default='', help_text="The DPO's plain-language explanation")),
                ('category', models.CharField(choices=[('principles', 'Principles'), ('lawful_basis', 'Lawful basis for processing'), ('consent', 'Consent'), ('special_categories', 'Special categories of personal data'), ('childrens_data', "Processing of children's data"), ('data_subject_rights', 'Rights of the data subject'), ('controller_processor', 'Controller and processor'), ('transfers', 'Transfers of personal data'), ('security_breach', 'Security and breach notification'), ('dpo_dpia', 'Data protection officer and DPIA')], default='principles', max_length=40)),
                ('source_act', models.CharField(default='Botswana DPA 2024', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'requirement_code'],
            },
        ),
        migrations.CreateModel(
            name='InternalPolicy',
            fields=[
                ('policy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('version', models.CharField(blank=True, default='', max_length=20)),
                ('document_link', models.CharField(blank=True, default='', max_length=500)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('is_placeholder', models.BooleanField(default=False, help_text='Auto-created from a requirement reference; DPO to complete.')),
                ('is_gap', models.BooleanField(default=False, help_text='The DPO flagged this policy as a known gap in the mapping.')),
                ('gap_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dpa_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'internal policies',
                'ordering': ['policy_name'],
            },
        ),
        migrations.CreateModel(
            name='PiiFieldReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('flagged', 'Flagged'), ('confirmed', 'Confirmed personal data'), ('dismissed', 'Not personal data')], default='needs_review', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['app_label', 'model_name', 'field_name'],
                'unique_together': {('app_label', 'model_name', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='RequirementPolicyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specific_section', models.CharField(blank=True, default='', help_text="e.g. 'Section 9' or 'Clause 3.7'", max_length=120)),
                ('confirmed', models.BooleanField(default=False, help_text='DPO has confirmed this auto-parsed link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='iso_compliance.internalpolicy')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='iso_compliance.frameworkrequirement')),
            ],
            options={
                'ordering': ['requirement__requirement_code'],
                'unique_together': {('requirement', 'policy', 'specific_section')},
            },
        ),
        migrations.AddField(
            model_name='frameworkrequirement',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='requirements', through='iso_compliance.RequirementPolicyLink', to='iso_compliance.internalpolicy'),
        ),
    ]
