# Generated by Django 5.2 on 2026-09-09 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0007_policy_library_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalBasisRule',
            fields=[
                ('rule_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('match_department', models.CharField(blank=True, default='', help_text='blank = any department', max_length=80)),
                ('match_purpose_keywords', models.JSONField(default=list, help_text='list of keywords, e.g. ["claim","policy servicing"]')),
                ('suggested_basis', models.CharField(choices=[('consent', 'Consent'), ('contract', 'Performance of a contract'), ('legal_obligation', 'Legal obligation'), ('vital_interests', 'Vital interests'), ('public_task', 'Public task'), ('legitimate_interests', 'Legitimate interests')], max_length=30)),
                ('reason_template', models.TextField(help_text='e.g. "This looks like {purpose}, which usually relies on performance of a contract."')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework_requirement', models.ForeignKey(blank=True, help_text='the lawful_basis requirement this cites', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basis_rules', to='iso_compliance.frameworkrequirement')),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='RulebookRequirement',
            fields=[
                ('requirement_id', models.CharField(help_text='e.g. DPA-s48, POL-AIGOV-S9', max_length=40, primary_key=True, serialize=False)),
                ('source', models.CharField(help_text='e.g. "Botswana DPA 2024, s.48"', max_length=200)),
                ('description', models.TextField()),
                ('trigger_field', models.CharField(help_text='ROPA field that activates this rule', max_length=80)),
                ('trigger_value', models.CharField(blank=True, default='', max_length=120)),
                ('satisfying_evidence', models.TextField(blank=True, default='', help_text='machine hint: "<field> filled" or "vendor.<field>=<value>"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rulebook_rules', to='iso_compliance.frameworkrequirement')),
            ],
            options={
                'ordering': ['requirement_id'],
            },
        ),
        migrations.CreateModel(
            name='VendorRegister',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=200, unique=True)),
                ('dpa_contract_signed', models.BooleanField(default=False)),
                ('sub_processors_used', models.BooleanField(default=False)),
                ('sub_processor_names', models.TextField(blank=True, default='')),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('safeguards_on_file', models.TextField(blank=True, default='')),
                ('suggested_risk_score', models.IntegerField(default=0)),
                ('suggested_risk_reason', models.JSONField(default=list, help_text='itemised contributing factors')),
                ('suggested_risk_level', models.CharField(blank=True, default='', max_length=10)),
                ('confirmed_risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='', max_length=10)),
                ('risk_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_vendor_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='RopaEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_table', models.CharField(blank=True, default='', max_length=150)),
                ('source_field', models.CharField(blank=True, default='', max_length=150)),
                ('detected_data_category', models.CharField(blank=True, default='', max_length=60)),
                ('date_last_reviewed', models.DateTimeField(auto_now=True)),
                ('flag_status', models.CharField(choices=[('draft_needs_review', 'Draft — needs review'), ('confirmed', 'Confirmed'), ('flagged_incomplete', 'Flagged — incomplete')], default='draft_needs_review', max_length=25)),
                ('flag_reasons', models.JSONField(default=list, help_text='unresolved rulebook requirement_ids')),
                ('suggested_lawful_basis', models.CharField(blank=True, default='', max_length=30)),
                ('suggested_lawful_basis_reason', models.TextField(blank=True, default='')),
                ('department', models.CharField(blank=True, default='', max_length=80)),
                ('processing_activity', models.CharField(blank=True, default='', max_length=200)),
                ('purpose_of_processing', models.TextField(blank=True, default='')),
                ('data_subject_categories', models.TextField(blank=True, default='')),
                ('confirmed_lawful_basis', models.CharField(blank=True, choices=[('consent', 'Consent'), ('contract', 'Performance of a contract'), ('legal_obligation', 'Legal obligation'), ('vital_interests', 'Vital interests'), ('public_task', 'Public task'), ('legitimate_interests', 'Legitimate interests')], default='', max_length=30)),
                ('lawful_basis_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_third_parties', models.TextField(blank=True, default='')),
                ('cross_border_transfer', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('cross_border_details', models.TextField(blank=True, default='')),
                ('retention_period', models.CharField(blank=True, default='', max_length=200)),
                ('security_measures', models.TextField(blank=True, default='')),
                ('description_of_risks', models.TextField(blank=True, default='')),
                ('dpia_required', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], default='', max_length=8)),
                ('dpia_status', models.CharField(blank=True, default='', max_length=120)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ropa_entries', to=settings.AUTH_USER_MODEL)),
                ('lawful_basis_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ropa_bases', to=settings.AUTH_USER_MODEL)),
                ('processor_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ropa_entries', to='iso_compliance.vendorregister')),
            ],
            options={
                'ordering': ['flag_status', 'department', 'source_table', 'source_field'],
                'unique_together': {('source_table', 'source_field')},
            },
        ),
    ]
