# Generated by Django 5.2 on 2026-09-09 11:34

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0008_ropa_registry'),
        ('payroll', '0021_employee_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionsScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('customer', 'Customer / policyholder'), ('supplier', 'Supplier / vendor'), ('claimant', 'Claimant / third party'), ('staff', 'Employee'), ('other', 'Other counterparty')], default='customer', max_length=10)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_ref', models.CharField(blank=True, default='', help_text='Policy number, supplier code or claim number — NOT an Omang.', max_length=100)),
                ('list_source', models.CharField(default='UNSC', help_text='Which list was searched, e.g. UNSC Consolidated.', max_length=100)),
                ('list_version', models.CharField(blank=True, default='', help_text='List date/version searched — what makes the search repeatable.', max_length=60)),
                ('result', models.CharField(choices=[('clear', 'Clear — no match'), ('possible', 'Possible match — under review'), ('match', 'Confirmed match')], default='clear', max_length=10)),
                ('pep_status', models.CharField(choices=[('none', 'Not a PEP'), ('pep', 'Politically Exposed Person'), ('associate', 'Close associate / family of a PEP'), ('unchecked', 'Not yet assessed')], default='unchecked', max_length=10)),
                ('screened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reported_to_fia_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanctions / PEP Screening',
                'verbose_name_plural': 'Sanctions / PEP Screenings',
                'ordering': ['-screened_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SuspiciousTransactionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_ref', models.CharField(blank=True, default='', max_length=100)),
                ('detected_on', models.DateField(db_index=True)),
                ('description', models.TextField(help_text='What was suspicious, in plain words.')),
                ('status', models.CharField(choices=[('detected', 'Detected — not yet filed'), ('filed', 'Filed with the FIA'), ('closed', 'Closed — no report required')], default='detected', max_length=10)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('fia_reference', models.CharField(blank=True, default='', max_length=100)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='iso_compliance.sanctionsscreening')),
            ],
            options={
                'verbose_name': 'Suspicious Transaction Report',
                'verbose_name_plural': 'Suspicious Transaction Reports',
                'ordering': ['-detected_on'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AMLTrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.CharField(default='AML/CFT awareness', max_length=200)),
                ('completed_on', models.DateField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='compliance/aml-training/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_training', to='payroll.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AML Training Record',
                'verbose_name_plural': 'AML Training Records',
                'ordering': ['-completed_on'],
                'abstract': False,
                'indexes': [models.Index(fields=['employee', 'completed_on'], name='amltrain_emp_when_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_quarter', models.PositiveSmallIntegerField(help_text='1-4, calendar quarter.')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('document', models.FileField(blank=True, help_text='The pack itself. A report with no document is not a report.', null=True, upload_to='compliance/board-packs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to EXCO'), ('noted', 'Noted by the Board')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.TextField(blank=True, default='', help_text='Who it went to, one address per line.')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Report to EXCO',
                'verbose_name_plural': 'Compliance Reports to EXCO',
                'ordering': ['-period_year', '-period_quarter'],
                'abstract': False,
                'unique_together': {('period_year', 'period_quarter')},
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_on', models.DateField(db_index=True)),
                ('complainant', models.CharField(max_length=200)),
                ('policy_ref', models.CharField(blank=True, default='', max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('social', 'Social media'), ('regulator', 'Via the regulator'), ('other', 'Other')], default='email', max_length=12)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('escalated', 'Escalated to the regulator')], default='open', max_length=14)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Complaint',
                'verbose_name_plural': 'Customer Complaints',
                'ordering': ['-received_on'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'received_on'], name='complaint_status_when_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegulatoryBreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regulator', models.CharField(default='NBFIRA', max_length=60)),
                ('rule', models.CharField(blank=True, default='', help_text='The rule, section or licence condition breached.', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('discovered_on', models.DateField(db_index=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('remediated', 'Remediated'), ('closed', 'Closed')], default='open', max_length=12)),
                ('reported_to_regulator_at', models.DateTimeField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, default='')),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regulatory Breach',
                'verbose_name_plural': 'Regulatory Breaches',
                'ordering': ['-discovered_on'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'severity'], name='regbreach_status_sev_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='sanctionsscreening',
            index=models.Index(fields=['result'], name='sancscr_result_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionsscreening',
            index=models.Index(fields=['pep_status'], name='sancscr_pep_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionsscreening',
            index=models.Index(fields=['subject_type', 'screened_at'], name='sancscr_type_when_idx'),
        ),
        migrations.AddIndex(
            model_name='suspicioustransactionreport',
            index=models.Index(fields=['status'], name='str_status_idx'),
        ),
    ]
