# Generated by Django 5.2 on 2026-09-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iso_compliance', '0009_sanctionsscreening_suspicioustransactionreport_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compliancereport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='kind',
            field=models.CharField(choices=[('aml', 'AML/CFT compliance'), ('data_prot', 'Data protection (DPO)')], db_index=True, default='aml', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='compliancereport',
            unique_together={('kind', 'period_year', 'period_quarter')},
        ),
    ]
