'use client'

/**
 * /commandments — the "10 Commandments" page, now monthly-rotating.
 *
 * CFO directive 2026-05-18: expand from 3 → 9 audiences (Finance,
 * Claims, Underwriting + HR, Admin, IT, Healthcare, Insurance,
 * Software Devs). Content is generated by Aria once per month
 * per category and cached server-side; the frontend just renders.
 *
 * The page renders curated seed content on the first paint, then
 * swaps to the Aria payload as soon as `/api/v1/commandments/<cat>/`
 * resolves. So the cold-page user never sees a spinner-only state.
 */
import { useEffect, useMemo, useState } from 'react'
import { useTheme } from '@/contexts/ThemeContext'
import { TopBar } from '@/components/layout/TopBar'
import {
  Sparkles, Flame, Skull, Eye, Users, ClipboardList, Server,
  HeartPulse, Shield, Code2, Loader2, RefreshCw,
} from 'lucide-react'
import { apiFetch } from '@/lib/api'

interface Commandment { n: number; short: string; long: string }
interface ApiResponse {
  category:     string
  label:        string
  tag:          string
  tone:         string
  year_month:   string
  source:       'cache' | 'deepseek' | 'seed'
  commandments: Commandment[]
}

// Static category metadata — mirrors core/commandments.CATEGORIES so
// the page can render tabs before the API responds.
const CATEGORIES: { key: string; label: string; tag: string; tone: string; icon: any }[] = [
  { key: 'finance',      label: 'Finance',         tag: 'numbers',    tone: '#F07F00', icon: Sparkles },
  { key: 'claims',       label: 'Claims',          tag: 'service',    tone: '#00C9B7', icon: Flame },
  { key: 'underwriting', label: 'Underwriting',    tag: 'risk',       tone: '#7C3AED', icon: Eye },
  { key: 'hr',           label: 'Human Resources', tag: 'people',     tone: '#16A34A', icon: Users },
  { key: 'admin',        label: 'Admin',           tag: 'operations', tone: '#0EA5E9', icon: ClipboardList },
  { key: 'it',           label: 'IT',              tag: 'systems',    tone: '#6366F1', icon: Server },
  { key: 'healthcare',   label: 'Healthcare',      tag: 'cover',      tone: '#EC4899', icon: HeartPulse },
  { key: 'insurance',    label: 'Insurance',       tag: 'industry',   tone: '#0D1B2A', icon: Shield },
  { key: 'software',     label: 'Software Dev',    tag: 'engineering',tone: '#F43F5E', icon: Code2 },
]

function fmtMonth(ym: string): string {
  const [y, m] = ym.split('-')
  if (!y || !m) return ym
  return new Date(parseInt(y), parseInt(m) - 1, 1).toLocaleString('en-BW', { month: 'long', year: 'numeric' })
}

export default function CommandmentsPage() {
  const { theme, isFun } = useTheme()
  const [active, setActive] = useState<string>('finance')
  const [byCategory, setByCategory] = useState<Record<string, ApiResponse>>({})
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const meta = useMemo(() => CATEGORIES.find(c => c.key === active) || CATEGORIES[0], [active])

  useEffect(() => {
    let cancelled = false
    if (byCategory[active]) return  // already loaded
    setLoading(true)
    setError(null)
    apiFetch<ApiResponse>(`/commandments/${active}/`)
      .then(r => { if (!cancelled) setByCategory(prev => ({ ...prev, [active]: r })) })
      .catch(e => { if (!cancelled) setError(e instanceof Error ? e.message : 'Failed to load') })
      .finally(() => { if (!cancelled) setLoading(false) })
    return () => { cancelled = true }
  }, [active])    // eslint-disable-line react-hooks/exhaustive-deps

  const payload = byCategory[active]
  const list = payload?.commandments || []

  return (
    <div className="min-h-screen relative overflow-hidden" style={{ background: theme.bg }}>
      <TopBar title="The 10 Commandments" />

      {/* Fun-mode haze */}
      {isFun && (
        <>
          <div className="absolute top-20 -left-32 w-[40rem] h-[40rem] rounded-full pointer-events-none"
               style={{ background: 'radial-gradient(circle, rgba(240,127,0,0.18), transparent 70%)', filter: 'blur(80px)' }} />
          <div className="absolute -bottom-40 -right-32 w-[50rem] h-[50rem] rounded-full pointer-events-none"
               style={{ background: 'radial-gradient(circle, rgba(124,58,237,0.20), transparent 70%)', filter: 'blur(80px)' }} />
        </>
      )}

      <div className="relative p-4 lg:p-6 max-w-[1100px] mx-auto space-y-6">
        {/* Hero */}
        <div className="relative overflow-hidden rounded-2xl"
             style={{
               background: isFun
                 ? 'linear-gradient(135deg, #0A0B1E 0%, #161434 60%, #1F1547 100%)'
                 : '#FFFFFF',
               border: isFun ? '1px solid rgba(255,255,255,0.08)' : '1px solid rgba(13,27,42,0.06)',
               boxShadow: isFun
                 ? '0 0 60px -10px rgba(240,127,0,0.25)'
                 : '0 10px 40px -12px rgba(13,27,42,0.12)',
             }}>
          {!isFun && (
            <div className="absolute -top-40 -right-32 w-[44rem] h-[44rem] rounded-full pointer-events-none"
                 style={{
                   background: `radial-gradient(circle at 30% 30%, rgba(240,127,0,0.18) 0%, transparent 55%),
                                radial-gradient(circle at 70% 60%, rgba(124,58,237,0.18) 0%, transparent 55%)`,
                   filter: 'blur(40px)',
                 }} />
          )}

          <div className="relative px-6 py-10 lg:px-12 lg:py-14"
               style={{ color: isFun ? '#FFFFFF' : '#0D1B2A' }}>
            <div className="flex items-center gap-2 mb-4">
              <Skull className="w-4 h-4" style={{ color: meta.tone }} strokeWidth={2} />
              <span className="text-[11px] uppercase tracking-[0.25em] font-semibold"
                    style={{ color: isFun ? 'rgba(255,255,255,0.6)' : '#6B7280' }}>
                Alpha Direct Culture · {fmtMonth(payload?.year_month || new Date().toISOString().slice(0, 7))}
              </span>
            </div>

            <h1 className="font-display-tight font-bold leading-[0.92] mb-5"
                style={{ fontSize: 'clamp(2.5rem, 5vw, 4.5rem)' }}>
              The Ten <span className="italic bg-clip-text text-transparent"
                           style={{ backgroundImage: 'linear-gradient(120deg, currentColor 0%, #F07F00 60%, #FF9A2E 100%)' }}>
                Commandments.
              </span>
            </h1>

            <p className="font-display text-lg italic max-w-2xl leading-relaxed"
               style={{ color: isFun ? 'rgba(255,255,255,0.7)' : '#374151' }}>
              Refreshed every month by Aria. Curated for nine audiences. The vibe is jokey;
              the numbers, decisions and audit trails are not.
            </p>

            {payload && (
              <div className="inline-flex items-center gap-2 mt-5 px-3 py-1 rounded-full text-[11px] font-semibold"
                   style={{
                     background: isFun ? 'rgba(255,255,255,0.08)' : '#F3F4F6',
                     color: isFun ? 'rgba(255,255,255,0.7)' : '#374151',
                   }}>
                <Sparkles className="w-3 h-3" />
                {payload.source === 'deepseek' && 'Freshly generated this month'}
                {payload.source === 'cache'    && `Cached for ${fmtMonth(payload.year_month)}`}
                {payload.source === 'seed'     && 'Curated fallback (AI offline)'}
              </div>
            )}
          </div>
        </div>

        {/* Category selector — 9 pills, wraps on small screens */}
        <div className="flex flex-wrap gap-2">
          {CATEGORIES.map(c => {
            const isActive = active === c.key
            return (
              <button key={c.key} onClick={() => setActive(c.key)}
                      className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold transition-all"
                      style={{
                        background: isActive
                          ? (isFun ? `linear-gradient(135deg, ${c.tone}, ${c.tone}cc)` : c.tone)
                          : (isFun ? 'rgba(255,255,255,0.05)' : '#FFFFFF'),
                        color: isActive ? '#FFFFFF' : (isFun ? 'rgba(255,255,255,0.7)' : '#374151'),
                        border: isActive
                          ? `1px solid ${c.tone}`
                          : (isFun ? '1px solid rgba(255,255,255,0.1)' : '1px solid rgba(13,27,42,0.08)'),
                        boxShadow: isActive && isFun ? `0 0 20px ${c.tone}66` : undefined,
                      }}>
                <c.icon className="w-3.5 h-3.5" strokeWidth={2} />
                {c.label}
                <span className="text-[10px] opacity-70 uppercase tracking-wider">{c.tag}</span>
              </button>
            )
          })}
        </div>

        {error && (
          <div className="rounded-lg p-3 text-sm"
               style={{ background: '#fef2f2', border: '1px solid #fecaca', color: '#b91c1c' }}>
            {error}
          </div>
        )}

        {loading && !payload && (
          <div className="rounded-2xl p-8 flex items-center justify-center gap-2"
               style={{ background: theme.card, border: `1px solid ${theme.cardBdr}`, color: theme.t2 }}>
            <Loader2 className="w-4 h-4 animate-spin" /> Loading {meta.label} commandments…
          </div>
        )}

        {/* Commandments grid */}
        {list.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {list.map(c => (
              <div key={c.n}
                   className="rounded-xl p-5 transition-all hover:-translate-y-0.5"
                   style={{
                     background: isFun ? 'rgba(255,255,255,0.04)' : '#FFFFFF',
                     border: isFun
                       ? `1px solid rgba(255,255,255,0.08)`
                       : '1px solid rgba(13,27,42,0.06)',
                     boxShadow: isFun
                       ? `0 0 30px -10px ${meta.tone}33`
                       : '0 1px 3px rgba(13,27,42,0.06)',
                   }}>
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 font-display-tight font-bold text-lg"
                       style={{
                         background: isFun ? `${meta.tone}22` : `${meta.tone}11`,
                         color: meta.tone,
                         boxShadow: isFun ? `0 0 16px ${meta.tone}55` : 'none',
                       }}>
                    {c.n}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="font-display text-base font-bold leading-snug mb-1"
                         style={{ color: isFun ? '#FFFFFF' : '#0D1B2A' }}>
                      {c.short}
                    </div>
                    <div className="text-xs leading-relaxed"
                         style={{ color: isFun ? 'rgba(255,255,255,0.6)' : '#6B7280' }}>
                      {c.long}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Footer disclaimer */}
        <div className="rounded-lg p-4 text-xs text-center"
             style={{
               background: isFun ? 'rgba(255,255,255,0.04)' : '#F8F9FA',
               border: isFun ? '1px solid rgba(255,255,255,0.08)' : '1px solid rgba(13,27,42,0.06)',
               color: isFun ? 'rgba(255,255,255,0.55)' : '#6B7280',
             }}>
          Refreshed monthly by Aria, cached per audience. The accounting rules,
          segregation of duties, approval gates and audit trails in Omni stay strict
          regardless of which mode you&apos;re in.
        </div>
      </div>
    </div>
  )
}
