# Generated by Django 5.2 on 2026-05-10 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('po_bill_mismatch', 'PO ↔ Bill mismatch (variance)'), ('banking_change', 'Vendor banking detail change'), ('ai_fraud_cue', 'AI fraud cue'), ('ai_anomaly', 'AI anomaly'), ('unmatched_payment', 'Payment against unmatched bill'), ('back_dated_bill', 'Bill dated before PO approval'), ('vendor_mismatch', 'Bill supplier ≠ PO supplier'), ('bill_no_po', 'Vendor bill without PO reference'), ('open_po_at_close', 'Open PO blocking period close'), ('fx_rate_stale', 'FX rate older than threshold'), ('manual', 'Manual flag'), ('other', 'Other')], default='other', max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source_app', models.CharField(blank=True, default='', max_length=50)),
                ('source_model', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_label', models.CharField(blank=True, default='', help_text='e.g. "BILL-2026-000123" or "VendorBankAccount #abc-123".', max_length=200)),
                ('requires_role', models.CharField(choices=[('any', 'Anyone in finance'), ('dept_manager', 'Department Manager'), ('finance_manager', 'Finance Manager (or CFO)'), ('cfo', 'CFO only')], default='any', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissal_reason', models.TextField(blank=True, default='')),
                ('linker_notified_at', models.DateTimeField(blank=True, null=True)),
                ('linker_response', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_created', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_dismissed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exception',
                'verbose_name_plural': 'Exceptions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', '-created_at'], name='exceptions__status_14f3c6_idx'), models.Index(fields=['exception_type'], name='exceptions__excepti_5a1f8b_idx'), models.Index(fields=['source_app', 'source_model', 'source_id'], name='exceptions__source__5bd24f_idx')],
            },
        ),
    ]
