# Generated by Django 5.2 on 2026-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="M365AccountSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("alerted", models.BooleanField(default=False)),
                (
                    "is_agent",
                    models.BooleanField(
                        default=False,
                        help_text="insurance.co.bw — UniCoin agent, not an HR alert.",
                    ),
                ),
            ],
            options={
                "ordering": ("-first_seen_at",),
            },
        ),
    ]
