# Generated by Django 5.2 on 2026-07-13 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_reconciliation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APAgingSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("as_of_date", models.DateField(db_index=True)),
                ("company_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "source_filename",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("vendor_count", models.PositiveIntegerField(default=0)),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("currency_code", models.CharField(default="BWP", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APAgingSnapshotLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_name", models.CharField(max_length=200)),
                (
                    "b_0_30",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "b_31_60",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "b_61_90",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "b_90_plus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
            ],
            options={
                "ordering": ["-total", "vendor_name"],
            },
        ),
        migrations.RenameIndex(
            model_name="reconciliation",
            new_name="reporting_r_status_1e26e2_idx",
            old_name="recn_status_sev_idx",
        ),
        migrations.RenameIndex(
            model_name="reconciliation",
            new_name="reporting_r_company_b58839_idx",
            old_name="recn_co_period_metric_idx",
        ),
        migrations.AddField(
            model_name="apagingsnapshot",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apagingsnapshotline",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="reporting.apagingsnapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="apagingsnapshot",
            index=models.Index(
                fields=["as_of_date", "company_id", "-created_at"],
                name="reporting_a_as_of_d_6ae513_idx",
            ),
        ),
    ]
