# Generated by Django 5.2 on 2026-09-11 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_apagingsnapshot_apagingsnapshotline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_slug', models.CharField(db_index=True, help_text='Matches reporting.finance_monitoring.REPORTS.', max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('email_key', models.CharField(editable=False, max_length=254)),
                ('name', models.CharField(blank=True, default='', help_text='Who this is, for the screen. Optional.', max_length=120)),
                ('kind', models.CharField(choices=[('to', 'Addressed to'), ('cc', 'Copied')], default='to', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_recipients_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report recipient',
                'verbose_name_plural': 'report recipients',
                'ordering': ['report_slug', 'kind', 'email'],
                'constraints': [models.UniqueConstraint(fields=('report_slug', 'email_key'), name='uniq_report_recipient')],
            },
        ),
    ]
