# Generated by Django 5.2 on 2026-06-17 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_aft_import_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(db_index=True, max_length=40, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_address', models.TextField(blank=True, default='')),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('vat_no', models.CharField(blank=True, default='', max_length=40)),
                ('benefit_start', models.DateField(blank=True, null=True)),
                ('billing_period', models.CharField(blank=True, default='', max_length=30)),
                ('underwriting', models.CharField(blank=True, default='Standard + Exclusions', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('invoiced', 'Invoiced')], db_index=True, default='draft', max_length=10)),
                ('subtotal_excl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_incl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=40)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health quote',
                'verbose_name_plural': 'Health quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthQuoteMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('member_type', models.CharField(choices=[('main', 'Policy Holder'), ('adult_dep', 'Adult Dependant'), ('child_dep', 'Child Dependant')], default='main', max_length=12)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('age_band', models.CharField(blank=True, default='', max_length=12)),
                ('tier', models.CharField(default='AD_ESSENTIAL', max_length=20)),
                ('premium_excl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('premium_incl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'full_name'],
            },
        ),
        migrations.RenameIndex(
            model_name='healthcareupload',
            new_name='healthcare__kind_342cc1_idx',
            old_name='healthcare__kind_uplo_idx',
        ),
        migrations.AddField(
            model_name='healthquote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_quotes_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_quotes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthquotemember',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='healthcare.healthquote'),
        ),
    ]
