# Generated by Django 5.2 on 2026-06-17 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_health_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthquote',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='review1_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='review1_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_quotes_review1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='review2_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='review2_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_quotes_review2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='review_stage',
            field=models.CharField(blank=True, choices=[('', 'Not in review'), ('review1', 'Reviewer 1 (Ritah)'), ('review2', 'Reviewer 2 (Meduduetso)'), ('final', 'Final approval (CFO)')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_quotes_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthquote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'In review'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=10),
        ),
    ]
