# Generated by Django 5.2 on 2026-07-30 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_vendor_onboarding_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='healthquote',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_no', ''), _negated=True), fields=('invoice_no',), name='uniq_healthquote_invoice_no'),
        ),
    ]
