# Generated by Django 5.2 on 2026-09-01 07:29

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_afa_loadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice_number', models.CharField(db_index=True, help_text='AFA practice number. Stored as text; leading zeros preserved.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('discipline', models.CharField(blank=True, max_length=128)),
                ('town', models.CharField(blank=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=128)),
                ('location', models.TextField(blank=True)),
                ('vendor_system', models.CharField(blank=True, max_length=64)),
                ('contract_status', models.CharField(blank=True, max_length=64)),
                ('afa_registration_date', models.CharField(blank=True, max_length=64)),
                ('welcome_pack', models.CharField(blank=True, max_length=16)),
                ('sticker_displayed', models.CharField(blank=True, max_length=16)),
                ('provider_orientation', models.CharField(blank=True, max_length=16)),
                ('onboarding_link', models.CharField(blank=True, max_length=512)),
                ('date_contacted', models.CharField(blank=True, max_length=64)),
                ('qc_confirmed', models.BooleanField(default=False)),
                ('qc_date', models.DateField(blank=True, null=True)),
                ('adh_acceptance', models.CharField(blank=True, max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service provider',
                'verbose_name_plural': 'Service providers',
                'ordering': ['name'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
