# Generated by Django 5.2 on 2026-09-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_providerdashboardconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthquote',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthquote',
            name='emailed_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
