# Generated by Django 5.2 on 2026-09-13 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0015_providerdailysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhSettlementRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loaded_on', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('loaded', 'Loaded'), ('partial', 'Loaded with problems'), ('nothing', 'Nothing to load'), ('failed', 'Failed')], default='loaded', max_length=10)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('rejected', models.JSONField(blank=True, default=list)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('problems', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-loaded_on', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('file_sha256__gt', '')), fields=('file_sha256',), name='adh_settlement_one_run_per_file')],
            },
        ),
        migrations.CreateModel(
            name='AdhSettlementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('claim_number', models.CharField(db_index=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_request_id', models.UUIDField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='healthcare.adhsettlementrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
