"""
iso_compliance/soa_seed.py — ISO/IEC 27001:2022 Annex A — all 93 controls.

Reference: ISO/IEC 27001:2022, Annex A — Information security controls
reference (informative). Source mapping based on the published standard
and ISO/IEC 27002:2022 implementation guidance.

Controls are stored under their 2022 clause numbers and grouped into
four domains: Organisational (A.5), People (A.6), Physical (A.7),
Technological (A.8).

Defaults: applicable=True for all (auditors review exclusions explicitly).
The CFO can mark controls excluded with a justification on review.
"""
from __future__ import annotations

from typing import Iterable

from .models import SoAControl, Commandment


# clause, domain, control_type, title, brief description, mapped commandment number
SOA_2022: list[tuple[str, str, str, str, str, int | None]] = [
    # ── A.5 Organisational controls (37) ──────────────────────────────
    ('A.5.1',  'organisational', 'preventive', 'Policies for information security',
     'Information-security policy + topic-specific policies defined, approved, communicated.', 10),
    ('A.5.2',  'organisational', 'preventive', 'Information-security roles and responsibilities',
     'IS roles defined and allocated per organisational need.', 1),
    ('A.5.3',  'organisational', 'preventive', 'Segregation of duties',
     'Conflicting duties and areas of responsibility are segregated.', 1),
    ('A.5.4',  'organisational', 'preventive', 'Management responsibilities',
     'Management requires all personnel to apply IS per the policies.', 10),
    ('A.5.5',  'organisational', 'preventive', 'Contact with authorities',
     'Appropriate contacts with relevant authorities maintained (NBFIRA, BoB, police, regulator).', 6),
    ('A.5.6',  'organisational', 'preventive', 'Contact with special-interest groups',
     'Contact with special-interest groups, security forums, professional bodies.', 6),
    ('A.5.7',  'organisational', 'detective',  'Threat intelligence',
     'Information relating to information-security threats is collected and analysed.', 6),
    ('A.5.8',  'organisational', 'preventive', 'Information security in project management',
     'IS integrated into project management.', 5),
    ('A.5.9',  'organisational', 'preventive', 'Inventory of information and other associated assets',
     'Asset inventory developed, maintained, with owners assigned.', 8),
    ('A.5.10', 'organisational', 'preventive', 'Acceptable use of information and other associated assets',
     'Acceptable-use rules documented, communicated, enforced.', 8),
    ('A.5.11', 'organisational', 'preventive', 'Return of assets',
     'Personnel return assets upon termination of employment or contract.', 8),
    ('A.5.12', 'organisational', 'preventive', 'Classification of information',
     'Information classified per legal, value, criticality and sensitivity.', 8),
    ('A.5.13', 'organisational', 'preventive', 'Labelling of information',
     'Labelling procedures for information per the classification scheme.', 8),
    ('A.5.14', 'organisational', 'preventive', 'Information transfer',
     'Transfer rules and procedures for all transfer types.', 3),
    ('A.5.15', 'organisational', 'preventive', 'Access control',
     'Access-control rules per business + IS requirements.', 1),
    ('A.5.16', 'organisational', 'preventive', 'Identity management',
     'Full lifecycle management of identities.', 1),
    ('A.5.17', 'organisational', 'preventive', 'Authentication information',
     'Allocation and management of authentication information.', 1),
    ('A.5.18', 'organisational', 'preventive', 'Access rights',
     'Access rights provisioned, reviewed, modified, removed.', 1),
    ('A.5.19', 'organisational', 'preventive', 'Information security in supplier relationships',
     'IS processes to manage supplier-relationship risks.', 7),
    ('A.5.20', 'organisational', 'preventive', 'Addressing information security within supplier agreements',
     'IS requirements established and agreed with each supplier.', 7),
    ('A.5.21', 'organisational', 'preventive', 'Managing information security in the ICT supply chain',
     'ICT supply-chain risks managed.', 7),
    ('A.5.22', 'organisational', 'detective',  'Monitoring, review and change management of supplier services',
     'Changes in supplier services monitored, reviewed, audited.', 7),
    ('A.5.23', 'organisational', 'preventive', 'Information security for use of cloud services',
     'Acquisition, use, management and exit of cloud services per IS requirements.', 7),
    ('A.5.24', 'organisational', 'corrective', 'Information security incident-management planning and preparation',
     'IS incident management planned, established, communicated.', 6),
    ('A.5.25', 'organisational', 'corrective', 'Assessment and decision on information-security events',
     'IS events assessed and classified as incidents or not.', 6),
    ('A.5.26', 'organisational', 'corrective', 'Response to information-security incidents',
     'Response according to documented procedures.', 6),
    ('A.5.27', 'organisational', 'corrective', 'Learning from information-security incidents',
     'Knowledge from incidents used to strengthen controls.', 6),
    ('A.5.28', 'organisational', 'corrective', 'Collection of evidence',
     'Procedures for identification, collection, acquisition, preservation of evidence.', 2),
    ('A.5.29', 'organisational', 'preventive', 'Information security during disruption',
     'Plan to maintain IS at appropriate level during disruption.', 9),
    ('A.5.30', 'organisational', 'corrective', 'ICT readiness for business continuity',
     'ICT readiness planned, implemented, maintained, tested.', 9),
    ('A.5.31', 'organisational', 'preventive', 'Legal, statutory, regulatory and contractual requirements',
     'Legal requirements identified, documented, kept current.', 10),
    ('A.5.32', 'organisational', 'preventive', 'Intellectual property rights',
     'IP rights procedures implemented.', 10),
    ('A.5.33', 'organisational', 'preventive', 'Protection of records',
     'Records protected from loss, destruction, falsification, unauthorised access.', 3),
    ('A.5.34', 'organisational', 'preventive', 'Privacy and protection of PII',
     'Privacy and PII protected per legal/regulatory + contractual requirements.', 10),
    ('A.5.35', 'organisational', 'detective',  'Independent review of information security',
     'IS approach reviewed independently at planned intervals.', 10),
    ('A.5.36', 'organisational', 'preventive', 'Compliance with policies, rules and standards',
     'Compliance with IS policies and standards regularly reviewed.', 10),
    ('A.5.37', 'organisational', 'preventive', 'Documented operating procedures',
     'Operating procedures documented and available.', 10),
    # ── A.6 People controls (8) ───────────────────────────────────────
    ('A.6.1', 'people', 'preventive', 'Screening',
     'Background verification on all candidates per laws, regulations, ethics.', 1),
    ('A.6.2', 'people', 'preventive', 'Terms and conditions of employment',
     'Employment agreements state IS responsibilities.', 1),
    ('A.6.3', 'people', 'preventive', 'Information security awareness, education and training',
     'Regular awareness, education, training relevant to job function.', 6),
    ('A.6.4', 'people', 'corrective', 'Disciplinary process',
     'Formal disciplinary process for IS-policy violations.', 6),
    ('A.6.5', 'people', 'preventive', 'Responsibilities after termination or change of employment',
     'IS responsibilities after termination/change defined and enforced.', 1),
    ('A.6.6', 'people', 'preventive', 'Confidentiality or non-disclosure agreements',
     'NDAs identified, documented, reviewed.', 7),
    ('A.6.7', 'people', 'preventive', 'Remote working',
     'Security measures for remote-working personnel.', 1),
    ('A.6.8', 'people', 'detective',  'Information-security event reporting',
     'Mechanism to report IS events timely through appropriate channels.', 6),
    # ── A.7 Physical controls (14) ────────────────────────────────────
    ('A.7.1',  'physical', 'preventive', 'Physical security perimeters',
     'Perimeters defined to protect sensitive areas.', 8),
    ('A.7.2',  'physical', 'preventive', 'Physical entry',
     'Secure areas protected by appropriate entry controls.', 1),
    ('A.7.3',  'physical', 'preventive', 'Securing offices, rooms and facilities',
     'Physical security for offices, rooms, facilities designed and applied.', 8),
    ('A.7.4',  'physical', 'detective',  'Physical security monitoring',
     'Premises monitored continuously for unauthorised physical access.', 8),
    ('A.7.5',  'physical', 'preventive', 'Protecting against physical and environmental threats',
     'Protection from physical/environmental threats (fire, flood, earthquake).', 9),
    ('A.7.6',  'physical', 'preventive', 'Working in secure areas',
     'Security measures for working in secure areas.', 8),
    ('A.7.7',  'physical', 'preventive', 'Clear desk and clear screen',
     'Clear-desk for papers, clear-screen for devices.', 8),
    ('A.7.8',  'physical', 'preventive', 'Equipment siting and protection',
     'Equipment sited securely and protected.', 8),
    ('A.7.9',  'physical', 'preventive', 'Security of assets off-premises',
     'Off-site assets protected.', 8),
    ('A.7.10', 'physical', 'preventive', 'Storage media',
     'Storage media managed across lifecycle (acquisition, use, transport, disposal).', 8),
    ('A.7.11', 'physical', 'preventive', 'Supporting utilities',
     'Information-processing facilities protected from power and other utility failures.', 9),
    ('A.7.12', 'physical', 'preventive', 'Cabling security',
     'Power/data cables protected from interception/interference/damage.', 8),
    ('A.7.13', 'physical', 'preventive', 'Equipment maintenance',
     'Equipment correctly maintained to ensure availability and integrity.', 8),
    ('A.7.14', 'physical', 'preventive', 'Secure disposal or re-use of equipment',
     'Equipment containing storage media verified to ensure removal or secure overwriting.', 8),
    # ── A.8 Technological controls (34) ──────────────────────────────
    ('A.8.1',  'technological', 'preventive', 'User end-point devices',
     'Information stored on, processed by, or accessible via end-point devices protected.', 8),
    ('A.8.2',  'technological', 'preventive', 'Privileged access rights',
     'Allocation and use of privileged access rights restricted and managed.', 1),
    ('A.8.3',  'technological', 'preventive', 'Information access restriction',
     'Access to information restricted per access-control policy.', 1),
    ('A.8.4',  'technological', 'preventive', 'Access to source code',
     'Read/write access to source code, dev tools, libraries appropriately managed.', 5),
    ('A.8.5',  'technological', 'preventive', 'Secure authentication',
     'Secure authentication technologies and procedures implemented.', 1),
    ('A.8.6',  'technological', 'preventive', 'Capacity management',
     'Use of resources monitored and adjusted per current and expected capacity.', 9),
    ('A.8.7',  'technological', 'preventive', 'Protection against malware',
     'Malware protection implemented and supported by user awareness.', 3),
    ('A.8.8',  'technological', 'preventive', 'Management of technical vulnerabilities',
     'Information about technical vulnerabilities obtained and exposure evaluated.', 3),
    ('A.8.9',  'technological', 'preventive', 'Configuration management',
     'Configurations, including security configurations, established, documented, monitored, reviewed.', 5),
    ('A.8.10', 'technological', 'corrective', 'Information deletion',
     'Information stored in systems, devices, media securely deleted when no longer required.', 3),
    ('A.8.11', 'technological', 'preventive', 'Data masking',
     'Data masking used per access-control + business requirements (PII, financial data).', 3),
    ('A.8.12', 'technological', 'detective',  'Data leakage prevention',
     'DLP measures applied to systems/networks/devices.', 3),
    ('A.8.13', 'technological', 'corrective', 'Information backup',
     'Backup copies of information, software, system images maintained and regularly tested.', 4),
    ('A.8.14', 'technological', 'preventive', 'Redundancy of information-processing facilities',
     'Sufficient redundancy of information-processing facilities to meet availability requirements.', 9),
    ('A.8.15', 'technological', 'detective',  'Logging',
     'Logs of activities, exceptions, faults, IS events produced, stored, protected, analysed.', 2),
    ('A.8.16', 'technological', 'detective',  'Monitoring activities',
     'Networks, systems and applications monitored for anomalous behaviour.', 2),
    ('A.8.17', 'technological', 'detective',  'Clock synchronisation',
     'Clocks of all relevant information-processing systems synchronised to approved time source.', 2),
    ('A.8.18', 'technological', 'preventive', 'Use of privileged utility programs',
     'Use of utility programs that can override system/application controls restricted.', 1),
    ('A.8.19', 'technological', 'preventive', 'Installation of software on operational systems',
     'Installation of software on operational systems managed.', 5),
    ('A.8.20', 'technological', 'preventive', 'Networks security',
     'Networks and network devices secured, managed, controlled.', 3),
    ('A.8.21', 'technological', 'preventive', 'Security of network services',
     'Security mechanisms, service levels, service requirements for network services identified and monitored.', 3),
    ('A.8.22', 'technological', 'preventive', 'Segregation of networks',
     'Groups of information services, users, information systems segregated.', 3),
    ('A.8.23', 'technological', 'preventive', 'Web filtering',
     'Access to external websites managed to reduce exposure to malicious content.', 3),
    ('A.8.24', 'technological', 'preventive', 'Use of cryptography',
     'Rules for effective use of cryptography (including key management) defined and implemented.', 3),
    ('A.8.25', 'technological', 'preventive', 'Secure development life cycle',
     'Rules for the secure development of software and systems established and applied.', 5),
    ('A.8.26', 'technological', 'preventive', 'Application security requirements',
     'IS requirements identified, specified, approved during development/acquisition of applications.', 5),
    ('A.8.27', 'technological', 'preventive', 'Secure system architecture and engineering principles',
     'Principles for secure systems engineering established, documented, maintained, applied.', 5),
    ('A.8.28', 'technological', 'preventive', 'Secure coding',
     'Secure coding principles applied to software development.', 5),
    ('A.8.29', 'technological', 'preventive', 'Security testing in development and acceptance',
     'Security-testing processes defined and implemented across development life cycle.', 5),
    ('A.8.30', 'technological', 'preventive', 'Outsourced development',
     'Outsourced system-development activities directed, monitored, reviewed.', 5),
    ('A.8.31', 'technological', 'preventive', 'Separation of development, test and production environments',
     'Environments separated and secured.', 5),
    ('A.8.32', 'technological', 'preventive', 'Change management',
     'Changes to information-processing facilities + systems subject to change-management procedures.', 5),
    ('A.8.33', 'technological', 'preventive', 'Test information',
     'Test information selected, protected, managed appropriately.', 5),
    ('A.8.34', 'technological', 'preventive', 'Protection of information systems during audit testing',
     'Audit tests + assurance activities planned/agreed to minimise disruption.', 10),
]


def seed_soa() -> int:
    """Idempotent. Returns number of NEW rows created."""
    created = 0
    by_number = {c.number: c for c in Commandment.objects.all()}
    for clause, domain, ctype, title, descr, cmd_number in SOA_2022:
        cmd = by_number.get(cmd_number) if cmd_number else None
        obj, was_created = SoAControl.objects.update_or_create(
            clause=clause,
            defaults={
                'title':         title,
                'domain':        domain,
                'control_type':  ctype,
                'description':   descr,
                'commandment':   cmd,
            },
        )
        if was_created:
            created += 1
    return created
