# Generated by Django 5.2 on 2026-03-24 06:19

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('delimiter', models.CharField(default=',', max_length=1)),
                ('encoding', models.CharField(default='utf-8', max_length=20)),
                ('skip_rows', models.IntegerField(default=0, help_text='Non-header rows to skip before the data begins')),
                ('date_column', models.CharField(max_length=100)),
                ('date_format', models.CharField(default='%d/%m/%Y', help_text='strptime format, e.g. %%d/%%m/%%Y', max_length=30)),
                ('description_column', models.CharField(max_length=100)),
                ('reference_column', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_column', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_column', models.CharField(blank=True, max_length=100, null=True)),
                ('sign_convention', models.CharField(choices=[('debit_negative', 'Negative = outflow (most banks)'), ('debit_positive', 'Positive = outflow (rare)')], default='debit_negative', max_length=20)),
                ('debit_column', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_column', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['bank_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_reconciled_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.ForeignKey(default='BWP', on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('gl_account', models.OneToOneField(help_text='GL account (is_bank_account must be True)', on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_detail', to='ledger.account')),
            ],
            options={
                'ordering': ['bank_name', 'account_name'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('file_name', models.CharField(max_length=255)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('in_progress', 'Reconciliation in progress'), ('reconciled', 'Reconciled')], default='imported', max_length=20)),
                ('line_count', models.IntegerField(default=0)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='banking.bankaccount')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date', '-import_date'],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('auto_matched', 'Auto-matched'), ('manually_matched', 'Manually matched'), ('excluded', 'Excluded')], default='unmatched', max_length=20)),
                ('match_confidence', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('matched_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_lines', to='ledger.journalentry')),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_lines', to='payments.payment')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.bankstatement')),
            ],
            options={
                'ordering': ['statement', 'line_number'],
                'unique_together': {('statement', 'line_number')},
            },
        ),
    ]
