# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_bank_recon_approval'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankrecrule',
            new_name='banking_ban_company_40b1ff_idx',
            old_name='banking_ban_company_e6e8b3_idx',
        ),
    ]
