# Generated by Django 5.2 on 2026-09-13 06:01
#
# CR-001 — a bank statement line can now carry the claim and the supplier
# invoice it settled, and what basis it was paid on.
#
# SCHEMA ONLY. Three columns are added with safe defaults ('' and 'unknown').
# NOTHING existing is rewritten: no data migration, no RunPython, not a single
# live financial row touched by this deploy. Rows imported before today stay
# blank until somebody deliberately runs
#
#     python manage.py backfill_bank_line_references            # look first
#     python manage.py backfill_bank_line_references --commit   # then write
#
# which is re-runnable and dry-run by default.
#
# DEPLOY NOTE: this is a MIGRATION, so the backend IMAGE must be REBUILT.
# Restarting the existing container does not apply it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_bankstatementline_dedupe_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='claim_reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Claim number this line settled, read off its own text.', max_length=50),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', help_text='Supplier invoice number this line settled. Blank means the money went to an individual claimant, not against an invoice.', max_length=50),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='payment_basis',
            field=models.CharField(blank=True, choices=[('invoice', 'Supplier invoice'), ('repair', 'Repair'), ('aol', 'AOL'), ('for', 'FOR'), ('cil', 'CIL'), ('third_party', 'Third party'), ('ex_gratia', 'Ex-gratia'), ('unknown', 'Unknown - not evidenced on the line')], default='unknown', help_text='What the payment was settled on. Only INVOICE may be de-grossed for VAT — every other basis, UNKNOWN included, stays gross.', max_length=20),
        ),
    ]
