# Generated by Django 5.2 on 2026-09-18 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0007_bankstatementline_claim_reference_and_more"),
        ("core", "0071_access_delegate_and_module_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankMatchMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counterparty_key",
                    models.CharField(
                        db_index=True,
                        help_text="Normalised key from the statement line's description.",
                        max_length=120,
                    ),
                ),
                (
                    "payee_key",
                    models.CharField(
                        help_text="Normalised key from the matched payment's contact/payee name.",
                        max_length=200,
                    ),
                ),
                ("times_confirmed", models.PositiveIntegerField(default=0)),
                ("last_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Finance user can disable this memory to stop it from generating suggestions.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_match_memories",
                        to="core.company",
                    ),
                ),
                (
                    "last_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-times_confirmed"],
                "unique_together": {("company", "counterparty_key", "payee_key")},
            },
        ),
    ]
