# Generated by Django 5.2 on 2026-09-19 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("procurement", "0014_vendorbankaccount_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim_ref",
                    models.CharField(
                        help_text="Graphite claim number, upper-cased.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("graphite_id", models.BigIntegerField(blank=True, null=True)),
                ("claim_type", models.CharField(blank=True, default="", max_length=64)),
                ("is_motor", models.BooleanField(default=False)),
                (
                    "facts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Latest facts Graphite sent (merged).",
                    ),
                ),
                (
                    "handler_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "premium_light",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("form_in", "Customer form received"),
                            ("assessed", "Assessment received"),
                            ("po_drafted", "Purchase orders drafted"),
                            ("aol_pending", "Agreement of Loss awaiting authorisation"),
                            ("repudiation_pending", "Repudiation awaiting approval"),
                            ("decided", "Decision recorded"),
                        ],
                        default="registered",
                        max_length=24,
                    ),
                ),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("ai_next_step", models.TextField(blank=True, default="")),
                ("ai_engine", models.CharField(blank=True, default="", max_length=40)),
                ("ai_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not yet read"),
                            ("straight_through", "Straight through"),
                            ("exception", "Needs a person"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("triage_reasons", models.JSONField(blank=True, default=list)),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Deterministic policy-breach flags.",
                    ),
                ),
                (
                    "po_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="procurement.claimsassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimAutomationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("claim_registered", "Claim registered"),
                            ("claim_form_submitted", "Customer form submitted"),
                            ("assessment_received", "Assessment received"),
                            ("write_off_flagged", "Write-off flagged"),
                            ("decision_recorded", "Decision recorded"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=12,
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="What Omni did, in plain words.",
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "received_via",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="claims_automation.claimcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClaimLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("aol", "Agreement of Loss"),
                            ("repudiation", "Repudiation"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting", "Awaiting authorisation"),
                            ("approved", "Approved"),
                            ("sent", "Approved and sent to the client"),
                            ("declined", "Declined"),
                        ],
                        default="awaiting",
                        max_length=10,
                    ),
                ),
                ("figures", models.JSONField(blank=True, default=dict)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Everything the letter renders from.",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, default="")),
                ("sent_to", models.CharField(blank=True, default="", max_length=254)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letters",
                        to="claims_automation.claimcase",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
