# Generated by Django 5.2 on 2026-09-19 21:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_invoice_receivable_account"),
        ("claims_automation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalvageHandover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'vehicle_in_yard': 'yes'|'no'|'na', ...}",
                    ),
                ),
                (
                    "yard_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The yard's own item number, if they have one.",
                        max_length=64,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("declared_at", models.DateTimeField(blank=True, null=True)),
                ("override_at", models.DateTimeField(blank=True, null=True)),
                ("override_reason", models.TextField(blank=True, default="")),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handover",
                        to="claims_automation.claimcase",
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VeritasSalvageCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settlement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What we paid the client (the Agreement of Loss net).",
                        max_digits=18,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.20"), max_digits=5
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_config", "Waiting for the income account"),
                            ("drafted", "Draft invoice raised for Finance"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_config",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veritas_charges",
                        to="claims_automation.claimcase",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "letter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veritas_charge",
                        to="claims_automation.claimletter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
