# Generated by Django 5.2 on 2026-09-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_automation', '0002_salvagehandover_veritassalvagecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcase',
            name='notification_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date the claim was notified to us. Every clock counts from here.', null=True),
        ),
        migrations.AlterField(
            model_name='claimautomationevent',
            name='event_type',
            field=models.CharField(choices=[('claim_registered', 'Claim registered'), ('claim_form_submitted', 'Customer form submitted'), ('premium_checked', 'Premium checked'), ('assessment_received', 'Assessment received'), ('write_off_flagged', 'Write-off flagged'), ('decision_recorded', 'Decision recorded')], max_length=32),
        ),
    ]
