# Generated by Django 5.2 on 2026-03-30 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ledger', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('file_size', models.IntegerField(default=0)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('classified', 'Classified'), ('extracted', 'Extracted'), ('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('error', 'Error')], default='uploading', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('bank_statement', 'Bank Statement'), ('expense', 'Expense'), ('credit_note', 'Credit Note'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('extraction_method', models.CharField(choices=[('rule_based', 'Rule-Based'), ('ai_assisted', 'AI-Assisted'), ('hybrid', 'Hybrid')], default='rule_based', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('suggested_action', models.JSONField(blank=True, null=True)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('user_decision', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=20)),
                ('user_corrections', models.JSONField(blank=True, null=True)),
                ('resulting_object_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_processed', to=settings.AUTH_USER_MODEL)),
                ('resulting_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ai_extraction', 'AI Extraction'), ('ai_error', 'AI Error'), ('rule_extraction', 'Rule Extraction'), ('user_confirm', 'User Confirm'), ('user_reject', 'User Reject')], max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='documents.documentupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_pattern', models.CharField(max_length=255, unique=True)),
                ('match_count', models.IntegerField(default=0)),
                ('auto_apply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_mappings', to='billing.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_mappings', to='ledger.account')),
            ],
            options={
                'ordering': ['-match_count'],
            },
        ),
    ]
