# Generated by Django 5.2 on 2026-08-08 10:31

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_emaillogincode_purpose'),
        ('underwriting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('client_name', models.CharField(max_length=200)),
                ('client_attn', models.CharField(blank=True, default='', max_length=200)),
                ('class_of_business', models.CharField(blank=True, default='', max_length=80)),
                ('period', models.CharField(blank=True, default='12 months', max_length=40)),
                ('broker', models.CharField(blank=True, default='', max_length=120)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('premium_is_suggested', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('lapsed', 'Lapsed'), ('won', 'Converted to policy'), ('lost', 'Lost')], db_index=True, default='draft', max_length=10)),
                ('source_text', models.TextField(blank=True, default='')),
                ('drafted_by_ai', models.BooleanField(default=False)),
                ('pdf_bytes', models.BinaryField(blank=True, null=True)),
                ('pdf_size', models.PositiveIntegerField(default=0)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('converted_policy_number', models.CharField(blank=True, default='', max_length=60)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.company')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_issued', to=settings.AUTH_USER_MODEL)),
                ('underwriter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_underwritten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', '-created_at'], name='uw_quote_status_idx'), models.Index(fields=['company', '-created_at'], name='uw_quote_company_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
