# Generated by Django 5.2 on 2026-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rate_incl_vat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='rate_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
