# Generated by Django 5.2 on 2026-08-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0003_quote_rate_incl_vat_quote_rate_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRateFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_of_business', models.CharField(blank=True, default='', help_text='Blank = the default floor that applies to every class.', max_length=80)),
                ('min_rate_pct', models.DecimalField(decimal_places=4, default=0, help_text='Lowest allowed premium rate %, e.g. 0.25 means 0.25%.', max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote rate floor',
                'verbose_name_plural': 'Quote rate floors',
            },
        ),
    ]
