# Generated by Django 5.2 on 2026-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0004_quoteratefloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('class_of_business', models.CharField(blank=True, default='', max_length=80)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('rate_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('rate_incl_vat', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote template',
                'verbose_name_plural': 'Quote templates',
                'ordering': ['name'],
            },
        ),
    ]
