# Generated by Django 5.2 on 2026-08-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0005_quotetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphiteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('class', 'Class of business → product / plan'), ('broker', 'Broker → agent code')], db_index=True, max_length=10)),
                ('omni_value', models.CharField(max_length=120)),
                ('product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_code', models.CharField(blank=True, default='', max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Graphite mapping',
                'verbose_name_plural': 'Graphite mappings',
                'constraints': [models.UniqueConstraint(fields=('kind', 'omni_value'), name='uniq_graphite_mapping_kind_value')],
            },
        ),
    ]
