# Generated by Django 5.2 on 2026-08-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0006_graphitemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
