# Generated by Django 5.2 on 2026-08-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0007_quote_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='period_months',
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
