# Generated by Django 5.2 on 2026-08-11 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0008_quote_period_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='period_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Months of cover, 1-12. 12 is a normal annual quotation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
