# Generated by Django 5.2 on 2026-08-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0009_alter_quote_period_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='annual_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
