# Generated by Django 5.2 on 2026-08-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0010_quote_annual_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteratefloor',
            name='min_premium',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lowest premium we will issue for this class, BWP. 0 = no minimum.', max_digits=14),
        ),
    ]
