# Generated by Django 5.2 on 2026-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0013_quote_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='emailed_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
