# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realpay', '0003_realpay_import_control'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='realpaymonthlyreport',
            new_name='realpay_rea_period__e05472_idx',
            old_name='realpay_period_idx',
        ),
        migrations.RenameIndex(
            model_name='realpaymonthlyreport',
            new_name='realpay_rea_benefic_8ce7a6_idx',
            old_name='realpay_user_idx',
        ),
        migrations.RenameIndex(
            model_name='realpayresponsecode',
            new_name='realpay_rea_product_375408_idx',
            old_name='rp_rc_prod_codenorm_idx',
        ),
        migrations.RenameIndex(
            model_name='realpayresponsecode',
            new_name='realpay_rea_code_no_f41d88_idx',
            old_name='rp_rc_codenorm_idx',
        ),
        migrations.RenameIndex(
            model_name='realpaytransaction',
            new_name='realpay_rea_source_1c04a3_idx',
            old_name='rp_txn_src_date_idx',
        ),
        migrations.RenameIndex(
            model_name='realpaytransaction',
            new_name='realpay_rea_source_2b6798_idx',
            old_name='rp_txn_src_status_idx',
        ),
        migrations.RenameIndex(
            model_name='realpaytransaction',
            new_name='realpay_rea_txn_dat_bdc07f_idx',
            old_name='rp_txn_date_idx',
        ),
        migrations.RenameIndex(
            model_name='realpaytransaction',
            new_name='realpay_rea_client__42b374_idx',
            old_name='rp_txn_client_idx',
        ),
        migrations.RenameIndex(
            model_name='realpaytransaction',
            new_name='realpay_rea_result__48fcb1_idx',
            old_name='rp_txn_codenorm_idx',
        ),
        migrations.AlterField(
            model_name='realpaymonthlyreport',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Raw transaction list from RealPay.'),
        ),
        migrations.AlterField(
            model_name='realpaymonthlyreport',
            name='xlsx_file',
            field=models.FileField(blank=True, help_text='Generated XLSX for download.', null=True, upload_to='realpay/%Y/%m/'),
        ),
    ]
