# Generated by Django 5.2 on 2026-09-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realpay', '0004_sync_model_state_2026_07_26'),
    ]

    operations = [
        migrations.AddField(
            model_name='realpaytransaction',
            name='tracking_start_date',
            field=models.DateField(blank=True, db_index=True, help_text="Billing only — RealPay's Tracking Start Date, the month the debit was TRACKED. A debit tracked in August often only settles in the September report, so the month basis has to come from this date and not from which report it arrived in (Bokani, bug 6a48367f).", null=True),
        ),
        migrations.AddIndex(
            model_name='realpaytransaction',
            index=models.Index(fields=['source', 'tracking_start_date'], name='realpay_rea_source_3d10fc_idx'),
        ),
    ]
