# Generated by Django 5.2 on 2026-06-22 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_chatmessage_edit_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('telematics', 'Telematics'), ('health', 'Health'), ('voucher', 'Voucher / Retail'), ('airtime', 'Airtime'), ('pharmacy', 'Pharmacy')], max_length=20)),
                ('status', models.CharField(default='active', help_text='active / pending / future', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Reward Partner',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RewardProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('premium_payment', 'Premium Payment Rewards'), ('claims_free', 'Claims-Free Rewards'), ('driving', 'Driving Points (Telematics)'), ('health', 'Health Points')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Tier weights, discount %, point rules.')),
            ],
            options={
                'verbose_name': 'Reward Program',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RewardMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(blank=True, default='', max_length=60)),
                ('customer_name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=12)),
                ('points_balance', models.IntegerField(default=0)),
                ('claims_free_months', models.IntegerField(default=0)),
                ('enrolled_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_members', to='core.company')),
            ],
            options={
                'verbose_name': 'Reward Member',
                'ordering': ['-points_balance', 'customer_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrivingScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=10)),
                ('vehicle_reg', models.CharField(blank=True, default='', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('idle_minutes', models.IntegerField(default=0)),
                ('harsh_events', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0, help_text='0-100 driving score')),
                ('points_awarded', models.IntegerField(default=0)),
                ('source', models.CharField(default='Kgare Digital', max_length=60)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_scores', to='rewards.rewardmember')),
            ],
            options={
                'verbose_name': 'Driving Score',
                'ordering': ['-period'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('adjust', 'Adjustment')], max_length=10)),
                ('points', models.IntegerField(help_text='+ on earn, - on redeem')),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('occurred_at', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.rewardmember')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='rewards.rewardpartner')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='rewards.rewardprogram')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
    ]
