# Generated by Django 5.2 on 2026-09-07 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0009_customer_step_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerWorkoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(
                        help_text="Health Connect ExerciseSessionRecord id",
                        max_length=128,
                    ),
                ),
                ("day", models.DateField(help_text="Local day the session started")),
                (
                    "exercise_type",
                    models.IntegerField(
                        default=0, help_text="Health Connect exercise type code"
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=0)),
                ("points_awarded", models.IntegerField(default=0)),
                ("source", models.CharField(default="health_connect", max_length=24)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to="rewards.rewardmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Workout Session",
                "ordering": ["-started_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "session_id"),
                        name="uniq_member_workout_session",
                    )
                ],
            },
        ),
    ]
