# Generated by Django 5.2 on 2026-09-08 18:18

from django.db import migrations, models


def backfill_quality(apps, schema_editor):
    """Judge every historical trip with the same parser the API now uses.

    Rows recorded before the ingest gate existed include GPS lock-on spikes
    (0 km in 12 seconds reporting 132 km/h) that were being graded as real
    driving. Nothing is deleted — the row keeps its captured numbers and simply
    carries the verdict, so it can never be counted again.
    """
    from rewards.drive_score import apply_quality
    Trip = apps.get_model('rewards', 'CustomerDriveTrip')
    fixed = sum(1 for t in Trip.objects.all().iterator() if apply_quality(t))
    if fixed:
        print(f'  drive-trip quality backfilled on {fixed} row(s)')


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0010_customer_workout_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdrivetrip",
            name="invalid_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="customerdrivetrip",
            name="is_valid",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False = not a real drive (GPS spike / no distance); excluded from every aggregate",
            ),
        ),
        migrations.AddField(
            model_name="customerdrivetrip",
            name="speed_reliable",
            field=models.BooleanField(
                default=True,
                help_text="False = the peak-speed reading is not supported by the distance covered",
            ),
        ),
        migrations.AlterField(
            model_name="customerdrivetrip",
            name="max_speed",
            field=models.FloatField(
                default=0, help_text="km/h as reported by the phone"
            ),
        ),
        migrations.RunPython(backfill_quality, migrations.RunPython.noop),
    ]
