# Generated by Django 5.2 on 2026-09-09 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    """Give every existing member their (derived, stable) referral code.

    make_code is a pure function of the member id, so this is idempotent and a
    member's code never changes.
    """
    from rewards.referral import make_code
    Member = apps.get_model('rewards', 'RewardMember')
    n = 0
    for m in Member.objects.all().only('id', 'referral_code').iterator():
        code = make_code(m.id)
        if code and m.referral_code != code:
            m.referral_code = code
            m.save(update_fields=['referral_code'])
            n += 1
    if n:
        print(f'  referral codes issued to {n} member(s)')


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0011_drivetrip_quality_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardmember",
            name="referral_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=12
            ),
        ),
        migrations.CreateModel(
            name="NexusTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
                (
                    "join_code",
                    models.CharField(
                        db_index=True,
                        help_text="Short code a friend types to join",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams_created",
                        to="rewards.rewardmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nexus Team",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScreeningVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Shown to the member and read at the clinic",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("issued_on", models.DateField()),
                ("expires_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="issued",
                        max_length=12,
                    ),
                ),
                (
                    "scans_at_issue",
                    models.IntegerField(
                        default=0,
                        help_text="Pulse checks the member had when this was earned",
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_vouchers",
                        to="rewards.rewardmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screening Voucher",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NexusTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="rewards.rewardmember",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="rewards.nexusteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nexus Team Member",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member",), name="uniq_member_one_team"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_used", models.CharField(max_length=12)),
                (
                    "qualified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the referred policy met the waiting period",
                        null=True,
                    ),
                ),
                (
                    "points_awarded",
                    models.IntegerField(
                        default=0, help_text="0 until qualified — never paid at signup"
                    ),
                ),
                (
                    "referred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_received",
                        to="rewards.rewardmember",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="rewards.rewardmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("referred",), name="uniq_referred_once"
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
    ]
