# Generated by Django 5.2 on 2026-07-06 08:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0031_sod_senior_accountant_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('interaction_seconds', models.PositiveIntegerField(default=0, help_text='Measured dwell time on the completion modal (kept for audit).', validators=[django.core.validators.MinValueValidator(30)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_completion_notes', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_note', to='core.omnitask')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('assign_day', 'Assigned'), ('due_day', 'Due today'), ('overdue', 'Overdue')], max_length=12)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='True once the user clears the force-modal (due/overdue).')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.omnitask')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['recipient', 'acknowledged'], name='taskboard_n_recipie_3e350d_idx'), models.Index(fields=['task', 'type'], name='taskboard_n_task_id_11bcdd_idx')],
            },
        ),
    ]
