# Generated by Django 5.2 on 2026-07-15 10:28

import django.db.models.deletion
import taskboard.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskboard", "0004_paymentrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("claim", "Claim payments"),
                    ("supplier", "Supplier payments"),
                    ("vendor", "Vendor payments"),
                    ("petty_cash", "Petty cash"),
                    ("other", "Other"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="PaymentRequestAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=taskboard.models._pr_attach_path)),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="taskboard.paymentrequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_request_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
