# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0010_backfill_legacy_paid_finance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskreminderemaillog',
            new_name='taskboard_t_recipie_5d80c1_idx',
            old_name='tb_treml_recip_senton_idx',
        ),
    ]
