# Generated by Django 5.2 on 2026-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0014_paymentrequest_duplicate_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted by WhatsApp (delivery not confirmed)'), ('failed', 'Failed'), ('queued', 'Queued')], default='queued', max_length=8),
        ),
    ]
