# Generated by Django 5.2 on 2026-08-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0015_whatsapp_accepted_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='duplicate_override_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='duplicate_override_approved_by',
            field=models.ForeignKey(blank=True, help_text='Must NOT be the person who raised the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_overrides_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='duplicate_override_category',
            field=models.CharField(blank=True, choices=[('bank_rejected', 'The bank rejected the first attempt'), ('partial', 'Partial payment of a larger amount'), ('separate_invoice', 'Genuinely a separate invoice'), ('prior_cancelled', 'The earlier request was cancelled'), ('other', 'Other — explain in the reason')], default='', help_text='Why this duplicate may be paid. Free text alone is not enough.', max_length=32),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='duplicate_override_evidence',
            field=models.ForeignKey(blank=True, help_text='The document proving the override — e.g. the bank rejection advice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_evidence_for', to='taskboard.paymentrequestattachment'),
        ),
    ]
