# Generated by Django 5.2 on 2026-08-11 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_bugreport_status_check'),
        ('taskboard', '0016_harden_duplicate_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='graphite_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Graphite refund reference this request was raised from.', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('claim', 'Claim payments'), ('supplier', 'Supplier payments'), ('vendor', 'Vendor payments'), ('petty_cash', 'Petty cash'), ('premium_refund', 'Premium refunds'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('graphite_ref__gt', '')), fields=('graphite_ref',), name='paymentrequest_one_per_graphite_refund'),
        ),
    ]
