# Generated by Django 5.2 on 2026-08-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0006_fnbhealthalertstate_stuck_keys_and_more'),
        ('payments', '0014_bank_facing_overrides'),
        ('taskboard', '0017_premium_refund_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CACC', 'Cheque / current'), ('SVGS', 'Savings')], default='', help_text='Blank is treated as cheque / current.', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='branch_code',
            field=models.CharField(blank=True, default='', help_text='Payee branch code. Needed for any bank other than FNB.', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='fnb_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='fnb.fnbbatchsubmission'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='fnb_load_error',
            field=models.TextField(blank=True, default='', help_text='Why the automatic load did not happen. Blank means it did, or was not attempted yet.'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='fnb_loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='payments.payment'),
        ),
    ]

