# Generated by Django 5.2 on 2026-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0018_payment_request_bank_and_fnb_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='bank_change_reason',
            field=models.TextField(blank=True, default='', help_text='Required when the payee bank account differs from the one last used for them.'),
        ),
    ]
