# Generated by Django 5.2 on 2026-08-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0019_payment_request_bank_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='bank_narration',
            field=models.CharField(blank=True, default='', help_text='What the payee sees on their statement. 140 characters.', max_length=140),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='bank_our_reference',
            field=models.CharField(blank=True, default='', help_text='Our own reference for matching the bank line back. 35 chars.', max_length=35),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='bank_payment_type',
            field=models.CharField(blank=True, default='', help_text='Decides the default wording on the bank statement.', max_length=20),
        ),
    ]
