# Generated by Django 5.2 on 2026-09-01 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0020_payment_request_bank_wording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLoadOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(help_text='Why they need to load a payment outside the morning window.')),
                ('for_date', models.DateField(help_text='The local day this override is (or would be) valid for.')),
                ('status', models.CharField(choices=[('pending', 'Waiting for CFO'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_load_overrides_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_load_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['requested_by', 'for_date', 'status'], name='taskboard_p_request_8f4b07_idx'), models.Index(fields=['status', 'for_date'], name='taskboard_p_status_492d16_idx')],
            },
        ),
    ]
