# Generated by Django 5.2 on 2026-09-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0025_payment_exception_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='pop_subject',
            field=models.CharField(blank=True, default='', help_text='The POP heading, copied from SUBJECT as it stood when the request was submitted. Falls back to the request reference.', max_length=200),
        ),
    ]
