# Generated by Django 5.2 on 2026-09-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0026_paymentrequest_pop_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='processing_method',
            field=models.CharField(choices=[('bulk', 'Bulk — one payment for the total'), ('individual', 'Individual — one payment per invoice')], default='bulk', help_text='How the money leaves: one bulk payment, or one payment per invoice.', max_length=10),
        ),
    ]
