# Generated by Django 5.2 on 2026-09-08 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0027_paymentrequest_processing_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='cancelled_reason',
            field=models.TextField(blank=True, default='', help_text='Why this request was pulled. Required on a cancel; an auditor asks this first.'),
        ),
        migrations.CreateModel(
            name='PaymentRequestChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('amend', 'Amended'), ('cancel_line', 'Line cancelled'), ('cancel_request', 'Request cancelled')], max_length=16)),
                ('line', models.PositiveIntegerField(blank=True, null=True)),
                ('field', models.CharField(blank=True, default='', max_length=40)),
                ('value_before', models.TextField(blank=True, default='')),
                ('value_after', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('actor_name', models.CharField(blank=True, default='', max_length=160)),
                ('actor_department', models.CharField(blank=True, default='', max_length=100)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='taskboard.paymentrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['request', 'created_at'], name='taskboard_p_request_6b80f0_idx')],
            },
        ),
    ]
