# Generated by Django 5.2 on 2026-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0029_alter_paymentrequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='graphite_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Graphite refund reference this request was raised from.', max_length=64),
        ),
    ]
