# Generated by Django 5.2 on 2026-09-13 23:23

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ariapopup'),
        ('fnb', '0010_synclog_waiting_status'),
        ('payments', '0015_payment_remittance_email'),
        ('taskboard', '0030_alter_paymentrequest_graphite_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskboardSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Taskboard Setting',
                'verbose_name_plural': 'Taskboard Settings',
                'ordering': ['key'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Set by the raising client once per submit attempt; repeats on a retry of that same attempt so the database can refuse a second row for it.', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__gt', '')), fields=('client_request_id',), name='paymentrequest_one_per_client_request_id'),
        ),
    ]
