# Generated by Django 5.2 on 2026-09-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0030_alter_paymentrequest_graphite_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='duplicated_from_ref',
            field=models.CharField(blank=True, default='', help_text='The payment request this one was copied from.', max_length=48),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='original_payment_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The reference of the payment being refunded.', max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('claim', 'Claim payments'), ('supplier', 'Supplier payments'), ('vendor', 'Vendor payments'), ('petty_cash', 'Petty cash'), ('premium_refund', 'Premium refunds'), ('erroneous_refund', 'Refund — erroneous payment'), ('excess_refund', 'Excess refunds'), ('unicoin', 'Unicoin payments'), ('quantum', 'Quantum payments'), ('rsa', 'Risk Software Africa'), ('veritas', 'Veritas Capital Mgmt'), ('adh', 'Alpha Direct Health'), ('gce', 'GCE payments'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
