# Generated by Django 5.2 on 2026-09-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0031_refund_categories_and_duplicate'),
        ('taskboard', '0031_taskboardsetting_paymentrequest_client_request_id_and_more'),
    ]

    operations = [
    ]
