# Generated by Django 5.2 on 2026-09-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskboard", "0032_merge_20260914_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("claim", "Claim payments"),
                    ("supplier", "Supplier payments"),
                    ("vendor", "Vendor payments"),
                    ("petty_cash", "Petty cash"),
                    ("premium_refund", "Premium refunds"),
                    ("erroneous_refund", "Refund — erroneous payment"),
                    ("excess_refund", "Excess refunds"),
                    ("unicoin", "Unicoin payments"),
                    ("staff_loan", "Staff loan disbursement"),
                    ("quantum", "Quantum payments"),
                    ("rsa", "Risk Software Africa"),
                    ("veritas", "Veritas Capital Mgmt"),
                    ("adh", "Alpha Direct Health"),
                    ("gce", "GCE payments"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
