# Generated by Django 5.2 on 2026-08-12 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('floor', models.CharField(blank=True, default='', max_length=120)),
                ('seats', models.PositiveIntegerField(blank=True, help_text='Number of seats. Blank until facilities confirm it.', null=True)),
                ('kit', models.CharField(blank=True, default='', help_text='Comma-separated equipment, e.g. "Screen, Speakerphone, Camera".', max_length=255)),
                ('is_prominent', models.BooleanField(default=False, help_text='Show first on the board — the Exco and Staff board rooms.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower shows first (after the prominent rooms).')),
            ],
            options={
                'ordering': ['-is_prominent', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('start_min', models.PositiveIntegerField(help_text='Minutes since midnight, e.g. 540 = 09:00.')),
                ('end_min', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('attendees', models.PositiveIntegerField(default=1)),
                ('booked_by_name', models.CharField(blank=True, default='', help_text="Booker's display name captured at booking time.", max_length=150)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='boardroom.room')),
            ],
            options={
                'ordering': ['day', 'start_min'],
                'indexes': [models.Index(fields=['room', 'day'], name='boardroom_b_room_id_92cb4b_idx'), models.Index(fields=['day'], name='boardroom_b_day_5da5ec_idx')],
            },
        ),
    ]
