# Generated by Django 5.2 on 2026-07-25 07:54

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0011_alter_billapprovalpolicy_tier2_ceiling_and_more'),
        ('core', '0048_compliancebrainsummary'),
        ('ledger', '0026_posted_je_immutable_triggers'),
        ('procurement', '0012_restore_po_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('group', models.CharField(choices=[('dispute', 'Query / Dispute'), ('docs_missing', 'Missing Documents'), ('salvage_not_in_yard', 'Salvage Not Yet in Yard'), ('awaiting_approval', 'Awaiting Approval'), ('no_po', 'No Purchase Order'), ('funds', 'Funding / Cash-flow Hold'), ('duplicate', 'Suspected Duplicate'), ('fx', 'FX / Rate Confirmation'), ('other', 'Other')], max_length=32)),
                ('requires_escalation', models.BooleanField(default=False, help_text='Using this reason forces an escalation to be raised before the run can close.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceReconItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_reference', models.CharField(blank=True, default='', max_length=100)),
                ('match_status', models.CharField(choices=[('matched', '3-Way Matched'), ('partial', 'Partially Matched'), ('no_po', 'No PO'), ('no_grn', 'No Goods Receipt'), ('no_claim', 'No Claim Authorisation'), ('unmatched', 'Unmatched')], default='unmatched', max_length=12)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('unpaid', 'Unpaid'), ('held', 'Held')], default='unpaid', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='', help_text='Mandatory for any bill not fully paid.')),
                ('actioned', models.BooleanField(default=False)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_recon_items', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recon_items', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_items', to='procurement.goodsreceiptnote')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recon_items', to='billing.invoice')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_items', to='procurement.purchaseorder')),
                ('reason_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='supplier_recon.reasoncode')),
            ],
            options={
                'ordering': ['due_date', 'invoice__invoice_number'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReconActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=16)),
                ('to_status', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='supplier_recon.invoicereconitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierReconLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('panel_beater', 'Panel Beater'), ('parts', 'Parts Supplier'), ('towing', 'Towing / Recovery'), ('assessor', 'Assessor'), ('glass', 'Glass Fitment'), ('medical', 'Medical Provider'), ('general', 'General / Operations'), ('other', 'Other')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Action'), ('exception', 'Exception'), ('cleared', 'Cleared')], default='pending', max_length=12)),
                ('invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('unpaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('held', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('unactioned_count', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Payables team member accountable for this supplier this month.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recon_lines', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recon_lines', to='billing.contact')),
            ],
            options={
                'ordering': ['supplier__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoicereconitem',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier_recon.supplierreconline'),
        ),
        migrations.CreateModel(
            name='SupplierReconRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(help_text="Reconciliation month, e.g. '2026-07'.", max_length=7)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('finalised', 'Finalised'), ('reopened', 'Reopened')], default='open', max_length=20)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_unpaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_held', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_escalated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_recon_runs', to='core.company')),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_recon_runs', to='ledger.fiscalperiod')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_recon_runs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recon_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Recon Run',
                'verbose_name_plural': 'Supplier Recon Runs',
                'ordering': ['-period_start', 'company_id'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='supplierreconline',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_recon.supplierreconrun'),
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('justification', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('waived', 'Waived')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_escalations', to=settings.AUTH_USER_MODEL)),
                ('raised_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_escalations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_escalations', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='supplier_recon.invoicereconitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='reconesc_status_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReconSupplierProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('panel_beater', 'Panel Beater'), ('parts', 'Parts Supplier'), ('towing', 'Towing / Recovery'), ('assessor', 'Assessor'), ('glass', 'Glass Fitment'), ('medical', 'Medical Provider'), ('general', 'General / Operations'), ('other', 'Other')], default='general', max_length=20)),
                ('in_scope', models.BooleanField(default=True, help_text='Include this supplier in monthly reconciliation runs.')),
                ('notes', models.TextField(blank=True, default='')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recon_profile', to='billing.contact')),
            ],
            options={
                'verbose_name': 'Recon Supplier Profile',
                'verbose_name_plural': 'Recon Supplier Profiles',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['category', 'in_scope'], name='reconprofile_cat_scope_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='invoicereconitem',
            index=models.Index(fields=['payment_status', 'actioned'], name='reconitem_pstatus_act_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicereconitem',
            index=models.Index(fields=['match_status'], name='reconitem_match_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicereconitem',
            constraint=models.UniqueConstraint(fields=('line', 'invoice'), name='uniq_recon_item_line_invoice'),
        ),
        migrations.AddIndex(
            model_name='supplierreconrun',
            index=models.Index(fields=['company', 'status'], name='reconrun_co_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierreconrun',
            constraint=models.UniqueConstraint(fields=('company', 'period_label'), name='uniq_recon_run_company_period'),
        ),
        migrations.AddConstraint(
            model_name='supplierreconline',
            constraint=models.UniqueConstraint(fields=('run', 'supplier'), name='uniq_recon_line_run_supplier'),
        ),
    ]
