# Generated by Django 5.2 on 2026-07-25 12:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_billapprovalpolicy_tier2_ceiling_and_more'),
        ('procurement', '0012_restore_po_discount'),
        ('supplier_recon', '0002_seed_reason_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereconitem',
            name='ledger_stage',
            field=models.CharField(choices=[('posted', 'Posted to the ledger'), ('draft', 'Not yet posted')], default='posted', max_length=8),
        ),
        migrations.AddField(
            model_name='supplierreconrun',
            name='total_not_posted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddIndex(
            model_name='invoicereconitem',
            index=models.Index(fields=['ledger_stage'], name='reconitem_stage_idx'),
        ),
    ]
