# Generated by Django 5.2 on 2026-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_recon', '0005_claims_other_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconsupplierprofile',
            name='category',
            field=models.CharField(choices=[('panel_beater', 'Panel Beater'), ('parts', 'Parts Supplier'), ('towing', 'Towing / Recovery'), ('assessor', 'Assessor'), ('glass', 'Glass Fitment'), ('medical', 'Medical Provider'), ('claims_other', 'Claims Supplier (trade unconfirmed)'), ('general', 'General / Operations'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierreconline',
            name='category',
            field=models.CharField(choices=[('panel_beater', 'Panel Beater'), ('parts', 'Parts Supplier'), ('towing', 'Towing / Recovery'), ('assessor', 'Assessor'), ('glass', 'Glass Fitment'), ('medical', 'Medical Provider'), ('claims_other', 'Claims Supplier (trade unconfirmed)'), ('general', 'General / Operations'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
