# Generated by Django 5.2 on 2026-07-25 15:03

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_compliancebrainsummary'),
        ('supplier_recon', '0006_alter_reconsupplierprofile_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierreconrun',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_recon_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReconOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_recon_owner', to='core.company')),
                ('owner', models.ForeignKey(help_text='Accountable owner. Escalations default to this person.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_recon_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recon Board Owner',
                'verbose_name_plural': 'Recon Board Owners',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
