# Generated by Django 5.2 on 2026-08-24 18:28

import core.models
import django.db.models.deletion
import supplier_recon.statement_models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_recon', '0008_line_overdue_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_date', models.DateField(blank=True, help_text='Date printed on the statement.', null=True)),
                ('currency', models.CharField(default='BWP', max_length=3)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('original_file', models.FileField(blank=True, max_length=400, null=True, upload_to=supplier_recon.statement_models._statement_upload_path)),
                ('file_name', models.CharField(blank=True, default='', max_length=400)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 of the uploaded bytes.', max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('matched', 'Matched'), ('error', 'Error')], default='uploaded', max_length=12)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='supplier_recon.supplierreconline')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_supplier_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('line_type', models.CharField(choices=[('invoice', 'Invoice / Charge'), ('credit_note', 'Credit Note'), ('payment', 'Payment / Receipt'), ('balance_fwd', 'Balance Brought Forward'), ('other', 'Other / Unclassified')], default='invoice', max_length=12)),
                ('reference', models.CharField(blank=True, default='', help_text='Supplier invoice / document number.', max_length=100)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Original row as parsed, for audit.')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_recon.supplierstatement')),
            ],
            options={
                'ordering': ['statement', 'row_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatementMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('matched', 'Matched'), ('amount_variance', 'Amount Variance'), ('credit_note', 'Credit Note'), ('already_paid', 'Already Paid in Omni'), ('statement_only', 'On Statement, not in Omni'), ('omni_only', 'In Omni, not on Statement'), ('duplicate', 'Duplicate on Statement'), ('unmatched_payment', 'Statement Payment, no Omni match')], max_length=18)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('proposal', models.CharField(choices=[('pay_now', 'Pay now'), ('hold', 'Hold'), ('do_not_pay', 'Do not pay'), ('investigate', 'Investigate')], default='investigate', max_length=12)),
                ('proposed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('recon_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_matches', to='supplier_recon.invoicereconitem')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='supplier_recon.supplierstatement')),
                ('statement_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='supplier_recon.supplierstatementline')),
            ],
            options={
                'ordering': ['match_type', 'statement_line__row_number'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='supplierstatement',
            index=models.Index(fields=['line', 'status'], name='stmt_line_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('checksum__gt', '')), fields=('line', 'checksum'), name='uniq_statement_line_checksum'),
        ),
        migrations.AddIndex(
            model_name='supplierstatementline',
            index=models.Index(fields=['statement', 'line_type'], name='stmtline_type_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstatementline',
            index=models.Index(fields=['reference'], name='stmtline_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='statementmatch',
            index=models.Index(fields=['statement', 'match_type'], name='stmtmatch_type_idx'),
        ),
        migrations.AddIndex(
            model_name='statementmatch',
            index=models.Index(fields=['statement', 'proposal'], name='stmtmatch_prop_idx'),
        ),
    ]
