# Generated by Django 5.2 on 2026-05-11 04:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, default='', help_text='Omang. Stored locally — do not include in API responses beyond the payslip context.', max_length=50),
        ),
        migrations.AlterField(
            model_name='payrollimportbatch',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Period the imported payslips will land in. Created on the fly if the file references one not in the system.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_name',
            field=models.CharField(help_text='e.g. 2026-05', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='ctc_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost to Company = Gross + Company contributions.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='payslipcomponent',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='If True, contributes to gross taxable income for PAYE. Pre-tax deductions reduce taxable income.'),
        ),
        migrations.AlterField(
            model_name='payslipcomponent',
            name='name',
            field=models.CharField(help_text='Header label as it appears on the payslip.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payslipcomponent',
            name='posting_account_code',
            field=models.CharField(blank=True, default='', help_text='Optional GL account code that this component should be posted to when generating the payroll JE. Leave blank to configure later.', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative tax due at lower_bound.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='effective_from',
            field=models.DateField(help_text='First date this band applies for monthly runs.'),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='lower_bound',
            field=models.DecimalField(decimal_places=2, help_text='Annual taxable income, exclusive lower bound.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='name',
            field=models.CharField(help_text='Human label, e.g. "Resident individual 2024-2025"', max_length=80),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='rate_pct',
            field=models.DecimalField(decimal_places=2, help_text='Marginal rate within this band (e.g. 12.00 for 12%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxbracket',
            name='upper_bound',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual taxable income, inclusive upper bound. NULL = no cap.', max_digits=18, null=True),
        ),
    ]
