# Generated by Claude for issue #57 — adds POSTED status to PayrollPeriod
# and a journal_entry FK so the period's GL posting can be tracked.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger',  '0008_journaltype_payroll_commitment'),
        ('payroll', '0003_alter_employee_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(
                choices=[
                    ('open',     'Open'),
                    ('locked',   'Locked (calculated, awaiting approval)'),
                    ('approved', 'Approved (ready to pay)'),
                    ('posted',   'Posted to GL'),
                    ('paid',     'Paid'),
                ],
                default='open',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='journal_entry',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'The GL entry created when this period was posted. '
                    'NULL until POSTED, cleared on reversal.'
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payroll_periods',
                to='ledger.journalentry',
            ),
        ),
    ]
