# Generated by Django 5.2 on 2026-07-26 04:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_medical_aid_ee_post_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloan',
            name='annual_rate_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), help_text='Annual interest %. 0 → straight-line amortisation.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='outstanding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Live outstanding balance — decremented by apply_loan_repayments() each period.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original loan amount advanced to the employee.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='start_period',
            field=models.ForeignKey(blank=True, help_text='First period this loan starts deducting from. Null → starts the next OPEN period encountered.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_starting_here', to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='term_months',
            field=models.PositiveIntegerField(default=12, help_text='Number of monthly instalments.'),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='allowance_template',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of recurring allowances at signing — {component_code: amount}. Picked up by the amendment engine when materialising the next period.'),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Basic salary per `frequency`. BWP unless `currency_code` differs.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollamendment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Signed BWP. For HIRE this is the new gross. For SALARY_CHANGE the new basic. For BONUS / OVERTIME / ARREARS the one-off amount.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollamendment',
            name='approver',
            field=models.CharField(blank=True, default='', help_text='Free-text approver name from the spreadsheet.', max_length=120),
        ),
        migrations.AlterField(
            model_name='payrollamendment',
            name='component',
            field=models.ForeignKey(blank=True, help_text='The payslip line being added / changed / removed. Null for hire/terminate.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='payroll.payslipcomponent'),
        ),
        migrations.AlterField(
            model_name='payrollamendment',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Resolved at parse time. Null = unresolved (see resolution_error).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_amendments', to='payroll.employee'),
        ),
        migrations.AlterField(
            model_name='payrollamendment',
            name='employee_ref',
            field=models.CharField(blank=True, default='', help_text='Raw employee identifier from the spreadsheet (employee_number or full_name).', max_length=120),
        ),
        migrations.AlterField(
            model_name='payrollamendmentbatch',
            name='baseline_period',
            field=models.ForeignKey(help_text='Source period whose payslips form the starting point.', on_delete=django.db.models.deletion.PROTECT, related_name='used_as_baseline', to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payrollamendmentbatch',
            name='target_period',
            field=models.ForeignKey(help_text='The period being CREATED (e.g. May 2026). Amendments shift the baseline (April 2026) → this period.', on_delete=django.db.models.deletion.PROTECT, related_name='amendment_batches', to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payslipcomponent',
            name='computation_kind',
            field=models.CharField(choices=[('fixed', 'Fixed amount (no formula)'), ('percent_of', 'Percent of another line'), ('formula', 'Custom safe formula')], default='fixed', help_text='How this component is computed. Drives payroll/formula_engine.py; ignored when fixed.', max_length=12),
        ),
        migrations.AlterField(
            model_name='payslipcomponent',
            name='formula',
            field=models.CharField(blank=True, default='', help_text='Safe expression evaluated by formula_engine. Whitelisted names: BASIC, GROSS, PRIOR_LINES_DICT.', max_length=200),
        ),
    ]
