# Generated by Django 5.2 on 2026-07-26 21:34

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_sync_model_state_2026_07_26'),
        ('payroll', '0016_sync_model_state_2026_07_26'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSignOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Awaiting CFO sign-off'), ('approved', 'Signed off by CFO'), ('rejected', 'Sent back by CFO')], default='submitted', max_length=12)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('paye_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('submitted_at', models.DateTimeField()),
                ('submit_note', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_sign_offs_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_sign_offs', to='core.company')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sign_offs', to='payroll.payrollperiod')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_sign_offs_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_sign_offs_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Sign-off',
                'verbose_name_plural': 'Payroll Sign-offs',
                'ordering': ['-period__start_date', 'company__name'],
                'abstract': False,
                'unique_together': {('period', 'company')},
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
