# Generated by Django 5.2 on 2026-08-12 17:35

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_bugreport_status_check'),
        ('payroll', '0019_employee_is_test_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdditionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Finance sign-off'), ('approved', 'Approved — live on the payroll'), ('rejected', 'Rejected — returned to requester')], default='pending', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('employee_number', models.CharField(blank=True, default='', max_length=60)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('incentive', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('allowances', models.JSONField(blank=True, default=list)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_comment', models.TextField(blank=True, default='')),
                ('linked_existing', models.BooleanField(default=False, help_text='True if approval linked to an existing employee instead of creating one.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_addition_requests', to='core.company')),
                ('created_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll.employee')),
                ('created_payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll.payslip')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_additions_decided', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addition_requests', to='payroll.payrollperiod')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_additions_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Addition Request',
                'verbose_name_plural': 'Payroll Addition Requests',
                'ordering': ['-requested_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
