# Generated by Django 5.2 on 2026-09-12 13:04

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_employee_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Payroll Setting',
                'verbose_name_plural': 'Payroll Settings',
                'ordering': ['key'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='employee',
            name='recruit_authority_ref',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
