# Generated by Django 5.2 on 2026-09-13 05:54

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ariapopup'),
        ('payroll', '0022_payrollsetting_employee_recruit_authority_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollamendment',
            name='feed_key',
            field=models.CharField(blank=True, editable=False, help_text='Automatic-feed fingerprint. Unique — the database-level no-double-pay guard. NULL for hand-keyed rows.', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_period', models.CharField(db_index=True, help_text='Payroll period the full amount is deducted in, e.g. 2026-10.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='BWP advanced — recovered in full.', max_digits=18)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly BASIC (BWP) from the latest payslip at request time.', max_digits=18)),
                ('basic_source', models.CharField(blank=True, default='', help_text='Period the BASIC snapshot came from.', max_length=20)),
                ('max_allowed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One third of basic_salary — the cap that applied on the day.', max_digits=18)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_cfo', 'Awaiting CFO approval'), ('approved', 'Approved by the CFO'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('recovered', 'Recovered from payroll')], db_index=True, default='pending_cfo', max_length=12)),
                ('cfo_approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('cfo_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='payroll.employee')),
                ('payroll_amendment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances', to='payroll.payrollamendment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending_cfo', 'approved', 'recovered'])), fields=('employee', 'recovery_period'), name='uniq_salary_advance_open_per_period')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
