# Generated by Django 5.2 on 2026-09-13 12:32

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ariapopup'),
        ('payroll', '0023_payrollamendment_feed_key_salaryadvance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollOrchestrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(db_index=True, help_text='e.g. 2026-10', max_length=10)),
                ('company_key', models.CharField(default='ALL', editable=False, max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('refused', 'Refused — nothing was touched'), ('ok', 'Completed'), ('empty', 'Completed but did NOTHING'), ('attention', 'Completed with gaps to look at'), ('failed', 'A step failed')], db_index=True, default='running', max_length=12)),
                ('trigger', models.CharField(choices=[('cron', 'Scheduled'), ('manual', 'Run by hand')], default='manual', max_length=8)),
                ('refusal_reason', models.TextField(blank=True, default='', help_text='Why nothing was touched.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_touched', models.PositiveIntegerField(default=0, help_text='Total amendment / payslip rows the steps raised or refreshed. Zero means NOTHING happened.')),
                ('gaps', models.TextField(blank=True, default='', help_text='Commission-population gaps found. Reported, never silently widened.')),
                ('notified_to', models.CharField(blank=True, default='', max_length=500)),
                ('notify_error', models.CharField(blank=True, default='', max_length=300)),
                ('company', models.ForeignKey(blank=True, help_text='NULL = every entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_orchestration_runs', to='core.company')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestration_runs', to='payroll.payrollperiod')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_orchestration_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Orchestration Run',
                'verbose_name_plural': 'Payroll Orchestration Runs',
                'ordering': ['-started_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollOrchestrationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ok', 'Ran'), ('nothing', 'Ran, found nothing to do'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='ok', max_length=8)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='payroll.payrollorchestrationrun')),
            ],
            options={
                'verbose_name': 'Payroll Orchestration Step',
                'verbose_name_plural': 'Payroll Orchestration Steps',
                'ordering': ['run', 'sequence'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='payrollorchestrationrun',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'running')),
                fields=('period_label', 'company_key'),
                name='uniq_orchestration_running_per_period_company'),
        ),
    ]
