# Generated by Django 5.2 on 2026-09-13 13:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_payrollorchestrationrun_payrollorchestrationstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvancePayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='BWP paid out by Finance.', max_digits=18)),
                ('paid_on', models.DateField(help_text='Date Finance paid it (Botswana time).')),
                ('reference', models.CharField(blank=True, default='', help_text='Bank / payment reference, for the trail.', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('advance', models.ForeignKey(blank=True, help_text='The approved advance this settles. Blank = none was found.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payroll.salaryadvance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advance_payouts', to='payroll.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Advance Payout',
                'verbose_name_plural': 'Salary Advance Payouts',
                'ordering': ['-paid_on', '-created_at'],
                'abstract': False,
            },
        ),
    ]
