# Generated by Django 5.2 on 2026-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_adopt_legacy_auto_feed_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='keep_access_after_exit',
            field=models.BooleanField(db_index=True, default=False, help_text='Keep the Omni login open after the exit date (external contractor or similar). HR sets this — the automatic close-off skips anyone ticked here.'),
        ),
    ]
