# Generated by Django 5.2 on 2026-09-19 10:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_access_delegate_and_module_access"),
        ("payroll", "0028_keep_access_contractor_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentcontract",
            name="retirement_fund",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pension", "Pension fund"),
                    ("provident", "Provident fund"),
                    ("none", "None"),
                ],
                default="",
                help_text="Pension or provident fund (HC 19-Sep-2026).",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="GroupPayrollSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("schedule", "Scheduled (28th)"),
                            ("manual", "Regenerated by hand"),
                        ],
                        default="schedule",
                        max_length=10,
                    ),
                ),
                ("totals", models.JSONField(blank=True, default=dict)),
                (
                    "excluded",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Company names left out of the group total.",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_payroll_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_snapshots",
                        to="payroll.payrollperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupPayrollLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("final", "Signed off"),
                            ("draft", "Draft — not signed off"),
                            ("not_run", "Not yet run"),
                        ],
                        max_length=8,
                    ),
                ),
                ("headcount", models.PositiveIntegerField(default=0)),
                (
                    "basic",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "incentive",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "employer_contrib",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "paye",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "ctc",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "source_currency",
                    models.CharField(blank=True, default="BWP", max_length=3),
                ),
                (
                    "source_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "fx_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("tieout_ok", models.BooleanField(default=True)),
                (
                    "tieout_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("by_department", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_payroll_lines",
                        to="core.company",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payroll.grouppayrollsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="grouppayrollsnapshot",
            constraint=models.UniqueConstraint(
                fields=("period", "version"), name="uniq_group_payroll_period_version"
            ),
        ),
    ]
