# Generated by Django 5.2 on 2026-07-03 05:03

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0031_sod_senior_accountant_title"),
        ("ledger", "0026_posted_je_immutable_triggers"),
        ("reporting", "0001_reconciliation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSourceMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_key", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                (
                    "unit",
                    models.CharField(
                        choices=[("bwp", "BWP"), ("count", "Count")],
                        default="bwp",
                        max_length=8,
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("period", "Period flow (P&L)"),
                            ("balance", "As-of balance (BS)"),
                            ("none", "No GL side"),
                        ],
                        default="period",
                        help_text="period = P&L flow over [from,to]; balance = cumulative as-of to.",
                        max_length=8,
                    ),
                ),
                (
                    "include_all_receivable",
                    models.BooleanField(
                        default=False,
                        help_text="If set, also include every Account with is_receivable=True.",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("graphite_rds", "Graphite (read-only replica)"),
                            ("register", "Expected-figures register (manual)"),
                            ("reporting_portal", "Reporting portal extract"),
                        ],
                        default="register",
                        max_length=20,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text source pointer (Graphite table, report type, note).",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "accounts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="GL accounts summed (signed) to get the omni posted figure.",
                        related_name="recon_metrics",
                        to="ledger.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric source map",
                "verbose_name_plural": "Metric source maps",
                "ordering": ["sort_order", "metric_key"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_label", models.CharField(db_index=True, max_length=24)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(db_index=True)),
                (
                    "tolerance_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=12,
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recon_runs",
                        to="core.company",
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recon_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation run",
                "verbose_name_plural": "Reconciliation runs",
                "ordering": ["-run_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReconciliationLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_key", models.CharField(db_index=True, max_length=40)),
                ("label", models.CharField(max_length=120)),
                (
                    "unit",
                    models.CharField(
                        choices=[("bwp", "BWP"), ("count", "Count")],
                        default="bwp",
                        max_length=8,
                    ),
                ),
                (
                    "source_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("graphite_rds", "Graphite (read-only replica)"),
                            ("register", "Expected-figures register (manual)"),
                            ("reporting_portal", "Reporting portal extract"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "omni_posted",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "variance_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("breach", "Breach"),
                            ("no_source", "No source figure"),
                            ("no_omni_side", "No omni GL side"),
                        ],
                        max_length=14,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "reconciliation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recon_hub_lines",
                        to="reporting.reconciliation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reconciliation_hub.reconciliationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation line",
                "verbose_name_plural": "Reconciliation lines",
                "ordering": ["run", "metric_key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgeingTieOut",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bucket", models.CharField(max_length=8)),
                (
                    "graphite_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "omni_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "portal_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "variance_graphite_vs_omni",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "variance_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("breach", "Breach"),
                            ("no_source", "No source figure"),
                            ("no_omni_side", "No omni GL side"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ageing_tieouts",
                        to="reconciliation_hub.reconciliationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ageing tie-out",
                "verbose_name_plural": "Ageing tie-outs",
                "ordering": ["run", "bucket"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceFigure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_label", models.CharField(db_index=True, max_length=24)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(db_index=True)),
                ("metric_key", models.CharField(db_index=True, max_length=40)),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("graphite_rds", "Graphite (read-only replica)"),
                            ("register", "Expected-figures register (manual)"),
                            ("reporting_portal", "Reporting portal extract"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                ("row_count", models.IntegerField(blank=True, null=True)),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recon_source_figures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recon_source_figures",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source figure",
                "verbose_name_plural": "Source figures",
                "ordering": ["-period_end", "metric_key"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["company", "period_label", "metric_key"],
                        name="reconciliat_company_828c68_idx",
                    )
                ],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
