# Generated by Django 5.2 on 2026-05-10 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FNBBatchSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('total_amount_bwp', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency_code', models.CharField(default='BWP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending submission'), ('submitted', 'Submitted to FNB'), ('acknowledged', 'Acknowledged by FNB'), ('settled', 'Settled (funds debited)'), ('failed', 'Failed'), ('cancelled', 'Cancelled before submission')], default='pending', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('fnb_reference', models.CharField(blank=True, default='', help_text='Reference issued by FNB on acknowledgement (their batch ID).', max_length=100)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_account', models.ForeignKey(help_text='The Alpha Direct FNB account being debited.', on_delete=django.db.models.deletion.PROTECT, related_name='fnb_batches', to='banking.bankaccount')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_batches_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FNB Batch Submission',
                'verbose_name_plural': 'FNB Batch Submissions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FNBSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound (we → FNB)'), ('inbound', 'Inbound (FNB → us)')], max_length=10)),
                ('service', models.CharField(choices=[('statement', 'Bank statement pull'), ('payment_batch', 'EFT batch submission'), ('payment_ack', 'Payment acknowledgement'), ('balance', 'Account balance check'), ('beneficiary', 'Beneficiary sync'), ('webhook', 'Generic webhook'), ('auth', 'Auth / token'), ('test', 'Connection test'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timed out'), ('skipped', 'Skipped (not configured)')], default='pending', max_length=10)),
                ('endpoint', models.CharField(blank=True, default='', help_text='URL path or webhook source.', max_length=300)),
                ('http_method', models.CharField(blank=True, default='', max_length=10)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('request_summary', models.TextField(blank=True, default='', help_text='Short human-readable description (e.g. "pull statements 1110 from 2026-05-01 to 2026-05-09").')),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Outbound request body, redacted of secrets.')),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Inbound response body or webhook event, raw.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='fnb.fnbbatchsubmission')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FNB Sync Log',
                'verbose_name_plural': 'FNB Sync Logs',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['direction', '-created_at'], name='fnb_fnbsync_directi_e24832_idx'), models.Index(fields=['service', '-created_at'], name='fnb_fnbsync_service_4d2509_idx'), models.Index(fields=['status'], name='fnb_fnbsync_status_5ca0c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FNBWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, default='', help_text='As reported by FNB (payment.acknowledged, statement.ready, etc.)', max_length=80)),
                ('external_id', models.CharField(blank=True, default='', help_text='FNB-assigned event ID for idempotent replay.', max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Signature verified'), ('processed', 'Processed'), ('rejected', 'Rejected (signature fail)'), ('failed', 'Processing failed')], default='received', max_length=12)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='fnb.fnbbatchsubmission')),
            ],
            options={
                'verbose_name': 'FNB Webhook Event',
                'verbose_name_plural': 'FNB Webhook Events',
                'ordering': ['-received_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='uq_fnb_webhook_external_id')],
            },
        ),
    ]
