# Generated by Django 5.2 on 2026-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnb", "0002_fnbcredential"),
        ("payments", "0012_payment_bank_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="fnbbatchsubmission",
            name="payments",
            field=models.ManyToManyField(
                blank=True, related_name="fnb_batches", to="payments.payment"
            ),
        ),
        migrations.AlterField(
            model_name="fnbbatchsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending submission"),
                    ("submitted", "Submitted to FNB"),
                    ("acknowledged", "Acknowledged by FNB"),
                    ("settled", "Settled (funds debited)"),
                    ("failed", "Failed (rejected — no money moved)"),
                    ("unknown", "Unknown — verify with FNB before resubmit"),
                    ("cancelled", "Cancelled before submission"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="fnbsynclog",
            name="service",
            field=models.CharField(
                choices=[
                    ("statement", "Bank statement pull"),
                    ("payment_batch", "EFT batch submission"),
                    ("payment_ack", "Payment acknowledgement"),
                    ("balance", "Account balance check"),
                    ("beneficiary", "Beneficiary sync"),
                    ("notification", "Notification feed pull"),
                    ("txn_history", "Transaction history pull"),
                    ("webhook", "Generic webhook"),
                    ("auth", "Auth / token"),
                    ("test", "Connection test"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
