# Generated by Django 5.2 on 2026-08-04 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0004_fnbbatchsubmission_payroll_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='FNBHealthAlertState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('unknown', 'Unknown'), ('up', 'Up'), ('down', 'Down')], default='unknown', max_length=10)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'FNB Health Alert State',
                'verbose_name_plural': 'FNB Health Alert State',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
