# Generated by Django 5.2 on 2026-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnb", "0005_fnbhealthalertstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="fnbhealthalertstate",
            name="stuck_keys",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="fnbhealthalertstate",
            name="stuck_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
