# Generated by Django 5.2 on 2026-08-26 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0006_fnbhealthalertstate_stuck_keys_and_more'),
        ('integrations', '0013_event_idempotency_attribution'),
        ('taskboard', '0020_payment_request_bank_wording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FNBProofOfPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph_message_id', models.CharField(max_length=512, unique=True)),
                ('mailbox', models.CharField(max_length=200)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body_text', models.TextField(help_text='The email exactly as FNB sent it. This IS the proof.')),
                ('reference', models.CharField(db_index=True, max_length=200)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=18)),
                ('bank_status', models.CharField(blank=True, default='', max_length=60)),
                ('paid', models.BooleanField(db_index=True, default=False)),
                ('proof_pdf', models.FileField(blank=True, null=True, upload_to='fnb-pop/%Y/%m/')),
                ('state', models.CharField(choices=[('filed_claim', 'Filed against a claim'), ('filed_request', 'Filed against a payment request'), ('unfiled', 'Unfiled — no record in Omni'), ('proposed', 'Match proposed, awaiting confirmation'), ('dismissed', 'Reviewed, deliberately left unfiled')], db_index=True, default='unfiled', max_length=16)),
                ('claim_number_seen', models.CharField(blank=True, db_index=True, default='', help_text='The claim number read out of the FNB reference, even when no claim row matched it.', max_length=64)),
                ('proposed_kind', models.CharField(blank=True, default='', help_text="'claim' or 'payment_request'", max_length=16)),
                ('proposed_ref', models.CharField(blank=True, default='', max_length=120)),
                ('proposed_reason', models.TextField(blank=True, default='')),
                ('proposed_at', models.DateTimeField(blank=True, null=True)),
                ('proposal_engine', models.CharField(blank=True, default='', max_length=40)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_proofs', to='integrations.graphiteclaim')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_fnb_proofs', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_proofs', to='taskboard.paymentrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['state', '-received_at'], name='fnb_fnbproo_state_f31828_idx'), models.Index(fields=['paid', 'state'], name='fnb_fnbproo_paid_6cec37_idx')],
            },
        ),
    ]
