# Generated by Django 5.2 on 2026-09-04 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0008_expresspayee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expresspayee',
            constraint=models.UniqueConstraint(fields=('account_number',), name='uniq_expresspayee_account'),
        ),
    ]
