# Generated by Django 5.2 on 2026-09-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0010_synclog_waiting_status'),
        ('taskboard', '0033_alter_paymentrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnbbatchsubmission',
            name='payment_request',
            field=models.ForeignKey(blank=True, help_text='The payment request this batch came from. One request can produce several batches (one per line under Individual processing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fnb_batches', to='taskboard.paymentrequest'),
        ),
    ]
