# Generated by Django 5.2 on 2026-03-24 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(choices=[('graphite', 'Graphite (Policy System)'), ('bank_api', 'Bank API')], max_length=30)),
                ('event_type', models.CharField(choices=[('policy_issued', 'Policy Issued'), ('policy_cancelled', 'Policy Cancelled'), ('claim_approved', 'Claim Approved'), ('commission_calculated', 'Commission Calculated'), ('bank_transaction', 'Bank Transaction')], max_length=50)),
                ('event_data', models.JSONField(help_text='Full event payload as received from source system.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('result_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('payment', 'Payment')], max_length=20, null=True)),
                ('result_id', models.UUIDField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source_system', 'event_type'], name='integration_source__cc717c_idx'), models.Index(fields=['status'], name='integration_status_f01e92_idx')],
            },
        ),
    ]
