# Generated by Django 5.2 on 2026-06-16 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_graphite_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDoctorDailySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.CharField(db_index=True, max_length=64)),
                ('as_of', models.DateField(db_index=True, help_text='The day these figures cover.')),
                ('totals', models.JSONField(default=dict, help_text='Company roll-up (hours, productivity %, counts).')),
                ('payload', models.JSONField(default=list, help_text='Per-user aggregates (no raw titles).')),
                ('emailed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Time Doctor Daily Snapshot',
                'verbose_name_plural': 'Time Doctor Daily Snapshots',
                'ordering': ['-as_of'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('company_id', 'as_of'), name='intg_td_company_asof_uniq')],
            },
        ),
    ]
