# Generated by Django 5.2 on 2026-07-14 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_graphiteclaim_damage_cause'),
        ('payroll', '0010_employmentcontract_type_probation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDoctorUserMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('td_user_id', models.CharField(db_index=True, help_text='Time Doctor user id (stable).', max_length=64, unique=True)),
                ('td_name', models.CharField(blank=True, default='', max_length=191)),
                ('td_email', models.CharField(blank=True, default='', max_length=191)),
                ('confirmed', models.BooleanField(default=False, help_text='Confirmed by a human â€” the matcher trusts this above all name matching.')),
                ('source', models.CharField(choices=[('auto', 'Auto-suggested by the matcher'), ('manual', 'Set by a human')], default='auto', max_length=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='td_maps', to='payroll.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Doctor User Map',
                'verbose_name_plural': 'Time Doctor User Map',
                'ordering': ['td_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['confirmed'], name='intg_tdmap_confirmed_idx')],
            },
        ),
    ]
