# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedoctorusermap',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Confirmed by a human — the matcher trusts this above all name matching.'),
        ),
    ]
