# Generated by Django 5.2 on 2026-09-02 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_graphiteclaim_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatusCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(help_text='On-file address the code was sent to (audit).', max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('sent_ip', models.CharField(blank=True, default='', max_length=45)),
            ],
            options={
                'verbose_name': 'Claim-status code',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['claim_number', 'consumed', 'expires_at'], name='integration_claim_n_df4984_idx')],
            },
        ),
    ]
