# Generated by Django 5.2 on 2026-09-08 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0016_screen_integrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealpayReconSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asof", models.DateField(db_index=True)),
                ("window_months", models.PositiveSmallIntegerField(default=6)),
                ("verdict", models.CharField(db_index=True, max_length=8)),
                ("summary", models.TextField(blank=True, default="")),
                ("total_shortfall", models.PositiveIntegerField(default=0)),
                ("months_breached", models.PositiveSmallIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "RealPay reconciliation snapshot",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="integration_created_b092c8_idx"
                    ),
                    models.Index(
                        fields=["asof", "verdict"], name="integration_asof_048d89_idx"
                    ),
                ],
            },
        ),
    ]
