# Generated by Django 5.2 on 2026-09-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_realpay_recon_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationevent',
            name='event_type',
            field=models.CharField(choices=[('policy_issued', 'Policy Issued'), ('policy_cancelled', 'Policy Cancelled'), ('claim_approved', 'Claim Approved'), ('commission_calculated', 'Commission Calculated'), ('bank_transaction', 'Bank Transaction'), ('claim_registered', 'Claim Registered'), ('form_submitted', 'Customer Form Submitted'), ('premium_checked', 'Premium Checked'), ('assessment_received', 'Assessment Received'), ('write_off_flagged', 'Write-off Flagged'), ('decision_recorded', 'Decision Recorded')], max_length=50),
        ),
    ]
