# Generated by Django 5.2 on 2026-09-24 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_screenflag_idle_frozen'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(choices=[('graphite', 'Graphite (Policy System)')], db_index=True, max_length=30)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(help_text='Fact/state to deliver. No money, no external PII.')),
                ('endpoint', models.URLField(help_text='Resolved target URL to POST to.', max_length=500)),
                ('auth_kind', models.CharField(choices=[('bearer', 'Bearer token'), ('apikey', 'ApiKey scope'), ('none', 'No auth')], default='bearer', max_length=10)),
                ('token_setting', models.CharField(blank=True, default='', help_text='NAME of the settings attribute holding the secret (resolved at send; never stored).', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed (will retry)'), ('dead', 'Dead (gave up)')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=6)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, help_text='When the worker should next try (backoff).', null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text="Sender's own unique id for this event; blank = not supplied.", max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='outevent_due_idx'), models.Index(fields=['target', 'event_type'], name='integration_target_d783f1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='outevent_idempotency_key_uniq')],
            },
        ),
    ]
