# Generated by Django 5.2 on 2026-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalrequirementparameter',
            name='value',
            field=models.CharField(help_text='String — services parse to Decimal or list as needed.', max_length=200),
        ),
        migrations.AlterField(
            model_name='regulatorycapitalsnapshot',
            name='capital_adequacy_ratio',
            field=models.DecimalField(decimal_places=4, help_text='Available / Required', max_digits=10),
        ),
        migrations.AlterField(
            model_name='regulatorycapitalsnapshot',
            name='components',
            field=models.JSONField(blank=True, default=dict, help_text='Full breakdown — equity, deductions, GWP, claims, the 3 candidates for required, etc.'),
        ),
    ]
