# Generated by Django 5.2 on 2026-09-11 09:15

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0002_alter_capitalrequirementparameter_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxComplianceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vat_cycle', models.CharField(choices=[('category_b', 'Two-monthly, Category B (periods end Feb/Apr/Jun/Aug/Oct/Dec)'), ('category_a', 'Two-monthly, Category A (periods end Jan/Mar/May/Jul/Sep/Nov)'), ('monthly', 'Monthly')], default='category_b', help_text='BURS VAT registration category. CFO-confirmed as Category B on 2026-09-11.', max_length=20)),
                ('financial_year_end_month', models.PositiveSmallIntegerField(default=6, help_text='Month the financial year ends. Alpha Direct = 6 (30 June).')),
                ('months_ahead', models.PositiveSmallIntegerField(default=18, help_text='How far ahead obligations are generated. 18 months keeps a full year visible without the board filling with distant items.')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_compliance_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax compliance settings',
                'verbose_name_plural': 'Tax compliance settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxObligationOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT return and payment'), ('paye', 'PAYE monthly remittance'), ('owht', 'OWHT monthly remittance'), ('paye_annual', 'Annual PAYE/OWHT return'), ('sat_quarterly', 'SAT quarterly instalment'), ('sat_annual', 'SAT annual return and final balance')], max_length=20, unique=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The preparer. Reminders go to this person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_obligations_owned', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_obligation_owner_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tax_type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxComplianceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obligation_key', models.CharField(help_text='Stable identity from tax_calendar.py, e.g. "vat:2026-10-31". Unique so regenerating the schedule can never duplicate a filing.', max_length=60, unique=True)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT return and payment'), ('paye', 'PAYE monthly remittance'), ('owht', 'OWHT monthly remittance'), ('paye_annual', 'Annual PAYE/OWHT return'), ('sat_quarterly', 'SAT quarterly instalment'), ('sat_annual', 'SAT annual return and final balance')], max_length=20)),
                ('period_label', models.CharField(max_length=60)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField(db_index=True, help_text='The STATUTORY deadline. Passing this without CFO verification is a breach.')),
                ('target_date', models.DateField(db_index=True, help_text='Internal deadline, 10 days before the statutory one. Reminders start here and lateness is measured against it.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('reminding', 'Active / reminding'), ('preparer_complete', 'Preparer complete'), ('verified', 'CFO verified / closed'), ('late', 'Closed late (before due date)'), ('breach', 'BREACH - statutory date missed')], db_index=True, default='scheduled', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True, default='', help_text='What was filed, and the BURS reference if there is one.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_note', models.TextField(blank=True, default='')),
                ('late_reason', models.TextField(blank=True, default='', help_text='State 5 only: completed after the 10-day target but before the statutory due date. An internal service miss.')),
                ('breach_note', models.TextField(blank=True, default='', help_text='State 6 only, CFO-written: the statutory date was missed. A live BURS exposure. Separate from late_reason by design - never merge them.')),
                ('breach_flagged_at', models.DateTimeField(blank=True, help_text='When the CFO was alerted to the breach. Set once; the alert never repeats.', null=True)),
                ('last_reminded_on', models.DateField(blank=True, help_text='Guards against two reminder runs in one day sending two emails.', null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Snapshotted from TaxObligationOwner when the task is created, so reassigning a tax type later does not rewrite history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_compliance_tasks', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_tasks_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'tax_type'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'due_date'], name='regulatory__status_fb20a1_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
