# Generated by Django 5.2 on 2026-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0003_taxcompliancesettings_taxobligationowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcompliancesettings',
            name='vat_due_day',
            field=models.PositiveSmallIntegerField(default=25, help_text='Day of the month VAT falls due. CFO correction 2026-09-11: Alpha Direct pays on the 25th, not the 28th the tax advisers quote.'),
        ),
    ]
