# Generated by Django 5.2 on 2026-09-11 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0004_taxcompliancesettings_vat_due_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcompliancetask',
            name='date_change_reason',
            field=models.TextField(blank=True, default='', help_text='Why the statutory date was moved. Mandatory on any change.'),
        ),
        migrations.AddField(
            model_name='taxcompliancetask',
            name='date_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxcompliancetask',
            name='date_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_tasks_date_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcompliancetask',
            name='original_due_date',
            field=models.DateField(blank=True, help_text='The computed date, kept when someone overrides due_date. Null means the date has never been changed.', null=True),
        ),
        migrations.CreateModel(
            name='TaxCalendarEditor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', help_text='Why this person has the right. Shown to the CFO on review.', max_length=200)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_calendar_editors_added', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calendar_edit_right', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
                'abstract': False,
            },
        ),
    ]
