# Generated by Django 5.2 on 2026-08-08 11:19

from django.db import migrations, models


def backfill_out_since(apps, schema_editor):
    """Set out_since for files that are ALREADY out.

    Without this, every record currently on loan shows a blank day counter —
    including the ones Admin actually has out today, which are the whole reason
    the counter was asked for. Read the date from the movement history: the most
    recent ISSUE, or the earliest TRANSFER after it if the file was passed on.
    """
    RecordItem = apps.get_model('records', 'RecordItem')
    RecordMovement = apps.get_model('records', 'RecordMovement')
    for rec in RecordItem.objects.filter(status='issued'):
        mv = (RecordMovement.objects
              .filter(record_id=rec.pk, kind__in=('issue', 'transfer'))
              .order_by('-moved_at', '-id').first())
        # Walk back to the ISSUE that started this spell out, so a transfer does
        # not restart the clock.
        issue = (RecordMovement.objects
                 .filter(record_id=rec.pk, kind='issue')
                 .order_by('-moved_at', '-id').first())
        chosen = issue or mv
        if chosen is not None:
            RecordItem.objects.filter(pk=rec.pk).update(out_since=chosen.moved_at)


def unbackfill(apps, schema_editor):
    apps.get_model('records', 'RecordItem').objects.update(out_since=None)


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_fix_due_back_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorditem',
            name='department',
            field=models.CharField(blank=True, default='', help_text='The department the record belongs to.', max_length=120),
        ),
        migrations.AddField(
            model_name='recorditem',
            name='out_since',
            field=models.DateField(blank=True, null=True),
        ),
            migrations.RunPython(backfill_out_since, unbackfill),
    ]
