# Generated by Django 5.2 on 2026-08-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_recorditem_department_recorditem_out_since'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recorditem',
            options={'ordering': ['reference'], 'permissions': [('view_restricted_records', 'Can see records marked restricted (personal data)')]},
        ),
    ]
