# Generated by Django 5.2 on 2026-09-19 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "manager_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "manager_email",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("headcount_now", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_now",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("headcount_target", models.PositiveSmallIntegerField(default=0)),
                (
                    "reallocate_to_acquisition",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("automation_note", models.TextField(blank=True, default="")),
                ("manual_work_note", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["department"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("plain_summary", models.TextField(blank=True, default="")),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("switch_on", "Switch on what exists"),
                            ("collections", "Collections and refunds"),
                            ("policy", "Policy lifecycle"),
                            ("claims", "Claims end to end"),
                            ("finance", "Finance close"),
                            ("service", "Customer service"),
                            ("acquisition", "Customer acquisition"),
                        ],
                        db_index=True,
                        default="switch_on",
                        max_length=16,
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(db_index=True, default=1)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Canonical department (hris.departments).",
                        max_length=64,
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The person answerable for this step.",
                        max_length=120,
                    ),
                ),
                (
                    "manager_email",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("target_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=12,
                    ),
                ),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                (
                    "annual_saving_bwp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "fte_released",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "blocked_on",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("blocked_since", models.DateField(blank=True, null=True)),
                ("is_vendor", models.BooleanField(db_index=True, default=False)),
                (
                    "devlog_area",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("improves_customer_service", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["month", "code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PulseSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("taken_for", models.DateField(db_index=True, unique=True)),
                ("overall_percent", models.PositiveSmallIntegerField(default=0)),
                ("days_remaining", models.SmallIntegerField(default=0)),
                (
                    "staff_cost_now",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "staff_cost_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("headcount_now", models.PositiveSmallIntegerField(default=0)),
                ("headcount_target", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_of_delay_bwp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("narrative", models.TextField(blank=True, default="")),
                (
                    "narrative_source",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("judge_verdict", models.TextField(blank=True, default="")),
                (
                    "judge_source",
                    models.CharField(blank=True, default="", max_length=60),
                ),
            ],
            options={
                "ordering": ["-taken_for"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InitiativeUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("status", models.CharField(default="", max_length=12)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "actor_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="transformation.initiative",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
