# Generated by Django 5.2 on 2026-09-19 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_access_delegate_and_module_access"),
        ("transformation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InitiativeAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "assignee_email",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What this person is on the hook for.",
                        max_length=120,
                    ),
                ),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False,
                        help_text="The one answerable person for the step.",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transformation_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="transformation.initiative",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transformation_assignments",
                        to="core.omnitask",
                    ),
                ),
            ],
            options={
                "ordering": ["initiative__code", "-is_owner", "assignee_name"],
                "abstract": False,
            },
        ),
    ]
