# Generated by Django 5.2 on 2026-09-19 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_access_delegate_and_module_access"),
        ("transformation", "0002_initiativeassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="initiativeassignment",
            constraint=models.UniqueConstraint(
                fields=("initiative", "assignee"),
                name="uniq_assignment_per_person_per_step",
            ),
        ),
    ]
