# Generated by Django 5.2 on 2026-08-24 07:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskboard', '0020_payment_request_bank_wording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexPaymentImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringForexPayee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_key', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('typical_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('cadence', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('irregular', 'Irregular')], default='monthly', max_length=12)),
                ('typical_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_account', models.CharField(blank=True, default='', max_length=40)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('months_active', models.PositiveIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring forex payee',
                'verbose_name_plural': 'Recurring forex payees',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedForexPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.CharField(max_length=255)),
                ('beneficiary_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_value_date', models.DateField(db_index=True)),
                ('source_account', models.CharField(blank=True, default='', max_length=40)),
                ('driver', models.CharField(choices=[('recurring', 'Recurring'), ('reinsurance', 'Reinsurance'), ('claim', 'Claim'), ('manual', 'Manual')], default='manual', max_length=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('requested', 'Payment requested'), ('paid', 'Paid'), ('skipped', 'Skipped')], default='planned', max_length=12)),
                ('estimated_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('estimated_bwp', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rate_is_estimate', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_plan_lines', to='taskboard.paymentrequest')),
                ('recurring_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned', to='fx_planning.recurringforexpayee')),
            ],
            options={
                'verbose_name': 'Planned forex payment',
                'verbose_name_plural': 'Planned forex payments',
                'ordering': ['expected_value_date', 'currency'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForexPaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('beneficiary', models.CharField(max_length=255)),
                ('beneficiary_key', models.CharField(db_index=True, max_length=255)),
                ('payment_type', models.CharField(blank=True, default='', max_length=40)),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source_account', models.CharField(blank=True, default='', max_length=40)),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', to='fx_planning.forexpaymentimport')),
            ],
            options={
                'verbose_name': 'Forex payment (history)',
                'verbose_name_plural': 'Forex payment history',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['beneficiary_key', 'currency'], name='fx_planning_benefic_0eabf2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringforexpayee',
            constraint=models.UniqueConstraint(fields=('beneficiary_key', 'currency'), name='uniq_recurring_payee_ccy'),
        ),
        migrations.AddConstraint(
            model_name='plannedforexpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('driver', 'recurring')), fields=('recurring_payee', 'expected_value_date'), name='uniq_recurring_plan_per_date'),
        ),
    ]
