# Generated by Django 5.2 on 2026-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringforexpayee',
            name='amount_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='recurringforexpayee',
            name='amount_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='recurringforexpayee',
            name='watch',
            field=models.BooleanField(default=False),
        ),
    ]
