# Generated by Django 5.2 on 2026-08-21 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0060_stuckworkescalation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchdogRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_date', models.DateField(db_index=True)),
                ('focus', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='running', max_length=10)),
                ('dry_run', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checks_run', models.PositiveIntegerField(default=0)),
                ('checks_passed', models.PositiveIntegerField(default=0)),
                ('findings_safe', models.PositiveIntegerField(default=0)),
                ('findings_danger', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Watchdog run',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WatchdogReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Watchdog report log',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('report_date',), name='uniq_watchdog_report_per_day')],
            },
        ),
        migrations.CreateModel(
            name='WatchdogFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_key', models.CharField(db_index=True, max_length=60)),
                ('category', models.CharField(choices=[('integrity', 'Cross-module integrity'), ('business_rule', 'Business rule'), ('module_health', 'Module health'), ('bug', 'Bug board'), ('machine_talk', 'Machine-talk change')], max_length=20)),
                ('module', models.CharField(blank=True, default='', max_length=40)),
                ('severity', models.CharField(choices=[('ok', 'OK'), ('info', 'Info'), ('warn', 'Warning'), ('danger', 'Danger')], db_index=True, default='warn', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('flagged', models.BooleanField(db_index=True, default=False)),
                ('safe_to_autofix', models.BooleanField(default=False)),
                ('auto_action', models.CharField(blank=True, default='', max_length=200)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('omnitask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.omnitask')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='watchdog.watchdogrun')),
            ],
            options={
                'verbose_name': 'Watchdog finding',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['check_key', 'resolved'], name='watchdog_wa_check_k_048dee_idx')],
            },
        ),
    ]
