# Generated by Django 5.2 on 2026-03-31 10:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('master', 'Master (Company-wide)'), ('finance', 'Finance'), ('claims', 'Claims'), ('underwriting', 'Underwriting'), ('health', 'Health'), ('bd', 'Business Development'), ('operations', 'Operations'), ('it', 'IT')], default='master', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('revised', 'Revised')], default='draft', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='ledger.fiscalperiod')),
            ],
            options={
                'ordering': ['fiscal_period__start_date', 'department'],
                'abstract': False,
                'unique_together': {('fiscal_period', 'department')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budgeted amount for this account in this period (positive)', max_digits=18)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='ledger.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgets.budget')),
            ],
            options={
                'ordering': ['account__code'],
                'abstract': False,
                'unique_together': {('budget', 'account')},
            },
        ),
    ]
