# Generated by Django 5.2 on 2026-07-13 09:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_budgetpack"),
        ("core", "0035_omnitask_due_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpendRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("golf_day", "Golf day"),
                            ("entertainment", "Custom entertainment"),
                            ("staff_party", "Staff birthday party"),
                            ("broker_party", "Broker party"),
                            ("broker_birthday", "Broker birthday"),
                            ("training", "Training"),
                            ("travel", "Travel"),
                            ("travel_advance", "Travel advance"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="event",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount requested, BWP.",
                        max_digits=14,
                    ),
                ),
                (
                    "within_budget",
                    models.BooleanField(
                        default=True,
                        help_text="Requester declares this is within the approved budget.",
                    ),
                ),
                (
                    "budget_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Requester note on the budget position (in / out of budget, why).",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="The budget / ROI / quote document.",
                        null=True,
                        upload_to="spend_requests/%Y/%m/",
                    ),
                ),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("ai_summary", models.TextField(blank=True, default="")),
                (
                    "ai_extracted_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("ai_flags", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_notes", models.TextField(blank=True, default="")),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spend_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spend_requests",
                        to="core.company",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status", "request_type"],
                        name="budgets_spe_status_649b54_idx",
                    ),
                    models.Index(
                        fields=["requester", "status"],
                        name="budgets_spe_request_5dabc0_idx",
                    ),
                ],
            },
        ),
    ]
