# Generated by Django 5.2 on 2026-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_spend_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="spendrequest",
            name="bqa_accredited",
            field=models.BooleanField(
                blank=True,
                help_text="Is the training provider BQA-accredited? Accredited → the levy is recoverable from BQA.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="spendrequest",
            name="bqa_recovery_status",
            field=models.CharField(
                choices=[
                    ("n/a", "Not applicable"),
                    ("recoverable", "Recoverable from BQA"),
                    (
                        "not_recoverable",
                        "Not recoverable — provider not BQA-accredited",
                    ),
                    ("claimed", "Claim submitted to BQA"),
                    ("recovered", "Recovered from BQA"),
                ],
                db_index=True,
                default="n/a",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="spendrequest",
            name="training_provider",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
