# Generated by Django 5.2 on 2026-07-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0004_spend_training_bqa"),
    ]

    operations = [
        migrations.AddField(
            model_name="spendrequest",
            name="actual_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PO / payment reference the spend was booked under.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="spendrequest",
            name="actual_spent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What was actually spent once the PO/payment went through.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
