# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbfira', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nbfiraauditlog',
            new_name='nbfira_nbfi_return__bb66b6_idx',
            old_name='nbf_audit_ret_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='nbfirareturnline',
            new_name='nbfira_nbfi_return__32926f_idx',
            old_name='nbf_line_ret_sch_idx',
        ),
        migrations.AlterField(
            model_name='nbfiracapitalfactor',
            name='key',
            field=models.CharField(help_text='IRC: class name (motor, accident, …). MRC: asset bucket (cash, fixed_interest_1yr, …). G:   "insurance" or "market". MCR: "default".', max_length=60),
        ),
        migrations.AlterField(
            model_name='nbfirareturn',
            name='period_label',
            field=models.CharField(help_text='e.g. 2026Q3, FY2026.', max_length=20),
        ),
        migrations.AlterField(
            model_name='nbfirareturnline',
            name='formula',
            field=models.CharField(blank=True, default='', help_text='Human formula description for source-trace tooltip.', max_length=200),
        ),
        migrations.AlterField(
            model_name='nbfirareturnline',
            name='schedule',
            field=models.CharField(help_text='IS, A, A.1, B, C, AFS, IMF_ASSETS, IMF_LIAB, …', max_length=8),
        ),
        migrations.AlterField(
            model_name='nbfirareturnline',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Sub-section inside a schedule for grouping the UI.', max_length=40),
        ),
        migrations.AlterField(
            model_name='nbfirareturnline',
            name='source_accounts',
            field=models.JSONField(blank=True, default=list, help_text='List of GL account codes that contributed to this value.'),
        ),
        migrations.AlterField(
            model_name='nbfirasubmission',
            name='filing_reference',
            field=models.CharField(blank=True, default='', help_text='Reference returned by the NBFIRA RBSS portal on accept.', max_length=80),
        ),
    ]
