# Generated by Django 5.2 on 2026-08-17 16:42

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbfira', '0002_sync_model_state_2026_07_26'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbfiraauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create draft'), ('generate', 'Generate schedules from GL'), ('edit', 'Edit a line value'), ('review', 'Mark as reviewed'), ('approve', 'Approve'), ('reject', 'Reject'), ('reopen', 'Reopen'), ('lock', 'Lock'), ('unlock', 'Unlock (privileged)'), ('export', 'Export XLSX/PDF'), ('submit', 'Mark as submitted'), ('upload', 'Attach filed return'), ('unattach', 'Remove filed return')], max_length=12),
        ),
        migrations.CreateModel(
            name='NBFIRAFiledDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='nbfira/filed/%Y/%m/')),
                ('original_name', models.CharField(help_text='Filename as uploaded — the stored name is slugified.', max_length=255)),
                ('statement', models.CharField(blank=True, default='', help_text='Which statement this file is, if it is a single one: IS, A, A.1, B, C. Blank = a full workbook covering several.', max_length=8)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_hash_sha256', models.CharField(blank=True, db_index=True, default='', help_text='Integrity + duplicate detection.', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
                ('parse_note', models.TextField(blank=True, default='')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_documents', to='nbfira.nbfirareturn')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nbfira_filed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NBFIRA Filed Document',
                'verbose_name_plural': 'NBFIRA Filed Documents',
                'ordering': ['-uploaded_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['return_obj', 'statement'], name='nbfira_nbfi_return__1dc25d_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
