# Generated by Django 5.2 on 2026-08-18 15:40

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbfira', '0003_filed_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NBFIRAA1Input',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anwp', models.JSONField(blank=True, default=dict, help_text="Assumed annual NWP for the next 12 months, per class, P'000.")),
                ('mer_total', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text="Maximum event retention, P'000.", max_digits=20)),
                ('net_assets', models.JSONField(blank=True, default=dict, help_text="Net total assets per asset bucket, P'000.")),
                ('alloc_mrctr', models.JSONField(blank=True, default=dict, help_text="Assets allocated to market-risk cover per bucket, P'000.")),
                ('source_note', models.TextField(blank=True, default='', help_text='Where these came from — e.g. "as per filed Q4 workbook, treaty schedule B". Required by the UI.')),
                ('effective_from', models.DateField(blank=True, help_text='Date the assumption takes effect.', null=True)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nbfira_a1_inputs', to=settings.AUTH_USER_MODEL)),
                ('return_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a1_input', to='nbfira.nbfirareturn')),
            ],
            options={
                'verbose_name': 'NBFIRA A.1 Input',
                'verbose_name_plural': 'NBFIRA A.1 Inputs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
