"""realpay/failed_debits_report.py — the spreadsheet and the covering email.

Separated from ``failed_debits.py`` (which only reads) so the data can be tested
without building a workbook, and so the Friday command is a thin caller.

The workbook is built with ``aware.reporting._wb``, the branded builder Graphite
Aware's reports already use. It is imported rather than copied: a second
Navy/Orange table builder would drift from the first the week anyone changed a
column width, and Finance would start receiving two house styles.
"""
from __future__ import annotations

import datetime
from decimal import Decimal
from typing import Any, Dict, List

from aware.reporting import NAVY, ORANGE, _wb

#: Column order. Policy number first because it is what somebody types into
#: Graphite to act on the row; agent last because the email already groups by
#: agent and the column is there to confirm, not to sort by.
COLUMNS = [
    'Policy number', 'Debit date', 'Amount (BWP)', 'Why it failed',
    'Retries', 'Policy status', 'Monthly premium (BWP)', 'Agency', 'Agent',
]

NOTES = [
    'Read live from Graphite on the morning it was sent — not a hand export.',
    'Commercial and domestic (agent-sold) policies only. The Instant/MIS book '
    'fails in the thousands weekly and is a cancellation-rules matter, not a '
    'phone-call one; it is deliberately excluded.',
    'A row whose policy status is NOT Active should not be chased for payment — '
    'the debit mandate needs stopping instead.',
    'No customer contact details are included. Look the client up in Graphite '
    'against the policy number.',
    'Omni does not move money. This report raises no payment and changes no policy.',
]


def _f(v) -> float:
    """Money as a float for the cell, so Excel gets a number it can total.

    Rounded to the thebe, never truncated: this figure is read as an amount
    owed, and a report that sums to a different total than the rows is the
    fastest way to lose the reader's trust in all of it.
    """
    return float(Decimal(str(v or 0)).quantize(Decimal('0.01')))


def _grouped_by_broker(rows: List[Dict[str, Any]]):
    """rows grouped by broker (the agency on the policy), biggest broker's
    total first; each broker's own rows kept in the report's existing
    biggest-first order. So a broker's own list can be lifted straight out of
    the sheet as one contiguous block (CFO 2026-09-12, Bokani Makosha's
    request)."""
    groups: Dict[str, List[Dict[str, Any]]] = {}
    for r in rows:
        groups.setdefault(r['agency'] or 'Unassigned', []).append(r)
    totals = {k: sum((r['amount'] for r in v), Decimal('0.00'))
             for k, v in groups.items()}
    return sorted(groups.items(), key=lambda kv: (-totals[kv[0]], kv[0]))


def build_xlsx(rows: List[Dict[str, Any]], summary: Dict[str, Any],
               start: datetime.date, end: datetime.date):
    """The attachment. Returns a BytesIO positioned at the start."""
    kpis = [
        ('Failed debits', f"{summary['count']:,}"),
        ('Value not collected', f"P {_f(summary['amount']):,.2f}"),
        ('On non-active policies', f"{summary['non_active']:,}"),
        ('Already retried and still failing', f"{summary['repeat']:,}"),
        ('Week covered', f"{start:%d %b %Y} to {end:%d %b %Y}"),
    ]
    body: List[List[Any]] = []
    for broker, brows in _grouped_by_broker(rows):
        for r in brows:
            body.append([
                r['policy_number'], r['action_date'], _f(r['amount']), r['reason'],
                r['retry_count'], r['policy_status'], _f(r['premium']),
                r['agency'], r['agent'],
            ])
        subtotal = sum((r['amount'] for r in brows), Decimal('0.00'))
        body.append([
            f'Subtotal — {broker}', '', _f(subtotal), '', '', '', '',
            broker, f'{len(brows)} row(s)',
        ])
    return _wb(
        title='Alpha Direct — Failed Debit Orders',
        subtitle=f"Week of {start:%d %b %Y} to {end:%d %b %Y} · generated by Omni",
        kpis=kpis,
        columns=COLUMNS,
        rows=body,
        notes=NOTES,
        # money_cols is DELIBERATELY NOT PASSED. aware.reporting._wb formats a
        # money column as '#,##0' — whole pula — because Aware pre-rounds its
        # figures. These are thebe-accurate, so a 594.50 row would display as
        # 595 while the KPI above it reads P 2,072.45, and the column would
        # visibly not add up to the total beside it. A report whose rows do not
        # sum to its own headline is the fastest way to lose the reader.
        # (Fix _wb for everyone, never; Aware's own reports are correct as they are.)
    )


def filename(end: datetime.date) -> str:
    return f'Alpha Direct Failed Debits {end:%Y-%m-%d}.xlsx'


def subject(end: datetime.date) -> str:
    return f'Alpha Direct failed debits — week to {end:%d %b %Y}'


def build_html(rows: List[Dict[str, Any]], summary: Dict[str, Any],
               start: datetime.date, end: datetime.date) -> str:
    """The covering email.

    Written the way Finance writes: what happened, what it is worth, who owns
    which part, what to do. The per-agent table is in the BODY on purpose —
    the whole point of failure in the old process was that the spreadsheet went
    round and nobody could see at a glance whether any of it was theirs.
    """
    rowsum = summary['by_agent']
    agent_rows = ''.join(
        f'<tr><td style="padding:6px 10px;border-bottom:1px solid #eceff5">{a["agent"]}</td>'
        f'<td style="padding:6px 10px;border-bottom:1px solid #eceff5;text-align:right">{a["count"]}</td>'
        f'<td style="padding:6px 10px;border-bottom:1px solid #eceff5;text-align:right">'
        f'P {_f(a["amount"]):,.2f}</td></tr>'
        for a in rowsum
    )
    non_active = ''
    if summary['non_active']:
        non_active = (
            f'<p style="margin:14px 0 0"><strong>{summary["non_active"]}</strong> of these '
            f'are on policies that are no longer active. Do not chase those for payment. '
            f'They need the debit mandate stopped.</p>'
        )
    return f"""
<div style="font-family:Montserrat,'Segoe UI',Arial,sans-serif;color:#1D3270;font-size:14px">
  <div style="border-left:6px solid #{ORANGE};padding:2px 0 2px 14px;margin-bottom:18px">
    <div style="font-size:18px;font-weight:700">Failed debit orders</div>
    <div style="color:#667;font-size:12px">Week of {start:%d %B %Y} to {end:%d %B %Y}</div>
  </div>

  <p style="margin:0 0 14px">
    <strong>{summary['count']}</strong> debit orders failed this week, worth
    <strong>P {_f(summary['amount']):,.2f}</strong>.
    The full list is attached.
  </p>

  <p style="margin:0 0 6px">Please contact your clients about the outstanding
  premium. When a client pays by EFT, reply to Debtors with the proof of payment.</p>

  {non_active}

  <table style="border-collapse:collapse;margin:18px 0;min-width:380px">
    <tr>
      <th style="background:#{NAVY};color:#fff;padding:8px 10px;text-align:left">Agent</th>
      <th style="background:#{NAVY};color:#fff;padding:8px 10px;text-align:right">Failed</th>
      <th style="background:#{NAVY};color:#fff;padding:8px 10px;text-align:right">Value</th>
    </tr>
    {agent_rows}
  </table>

  <p style="color:#667;font-size:12px;margin-top:20px">
    Commercial and domestic policies only. Read live from Graphite by Omni on the
    morning it was sent. Omni moves no money and changes no policy.
  </p>
</div>
"""
