// Reference data ported from Motlatsi's commission_reports tool (v3/v31).
// AGENT_PROFILE: June module-report amounts (her baked reference data).
// STREAM_COLS: submission-template column order per stream (drives the
// add-a-row form and the paste placeholder).
export const AGENT_PROFILE: Record<string, { mods: string[]; amt: Record<string, number> }> = { "Alindo Govati": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 79.0 } }, "Amantle Ntshweu": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 217.5, "new_sales_liberty": 0.0 } }, "Amogelang Jennifer Makwinja": { "mods": [ "collection", "conversion", "new_sales_mis" ], "amt": { "conversion": 55.3, "collection": 514.14, "new_sales_mis": 0.0 } }, "Aobakwe \ufffd Letsweletse": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Bakang Chief Dibapile": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Bakang Valela": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Balekanye Seduledi": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 99.0, "new_sales_liberty": 79.0 } }, "Balemogeng Jessica Kgotleng": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 79.0 } }, "Barati Mogopa": { "mods": [ "conversion" ], "amt": { "conversion": 0.0 } }, "Basetsana Poitshego": { "mods": [ "conversion" ], "amt": { "conversion": 55.3 } }, "Batsile Fredah Nawe": { "mods": [ "collection", "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 49.0, "new_sales_liberty": 79.0, "collection": 55.4 } }, "Batsile Nawe": { "mods": [ "conversion" ], "amt": { "conversion": 1066.46 } }, "Boemo Mavuka": { "mods": [ "collection", "conversion", "kyc_claims" ], "amt": { "conversion": 55.3, "collection": 363.4, "kyc_claims": 640.0 } }, "Cathrine Khali": { "mods": [ "collection", "conversion" ], "amt": { "conversion": 0.0, "collection": 0.0 } }, "Cynthia Tlhaloso Rammiki": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Gagothata Eric Pona": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 297.0, "new_sales_liberty": 0.0 } }, "Gaolatlhe Marumo": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Gaone Karema": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Gaongalelwe Nage": { "mods": [ "collection", "conversion", "incentives", "new_sales_liberty", "new_sales_mis" ], "amt": { "conversion": 34.3, "collection": 1320.59, "incentives": 1200.0, "new_sales_mis": 0.0, "new_sales_liberty": 0.0 } }, "George Modimoosi": { "mods": [ "collection", "conversion" ], "amt": { "conversion": 1077.3, "collection": 84.4 } }, "Godi R Lucas": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 712.0 } }, "Gofaone Mothibi": { "mods": [ "incentives" ], "amt": { "incentives": 2000.0 } }, "Gofiwa Elias": { "mods": [ "incentives" ], "amt": { "incentives": 2000.0 } }, "Gofiwa Yaone Elias": { "mods": [ "collection", "new_sales_mis" ], "amt": { "new_sales_mis": 99.0, "collection": 143.8 } }, "Gomolemo Elias": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Gontse Ramong": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Gorata Kebalepile": { "mods": [ "collection", "conversion" ], "amt": { "conversion": 34.3, "collection": 67.0 } }, "Gorata Taele": { "mods": [ "kyc_claims" ], "amt": { "kyc_claims": 100.0 } }, "Jennifer Boitshepho Billy": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Jessica Nkala": { "mods": [ "collection", "conversion", "new_sales_mis" ], "amt": { "conversion": 1133.3, "collection": 625.2, "new_sales_mis": 0.0 } }, "Katlego Cave": { "mods": [ "collection", "conversion" ], "amt": { "conversion": 427.7, "collection": 501.4 } }, "Katlego Masilo": { "mods": [ "incentives", "motor" ], "amt": { "incentives": 2500.0, "motor": 0.0 } }, "Katlego Molao": { "mods": [ "collection", "conversion" ], "amt": { "collection": 92.6, "conversion": 0.0 } }, "Katlego Mosadi": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Kebaokeditse Florence Modimootsike": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Kelebogile Tshenolo": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Kesego Thabiso Atang Mmolawa": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 99.0 } }, "Kesegofetse Jim": { "mods": [ "collection", "conversion", "hospital", "incentives", "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_liberty": 79.0, "conversion": 387.1, "collection": 548.2, "hospital": 543.0, "incentives": 500.0, "new_sales_mis": 0.0 } }, "Ketshephaone Abel": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Khumoetsile Ursila Modibedi": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Kunyalala July": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 99.0, "new_sales_liberty": 0.0 } }, "Kutlo Koma": { "mods": [ "collection", "conversion", "incentives", "new_sales_liberty" ], "amt": { "conversion": 144.9, "collection": 15.8, "incentives": 1000.0, "new_sales_liberty": 0.0 } }, "Laone Gomang": { "mods": [ "collection" ], "amt": { "collection": 0.0 } }, "Laone Thembi Baswetsang": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Leshoa Mosimakoko": { "mods": [ "collection", "kyc_claims" ], "amt": { "collection": 258.3, "kyc_claims": 540.0 } }, "Letso Chinambe": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 49.5 } }, "Lone Lefa Morolong": { "mods": [ "incentives" ], "amt": { "incentives": 5000.0 } }, "Maatla Boletswane": { "mods": [ "collection", "conversion", "incentives", "motor", "new_sales_mis" ], "amt": { "conversion": 124.6, "collection": 409.0, "incentives": 2500.0, "new_sales_mis": 0.0, "motor": 0.0 } }, "Maatla Rabotshoma": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Marylyn Ramolefhe": { "mods": [ "conversion", "motor" ], "amt": { "conversion": 0.0, "motor": 0.0 } }, "Marylyn T Y Ramolefhe": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Mooketsi Molapo": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Morati Segwe": { "mods": [ "collection", "conversion", "incentives", "new_sales_mis" ], "amt": { "conversion": 69.3, "collection": 130.6, "incentives": 3000.0, "new_sales_mis": 0.0 } }, "Mosimanegape Mojara": { "mods": [ "collection", "hospital", "incentives", "kyc_claims", "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 49.0, "collection": 655.18, "kyc_claims": 80.0, "hospital": 552.0, "incentives": 1200.0, "new_sales_liberty": 0.0 } }, "Motsei Mothoosele": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 89.0, "new_sales_liberty": 0.0 } }, "Musawenkosi Sibanda": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Mykkells Peter": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Nametso Albert": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Nkgomotsang Mosenki": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Norah Dibuile": { "mods": [ "collection", "new_sales_mis" ], "amt": { "new_sales_mis": 49.5, "collection": 9.8 } }, "Obakeng T Molefe": { "mods": [ "kyc_claims" ], "amt": { "kyc_claims": 180.0 } }, "Obakeng Tatenda Molefhe": { "mods": [ "collection" ], "amt": { "collection": 244.0 } }, "Olga Koketso Rakgomo": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 49.5, "new_sales_liberty": 0.0 } }, "Olorato Kantini": { "mods": [ "collection" ], "amt": { "collection": 29.4 } }, "Olorato Tshephang Wally": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 24.5 } }, "Olorato Wally": { "mods": [ "conversion" ], "amt": { "conversion": 231.87 } }, "Onneile Molefhe": { "mods": [ "collection", "motor" ], "amt": { "collection": 0.0, "motor": 0.0 } }, "Pako Angela Mampane": { "mods": [ "collection", "conversion", "new_sales_liberty" ], "amt": { "conversion": 89.6, "collection": 192.25, "new_sales_liberty": 0.0 } }, "Peo Dilaolo": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 99.0 } }, "Phatsimo Ojang": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Phomolo Johane": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Pono Duduetsang Moagi": { "mods": [ "collection", "new_sales_mis" ], "amt": { "collection": 69.6, "new_sales_mis": 0.0 } }, "Pontsho Shabana": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Rachel Mufoyi": { "mods": [ "collection" ], "amt": { "collection": 476.6 } }, "Rachel Mufoyi Mufoyi": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Ramaphane Ramaphane": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 79.0, "new_sales_liberty": 0.0 } }, "Reabetswe Mookodi": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 99.0, "new_sales_liberty": 0.0 } }, "Refilwe Vanessah Boitumelo Ramphaleng": { "mods": [ "kyc_claims" ], "amt": { "kyc_claims": 760.0 } }, "Refilwe Vanessah Ramphaleng": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Shadrack Theba": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Stellah Rakgomo": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 89.0 } }, "Tapiwa Percy Selogelo": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Tebogo Phiri": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Thabang Amos Thantshi": { "mods": [ "collection", "kyc_claims" ], "amt": { "kyc_claims": 1260.0, "collection": 0.0 } }, "Thato Barati Mogopa": { "mods": [ "collection" ], "amt": { "collection": 124.2 } }, "Theko Kelefile": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Thuso Letang Kegontse": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Thuto Mosimanewakgomo": { "mods": [ "collection", "incentives" ], "amt": { "collection": 92.8, "incentives": 2000.0 } }, "Tlotlo Rabakane": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 0.0 } }, "Tshepo Sesika": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 346.0 } }, "Tuduetso Alimah Mantirisi": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 79.0 } }, "Wadza Joshua": { "mods": [ "new_sales_liberty", "new_sales_mis" ], "amt": { "new_sales_mis": 1754.5, "new_sales_liberty": 0.0 } }, "Zwiseko Monyatsi": { "mods": [ "new_sales_mis" ], "amt": { "new_sales_mis": 198.0 } } }

export const STREAM_COLS: Record<string, string[]> = {
  "new_sales_mis": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Policy Status",
    "Created Date",
    "Inception Date",
    "Commission Month",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Paid Amount",
    "Payment Date"
  ],
  "new_sales_liberty": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Policy Status",
    "Created Date",
    "Inception Date",
    "Commission Month",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Paid Amount",
    "Payment Date"
  ],
  "collection": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Policy Status",
    "Billing Date",
    "Claimed / Collected",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Paygate Collected",
    "Payment Date"
  ],
  "motor": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Policy Status",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Paid Amount",
    "Payment Date"
  ],
  "kyc_claims": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Evidence Type",
    "Confirmed?",
    "Withheld?",
    "Date Confirmed"
  ],
  "hospital": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Base Premium",
    "Expected Total",
    "Payment (Exp\u2212Base)",
    "KYC Status",
    "Policy Status",
    "Reconciliation",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Payment Date"
  ],
  "incentives": [
    "Agent Name",
    "Section / Operation",
    "Memo Reference",
    "Approved Amount",
    "Approved By"
  ],
  "conversion_mis": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Policy Status",
    "Inception Date",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Paid Amount",
    "Payment Date"
  ],
  "conversion_liberty": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Policy Status",
    "Inception Date",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Paid Amount",
    "Payment Date"
  ],
  "bank_confirmation": [
    "Agent Name",
    "Policy Number",
    "Policy Holder",
    "Product",
    "Book",
    "Premium",
    "KYC Status",
    "Policy Status",
    "Billing Date",
    "Claimed / Collected",
    "Payment Source",
    "Paygate Ref",
    "Paygate Status",
    "Paygate Collected",
    "Payment Date"
  ]
}
