# Generated by Django 5.2 on 2026-07-26 04:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinsurance', '0002_cession_invoice_link'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cession',
            new_name='reinsurance_status_cddadb_idx',
            old_name='reins_cess_status_idx',
        ),
        migrations.RenameIndex(
            model_name='cession',
            new_name='reinsurance_treaty__25e864_idx',
            old_name='reins_cess_treaty_st_idx',
        ),
        migrations.RenameIndex(
            model_name='cession',
            new_name='reinsurance_invoice_3e5282_idx',
            old_name='cession_invoice_treaty_idx',
        ),
        migrations.RenameIndex(
            model_name='reinsurancerecovery',
            new_name='reinsurance_status_956c53_idx',
            old_name='reins_rec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reinsurancerecovery',
            new_name='reinsurance_treaty__6dd02b_idx',
            old_name='reins_rec_treaty_st_idx',
        ),
        migrations.AlterField(
            model_name='cession',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reinsurance commission earned (net off the cession).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='cession',
            name='policy_reference',
            field=models.CharField(blank=True, help_text='Graphite policy number this cession relates to (optional).', max_length=120),
        ),
        migrations.AlterField(
            model_name='reinsurancerecovery',
            name='claim_reference',
            field=models.CharField(help_text='Graphite claim number (mandatory for traceability).', max_length=120),
        ),
        migrations.AlterField(
            model_name='reinsurancetreaty',
            name='cession_share_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='For QS/Surplus: % of each risk ceded.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='reinsurancetreaty',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Reinsurance commission paid back to us.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='reinsurancetreaty',
            name='limit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For XL: the upper limit of the layer.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reinsurancetreaty',
            name='line_of_business',
            field=models.CharField(help_text='Motor / Property / Liability / All Lines / etc.', max_length=80),
        ),
        migrations.AlterField(
            model_name='reinsurancetreaty',
            name='retention_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For XL: the retention layer below which we keep the loss.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reinsurer',
            name='country',
            field=models.CharField(default='BW', help_text='ISO 3166-1 alpha-2.', max_length=2),
        ),
        migrations.AlterField(
            model_name='reinsurer',
            name='credit_rating',
            field=models.CharField(blank=True, help_text='Latest counterparty rating (e.g. AA-, A+).', max_length=10),
        ),
        migrations.AlterField(
            model_name='reinsurer',
            name='short_code',
            field=models.CharField(help_text='Short code used in JE descriptions and reports (e.g. MUNICH_RE).', max_length=20, unique=True),
        ),
    ]
