# Generated by Django 5.2 on 2026-08-14 13:40

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinsurance', '0004_alter_bordereauimport_received_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinsuranceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='PRIMARY', editable=False, max_length=20, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('locked', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_amended_at', models.DateTimeField(blank=True, null=True)),
                ('source_note', models.CharField(blank=True, max_length=300)),
                ('last_amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinsurance_history_amendments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reinsurance 11-year history',
                'verbose_name_plural': 'Reinsurance 11-year history',
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReinsuranceHistorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinsurance_history_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
