# Generated by Django 5.2 on 2026-09-15 18:08

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinsurance', '0005_reinsurance_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reinsurer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_uw_manager', 'Pending Underwriting Manager'), ('pending_compliance', 'Pending Compliance'), ('pending_principal', 'Pending Principal review'), ('pending_ceo', 'Pending CEO'), ('approved', 'Approved / Eligible'), ('returned', 'Returned for correction'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('expired', 'Expired')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='broker',
            field=models.CharField(blank=True, default='', help_text='Placing broker, where the line comes through one.', max_length=200),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='carrier_group',
            field=models.CharField(blank=True, default='', help_text='Normalised security / parent group. Concentration is measured per group as well as per carrier — two panel lines on the same group are one exposure.', max_length=240),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='domicile',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country of domicile.', max_length=2),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='licence_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='onboarding_purposes',
            field=models.JSONField(blank=True, default=list, help_text='List of OnboardingPurpose values this counterparty is approved for.'),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='registered_name',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='regulator',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='suspension_reason',
            field=models.TextField(blank=True, default='', help_text='Mandatory when suspending or rejecting — enforced in the service layer, never optional in practice.'),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reinsurer',
            name='trading_name',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.CreateModel(
            name='FacRiskExposure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('graphite_policy_id', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('graphite_risk_id', models.CharField(blank=True, default='', max_length=60)),
                ('policy_number', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('insured_name', models.CharField(blank=True, default='', help_text='PII — shown on screen to permitted users, never sent to an AI pipeline or an unfiltered export.', max_length=240)),
                ('risk_description', models.TextField(blank=True, default='')),
                ('regulatory_class', models.CharField(blank=True, default='', max_length=120)),
                ('risk_address', models.TextField(blank=True, default='', help_text='Accumulation is tested per address/situation where the source data supports it.')),
                ('currency_code', models.CharField(default='BWP', max_length=3)),
                ('gross_sum_insured', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('gross_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('net_retention', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What Alpha Direct keeps before any facultative placement.', max_digits=20)),
                ('autofac_capacity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('fac_placed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('unplaced_retained_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Capacity sought but NOT placed. This sits on Alpha Direct's own balance sheet and is flagged, never shown as ceded.", max_digits=20)),
                ('ceded_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('ceded_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('slip_reference', models.CharField(blank=True, default='', max_length=120)),
                ('evidence_note', models.CharField(blank=True, default='', max_length=300)),
                ('placement_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('partially_placed', 'Partially placed'), ('unplaced', 'Unplaced — retained'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('status_override_reason', models.CharField(blank=True, default='', help_text='Active/expired is normally date-driven. When a person overrides it, the reason is recorded and the override is what stands.', max_length=300)),
                ('status_overridden', models.BooleanField(default=False)),
                ('source_system', models.CharField(blank=True, default='', max_length=60)),
                ('source_file', models.CharField(blank=True, default='', max_length=240)),
                ('source_sheet', models.CharField(blank=True, default='', max_length=120)),
                ('source_row', models.CharField(blank=True, default='', max_length=40)),
                ('source_key', models.CharField(blank=True, db_index=True, default='', help_text='Idempotency key from the source. Re-importing the same row updates it instead of creating a second exposure.', max_length=200)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('import_warnings', models.JSONField(blank=True, default=list)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAC risk exposure',
                'verbose_name_plural': 'FAC risk exposures',
                'ordering': ['-effective_date', 'reference'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FacReinsurerAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_percent', models.DecimalField(blank=True, decimal_places=4, help_text='NULL where the panel did not state a share — renders as unknown, never as zero.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('allocated_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('slip_reference', models.CharField(blank=True, default='', max_length=120)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('reinsurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fac_allocations', to='reinsurance.reinsurer')),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='reinsurance.facriskexposure')),
            ],
            options={
                'verbose_name': 'FAC reinsurer allocation',
                'ordering': ['-allocated_amount'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReinsurerApprovalTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('actor_email', models.CharField(blank=True, default='', help_text='Captured at the time. A user row can be renamed later; the audit trail must still say who acted.', max_length=254)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reinsurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_transitions', to='reinsurance.reinsurer')),
            ],
            options={
                'verbose_name': 'reinsurer approval transition',
                'ordering': ['created_at_local'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReinsurerSecurityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(blank=True, default='', max_length=16)),
                ('rating_agency', models.CharField(blank=True, default='', max_length=80)),
                ('rating_scale', models.CharField(choices=[('international', 'International scale'), ('national', 'National scale'), ('unknown', 'Scale not stated')], default='unknown', help_text='Never compare a national-scale rating with an international one — they are different measures.', max_length=16)),
                ('outlook', models.CharField(blank=True, default='', max_length=40)),
                ('rating_date', models.DateField(blank=True, null=True)),
                ('evidence_date', models.DateField(blank=True, help_text='When we last SAW the evidence, which is not the same as when the agency issued the rating.', null=True)),
                ('internal_tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3'), ('watch', 'Watch list'), ('unrated', 'Unrated')], default='unrated', max_length=12)),
                ('verified', models.BooleanField(default=False, help_text='Set only when a person has checked the rating against source evidence. Unverified must never render as verified.')),
                ('conflicts', models.TextField(blank=True, default='', help_text='Where two sources disagree, record BOTH here rather than picking one silently.')),
                ('audited_financial_years', models.JSONField(blank=True, default=list, help_text='Financial years for which we hold audited statements, e.g. [2024, 2025]. Paul Beka reported these incomplete for the offshore carriers — the gap stays visible.')),
                ('solvency_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('capital_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('capital_currency', models.CharField(blank=True, default='', max_length=3)),
                ('panel_provider', models.CharField(blank=True, default='', max_length=200)),
                ('panel_section', models.CharField(blank=True, default='', max_length=200)),
                ('participation_share', models.DecimalField(blank=True, decimal_places=4, help_text='Percent share on this panel section. NULL means the panel did not state a share — four of the supplied panels did not — and NULL must render as unknown, never as zero.', max_digits=7, null=True)),
                ('cover_from', models.DateField(blank=True, null=True)),
                ('cover_to', models.DateField(blank=True, null=True)),
                ('source_note', models.CharField(blank=True, default='', help_text='Where this came from: file, sheet and row.', max_length=300)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reinsurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_assessments', to='reinsurance.reinsurer')),
            ],
            options={
                'verbose_name': 'reinsurer security assessment',
                'ordering': ['-rating_date', '-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='facriskexposure',
            index=models.Index(fields=['status', 'expiry_date'], name='reinsurance_status_39bd10_idx'),
        ),
        migrations.AddIndex(
            model_name='facriskexposure',
            index=models.Index(fields=['policy_number'], name='reinsurance_policy__037ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='facriskexposure',
            index=models.Index(fields=['regulatory_class'], name='reinsurance_regulat_d9fc2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='facriskexposure',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key__gt', '')), fields=('source_system', 'source_key'), name='uniq_fac_exposure_source_key'),
        ),
        migrations.AddIndex(
            model_name='facreinsurerallocation',
            index=models.Index(fields=['reinsurer'], name='reinsurance_reinsur_dcbe2f_idx'),
        ),
        migrations.AddIndex(
            model_name='facreinsurerallocation',
            index=models.Index(fields=['exposure'], name='reinsurance_exposur_3c127a_idx'),
        ),
        migrations.AddIndex(
            model_name='reinsurerapprovaltransition',
            index=models.Index(fields=['reinsurer', 'created_at_local'], name='reinsurance_reinsur_fca091_idx'),
        ),
        migrations.AddIndex(
            model_name='reinsurersecurityassessment',
            index=models.Index(fields=['reinsurer', '-rating_date'], name='reinsurance_reinsur_8d2c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='reinsurersecurityassessment',
            index=models.Index(fields=['internal_tier'], name='reinsurance_interna_f92c37_idx'),
        ),
    ]
