# Generated by Django 5.2 on 2026-09-15 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinsurance', '0006_reinsurer_address_reinsurer_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinsurerapprovaltransition',
            name='reinsurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_transitions', to='reinsurance.reinsurer'),
        ),
    ]
