# Generated by Django 5.2 on 2026-09-16 19:52

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinsurance', '0007_alter_reinsurerapprovaltransition_reinsurer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinsurerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('incorporation', 'Certificate of incorporation / registration'), ('licence', 'Licence / regulator proof'), ('address', 'Proof of business address'), ('directors_ubo', 'Directors / ultimate beneficial owners'), ('identity', 'Identity documents (where legally required)'), ('board_resolution', 'Board resolution / signing authority'), ('org_chart', 'Organisation chart'), ('tax', 'Tax registration'), ('aml_sanctions_pep', 'AML / sanctions / PEP screening result'), ('audited_financials', 'Audited financial statements'), ('rating_evidence', 'Rating evidence'), ('broker_panel', 'Broker security panel'), ('slip', 'Signed treaty / FAC / retrocession slip'), ('bank_verification', 'Bank account verification'), ('other', 'Other compliance evidence')], db_index=True, max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to='reinsurer_documents/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', help_text='Derived from the EXTENSION on upload, never taken from the browser — a caller-supplied content type is caller-supplied control over what the browser does with the bytes.', max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Blank means it does not expire. A past date blocks a NEW onboarding or placement, never an existing record.', null=True)),
                ('source', models.CharField(blank=True, default='', help_text='Who provided it — the reinsurer, the broker, a registry.', max_length=200)),
                ('verification_status', models.CharField(choices=[('pending', 'Uploaded — not yet verified'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('reinsurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reinsurance.reinsurer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reinsurer Document',
                'verbose_name_plural': 'Reinsurer Documents',
                'ordering': ['reinsurer__name', 'kind', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['reinsurer', 'kind'], name='re_doc_counterparty_kind_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
