# Generated by Django 5.2 on 2026-07-15 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("agent_code", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.CharField(blank=True, default="", max_length=160)),
                ("works_via_company", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommissionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("independent", "Independent agents"),
                            ("in_house", "In-house / payroll agents"),
                            ("bdu", "BDU domestic sales team"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "withholding_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "pays_via",
                    models.CharField(
                        choices=[
                            ("direct_bank", "Direct bank payment"),
                            ("payroll", "Through payroll"),
                        ],
                        default="direct_bank",
                        max_length=12,
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommissionBankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("account_number", models.CharField(max_length=40)),
                (
                    "branch_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank",
                        to="commissions.commissionagent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="commissionagent",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="commissions.commissiongroup",
            ),
        ),
        migrations.CreateModel(
            name="CommissionSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_label",
                    models.CharField(
                        help_text="Month as YYYY-MM, e.g. 2026-05.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-(0[1-9]|1[0-2])$",
                                "Period must be YYYY-MM, e.g. 2026-06.",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted — 1st review"),
                            ("second_review", "1st reviewed — 2nd review"),
                            ("final_review", "2nd reviewed — final approval"),
                            ("approved", "Approved — awaiting payroll"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid — payroll processed"),
                        ],
                        default="draft",
                        max_length=14,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("first_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("second_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("final_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "gross_commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "withholding_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "withholding_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "net_payable",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="commissions.commissionagent",
                    ),
                ),
                (
                    "final_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="commissions.commissiongroup",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "second_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_label", "agent__name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommissionSubmissionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("new_business", "New business"),
                            ("renewal", "Renewal"),
                            ("endorsement", "Endorsement"),
                            ("previous_month", "Previous month"),
                        ],
                        default="new_business",
                        max_length=16,
                    ),
                ),
                ("frequency", models.CharField(blank=True, default="", max_length=10)),
                (
                    "amount_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "annualised_premium",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                (
                    "amount_applicable",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("collection_date", models.DateField(blank=True, null=True)),
                ("is_policy_closed", models.BooleanField(default=False)),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="commissions.commissionsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="commissionsubmission",
            index=models.Index(
                fields=["group", "period_label"], name="commissions_group_i_31aa19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionsubmission",
            index=models.Index(
                fields=["status", "period_label"], name="commissions_status_f0d472_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionsubmission",
            constraint=models.UniqueConstraint(
                fields=("agent", "period_label"), name="uniq_commission_agent_period"
            ),
        ),
    ]
