# Generated by Django 5.2 on 2026-07-15 15:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0002_seed_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionsubmissionline",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=12
            ),
        ),
    ]
