# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissionamendment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionamendment',
            new_name='commissions_submiss_371957_idx',
            old_name='commission_amend_sub_ct_idx',
        ),
    ]
