# Generated by Django 5.2 on 2026-08-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_sync_model_state_2026_07_26'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsubmission',
            name='statement_file',
            field=models.FileField(blank=True, null=True, upload_to='commission_statements/'),
        ),
        migrations.AddField(
            model_name='commissionsubmission',
            name='statement_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
