# Generated by Django 5.2 on 2026-09-08 11:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_commissionsubmission_payroll_amendment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('short_name', models.CharField(blank=True, default='', help_text="What Finance calls them on the workbook tab, e.g. 'Finsef'.", max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graphite_agency_name', models.CharField(max_length=200)),
                ('graphite_agency_id', models.CharField(blank=True, default='', max_length=40)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='commissions.broker')),
            ],
            options={
                'ordering': ['graphite_agency_name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('graphite_agency_name',), name='uniq_broker_alias_agency_name')],
            },
        ),
        migrations.CreateModel(
            name='BrokerPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(db_index=True, max_length=60)),
                ('insured_name', models.CharField(blank=True, default='', help_text='PII — shown in the auth-gated screen only, never sent to an AI pipeline.', max_length=160)),
                ('period_label', models.CharField(blank=True, default='', help_text='Month this row belongs to, YYYY-MM. Blank = standing.', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-(0[1-9]|1[0-2])$', 'Period must be YYYY-MM, e.g. 2026-06.')])),
                ('premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('motor_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('motor_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('non_motor_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('non_motor_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('commission_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('source', models.CharField(choices=[('manual', 'Added in Omni'), ('upload', 'Uploaded from a workbook')], default='manual', max_length=8)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='commissions.broker')),
            ],
            options={
                'ordering': ['policy_number'],
                'abstract': False,
                'indexes': [models.Index(fields=['broker', 'period_label'], name='commissions_broker__077a70_idx')],
                'constraints': [models.UniqueConstraint(fields=('broker', 'policy_number', 'period_label'), name='uniq_broker_policy_period')],
            },
        ),
    ]
