# Generated by Django 5.2 on 2026-09-17 19:00

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_broker_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCommissionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(help_text='First day this set of rates applies to. One row per change.', unique=True)),
                ('motor_pct', models.DecimalField(decimal_places=3, default=Decimal('12.500'), max_digits=6)),
                ('non_motor_pct', models.DecimalField(decimal_places=3, default=Decimal('20.000'), max_digits=6)),
                ('vat_pct', models.DecimalField(decimal_places=3, default=Decimal('14.000'), max_digits=6)),
                ('admin_pct', models.DecimalField(decimal_places=3, default=Decimal('8.000'), max_digits=6)),
                ('wht_pct', models.DecimalField(decimal_places=3, default=Decimal('10.000'), max_digits=6)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['-effective_from'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='broker',
            name='withholding_tax',
            field=models.BooleanField(default=True, help_text="Deduct 10% withholding tax from this broker's commission. Off for brokers holding a valid exemption."),
        ),
    ]
