# Generated by Django 5.2 on 2026-09-19 08:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0009_brokercommissionrate_broker_withholding_tax"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerpolicy",
            name="graphite_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="brokerpolicy",
            name="graphite_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BrokerMonthClose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-(0[1-9]|1[0-2])$",
                                "Period must be YYYY-MM, e.g. 2026-06.",
                            )
                        ],
                    ),
                ),
                (
                    "commission_excl_vat",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("wht", models.DecimalField(decimal_places=2, max_digits=18)),
                ("vat", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "current_payable",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="month_closes",
                        to="commissions.broker",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "broker__name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BrokerPayableChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_payable", models.DecimalField(decimal_places=2, max_digits=18)),
                ("new_payable", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(max_length=300)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "month_close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="commissions.brokermonthclose",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BrokerStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_number", models.CharField(db_index=True, max_length=60)),
                (
                    "debit_month",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-(0[1-9]|1[0-2])$",
                                "Period must be YYYY-MM, e.g. 2026-06.",
                            )
                        ],
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                (
                    "source",
                    models.CharField(
                        choices=[("close", "Month close"), ("late", "Late resolution")],
                        max_length=8,
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="commissions.broker",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["debit_month", "policy_number", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BrokerCompliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-(0[1-9]|1[0-2])$",
                                "Period must be YYYY-MM, e.g. 2026-06.",
                            )
                        ],
                    ),
                ),
                (
                    "compliance",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance",
                        to="commissions.broker",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "broker__name"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("broker", "period"),
                        name="uniq_broker_compliance_period",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="brokermonthclose",
            constraint=models.UniqueConstraint(
                fields=("broker", "period"), name="uniq_broker_month_close"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerstatushistory",
            index=models.Index(
                fields=["broker", "debit_month"], name="commissions_broker__bf8738_idx"
            ),
        ),
    ]
