# Generated by Django 5.2 on 2026-05-11 04:21

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0003_alter_employee_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Competency Area',
                'verbose_name_plural': 'Competency Areas',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveSmallIntegerField(help_text='Hierarchy level 1-8 (1=junior, 8=chief officer).')),
                ('spread', models.PositiveSmallIntegerField(default=40, help_text='Range spread in percent — salary band width.')),
                ('midpoint', models.DecimalField(decimal_places=2, help_text='Midpoint monthly salary in BWP.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pay Grade',
                'verbose_name_plural': 'Pay Grades',
                'ordering': ['-level', 'code'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('default_annual_days', models.PositiveSmallIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HRISProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, default='', max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other / prefer not to say')], default='', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=80)),
                ('demographic_marker', models.CharField(blank=True, default='', help_text='Optional self-identified diversity marker. Never required.', max_length=80)),
                ('talent_segment', models.CharField(blank=True, choices=[('star', 'Star (high performance, high potential)'), ('high_potential', 'High potential'), ('solid_performer', 'Solid performer'), ('specialist', 'Technical specialist'), ('developing', 'Developing'), ('underperforming', 'Underperforming'), ('new_hire', 'New hire (under 6 months)')], default='', max_length=20)),
                ('initials', models.CharField(blank=True, default='', max_length=4)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hris_profile', to='payroll.employee')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hris.grade')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='payroll.employee')),
            ],
            options={
                'verbose_name': 'HRIS Profile',
                'verbose_name_plural': 'HRIS Profiles',
                'ordering': ['employee__full_name'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('refused', 'Refused'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hris.hrisprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hris.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-start_date'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OKR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('weight_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weight 0-100. Sum across employee+period must = 100.', max_digits=5)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('score_h1', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-year score 0-5.', max_digits=4, null=True)),
                ('score_h2', models.DecimalField(blank=True, decimal_places=2, help_text='Year-end score 0-5.', max_digits=4, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='hris.hrisprofile')),
            ],
            options={
                'verbose_name': 'OKR',
                'verbose_name_plural': 'OKRs',
                'ordering': ['-period', 'profile__employee__full_name', '-weight_pct'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='e.g. 2024-H1, FY24', max_length=20)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Overall rating 1.00 - 5.00', max_digits=4, null=True)),
                ('competency_scores', models.JSONField(blank=True, default=dict, help_text='Dict of {competency_code: [score, score, score, score]} matching the TMS Orbit comp structure.')),
                ('values_scores', models.JSONField(blank=True, default=list, help_text='Array of 5 value scores (1-5).')),
                ('potential_scores', models.JSONField(blank=True, default=list, help_text='Array of 4 potential scores (1-5).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finalised', 'Finalised')], default='draft', max_length=12)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hris.hrisprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_reviews_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['-period', 'profile__employee__full_name'],
                'abstract': False,
                'unique_together': {('profile', 'period')},
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
