# Generated by Django 5.2 on 2026-06-07 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hris", "0009_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HRISAmendment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("employee", "Employee record"),
                            ("profile", "HRIS profile"),
                            ("grade", "Grade / salary band"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        help_text="Primary key (UUID/str) of the target record.",
                        max_length=64,
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cached human label of the target (e.g. employee name) so notifications need no re-query.",
                        max_length=200,
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("approved", "Approved & applied"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "maker_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "approver_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="hrisamendment",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hris_amendments_decided",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hrisamendment",
            name="maker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hris_amendments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="hrisamendment",
            index=models.Index(
                fields=["status", "-created_at"], name="hris_amend_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrisamendment",
            index=models.Index(
                fields=["target_kind", "target_id"], name="hris_amend_target_idx"
            ),
        ),
    ]
