# Generated by Django 5.2 on 2026-06-12 15:18

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_bugreport_triage_queue'),
        ('hris', '0011_seed_hris_role'),
        ('payroll', '0008_seed_employer_contrib_payable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(help_text='Date the move takes effect.')),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_out', 'Awaiting source (Transfer Out) approval'), ('pending_in', 'Out approved — awaiting destination (Transfer In)'), ('completed', 'Both approved — applied to employee'), ('rejected', 'Rejected')], db_index=True, default='pending_out', max_length=12)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('out_approver_email', models.EmailField(blank=True, max_length=254)),
                ('out_approved_at', models.DateTimeField(blank=True, null=True)),
                ('in_approver_email', models.EmailField(blank=True, max_length=254)),
                ('in_approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee Transfer',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.RenameIndex(
            model_name='hrisalert',
            new_name='hris_hrisal_state_eafa0c_idx',
            old_name='hris_alert_state_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='hrisalert',
            new_name='hris_hrisal_employe_48e52f_idx',
            old_name='hris_alert_emp_state_idx',
        ),
        migrations.RenameIndex(
            model_name='hrisalert',
            new_name='hris_hrisal_kind_fe1044_idx',
            old_name='hris_alert_kind_target_idx',
        ),
        migrations.AlterField(
            model_name='policy',
            name='body_md',
            field=models.TextField(blank=True, default='', help_text='Verbatim policy text in markdown. ARIA ingests this.'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='source_doc',
            field=models.CharField(blank=True, default='', help_text='Filename of source document (e.g. "CoS-2023 §7").', max_length=200),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='dest_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.company'),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='payroll.employee'),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='in_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='out_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='source_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.company'),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeetransfer',
            index=models.Index(fields=['status', '-created_at'], name='hris_employ_status_9cddb9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetransfer',
            index=models.Index(fields=['employee', '-created_at'], name='hris_employ_employe_42e0de_idx'),
        ),
    ]
