# Generated by Django 5.2 on 2026-06-16 09:49

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0013_employeetransfer_scheduled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveOpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type_code', models.CharField(max_length=20)),
                ('as_at_date', models.DateField(help_text='Date these figures are correct as at.')),
                ('entitlement_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('opening_balance_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('accrued_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('batch', models.CharField(blank=True, default='', max_length=60)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_opening_balances', to='hris.hrisprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_opening_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Opening Balance',
                'verbose_name_plural': 'Leave Opening Balances',
                'ordering': ['profile__employee__full_name', 'leave_type_code', '-as_at_date'],
                'abstract': False,
                'indexes': [models.Index(fields=['profile', 'leave_type_code', 'as_at_date'], name='hris_leaveo_profile_538f66_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
