# Generated by Django 5.2 on 2026-07-14 13:34

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0027_incentive_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='is_working_day',
            field=models.BooleanField(default=False, help_text='Staff work on this holiday (an UNPAID public holiday) → normal required hours. Unset = PAID day off, no hours required.'),
        ),
        migrations.CreateModel(
            name='WorkdayJustification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('required_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tracked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('justified_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('reason', models.CharField(choices=[('none', 'No shortfall'), ('on_leave', 'On leave'), ('external_meeting', 'External meeting'), ('client_visit', 'Client visit'), ('other', 'Other')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('met', 'Met required hours'), ('not_required', 'No hours required (off day)'), ('justified', 'Shortfall justified'), ('unjustified', 'Shortfall NOT justified'), ('pending', 'Awaiting employee response')], default='pending', max_length=14)),
                ('justification', models.TextField(blank=True, default='', help_text='Employee explanation for the shortfall.')),
                ('meeting_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', help_text='Where the external visit took place.', max_length=160)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('linked_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications', to='hris.leaverequest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_justifications', to='hris.hrisprofile')),
            ],
            options={
                'verbose_name': 'Workday Justification',
                'verbose_name_plural': 'Workday Justifications',
                'ordering': ['-work_date', 'profile__employee__full_name'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('client_name', models.CharField(max_length=160)),
                ('reason', models.TextField(blank=True, default='', help_text='Why did you see the client?')),
                ('outcome', models.TextField(blank=True, default='', help_text='What happened afterward?')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Potential premium (BWP) from this meeting. Optional.', max_digits=14, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_visits', to='hris.hrisprofile')),
                ('justification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_visits', to='hris.workdayjustification')),
            ],
            options={
                'verbose_name': 'Client Visit',
                'verbose_name_plural': 'Client Visits',
                'ordering': ['-visit_date'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('announcement', 'Company announcement'), ('hr_matter', 'HR matter'), ('meeting', 'Meeting / schedule'), ('disciplinary', 'Disciplinary')], default='announcement', max_length=14)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('starts_on', models.DateField(db_index=True)),
                ('ends_on', models.DateField(blank=True, help_text='Last day to show in the brief. Blank = show once from starts_on.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hris.hrisprofile')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-starts_on', 'category'],
                'abstract': False,
                'indexes': [models.Index(fields=['starts_on', 'is_active'], name='hris_announ_starts__54572f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workdayjustification',
            index=models.Index(fields=['work_date', 'status'], name='hris_workda_work_da_20f194_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workdayjustification',
            unique_together={('profile', 'work_date')},
        ),
    ]
