# Generated by Django 5.2 on 2026-07-21 — trimmed by hand to ONLY the new
# LeaveEncashment table (CFO directive 2026-07-21). makemigrations also
# emitted unrelated help_text/index drift in core/payroll/hris that pre-exists
# on main; that drift is deliberately NOT included here (surgical-change rule).

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_datasubjectrequest'),
        ('hris', '0042_perfresult_vat_split'),
        ('payroll', '0012_encrypt_employee_pii'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEncashment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type_code', models.CharField(default='annual', max_length=30)),
                ('days', models.DecimalField(decimal_places=2, help_text='Leave days converted to cash.', max_digits=6)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly BASIC (BWP) from the latest payslip at request time.', max_digits=18)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='basic_salary ÷ 22 (BWP).', max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='daily_rate × days (BWP) — the payout.', max_digits=18)),
                ('balance_at_request', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual-leave days available when raised (audit trail for the ≤-balance check).', max_digits=6)),
                ('basic_source', models.CharField(blank=True, default='', help_text='Payroll period the BASIC snapshot came from, e.g. 2026-06.', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('maker_email', models.CharField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending CFO approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12)),
                ('cfo_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('payroll_processed', models.BooleanField(default=False)),
                ('payroll_processed_at', models.DateTimeField(blank=True, null=True)),
                ('cfo_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_encashments', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_encashments', to='payroll.employee')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_encashments_raised', to=settings.AUTH_USER_MODEL)),
                ('payroll_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, help_text='HRIS profile at request time — the balance the days are deducted from. Null if the employee has no profile row yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_encashments', to='hris.hrisprofile')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Encashment',
                'verbose_name_plural': 'Leave Encashments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
