# Generated by Django 5.2 on 2026-07-21 07:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0043_leaveencashment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveencashment',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='leaveencashment',
            name='maker_email',
        ),
        migrations.RemoveField(
            model_name='leaveencashment',
            name='notes',
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_encashments_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='applicant_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='finance_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='hr_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Employee reason / note for the application.'),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='rejected_stage',
            field=models.CharField(blank=True, default='', help_text='Which stage rejected it (cfo/hr/finance).', max_length=16),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='balance_at_request',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual-leave days available when applied (audit trail for the ≤-balance check).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly BASIC (BWP) from the latest payslip at application time.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='HRIS profile at application time — the balance the days are deducted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_encashments', to='hris.hrisprofile'),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='status',
            field=models.CharField(choices=[('pending_cfo', 'Awaiting CFO approval'), ('pending_hr', 'Awaiting HR approval'), ('pending_finance', 'Awaiting Finance (FC/FM) approval'), ('approved', 'Approved — for payment'), ('rejected', 'Rejected'), ('paid', 'Paid')], db_index=True, default='pending_cfo', max_length=16),
        ),
        # NOTE: makemigrations also emitted pre-existing help_text drift on
        # monthlycheckin + performanceimprovementplan (unrelated to this feature)
        # — deliberately excluded to keep this migration surgical.
    ]
