# Generated by Django 5.2 on 2026-07-21 08:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hris", "0044_remove_leaveencashment_maker_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("category", models.CharField(blank=True, default="", max_length=60)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="okr",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="hris.okr",
            ),
        ),
        migrations.AddField(
            model_name="okr",
            name="scope",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("department", "Department"),
                    ("individual", "Individual"),
                ],
                default="individual",
                max_length=12,
            ),
        ),
        # NOTE: makemigrations also detected pre-existing drift on monthlycheckin
        # (improvement_actions/objectives/reviewer/support_provided) and PIP
        # (support_plan) — help_text-only changes unrelated to this feature pack.
        # Deliberately EXCLUDED to keep this migration surgical; that drift is a
        # separate pre-existing item, not introduced here.
        migrations.AlterField(
            model_name="okr",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="okrs",
                to="hris.hrisprofile",
            ),
        ),
        migrations.CreateModel(
            name="FeatureAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feature_key", models.CharField(max_length=50)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hris_feature_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "feature_key"],
                        name="hris_featur_user_id_46d7f1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "feature_key"),
                        name="uniq_feature_acceptance_user_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PulseResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week_start",
                    models.DateField(
                        help_text="Monday of the week this check-in covers."
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="1 (struggling) – 5 (great).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_responses",
                        to="hris.hrisprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pulse Response",
                "verbose_name_plural": "Pulse Responses",
                "ordering": ["-week_start"],
                "abstract": False,
                "unique_together": {("profile", "week_start")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="Proficiency 1 (novice) - 5 (expert)."
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="hris.hrisprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="hris.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Skill",
                "verbose_name_plural": "Employee Skills",
                "ordering": ["-updated_at"],
                "abstract": False,
                "unique_together": {("profile", "skill")},
            },
        ),
    ]
