# Generated by Django 5.2 on 2026-07-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0050_manageraccountabilitynote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycheckin',
            name='improvement_actions',
            field=models.JSONField(blank=True, default=list, help_text='[{action, owner, due_date, status}] — agreed corrective actions.'),
        ),
        migrations.AlterField(
            model_name='monthlycheckin',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='[{description, target, result, score}] — monthly KPI snapshot.'),
        ),
        migrations.AlterField(
            model_name='monthlycheckin',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Line manager who held the check-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_checkins_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlycheckin',
            name='support_provided',
            field=models.TextField(blank=True, default='', help_text='ELRA "support / opportunity to improve" evidence.'),
        ),
        migrations.AlterField(
            model_name='performanceimprovementplan',
            name='support_plan',
            field=models.TextField(blank=True, default='', help_text='Training / mentoring / resources offered — ELRA support evidence.'),
        ),
    ]
