# Generated by Django 5.2 on 2026-07-26 06:04

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0051_sync_model_state_2026_07_26'),
        ('payroll', '0016_sync_model_state_2026_07_26'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerMonthlyReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted — awaiting manager'), ('returned', 'Sent back for more detail'), ('cleared', 'Cleared')], default='draft', max_length=10)),
                ('team_snapshot', models.JSONField(blank=True, default=list, help_text='[{name, required_hours, tracked_hours, shortfall, unexplained_days, leave_days, tasks_assigned, tasks_completed, tasks_on_time_pct}] — frozen at submit.')),
                ('own_snapshot', models.JSONField(blank=True, default=dict, help_text="The manager's own hours/tasks for the month — frozen at submit.")),
                ('headcount_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='Team actual hours / required hours per head — the overstaffing signal. e.g. 6 people delivering 4.2 people of hours.', max_digits=6, null=True)),
                ('leave_action', models.TextField(blank=True, default='', help_text='What the manager DID about people who lost hours without leave or an explanation.')),
                ('sla_breaches', models.PositiveIntegerField(blank=True, null=True)),
                ('sla_explanation', models.TextField(blank=True, default='')),
                ('sales_target_met', models.BooleanField(blank=True, null=True)),
                ('new_sales_amount', models.DecimalField(blank=True, decimal_places=2, help_text='New sales written in the month, in BWP. Declaration.', max_digits=14, null=True)),
                ('work_finished_on_time', models.BooleanField(blank=True, null=True)),
                ('work_on_time_comment', models.TextField(blank=True, default='')),
                ('dashboard_cleared_on_time', models.BooleanField(blank=True, null=True)),
                ('tasks_comment', models.TextField(blank=True, default='')),
                ('overstaffed', models.BooleanField(blank=True, null=True)),
                ('overstaffed_comment', models.TextField(blank=True, default='')),
                ('fy27_aligned', models.BooleanField(blank=True, null=True)),
                ('fy27_actions', models.TextField(blank=True, default='')),
                ('innovation', models.TextField(blank=True, default='')),
                ('dept_answers', models.JSONField(blank=True, default=dict, help_text='{question_key: answer} for the department / Aria questions.')),
                ('question_spec', models.JSONField(blank=True, default=dict, help_text='The question set shown to this manager — frozen at submit.')),
                ('prior_commitments', models.TextField(blank=True, default='', help_text="Copied from last month's fy27_actions at draft time.")),
                ('prior_outcome', models.TextField(blank=True, default='', help_text="What actually happened to last month's commitments.")),
                ('next_month_commitment', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_verdict', models.CharField(blank=True, choices=[('on_track', 'On track'), ('watch', 'Watch'), ('intervene', 'Intervene')], default='', max_length=10)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_returns_cleared', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(help_text='The people-manager filing the return.', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_returns', to='payroll.employee')),
                ('submitted_to', models.ForeignKey(blank=True, help_text="The filer's own manager, resolved at submit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_returns_to_review', to='payroll.employee')),
            ],
            options={
                'verbose_name': 'Monthly Manager Return',
                'verbose_name_plural': 'Monthly Manager Returns',
                'ordering': ['-period_year', '-period_month', 'manager__full_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['manager', 'period_year', 'period_month'], name='hris_mgrret_mgr_prd_idx'), models.Index(fields=['status'], name='hris_mgrret_status_idx')],
                'unique_together': {('manager', 'period_month', 'period_year')},
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
