# Generated by Django 5.2 on 2026-07-26 21:09

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0052_managermonthlyreturn'),
        ('payroll', '0016_sync_model_state_2026_07_26'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hrisprofile',
            name='co_manager',
            field=models.ForeignKey(blank=True, help_text='Second person who also rates this employee. Does NOT approve leave and is not the line manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_reports', to='payroll.employee'),
        ),
        migrations.AddField(
            model_name='hrisprofile',
            name='co_manager_weight',
            field=models.PositiveSmallIntegerField(default=50, help_text='Co-reviewer share of the combined score, 0-100. The line manager gets the remainder. Default 50/50.'),
        ),
        migrations.CreateModel(
            name='CoRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('rater_role', models.CharField(choices=[('line', 'Line manager'), ('co', 'Co-reviewer')], max_length=4)),
                ('score', models.PositiveSmallIntegerField(help_text='0-100. Weighted with the other rater into the combined score.')),
                ('comment', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_ratings', to='hris.hrisprofile')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Joint monthly rating',
                'verbose_name_plural': 'Joint monthly ratings',
                'ordering': ['-period_year', '-period_month', 'profile__employee__full_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['profile', 'period_year', 'period_month'], name='hris_corate_prof_prd_idx')],
                'unique_together': {('profile', 'period_month', 'period_year', 'rater')},
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
