# Generated by Django 5.2 on 2026-07-26 21:16

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0053_hrisprofile_co_manager_hrisprofile_co_manager_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('not_mine', 'Not reporting to me'), ('resigned', 'Resigned / left the company'), ('long_leave', 'On long leave — exclude this month'), ('wrong_info', 'Job title or details are wrong'), ('other', 'Something else')], max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open — waiting for HR'), ('actioned', 'Actioned by HR'), ('rejected', 'Not accepted')], default='open', max_length=10)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('hr_note', models.TextField(blank=True, default='')),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_flags_actioned', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_flags', to='hris.hrisprofile')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_flags_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roster flag',
                'verbose_name_plural': 'Roster flags',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'kind'], name='hris_rflag_status_idx'), models.Index(fields=['profile', 'status'], name='hris_rflag_prof_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
