# Generated by Django 5.2 on 2026-08-21 10:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0059_arjun_dont_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveopeningbalance',
            name='entitlement_days',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=7),
        ),
    ]
