# Generated by Django 5.2 on 2026-08-07 12:30

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0061_leave_opening_balance_unique_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecSignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('leave', 'Leave request'), ('loan', 'Staff loan'), ('incentive', 'Incentive request')], db_index=True, max_length=12)),
                ('object_id', models.UUIDField(db_index=True)),
                ('applicant_name', models.CharField(blank=True, default='', max_length=160)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('overdue_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Awaiting CEO / CFO signature'), ('approved', 'Signed — may proceed'), ('declined', 'Declined by CEO / CFO')], db_index=True, default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exec_signoffs_raised', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exec_signoffs_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive countersignature',
                'verbose_name_plural': 'Executive countersignatures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'object_id', 'status'], name='hris_execsi_module_3bd1b5_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
