# Generated by Django 5.2 on 2026-08-10 15:43

import core.models
import django.core.validators
import django.db.models.deletion
import hris.leave_reversal_models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0062_execsignoff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.DecimalField(decimal_places=2, help_text='Days worked and claimed back. Half a day upwards.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('reason', models.TextField(help_text='Mandatory. Why the employee worked days they had booked off.')),
                ('attachment', models.FileField(blank=True, help_text='Optional supporting document, e.g. a Time Doctor hours report.', null=True, upload_to=hris.leave_reversal_models.reversal_attachment_path)),
                ('original_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('original_start_date', models.DateField(blank=True, null=True)),
                ('original_end_date', models.DateField(blank=True, null=True)),
                ('original_status', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Awaiting your manager'), ('approved', 'Approved — days credited back'), ('declined', 'Declined')], db_index=True, default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='', help_text="Mandatory when declining — the employee is shown the manager's own words.")),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_reversals_decided', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(help_text='The approved leave being reversed. PROTECT: the original must outlive the reversal.', on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='hris.leaverequest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_reversals', to='hris.hrisprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_reversals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Reversal',
                'verbose_name_plural': 'Leave Reversals',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('days__gte', Decimal('0.5'))), name='leavereversal_at_least_half_a_day'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'declined'), _negated=True), models.Q(('decision_notes', ''), _negated=True), _connector='OR'), name='leavereversal_declined_needs_a_reason')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
