# Generated by Django 5.2 on 2026-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0063_leavereversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinarycase',
            name='override_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
