# Generated by Django 5.2 on 2026-08-12 11:51

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0064_disciplinarycase_override_reason'),
        ('payroll', '0019_employee_is_test_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corating',
            name='rater_role',
            field=models.CharField(choices=[('line', 'Line manager'), ('co', 'Co-reviewer'), ('extra', 'Additional reviewer')], max_length=8),
        ),
        migrations.CreateModel(
            name='AdditionalReviewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, default='', help_text='Why this person reviews them, e.g. "Operations oversight".', max_length=120)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_reviewers', to='hris.hrisprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_reviews', to='payroll.employee')),
            ],
            options={
                'verbose_name': 'Additional reviewer',
                'verbose_name_plural': 'Additional reviewers',
                'ordering': ['profile__employee__full_name', 'reviewer__full_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['reviewer'], name='hris_addrev_reviewer_idx')],
                'unique_together': {('profile', 'reviewer')},
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
