# Generated by Django 5.2 on 2026-08-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0068_leaveencashment_paye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='Who confirmed this refund was paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims_marked_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='paid_note',
            field=models.TextField(blank=True, default='', help_text='How it was paid, if it did not go through the normal accountant + CFO route.'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='paid_reference',
            field=models.CharField(blank=True, default='', help_text='Bank / payroll reference proving the payment, e.g. an FNB reference or a payroll period.', max_length=120),
        ),
    ]
