# Generated by Django 5.2 on 2026-08-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0069_expense_claim_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiverequest',
            name='manager_attested',
            field=models.BooleanField(default=False),
        ),
    ]
