# Generated by Django 5.2 on 2026-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0070_incentiverequest_manager_attested'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycheckin',
            name='employee_decision',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('partial', 'Partially accept'), ('decline', 'Do not accept')], default='', max_length=8),
        ),
    ]
