# Generated by Django 5.2 on 2026-08-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0060_widen_entitlement_decimal_places'),
        ('hris', '0071_monthlycheckin_employee_decision'),
    ]

    operations = [
    ]
