# Generated by Django 5.2 on 2026-08-26 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0075_seed_td_deduction_leave_type'),
        ('payroll', '0021_employee_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycheckin',
            name='auto_posted',
            field=models.BooleanField(db_index=True, default=False, help_text='Written by Omni on the 7th because the manager did not confirm or edit the draft.'),
        ),
        migrations.AddField(
            model_name='monthlycheckin',
            name='auto_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycheckin',
            name='employee_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycheckin',
            name='employee_requested_comments',
            field=models.BooleanField(db_index=True, default=False, help_text='Employee asked the manager to add comments before they accept.'),
        ),
        migrations.AddField(
            model_name='monthlycheckin',
            name='manager_followup',
            field=models.TextField(blank=True, default='', help_text="The manager's answer to the employee's request for more comment."),
        ),
        migrations.AddField(
            model_name='monthlycheckin',
            name='manager_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycheckin',
            name='manager_followup_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlycheckin',
            name='overall_rating',
            field=models.CharField(choices=[('EX', 'Exceeds expectations'), ('ME', 'Meets expectations'), ('PA', 'Partially meets'), ('BE', 'Below expectations'), ('SB', 'Significantly below'), ('NR', 'Not rated — manager did not respond')], max_length=2),
        ),
        migrations.CreateModel(
            name='MonthlyFeedbackNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('notice', 'Draft sent (5th)'), ('reminder', 'Last reminder (6th)'), ('autopost', 'Auto-posted (7th)')], max_length=10)),
                ('outstanding', models.PositiveSmallIntegerField(default=0)),
                ('team_size', models.PositiveSmallIntegerField(default=0)),
                ('sent_to', models.CharField(blank=True, default='', max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_notices', to='payroll.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['period_year', 'period_month', 'kind'], name='hris_monthl_period__e8ca52_idx')],
                'constraints': [models.UniqueConstraint(fields=('manager', 'period_year', 'period_month', 'kind'), name='uniq_feedback_notice_mgr_period_kind')],
            },
        ),
    ]
