# Generated by Django 5.2 on 2026-09-09 11:34

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_calendar_invite_log'),
        # Renumbered from 0083 after the Mac shipped 0083_latenotice while this
        # branch was open. Two 0083 leaves would crash the backend on deploy
        # while the site kept serving pages.
        ('hris', '0083_latenotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Stable identifier, e.g. "kyc-failed-active". Used in the task source tag.', max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('how_to', models.TextField(blank=True, default='', help_text='Plain, click-by-click instruction shown on the task — never a vague summary.')),
                ('counter', models.CharField(help_text='Name registered in hris.objective_counters.COUNTERS.', max_length=60)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly — raised Sunday, due Wednesday'), ('quarterly', 'Quarterly — raised at quarter end, due the 5th'), ('annual', 'Annual — raised at the period start')], db_index=True, default='weekly', max_length=10)),
                ('due_days', models.PositiveSmallIntegerField(default=0, help_text='ANNUAL only: days after the period start that the task is due. Weekly and quarterly due dates are policy, not per-objective — see the cycle command.')),
                ('direction', models.CharField(choices=[('reduce', 'Backlog must come DOWN by the target'), ('increase', 'Count must go UP by the target'), ('nil', 'Must be zero for the week (zero tolerance)')], default='reduce', max_length=10)),
                ('target', models.PositiveIntegerField(default=0, help_text='How much must move in one week. Ignored for NIL objectives.')),
                ('note', models.TextField(blank=True, default='', help_text='Why this target, and what the number was when it was set. Without it, a target read a year later looks arbitrary and nobody can tell whether it was ambitious or trivial.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_objectives_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_objectives', to='hris.hrisprofile')),
            ],
            options={
                'verbose_name': 'Weekly Objective',
                'verbose_name_plural': 'Weekly Objectives',
                'ordering': ['profile__employee__full_name', 'key'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WeeklyObjectiveRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(db_index=True, help_text='First day of the period. For a WEEKLY objective this is the Monday and it matches OmniTask.week_of; for a quarterly one it is the first day of the quarter being reported on.')),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly — raised Sunday, due Wednesday'), ('quarterly', 'Quarterly — raised at quarter end, due the 5th'), ('annual', 'Annual — raised at the period start')], default='weekly', max_length=10)),
                ('baseline', models.IntegerField(help_text='Counter value read when the task was raised — frozen, never recomputed.')),
                ('target', models.PositiveIntegerField(default=0, help_text='Snapshot of the target at raise time.')),
                ('direction', models.CharField(choices=[('reduce', 'Backlog must come DOWN by the target'), ('increase', 'Count must go UP by the target'), ('nil', 'Must be zero for the week (zero tolerance)')], default='reduce', max_length=10)),
                ('actual', models.IntegerField(blank=True, help_text='Counter value read at settle time. Null = not settled.', null=True)),
                ('met', models.BooleanField(blank=True, help_text='Null until settled.', null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settle_error', models.TextField(blank=True, default='', help_text='Why the counter could not be read. A run that could NOT be measured is never marked failed — an unreachable database is not a manager missing their number.')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='hris.weeklyobjective')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_objective_runs', to='core.omnitask')),
            ],
            options={
                'verbose_name': 'Weekly Objective Run',
                'verbose_name_plural': 'Weekly Objective Runs',
                'ordering': ['-period_start', 'objective__key'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='weeklyobjective',
            index=models.Index(fields=['active'], name='wkobj_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyobjective',
            unique_together={('profile', 'key')},
        ),
        migrations.AddIndex(
            model_name='weeklyobjectiverun',
            index=models.Index(fields=['period_start', 'met'], name='wkobjrun_week_met_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyobjectiverun',
            unique_together={('objective', 'period_start')},
        ),
    ]
