# Generated by Django 5.2 on 2026-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0086_moemedi_dont_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='execsignoff',
            name='cfo_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execsignoff',
            name='kind',
            field=models.CharField(choices=[('overdue', 'Long-overdue work'), ('leave_policy', 'Discretionary leave')], db_index=True, default='overdue', max_length=14),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='policy_ack',
            field=models.BooleanField(default=False, help_text='Applicant ticked "I remain at work until this leave is approved".'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='policy_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Answers to the discretionary-leave questions, keyed by question id.'),
        ),
    ]
