# Generated by Django 5.2 on 2026-09-13 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0087_execsignoff_cfo_only_execsignoff_kind_and_more'),
        ('payroll', '0022_payrollsetting_employee_recruit_authority_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveencashment',
            name='payroll_amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_encashments', to='payroll.payrollamendment'),
        ),
    ]
