# Generated by Django 5.2 on 2026-09-13 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0088_leaveencashment_payroll_amendment'),
        ('payroll', '0025_salaryadvancepayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEncashmentPayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('feed', 'Raised by the leave-pay feed'), ('hand', 'Hand-keyed amendment')], default='feed', max_length=8)),
                ('amendment', models.ForeignKey(help_text='The payroll amendment that already carries this encashment.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_encashment_claims', to='payroll.payrollamendment')),
                ('encashment', models.OneToOneField(help_text='The encashment. UNIQUE — this is the no-double-pay guard.', on_delete=django.db.models.deletion.CASCADE, related_name='payroll_line_claim', to='hris.leaveencashment')),
            ],
            options={
                'verbose_name': 'Leave Encashment Payroll Line',
                'verbose_name_plural': 'Leave Encashment Payroll Lines',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
