# Generated by Django 5.2 on 2026-09-19 10:21

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# HC 19-Sep-2026: employees 2 months, controllers / C-suite / senior managers 4, expatriates 6.
DEFAULT_RULES = {'expatriate': 6, 'controller': 4, 'c_suite': 4, 'senior_manager': 4, 'employee': 2}
# CFO 19-Sep-2026: Unami and Dorothy run HR settings themselves.
DEFAULT_SETTINGS = {
    'hr_heads': ['ubutale@alphadirect.co.bw', 'dikgopoleng@alphadirect.co.bw'],
    'contract_reminder_recipients': ['dikgopoleng@alphadirect.co.bw', 'ubutale@alphadirect.co.bw',
                                     'hc@alphadirect.co.bw'],
}


def seed_defaults(apps, schema_editor):
    Rule = apps.get_model('hris', 'ContractReminderRule')
    for category, months in DEFAULT_RULES.items():
        Rule.objects.get_or_create(category=category, defaults={'months_before': months})
    Setting = apps.get_model('hris', 'HRSetting')
    for key, value in DEFAULT_SETTINGS.items():
        Setting.objects.get_or_create(key=key, defaults={'value': value})


class Migration(migrations.Migration):

    dependencies = [
        ("hris", "0089_leaveencashmentpayrollline"),
        ("payroll", "0029_employmentcontract_retirement_fund_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractReminderRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("expatriate", "Expatriate"),
                            ("controller", "Controller"),
                            ("c_suite", "C-suite"),
                            ("senior_manager", "Senior manager"),
                            ("employee", "Employee"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("months_before", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Contract reminder rule",
                "ordering": ["-months_before", "category"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name="hrisprofile",
            name="is_controller",
            field=models.BooleanField(
                default=False,
                help_text="NBFIRA controller position — contract reminder 4 months ahead.",
            ),
        ),
        migrations.AddField(
            model_name="hrisprofile",
            name="is_expatriate",
            field=models.BooleanField(
                default=False,
                help_text="Expatriate — contract reminder 6 months ahead.",
            ),
        ),
        migrations.CreateModel(
            name="ContractReminderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("escalation", "Escalation to CFO"),
                        ],
                        max_length=12,
                    ),
                ),
                ("sent_on", models.DateField()),
                ("recipients", models.JSONField(blank=True, default=list)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="payroll.employmentcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_on"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContractRenewalDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("renew_same", "Renew on the same terms"),
                            ("change", "Renew with changes"),
                            ("end", "End the contract"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewal_decisions",
                        to="payroll.employmentcontract",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HRSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=60, unique=True)),
                ("value", models.JSONField(blank=True, default=list)),
                ("locked", models.BooleanField(default=False)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "abstract": False,
            },
        ),
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
