# Generated by Django 5.2 on 2026-09-19 16:41

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# HC 19-Sep-2026: "depending on role, notify IT of their systems requirements (e.g.
# Underwriting needs Graphite at the level of hire, Time Doctor)". HR edits on HR Settings.
DEFAULT_SYSTEMS = {
    '*': ['Microsoft 365 email', 'Omni', 'Time Doctor'],
    'Underwriting': ['Graphite (underwriting, at the level of hire)'],
    'Claims': ['Graphite (claims)'],
}


def seed_systems(apps, schema_editor):
    Req = apps.get_model('hris', 'RoleSystemRequirement')
    for dept, systems in DEFAULT_SYSTEMS.items():
        Req.objects.get_or_create(department=dept, defaults={'systems': systems})


class Migration(migrations.Migration):

    dependencies = [
        ("hris", "0090_hr_contracts_and_settings"),
        ("payroll", "0029_employmentcontract_retirement_fund_and_more"),
        ("recruitment", "0006_position_tiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleSystemRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.CharField(
                        help_text="Department name, or '*' for every new joiner.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("systems", models.JSONField(blank=True, default=list)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
            ],
            options={
                "ordering": ["department"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="hrdocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("onboarding", "Onboarding"),
                    ("preboarding", "Pre-boarding pack"),
                    ("cv", "CV / résumé"),
                    ("certificate", "Certificate / qualification"),
                    ("policy", "Policy"),
                    ("contract", "Contract / agreement"),
                    ("job_description", "Job Description"),
                    ("resignation", "Resignation"),
                    ("exit_interview", "Exit interview"),
                    ("disciplinary", "Disciplinary"),
                    ("development_dialogue", "Development Dialogue"),
                    ("id_document", "ID / passport"),
                    ("bank_letter", "Bank confirmation letter"),
                    ("police_clearance", "Police clearance"),
                    ("nbfira_letter", "NBFIRA letter (controllers)"),
                    ("controller_docs", "Controller documents"),
                    ("offboarding_it", "IT offboarding document"),
                    ("offboarding_hc", "HC offboarding document"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="onboarding",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("job_description", "Job description"),
                            ("policy", "Company policy"),
                            ("monthly_review", "Monthly review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="YYYY-MM for a monthly review.",
                        max_length=7,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("needs_manager", models.BooleanField(default=False)),
                ("employee_signed_at", models.DateTimeField(blank=True, null=True)),
                ("manager_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledgements",
                        to="hris.hrdocument",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="payroll.employee",
                    ),
                ),
                (
                    "manager_signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoginClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("staff", "Our staff (fix payroll record)"),
                            ("partner", "Partner / external — keep"),
                            ("service", "Service / system account — keep"),
                            ("close", "Unknown — close the login"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "classified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_login_classification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OffboardingCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("resignation", "Resignation"),
                            ("end_of_contract", "End of contract"),
                            ("dismissal", "Dismissal"),
                            ("other", "Other"),
                        ],
                        default="resignation",
                        max_length=20,
                    ),
                ),
                ("last_working_day", models.DateField()),
                (
                    "seniority",
                    models.CharField(
                        choices=[
                            ("c_suite", "C-suite"),
                            ("senior_manager", "Senior manager"),
                            ("senior_associate", "Senior associate"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "In progress"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "access_removed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When Omni access was closed for this leaver.",
                        null=True,
                    ),
                ),
                ("it_ticket_sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offboarding_cases",
                        to="payroll.employee",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offboarding_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OfferLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent by HC"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "candidate_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authority",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_letter",
                        to="recruitment.authoritytorecruit",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onboarding_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hris.onboardingrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProbationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("confirm", "Confirm the appointment"),
                            ("extend", "Extend probation"),
                            ("end", "End employment"),
                        ],
                        max_length=10,
                    ),
                ),
                ("new_probation_end", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probation_decisions",
                        to="payroll.employmentcontract",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OffboardingStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("resignation_letter", "Resignation letter (HC uploads)"),
                            ("it_document", "IT offboarding document (IT uploads)"),
                            ("hc_document", "HC offboarding document (HC uploads)"),
                            ("signoff_hc", "Sign-off: Human Capital"),
                            ("signoff_manager", "Sign-off: manager / supervisor"),
                            ("signoff_finance", "Sign-off: Finance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="hris.offboardingcase",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offboarding_steps",
                        to="hris.hrdocument",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offboarding_steps_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["case", "kind"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "kind"), name="uniq_offboarding_step_kind"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_systems, migrations.RunPython.noop),
    ]
