# Generated by Django 5.2 on 2026-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hris", "0091_hr_lifecycle_batch2"),
    ]

    operations = [
        migrations.AddField(
            model_name="offboardingcase",
            name="m365_disabled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When Omni switched off the Microsoft 365 account (day after the last working day).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offboardingcase",
            name="m365_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last result of the Microsoft switch-off attempt.",
                max_length=300,
            ),
        ),
    ]
