# Generated by Django 5.2 on 2026-09-20 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hris", "0092_leaver_m365_switch_off"),
        ("payroll", "0029_employmentcontract_retirement_fund_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("question_ids", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["course", "number"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_no", models.PositiveSmallIntegerField(default=1)),
                ("option_order", models.JSONField(default=dict)),
                ("question_order", models.JSONField(default=list)),
                ("answers", models.JSONField(default=dict)),
                ("late_submission", models.BooleanField(default=False)),
                ("slides_seen", models.JSONField(default=list)),
                ("dwell_seconds", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="induction_attempts",
                        to="payroll.employee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="induction_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="hris.examversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("serial", models.CharField(max_length=40, unique=True)),
                ("verify_code", models.CharField(max_length=12, unique=True)),
                ("holder_name", models.CharField(max_length=160)),
                ("course_title", models.CharField(max_length=200)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="hris.trainingattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seeded", "Authored in Omni"),
                            ("uploaded", "Generated from an uploaded document"),
                        ],
                        default="seeded",
                        max_length=12,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("source_chars", models.PositiveIntegerField(default=0)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("min_dwell_seconds", models.PositiveIntegerField(default=900)),
                ("questions_per_paper", models.PositiveSmallIntegerField(default=30)),
                ("version_count", models.PositiveSmallIntegerField(default=15)),
                ("pass_mark", models.PositiveSmallIntegerField(default=80)),
                ("time_limit_minutes", models.PositiveSmallIntegerField(default=45)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("is_induction", models.BooleanField(default=False)),
                ("ai_generated", models.BooleanField(default=False)),
                ("ai_engine", models.CharField(blank=True, max_length=40)),
                ("ai_notes", models.TextField(blank=True)),
                ("papers_issued", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="induction_courses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="induction_courses",
                        to="hris.hrdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_induction", "title"],
            },
        ),
        migrations.AddField(
            model_name="trainingattempt",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="hris.trainingcourse",
            ),
        ),
        migrations.AddField(
            model_name="examversion",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="hris.trainingcourse",
            ),
        ),
        migrations.CreateModel(
            name="TrainingQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stem", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_index", models.PositiveSmallIntegerField(default=0)),
                ("explanation", models.TextField(blank=True)),
                ("section_ref", models.CharField(blank=True, max_length=40)),
                ("topic", models.CharField(blank=True, max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="hris.trainingcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("body_md", models.TextField(blank=True)),
                ("section_ref", models.CharField(blank=True, max_length=40)),
                ("est_seconds", models.PositiveSmallIntegerField(default=60)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="hris.trainingcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("started", "Started"),
                            ("passed", "Passed"),
                            ("failed", "Failed — must re-sit"),
                        ],
                        default="assigned",
                        max_length=12,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("extra_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="induction_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="induction_assignments",
                        to="payroll.employee",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="hris.trainingcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "employee"), name="uniq_training_assignment"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="examversion",
            constraint=models.UniqueConstraint(
                fields=("course", "number"), name="uniq_exam_version_per_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingslide",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="uniq_slide_order_per_course"
            ),
        ),
    ]
