# Generated by Claude for issue #58 — adds PurchaseOrder.commitment_journal_entry FK
# so the encumbrance-style commitment JE posted on cfo_approve can be tracked
# (and reversed on receipt / cancellation).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger',      '0007_alter_journalentry_is_related_party_and_more'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='commitment_journal_entry',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'The commitment JE created when this PO was CFO-approved. '
                    'NULL for POs approved before this feature shipped, '
                    'cleared on cancellation.'
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='commitment_for_pos',
                to='ledger.journalentry',
            ),
        ),
    ]
