# Generated by Django 5.2 on 2026-07-06 — trimmed to the ClaimsAssessment model only.
# (makemigrations bundled unrelated pre-existing index/help_text drift on vendorkyc /
# purchaseorder / core.chatmessage; that drift is not part of this feature and is left
# for its owner. CFO 2026-07-06 claims-PO port, Phase 2.)
import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sod_senior_accountant_title'),
        ('procurement', '0006_line_level_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_file', models.FileField(blank=True, help_text='The uploaded vehicle-assessment PDF.', null=True, upload_to='claims_assessments/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('ready_for_review', 'Ready for Review'), ('parse_failed', 'Parse Failed'), ('pos_created', 'POs Created'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('report_json', models.JSONField(blank=True, default=dict, help_text='Parsed assessment (Phase 3 fills it). Consumed by claims_engine.claims_split / build_allocation_plan.')),
                ('deepseek_notes', models.JSONField(blank=True, default=list)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('claims_type', models.CharField(blank=True, max_length=64, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=64, null=True)),
                ('claim_number', models.CharField(blank=True, max_length=64, null=True)),
                ('assessment_number', models.CharField(blank=True, max_length=64, null=True)),
                ('claim_description', models.TextField(blank=True, null=True)),
                ('ad_note', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration', models.CharField(blank=True, max_length=32, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('excess_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percent, e.g. 5.00 = 5%.', max_digits=5, null=True)),
                ('excess_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum-excess floor (matrix minimum).', max_digits=18, null=True)),
                ('excess_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Directly-typed excess — overrides pct/min and the assessment figure.', max_digits=18, null=True)),
                ('markup_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percent markup on supplier-sourced parts.', max_digits=5, null=True)),
                ('line_allocations', models.JSONField(blank=True, default=list, help_text='List of {"id", "vendor"} overrides — merged by claims_engine.apply_allocations.')),
                ('supplier_settings', models.JSONField(blank=True, default=dict, help_text='{"<vendor label>": {"vat": bool, "currency": "BWP"|"ZAR"}}.')),
                ('po_results', models.JSONField(blank=True, default=list, help_text='Outcome of draft-PO creation.')),
            ],
            options={
                'verbose_name': 'Claims Assessment',
                'verbose_name_plural': 'Claims Assessments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='claimsassessment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims_assessments', to='core.company'),
        ),
        migrations.AddField(
            model_name='claimsassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_assessments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
