# Generated by Django 5.2 on 2026-07-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_restore_po_discount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendorkyc',
            new_name='procurement_sanctio_f24fa1_idx',
            old_name='proc_kyc_sanc_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorkyc',
            new_name='procurement_pep_sta_2ac319_idx',
            old_name='proc_kyc_pep_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorkyc',
            new_name='procurement_kyc_exp_9eb872_idx',
            old_name='proc_kyc_expires_idx',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='amendment_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = original PO. Each applied amendment +1.'),
        ),
    ]
