# Generated by Django 5.2 on 2026-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_sync_model_state_2026_07_26'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbankaccount',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Where FNB emails this vendor their proof of payment (POP). Remembered here so it does not have to be re-typed each payment (CFO 2026-08-22).', max_length=254),
        ),
    ]
