"""
hris/omni_tips.py

A rotating "Did you know?" omni feature tip for the daily Morning Brief
(CFO 2026-07-14): a different small omni/Nexus feature each day, so staff
discover what the system can do. The flagship tip is downloading your payslip
on your phone via the Alpha Nexus PWA — with the ANDROID and iOS install links
(the progressive-web-app pages, NOT the Play Store / App Store).

Links are CURATED here (not generated by the AI) so they are always correct —
same discipline as the frozen-numbers rule. Aria writes the warm personal note;
this tip is a fixed daily rotation.
"""
from __future__ import annotations

import datetime

BASE = 'https://omni.alphadirect.co.bw'

# Each tip: title, blurb, and optional (label, url) action links.
TIPS = [
    {
        'emoji': '📄',
        'title': 'Get your payslip on your phone',
        'blurb': 'You can download your payslip any time from Alpha Nexus on your phone — '
                 'add it to your home screen once and it opens like an app.',
        'links': [('📱 Install on Android', f'{BASE}/m/get/android'),
                  ('🍏 Install on iPhone', f'{BASE}/m/get/ios')],
    },
    {
        'emoji': '🌴',
        'title': 'Apply for leave online',
        'blurb': 'Book annual, sick or study leave in omni — you can see your balance before you apply, '
                 'and your manager approves it in a click.',
        'links': [('Open leave', f'{BASE}/hris/leave')],
    },
    {
        'emoji': '⏱️',
        'title': 'Explain a short day in seconds',
        'blurb': 'If your hours were short, you can tell us why — on leave, a client visit or an external '
                 'meeting — right from your brief. No paperwork.',
        'links': [('My brief', f'{BASE}/hris/my-brief')],
    },
    {
        'emoji': '🏃',
        'title': 'Earn rewards for staying active',
        'blurb': 'Alpha Nexus Thrive turns your daily steps into reward points. Your health data is only '
                 'ever used for rewards — never for your insurance price.',
        'links': [('📱 Android', f'{BASE}/m/get/android'), ('🍏 iPhone', f'{BASE}/m/get/ios')],
    },
    {
        'emoji': '✅',
        'title': 'See all your tasks in one place',
        'blurb': 'Your omni task board shows everything assigned to you, what is due, and lets you mark '
                 'progress so your manager always knows where things stand.',
        'links': [('My tasks', f'{BASE}/task-dashboard')],
    },
    {
        'emoji': '🛠️',
        'title': 'Something not working? Raise a ticket',
        'blurb': 'The omni Help Desk logs any IT problem straight to the team — much faster than email, '
                 'and you can see when it is fixed.',
        'links': [('Help Desk', f'{BASE}/helpdesk')],
    },
    {
        'emoji': '📚',
        'title': 'Find any company procedure',
        'blurb': 'The SOP Bank holds our approved procedures and forms. Search it any time instead of '
                 'asking around for the right document.',
        'links': [('SOP Bank', f'{BASE}/sop-bank')],
    },
    {
        'emoji': '🚗',
        'title': 'Alpha Nexus rewards safe driving',
        'blurb': 'If you drive, Alpha Nexus scores your trips and rewards smooth, safe driving. Install it '
                 'on your phone to see your driving score.',
        'links': [('📱 Android', f'{BASE}/m/get/android'), ('🍏 iPhone', f'{BASE}/m/get/ios')],
    },
    {
        'emoji': '⏱️',
        'title': 'Check your Time Doctor hours',
        'blurb': 'Your tracked and productive hours show in your daily brief — see where your day went, '
                 'any time, from your phone or desktop.',
        'links': [('My brief', f'{BASE}/hris/my-brief')],
    },
    {
        'emoji': '🚪',
        'title': 'Book a meeting room in seconds',
        'blurb': 'Alpha Rooms shows every meeting room’s free/busy for the day — click a free slot to book '
                 'it, and manage your own under “My bookings”.',
        'links': [('Open Alpha Rooms', f'{BASE}/rooms')],
    },
    {
        'emoji': '📊',
        'title': 'IFRS 17 reporting is live',
        'blurb': 'Omni now produces our IFRS 17 insurance-contract reporting in-house, straight from the '
                 'ledger — no more external spreadsheets for the standard.',
        'links': [],
    },
]


def tip_for(day: datetime.date) -> dict:
    """The tip for a given day — rotates through the list so staff see a
    different feature each day."""
    return TIPS[day.toordinal() % len(TIPS)]
