# Generated by Django 5.2 on 2026-07-16 13:53

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexus", "0004_fleetvehicle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetvehicle",
            name="colour",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="home_yard",
            field=models.CharField(blank=True, default="Head Office", max_length=80),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("out", "Out"),
                    ("maintenance", "Under maintenance"),
                    ("retired", "Retired"),
                ],
                db_index=True,
                default="available",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="vin",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VehicleTrip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("driver_name", models.CharField(max_length=120)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("events", "Events"),
                            ("customer_visits", "Customer visits"),
                            ("customer_gifts", "Buying customer gifts"),
                            ("deliver_goods", "Delivery of goods to customers"),
                            ("pickup_customers", "Picking up customers"),
                            ("pickup_brokers", "Picking up brokers"),
                            ("pickup_computers", "Picking up computers"),
                            ("pickup_stationery", "Picking up stationery"),
                            ("pickup_water", "Picking up water"),
                            ("bank_deposit", "Bank / cash deposits"),
                            (
                                "nbfira_submission",
                                "NBFIRA / regulator document submission",
                            ),
                            ("courier_post", "Courier / post collection or drop-off"),
                            ("airport_transfer", "Staff airport transfers (business)"),
                            (
                                "vehicle_servicing",
                                "Vehicle servicing / fuel / car wash",
                            ),
                            (
                                "marketing_transport",
                                "Marketing / branding material transport",
                            ),
                            ("choppies_pos", "Choppies point-of-sale support visits"),
                            ("claims_inspection", "Claims site / salvage inspection"),
                            ("supplier_collect", "Supplier or vendor collections"),
                            ("interbranch_docs", "Inter-branch document transfer"),
                            ("other", "Other (explain — flagged for review)"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("purpose_notes", models.TextField(blank=True, default="")),
                ("destination", models.CharField(max_length=200)),
                ("checkout_at", models.DateTimeField(blank=True, null=True)),
                ("odometer_out", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fuel_level_out",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("empty", "Empty"),
                            ("quarter", "¼"),
                            ("half", "½"),
                            ("three_q", "¾"),
                            ("full", "Full"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                ("driver_condition_confirm", models.BooleanField(default=False)),
                ("pre_trip_notes", models.TextField(blank=True, default="")),
                ("expected_return_at", models.DateTimeField(blank=True, null=True)),
                ("checkin_at", models.DateTimeField(blank=True, null=True)),
                ("odometer_in", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fuel_level_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("empty", "Empty"),
                            ("quarter", "¼"),
                            ("half", "½"),
                            ("three_q", "¾"),
                            ("full", "Full"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                ("driver_return_confirm", models.BooleanField(default=False)),
                ("damage_on_return", models.BooleanField(default=False)),
                ("damage_notes", models.TextField(blank=True, default="")),
                ("receptionist_confirm", models.BooleanField(default=False)),
                (
                    "receptionist_signoff_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("receptionist_notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked_out", "Checked out"),
                            ("returned_pending", "Returned — pending sign-off"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="checked_out",
                        max_length=20,
                    ),
                ),
                ("flagged", models.BooleanField(db_index=True, default=False)),
                (
                    "flag_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("gps_checkout_lat", models.FloatField(blank=True, null=True)),
                ("gps_checkout_lng", models.FloatField(blank=True, null=True)),
                ("gps_checkin_lat", models.FloatField(blank=True, null=True)),
                ("gps_checkin_lng", models.FloatField(blank=True, null=True)),
                (
                    "cartrack_trip_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receptionist_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="nexus.fleetvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Trip",
                "ordering": ["-checkout_at", "-created_at"],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VehicleTripPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pre_trip", "Pre-trip condition"),
                            ("return_damage", "Damage on return"),
                        ],
                        default="pre_trip",
                        max_length=16,
                    ),
                ),
                ("image", models.FileField(upload_to="vehicle_register/")),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="nexus.vehicletrip",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Trip Photo",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicletrip",
            index=models.Index(
                fields=["vehicle", "status"], name="vehtrip_veh_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicletrip",
            index=models.Index(
                fields=["status", "expected_return_at"], name="vehtrip_status_due_idx"
            ),
        ),
    ]
