# Generated by Django 5.2 on 2026-08-03 11:29

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonuInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=80)),
                ('invoice_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('received', 'Received'), ('review', 'Under review'), ('queried', 'Queried with the firm'), ('approved', 'Approved for payment'), ('rejected', 'Rejected')], default='received', max_length=10)),
                ('source_file', models.CharField(blank=True, default='', help_text='The file this was ingested from, for audit.', max_length=255)),
                ('review_note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'BONU invoice',
                'ordering': ['-invoice_date', 'firm__name'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('trading_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('agreed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed rate per hour in BWP. Blank = no tariff on file, so rate checks cannot run for this firm.', max_digits=12, null=True)),
                ('agreed_fixed_fees', models.JSONField(blank=True, default=dict, help_text='{service_code: agreed fee} for fixed-fee work such as conveyancing.')),
                ('panel_since', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'BONU law firm',
                'verbose_name_plural': 'BONU law firms',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BonuInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveSmallIntegerField(default=0)),
                ('service_date', models.DateField(blank=True, help_text='When the work was performed — not the invoice date.', null=True)),
                ('matter_ref', models.CharField(blank=True, default='', help_text="The firm's matter/file reference.", max_length=80)),
                ('member_ref', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('service_code', models.CharField(blank=True, default='', max_length=40)),
                ('matter_description', models.TextField(blank=True, default='', help_text='Free text from the firm. Treated as unsafe: redacted before any AI review.')),
                ('basis', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed fee'), ('disb', 'Disbursement'), ('other', 'Other')], default='hourly', max_length=8)),
                ('fee_earner', models.CharField(blank=True, default='', max_length=120)),
                ('units', models.DecimalField(blank=True, decimal_places=2, help_text='Hours, or 1 for a fixed fee.', max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bonu.bonuinvoice')),
            ],
            options={
                'verbose_name': 'BONU invoice line',
                'ordering': ['invoice', 'line_no'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='bonuinvoice',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bonu.lawfirm'),
        ),
        migrations.CreateModel(
            name='BonuFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable rule id, e.g. DUP_SAME_MATTER.', max_length=40)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6)),
                ('source', models.CharField(choices=[('rule', 'Rule'), ('ai', 'AI review')], default='rule', max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('amount_at_risk', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('question_for_firm', models.TextField(blank=True, default='', help_text='The exact question to put to the firm.')),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='bonu.bonuinvoice')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='bonu.bonuinvoiceline')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='bonu.lawfirm')),
            ],
            options={
                'verbose_name': 'BONU finding',
                'ordering': ['-amount_at_risk', 'severity'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='bonuinvoiceline',
            index=models.Index(fields=['matter_ref'], name='bonu_line_matter_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuinvoiceline',
            index=models.Index(fields=['service_date'], name='bonu_line_svcdate_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuinvoice',
            index=models.Index(fields=['invoice_date'], name='bonu_inv_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='bonuinvoice',
            constraint=models.UniqueConstraint(fields=('firm', 'invoice_number'), name='bonu_uniq_firm_invoice_no'),
        ),
        migrations.AddIndex(
            model_name='bonufinding',
            index=models.Index(fields=['code', 'resolved'], name='bonu_find_code_idx'),
        ),
    ]
