# Generated by Django 5.2 on 2026-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuinvoiceline',
            name='matter_type',
            field=models.CharField(choices=[('divorce', 'Divorce / family'), ('conveyancing', 'Conveyancing / property transfer'), ('criminal', 'Criminal defence'), ('labour', 'Labour / employment'), ('debt', 'Debt collection'), ('estate', 'Deceased estate / will'), ('civil', 'Civil litigation'), ('contract', 'Contract / commercial'), ('road', 'Traffic / road accident'), ('tenancy', 'Landlord / tenancy'), ('advice', 'Consultation / advice only'), ('other', 'Other / unclassified')], db_index=True, default='other', help_text='The case type, from a fixed list — this is what makes "show me every divorce" possible.', max_length=14),
        ),
        migrations.AddIndex(
            model_name='bonuinvoiceline',
            index=models.Index(fields=['matter_type'], name='bonu_line_mtype_idx'),
        ),
        migrations.AddIndex(
            model_name='bonuinvoiceline',
            index=models.Index(fields=['fee_earner'], name='bonu_line_earner_idx'),
        ),
    ]
