# Generated by Django 5.2 on 2026-08-03 12:08

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonu', '0002_bonuinvoiceline_matter_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainerAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Jeremiah & Taldi — BONU panel".', max_length=140)),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='The flat fee, e.g. 85000.00 BWP.', max_digits=14)),
                ('committed_cases', models.PositiveSmallIntegerField(default=0, help_text='Cases they undertake to have under management each month, e.g. 40.')),
                ('max_days_no_activity', models.PositiveSmallIntegerField(default=30, help_text='A case with no recorded movement for this many days is slipping.')),
                ('max_days_to_first_action', models.PositiveSmallIntegerField(default=5, help_text='Days from instruction to first recorded action.')),
                ('scope_note', models.TextField(blank=True, default='', help_text='What the fee covers — and what it does NOT, so extra invoices for in-scope work can be challenged.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retainers', to='bonu.lawfirm')),
            ],
            options={
                'verbose_name': 'BONU retainer',
                'ordering': ['firm__name', '-start_date'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_ref', models.CharField(help_text="The firm's own file reference.", max_length=80)),
                ('member_ref', models.CharField(db_index=True, help_text='Scheme reference only — never a name.', max_length=80)),
                ('matter_type', models.CharField(choices=[('divorce', 'Divorce / family'), ('conveyancing', 'Conveyancing / property transfer'), ('criminal', 'Criminal defence'), ('labour', 'Labour / employment'), ('debt', 'Debt collection'), ('estate', 'Deceased estate / will'), ('civil', 'Civil litigation'), ('contract', 'Contract / commercial'), ('road', 'Traffic / road accident'), ('tenancy', 'Landlord / tenancy'), ('advice', 'Consultation / advice only'), ('other', 'Other / unclassified')], db_index=True, default='other', max_length=14)),
                ('status', models.CharField(choices=[('instructed', 'Instructed — not yet started'), ('active', 'Active'), ('court', 'Awaiting court date'), ('member', 'Waiting on the member'), ('settled', 'Settled'), ('won', "Judgment in our member's favour"), ('lost', 'Judgment against'), ('withdrawn', 'Withdrawn'), ('abandoned', 'Abandoned / went quiet')], db_index=True, default='instructed', max_length=12)),
                ('instructed_on', models.DateField()),
                ('first_action_on', models.DateField(blank=True, null=True)),
                ('last_activity_on', models.DateField(blank=True, db_index=True, null=True)),
                ('next_action_due', models.DateField(blank=True, null=True)),
                ('court_date', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('outcome_note', models.TextField(blank=True, default='')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='bonu.lawfirm')),
                ('retainer', models.ForeignKey(blank=True, help_text='Set when this case counts toward a retainer caseload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='bonu.retaineragreement')),
            ],
            options={
                'verbose_name': 'BONU legal case',
                'ordering': ['-instructed_on'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('happened_on', models.DateField()),
                ('kind', models.CharField(choices=[('instructed', 'Instructed'), ('consult', 'Consultation'), ('letter', 'Letter / correspondence'), ('filing', 'Filed at court'), ('hearing', 'Court appearance'), ('negotiation', 'Negotiation'), ('update', 'Status update from the firm'), ('closed', 'Closed'), ('note', 'Internal note')], default='update', max_length=12)),
                ('detail', models.TextField(blank=True, default='')),
                ('reported_by', models.CharField(blank=True, default='', help_text='Who told us — the firm, the member, or us.', max_length=120)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bonu.legalcase')),
            ],
            options={
                'verbose_name': 'BONU case event',
                'ordering': ['-happened_on'],
                'abstract': False,
                'indexes': [models.Index(fields=['case', '-happened_on'], name='bonu_event_case_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='legalcase',
            index=models.Index(fields=['status', 'last_activity_on'], name='bonu_case_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalcase',
            constraint=models.UniqueConstraint(fields=('firm', 'case_ref'), name='bonu_uniq_firm_case_ref'),
        ),
    ]
