# Generated by Django 5.2 on 2026-08-18 13:28

import core.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonu', '0006_bonuschedulesheet_bonuschedulerow'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalMonthlyBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(help_text='YYYY-MM', max_length=7, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'BONU legal monthly bonus',
                'verbose_name_plural': 'BONU legal monthly bonuses',
                'ordering': ['-month'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalRateMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_description', models.CharField(max_length=240, unique=True)),
                ('internal_unit', models.CharField(blank=True, default='', max_length=60)),
                ('internal_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('external_item', models.CharField(blank=True, default='', max_length=240)),
                ('external_unit', models.CharField(blank=True, default='', max_length=60)),
                ('external_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('calc_basis', models.CharField(choices=[('flat', 'Flat'), ('per_hour', 'Per hour')], default='flat', max_length=10)),
                ('is_disbursement', models.BooleanField(default=False, help_text='True for items an external attorney recovers as a disbursement (email, telephone). These keep their own rate and are NOT moved when the standard hourly rate changes.')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'BONU legal rate mapping',
                'verbose_name_plural': 'BONU legal rate mappings',
                'ordering': ['position', 'fee_description'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarterly_threshold', models.DecimalField(decimal_places=2, default=Decimal('50000'), help_text='Quarterly saving that must be reached before the quarterly bonus becomes payable (BWP).', max_digits=14)),
                ('quarterly_bonus_pct', models.DecimalField(decimal_places=4, default=Decimal('0.02'), help_text='Fraction of the quarterly saving payable once the threshold is met. 0.02 = 2%.', max_digits=6)),
                ('monthly_bonus_cap', models.DecimalField(decimal_places=2, default=Decimal('6500'), help_text='Ceiling on the monthly performance bonus (BWP).', max_digits=14)),
                ('external_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('2250'), help_text='Standard external attorney hourly rate (BWP/hr). Drives every hourly comparison and the advisory value. Disbursements (email, telephone, copies, mileage) keep their own rates.', max_digits=12)),
                ('sla_days', models.PositiveIntegerField(default=5, help_text='Target working days between receiving an external bill and reviewing it.')),
            ],
            options={
                'verbose_name': 'BONU legal office settings',
                'verbose_name_plural': 'BONU legal office settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalTariffItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('internal', 'Internal (Alpha Law)'), ('external', 'External attorney')], max_length=10)),
                ('section', models.CharField(blank=True, default='', max_length=160)),
                ('item', models.CharField(max_length=240)),
                ('unit', models.CharField(blank=True, default='', max_length=60)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'BONU legal tariff item',
                'verbose_name_plural': 'BONU legal tariff items',
                'ordering': ['scope', 'position', 'item'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalAdvisoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('department', models.CharField(blank=True, default='', max_length=80)),
                ('client', models.CharField(blank=True, default='', max_length=200)),
                ('matter_ref', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.CharField(max_length=240)),
                ('type_of_work', models.CharField(blank=True, default='', max_length=160)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'BONU legal advisory entry',
                'verbose_name_plural': 'BONU legal advisory entries',
                'ordering': ['-date'],
                'abstract': False,
                'indexes': [models.Index(fields=['date'], name='bonu_legala_date_258b1f_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalFeeNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('client', models.CharField(help_text='Client / BONU member.', max_length=200)),
                ('portfolio', models.CharField(default='BONU', max_length=60)),
                ('description', models.CharField(max_length=240)),
                ('unit', models.CharField(blank=True, default='', max_length=60)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity or hours.', max_digits=10)),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'BONU legal fee note line',
                'verbose_name_plural': 'BONU legal fee note lines',
                'ordering': ['-date', 'client'],
                'abstract': False,
                'indexes': [models.Index(fields=['date'], name='bonu_legalf_date_2877fb_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalInvoiceSaving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_reviewed', models.DateField()),
                ('invoice_ref', models.CharField(max_length=120)),
                ('external_attorney', models.CharField(blank=True, default='', max_length=200)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('agreed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'BONU legal invoice saving',
                'verbose_name_plural': 'BONU legal invoice savings',
                'ordering': ['-date_reviewed', 'invoice_ref'],
                'abstract': False,
                'indexes': [models.Index(fields=['date_reviewed'], name='bonu_legali_date_re_2a5db6_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
