# Generated by Django 5.2 on 2026-08-18 18:56

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonu', '0007_legalmonthlybonus_legalratemapping_legalsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonuMemberListLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_at', models.DateField(db_index=True, help_text="The date the union's list speaks as of — usually a month end.")),
                ('source_name', models.CharField(blank=True, default='', help_text='The file the union sent, so a figure can be traced back to it.', max_length=300)),
                ('source_note', models.TextField(blank=True, default='')),
                ('rows_seen', models.PositiveIntegerField(default=0)),
                ('members_loaded', models.PositiveIntegerField(default=0)),
                ('loaded_by_email', models.CharField(blank=True, default='', max_length=200)),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='The list eligibility is measured against. Exactly one is current.')),
            ],
            options={
                'verbose_name': 'BONU membership list load',
                'ordering': ['-as_at', '-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BonuMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_no', models.CharField(db_index=True, help_text="The union's membership number. The one thing every list has.", max_length=60, unique=True)),
                ('full_name', models.CharField(blank=True, default='', help_text='Stored by CFO decision 18-Aug-2026. Never leaves Omni.', max_length=200)),
                ('member_token', models.CharField(blank=True, db_index=True, default='', help_text='Links to the invoice-side token so per-member spend can be totalled without carrying a name around.', max_length=64)),
                ('station', models.CharField(blank=True, default='', help_text='Hospital / clinic / workplace.', max_length=200)),
                ('district', models.CharField(blank=True, db_index=True, default='', help_text='District or town — used to place a case near a firm.', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active — paid up'), ('arrears', 'In arrears'), ('suspended', 'Suspended'), ('resigned', 'Resigned / left the union'), ('unknown', 'Status not stated on the list')], db_index=True, default='unknown', max_length=10)),
                ('monthly_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_up_to', models.DateField(blank=True, help_text="Last period the member's premium covers, when the list says so.", null=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('cells', models.JSONField(blank=True, default=dict, help_text="The union's own columns, kept verbatim.")),
                ('note', models.TextField(blank=True, default='')),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=200)),
                ('first_seen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_members', to='bonu.bonumemberlistload')),
                ('last_seen', models.ForeignKey(blank=True, help_text='The most recent list this member appeared on. A member missing from the current list is the single most important refusal reason there is.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_members', to='bonu.bonumemberlistload')),
            ],
            options={
                'verbose_name': 'BONU member',
                'ordering': ['membership_no'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'district'], name='bonu_member_status_idx')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
