# Generated by Django 5.2 on 2026-08-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_billapprovalpolicy_tier2_ceiling_and_more'),
        ('bonu', '0008_member_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='vendor_contact',
            field=models.ForeignKey(blank=True, help_text="The billing Contact that carries this firm's vaulted bank details.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonu_law_firms', to='billing.contact'),
        ),
    ]
