# Generated by Django 5.2 on 2026-09-09 09:26

import core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonu', '0009_lawfirm_vendor_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('external', 'External law firm'), ('in_house', 'In-house (Alpha Law)')], db_index=True, default='external', max_length=8)),
                ('reference', models.CharField(help_text='The billing party own bill or invoice number.', max_length=120)),
                ('bill_date', models.DateField()),
                ('received_on', models.DateField(blank=True, help_text='When the bill reached us.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The bill total (BWP). Its allocations must account for exactly this.', max_digits=14)),
                ('stage', models.CharField(choices=[('billed', 'Billed — not yet paid'), ('paid', 'Paid'), ('rejected', 'Rejected / withdrawn')], db_index=True, default='billed', max_length=8)),
                ('allocation_state', models.CharField(choices=[('allocated', 'Allocated to a client'), ('unallocated', 'Unallocated — needs a person')], db_index=True, default='unallocated', help_text='Unallocated is an EXCEPTION, not a resting state. A bill that cannot be tied to a matter and a client stays visible here until somebody assigns it — never silently dropped and never counted against a guessed client, because one wrong allocation makes two cap totals wrong at once.', max_length=11)),
                ('billed_client_name', models.CharField(blank=True, default='', help_text='The client name exactly as the firm wrote it, kept so a match can be explained afterwards and so the alias can be learned from it.', max_length=200)),
                ('dup_key', models.CharField(blank=True, db_index=True, default='', help_text='Firm plus amount plus reference, normalised (legal_rules.bill_dup_key). Used to WARN about a suspected duplicate before it is committed. Deliberately NOT unique: a firm can legitimately re-issue, and refusing the entry outright would push the bill out of Omni.', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('captured_by_email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'BONU legal bill',
                'ordering': ['-bill_date', 'reference'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalBillAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
            ],
            options={
                'verbose_name': 'BONU legal bill allocation',
                'ordering': ['case__case_ref'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalClientAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_raw', models.CharField(help_text='The name exactly as the firm wrote it.', max_length=200)),
                ('alias_key', models.CharField(db_index=True, help_text='The normalised spelling (bonu/member_identity.normalise) — uppercased, punctuation stripped, words sorted, so surname-first still matches.', max_length=200)),
                ('learned_by_email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'BONU legal client name alias',
                'ordering': ['alias_raw'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The structured client link. The per-client legal-spend cap is aggregated on THIS, never on a typed name.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_cases', to='bonu.bonumember'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='date_of_loss',
            field=models.DateField(blank=True, help_text='When the incident or loss happened.', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='firm_contact_on',
            field=models.DateField(blank=True, help_text='When the law firm (or the in-house team) was FIRST CONTACTED — the earlier, separate step before they were formally instructed.', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='firm_type',
            field=models.CharField(choices=[('external', 'External law firm'), ('in_house', 'In-house (Alpha Law)')], db_index=True, default='external', help_text='In-house or external. Exactly one, and it decides whether a firm is set.', max_length=8),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='internal_officer',
            field=models.CharField(blank=True, default='', help_text='The in-house officer running it, when we know. Deliberately optional and deliberately gates nothing — an unnamed in-house matter is still an in-house matter, and refusing to open it would push it off the register.', max_length=120),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='matter_arose_on',
            field=models.DateField(blank=True, help_text='When the legal matter or dispute arose — often later than the loss.', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='received_on',
            field=models.DateField(blank=True, db_index=True, help_text='When the claim reached us. Days-to-process counts from here, so a case with no received date reports "not known" rather than nought days.', null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The Botswana city or town the matter sits in, from the fixed list in bonu/legal_rules.py. A list and not free text, because the reason for capturing it is to group matters, and three spellings are three groups.', max_length=40),
        ),
        migrations.AddField(
            model_name='legalsettings',
            name='cap_blocks_capture',
            field=models.BooleanField(default=False, help_text='OFF (the agreed default): reaching the cap turns the flag red and the client is monitored. ON: a bill that would take a client past the cap is refused at capture. Left as a switch, and defaulted OFF, because refusing to record a bill pushes it out of Omni — and an unrecorded bill makes every cap total on the screen wrong, which is the worse failure of the two.'),
        ),
        migrations.AddField(
            model_name='legalsettings',
            name='client_spend_amber',
            field=models.DecimalField(decimal_places=2, default=Decimal('60000'), help_text='Early-warning level (BWP). At or above this a client shows amber, "approaching cap", so the ceiling is seen coming rather than crossed.', max_digits=14),
        ),
        migrations.AddField(
            model_name='legalsettings',
            name='client_spend_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('80000'), help_text='Legal spend ceiling per CLIENT, aggregated across ALL their matters (BWP). One client with three matters shares one ceiling of 80,000 — not 80,000 each.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='firm',
            field=models.ForeignKey(blank=True, help_text='The panel firm. Empty ONLY when the matter is in-house.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='bonu.lawfirm'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='instructed_on',
            field=models.DateField(help_text='Law firm INSTRUCTION date — when they were formally instructed.'),
        ),
        migrations.AddConstraint(
            model_name='legalcase',
            constraint=models.UniqueConstraint(condition=models.Q(('firm__isnull', True)), fields=('case_ref',), name='bonu_uniq_inhouse_case_ref'),
        ),
        migrations.AddConstraint(
            model_name='legalcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('firm__isnull', False), ('firm_type', 'external')), models.Q(('firm__isnull', True), ('firm_type', 'in_house')), _connector='OR'), name='bonu_case_firm_matches_type'),
        ),
        migrations.AddField(
            model_name='legalbill',
            name='firm',
            field=models.ForeignKey(blank=True, help_text='Empty ONLY when the bill is in-house.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_bills', to='bonu.lawfirm'),
        ),
        migrations.AddField(
            model_name='legalbillallocation',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='bonu.legalbill'),
        ),
        migrations.AddField(
            model_name='legalbillallocation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_allocations', to='bonu.legalcase'),
        ),
        migrations.AddField(
            model_name='legalclientalias',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_aliases', to='bonu.bonumember'),
        ),
        migrations.AddField(
            model_name='legalclientalias',
            name='firm',
            field=models.ForeignKey(blank=True, help_text='Which firm writes it this way, when we know.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_aliases', to='bonu.lawfirm'),
        ),
        migrations.AddIndex(
            model_name='legalbill',
            index=models.Index(fields=['allocation_state', 'stage'], name='bonu_bill_state_idx'),
        ),
        migrations.AddIndex(
            model_name='legalbill',
            index=models.Index(fields=['bill_date'], name='bonu_bill_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalbill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('firm__isnull', False), ('source', 'external')), models.Q(('firm__isnull', True), ('source', 'in_house')), _connector='OR'), name='bonu_bill_firm_matches_source'),
        ),
        migrations.AddConstraint(
            model_name='legalbill',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bonu_bill_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='legalbillallocation',
            constraint=models.UniqueConstraint(fields=('bill', 'case'), name='bonu_uniq_bill_case'),
        ),
        migrations.AddConstraint(
            model_name='legalbillallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bonu_bill_alloc_positive'),
        ),
        migrations.AddConstraint(
            model_name='legalclientalias',
            constraint=models.UniqueConstraint(fields=('alias_key',), name='bonu_uniq_client_alias_key'),
        ),
    ]
