# Generated by Django 5.2 on 2026-09-09, then given a data step by hand.
#
# The CFO decided on 9 Sep 2026 that crossing the 80,000 per-client legal-spend
# cap must REFUSE the bill rather than merely flag it red.
#
# Changing the model default is NOT enough on its own. `LegalSettings` is a
# single existing row — the legal office's settings, live since 18 Aug 2026 —
# and migration 0010 added this column to it with a default of False. A new
# default only applies to rows created afterwards, so without the data step
# below the switch would arrive on prod switched OFF and the CFO's decision
# would silently not be in force. That is the exact shape of mistake the
# review ledger keeps recording: a change that is correct in the model and a
# no-op where it actually matters.
from django.db import migrations, models


def turn_the_ceiling_on(apps, schema_editor):
    """Apply the CFO's decision to the row that already exists."""
    LegalSettings = apps.get_model('bonu', 'LegalSettings')
    LegalSettings.objects.update(cap_blocks_capture=True)


def turn_the_ceiling_off(apps, schema_editor):
    """Reverse: back to monitoring only, which is what 0010 shipped."""
    LegalSettings = apps.get_model('bonu', 'LegalSettings')
    LegalSettings.objects.update(cap_blocks_capture=False)


class Migration(migrations.Migration):

    dependencies = [
        ('bonu', '0010_legalbill_legalbillallocation_legalclientalias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalsettings',
            name='cap_blocks_capture',
            field=models.BooleanField(default=True, help_text='ON (the CFO decision of 9 Sep 2026): a bill that would take a client past the cap is REFUSED, and needs authorisation before it can be recorded. OFF: reaching the cap only turns the flag red and the client is monitored. Kept as a switch either way so the policy can change without a release. Note the trade-off the CFO accepted: a refused bill does not disappear, it just stops being written down here — so if bills start going unrecorded, turn this OFF rather than let the cap totals drift.'),
        ),
        migrations.RunPython(turn_the_ceiling_on, turn_the_ceiling_off),
    ]
