# Generated by Django 5.2 on 2026-08-07 17:30

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0058_emaillogincode_purpose'),
        ('ledger', '0027_sync_model_state_2026_07_26'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='What people call it, e.g. "CFO Visa".', max_length=60)),
                ('last4', models.CharField(help_text='Last FOUR digits only — never the full number.', max_length=4)),
                ('currency', models.CharField(default='BWP', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_cards', to='core.company')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CardStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('source_name', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_statements', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='company_cards.companycard')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CardSpend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spent_on', models.DateField()),
                ('merchant', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BWP', max_length=3)),
                ('what_for', models.CharField(help_text='One line — what it was for. Finance codes the account from this.', max_length=200)),
                ('receipt', models.FileField(blank=True, upload_to='card-receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('uncoded', 'Waiting for Finance to code'), ('coded', 'Coded'), ('queried', 'Finance has a question')], db_index=True, default='uncoded', max_length=10)),
                ('coded_at', models.DateTimeField(blank=True, null=True)),
                ('finance_note', models.TextField(blank=True, default='')),
                ('coded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_spends_coded', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_spends', to='ledger.account')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_spends', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spends', to='company_cards.companycard')),
            ],
            options={
                'ordering': ['-spent_on', '-created_at'],
                'abstract': False,
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CardStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_on', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waived', models.BooleanField(default=False)),
                ('waived_note', models.CharField(blank=True, default='', max_length=200)),
                ('matched_spend', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_line', to='company_cards.cardspend')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='company_cards.cardstatement')),
            ],
            options={
                'ordering': ['posted_on', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['statement', 'posted_on'], name='cardline_stmt_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='companycard',
            constraint=models.UniqueConstraint(fields=('last4', 'holder'), name='company_card_last4_holder_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cardstatement',
            constraint=models.UniqueConstraint(fields=('card', 'period_year', 'period_month'), name='card_statement_period_uniq'),
        ),
        migrations.AddIndex(
            model_name='cardspend',
            index=models.Index(fields=['card', 'spent_on'], name='cardspend_card_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cardspend',
            index=models.Index(fields=['status'], name='cardspend_status_idx'),
        ),
    ]
