# Generated by Django 5.2 on 2026-08-26 05:51

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IFRS17Exception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=16)),
                ('financial_year', models.CharField(default='FY2026', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('source', models.CharField(blank=True, default='', help_text="Where in the actuary's report this sits.", max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('severity', models.CharField(blank=True, default='', max_length=8)),
                ('band', models.CharField(choices=[('material', 'Material — explanation required'), ('watch', 'Watch — monitored, no explanation required'), ('immaterial', 'Immaterial — disclosed, no response required')], max_length=12)),
                ('materiality_basis', models.CharField(blank=True, default='', help_text='quantitative or qualitative', max_length=12)),
                ('materiality_reason', models.TextField(blank=True, default='')),
                ('threshold_at_seed', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('open', 'Open — awaiting Finance'), ('answered', 'Answered — awaiting review'), ('accepted', 'Accepted'), ('returned', 'Returned to Finance'), ('no_response_required', 'Below materiality — no response required')], default='open', max_length=24)),
                ('explanation', models.TextField(blank=True, default='', help_text='What this exception is, and why the position taken is right. Mandatory for material exceptions.')),
                ('action', models.TextField(blank=True, default='', help_text='What is being done about it, and by when.')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='', help_text='Why it was accepted, or what is missing.')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_ifrs17_exceptions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='The person in Finance accountable for this answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ifrs17_exceptions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ifrs17_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['financial_year', 'band', 'status'], name='ifrs17_ifrs_financi_aec3f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('ref', 'financial_year'), name='uniq_ifrs17_exception_ref_year')],
            },
            bases=(core.models.AuditableMixin, models.Model),
        ),
    ]
