"""payroll/advance_mismatch_report.py — the workbook and the covering email for
the salary-advance mismatch warning.

Separated from ``advance_mismatch.py`` (which only reads) so the data can be
tested without building a spreadsheet, and so the scheduled command is a thin
caller — the same three-file shape as ``realpay/failed_debits*``.

The workbook is built with ``aware.reporting._wb``, the branded Navy/Orange
builder the other finance reports already use. Imported, never copied: a second
table builder drifts from the first the week somebody changes a column width,
and Finance start receiving two house styles.
"""
from __future__ import annotations

import datetime
from decimal import Decimal
from typing import Any, Dict, List

from aware.reporting import NAVY, ORANGE, _wb

COLUMNS = [
    'What is wrong', 'Employee', 'Staff no.', 'Entity', 'Date',
    'Amount (BWP)', 'Recovery month', 'Reference', 'What to do',
]

NOTES = [
    'Omni does not raise the payout for a salary advance. Finance raise the '
    'payment themselves; Omni records the advance, the payout and the recovery. '
    'This report is the warning that those three disagree.',
    'A recovery raised against an advance with no payout recorded is the one to '
    'act on first — the deduction comes off a payslip whether or not the person '
    'ever received the money.',
    'An advance approved in the last couple of days is not listed. It is not a '
    'mismatch yet, and listing it would train the reader to ignore the rest.',
    'This report reads only. It raises no payment, posts no journal and changes '
    'no record.',
]


def _f(v) -> float:
    """Money as a number Excel can total, rounded to the thebe.

    Never truncated: these are amounts owed, and a sheet whose rows do not add
    up to its own headline is the fastest way to lose the reader.
    """
    return float(Decimal(str(v or 0)).quantize(Decimal('0.01')))


def _rows_for_sheet(result: Dict[str, Any]) -> List[List[Any]]:
    body: List[List[Any]] = []
    for r in result['recovery_without_payout']:
        body.append([r['issue'], r['employee'], r['employee_number'], r['entity'],
                     '', _f(r['amount']), r['recovery_period'], '', r['what_to_do']])
    for r in result['approved_not_paid']:
        body.append([r['issue'], r['employee'], r['employee_number'], r['entity'],
                     r['approved_on'], _f(r['amount']), r['recovery_period'], '',
                     r['what_to_do']])
    for r in result['payout_without_advance']:
        body.append([r['issue'], r['employee'], r['employee_number'], r['entity'],
                     r['paid_on'], _f(r['amount']), '', r['reference'],
                     r['what_to_do']])
    return body


def build_xlsx(result: Dict[str, Any]):
    """The attachment. Returns a BytesIO positioned at the start."""
    as_at: datetime.date = result['as_at']
    kpis = [
        ('Recovery raised, no payout recorded',
         f"{len(result['recovery_without_payout']):,}"),
        ('Approved, never paid out', f"{len(result['approved_not_paid']):,}"),
        ('Payout with no approved advance',
         f"{len(result['payout_without_advance']):,}"),
        ('Value in question', f"P {_f(result['value']):,.2f}"),
        ('As at', f"{as_at:%d %b %Y}"),
    ]
    return _wb(
        title='Alpha Direct — Salary advances that do not agree',
        subtitle=f'As at {as_at:%d %b %Y} · generated by Omni',
        kpis=kpis,
        columns=COLUMNS,
        rows=_rows_for_sheet(result),
        notes=NOTES,
        # money_cols deliberately not passed: _wb formats a money column as
        # whole pula, and these figures are thebe-accurate, so the column would
        # visibly not add up to the KPI above it.
    )


def filename(as_at: datetime.date) -> str:
    return f'Alpha Direct Salary Advance Mismatches {as_at:%Y-%m-%d}.xlsx'


def subject(result: Dict[str, Any]) -> str:
    as_at: datetime.date = result['as_at']
    return (f"Salary advances that do not agree — {result['count']} to check "
            f"({as_at:%d %b %Y})")


def _block(title: str, rows: List[Dict[str, Any]], cols: List[tuple]) -> str:
    if not rows:
        return ''
    head = ''.join(
        f'<th style="background:#{NAVY};color:#fff;padding:8px 10px;'
        f'text-align:left">{label}</th>' for label, _k, _money in cols)
    body = ''
    for r in rows[:25]:
        cells = ''
        for _label, key, money in cols:
            val = r.get(key, '')
            text = f'P {_f(val):,.2f}' if money else str(val)
            align = 'right' if money else 'left'
            cells += (f'<td style="padding:6px 10px;border-bottom:1px solid #eceff5;'
                      f'text-align:{align}">{text}</td>')
        body += f'<tr>{cells}</tr>'
    more = ''
    if len(rows) > 25:
        more = (f'<p style="color:#667;font-size:12px;margin:4px 0 0">'
                f'…and {len(rows) - 25} more in the attachment.</p>')
    return (f'<div style="margin:22px 0 0"><div style="font-weight:700;'
            f'margin-bottom:6px">{title}</div>'
            f'<table style="border-collapse:collapse;min-width:420px">'
            f'<tr>{head}</tr>{body}</table>{more}</div>')


def build_html(result: Dict[str, Any]) -> str:
    """The covering email: what disagrees, how much is in question, what to do.

    The worst case is first on purpose. A recovery already raised against an
    advance with no payout takes money off a payslip whether or not the person
    ever received it, so it is the block a reader must not scroll past.
    """
    as_at: datetime.date = result['as_at']
    money = ('Amount (BWP)', 'amount', True)
    blocks = (
        _block('Recovery raised, advance not marked as paid out',
               result['recovery_without_payout'],
               [('Employee', 'employee', False), ('Entity', 'entity', False),
                ('Recovery month', 'recovery_period', False), money])
        + _block('Approved, never paid out', result['approved_not_paid'],
                 [('Employee', 'employee', False), ('Entity', 'entity', False),
                  ('Approved', 'approved_on', False), money])
        + _block('Payout with no approved advance',
                 result['payout_without_advance'],
                 [('Employee', 'employee', False), ('Entity', 'entity', False),
                  ('Paid on', 'paid_on', False), money])
    )
    return f"""
<div style="font-family:Montserrat,'Segoe UI',Arial,sans-serif;color:#1D3270;font-size:14px">
  <div style="border-left:6px solid #{ORANGE};padding:2px 0 2px 14px;margin-bottom:18px">
    <div style="font-size:18px;font-weight:700">Salary advances that do not agree</div>
    <div style="color:#667;font-size:12px">As at {as_at:%d %B %Y}</div>
  </div>

  <p style="margin:0 0 14px">
    <strong>{result['count']}</strong> salary advance(s) do not agree with what
    Omni holds, covering <strong>P {_f(result['value']):,.2f}</strong>.
    The full list is attached.
  </p>

  <p style="margin:0 0 6px">Finance raise the advance payment by hand — Omni only
  records the advance and the recovery. Please check each row and either record
  the payout in Omni or hold the recovery.</p>

  {blocks}

  <p style="color:#667;font-size:12px;margin-top:22px">
    Read from Omni's own records on the morning it was sent. This report raises
    no payment, posts no journal and changes nothing.
  </p>
</div>
"""
