"""Group Payroll Report — frozen monthly snapshot across every payroll company
(CFO 19-Sep-2026, approved plan items #1-5).

A snapshot never changes after it is written: later payroll edits make a NEW
version (v2, v3 ...) via Regenerate. Read-only — Omni moves no money.

Imported into payroll/models.py so Django's app registry sees the models.
"""
from decimal import Decimal

from django.conf import settings
from django.db import models

from core.models import BaseModel, Company

ZERO = Decimal('0.00')


class GroupPayrollSnapshot(BaseModel):
    class Trigger(models.TextChoices):
        SCHEDULE = 'schedule', 'Scheduled (28th)'
        MANUAL   = 'manual',   'Regenerated by hand'

    period = models.ForeignKey(
        'payroll.PayrollPeriod', on_delete=models.PROTECT,
        related_name='group_snapshots',
    )
    version = models.PositiveIntegerField()
    trigger = models.CharField(max_length=10, choices=Trigger.choices,
                               default=Trigger.SCHEDULE)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='group_payroll_snapshots',
    )
    # Group totals in BWP over INCLUDED companies only (final or draft with slips).
    totals = models.JSONField(default=dict, blank=True)
    excluded = models.JSONField(default=list, blank=True,
                                help_text='Company names left out of the group total.')

    class Meta(BaseModel.Meta):
        ordering = ['-created_at']
        constraints = [
            models.UniqueConstraint(fields=['period', 'version'],
                                    name='uniq_group_payroll_period_version'),
        ]

    def __str__(self):
        return f'Group payroll {self.period_id} v{self.version}'


class GroupPayrollLine(BaseModel):
    """One company's totals inside a snapshot (BWP, plus source currency)."""

    class Status(models.TextChoices):
        FINAL   = 'final',   'Signed off'
        DRAFT   = 'draft',   'Draft — not signed off'
        NOT_RUN = 'not_run', 'Not yet run'

    snapshot = models.ForeignKey(GroupPayrollSnapshot, on_delete=models.CASCADE,
                                 related_name='lines')
    company = models.ForeignKey(Company, on_delete=models.PROTECT,
                                related_name='group_payroll_lines')
    status = models.CharField(max_length=8, choices=Status.choices)
    headcount = models.PositiveIntegerField(default=0)
    basic = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    incentive = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    commission = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    employer_contrib = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    gross = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    paye = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    net = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    ctc = models.DecimalField(max_digits=18, decimal_places=2, default=ZERO)
    source_currency = models.CharField(max_length=3, blank=True, default='BWP')
    source_gross = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    fx_rate = models.DecimalField(max_digits=18, decimal_places=8, null=True, blank=True)
    tieout_ok = models.BooleanField(default=True)
    tieout_note = models.CharField(max_length=300, blank=True, default='')
    by_department = models.JSONField(default=dict, blank=True)

    class Meta(BaseModel.Meta):
        ordering = ['company__name']

    def __str__(self):
        return f'{self.company_id} {self.status}'
