# Generated by Django 5.2 on 2026-07-06 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0002_agentcode_bankname_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionline',
            new_name='agent_porta_cycle_i_e32058_idx',
            old_name='ap_line_cycle_stream_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionline',
            new_name='agent_porta_cycle_i_0f802b_idx',
            old_name='ap_line_cycle_payable_idx',
        ),
        migrations.AddField(
            model_name='commissioncycle',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioncycle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionline',
            name='policy_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
    ]
