# Generated by Django 5.2 on 2026-07-07 04:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0003_rename_ap_line_cycle_stream_idx_agent_porta_cycle_i_e32058_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.CharField(max_length=24)),
                ('agent_name', models.CharField(blank=True, default='', help_text="The 'Your name' field on the Daily tab (may differ per row).", max_length=160)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('paste', 'Pasted rows'), ('sheet', 'Template sheet upload'), ('hand', 'Single row by hand'), ('all_policies', 'All-policies import')], default='paste', max_length=16)),
                ('raw_text', models.TextField(help_text='The rows exactly as submitted (CSV/TSV).')),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('payable_bwp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='agent_portal.commissioncycle')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['cycle', 'stream'], name='agent_porta_cycle_i_c9f15a_idx')],
            },
        ),
    ]
