# Generated by Django 5.2 on 2026-07-07 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0004_reportsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('all_policies', 'All Policies Report'), ('transactions', 'Transaction Report'), ('bank_statement', 'Bank Statement Report')], max_length=16)),
                ('raw_text', models.TextField(help_text='Rows exactly as uploaded/pasted (CSV/TSV).')),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_reports', to='agent_portal.commissioncycle')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['cycle', 'kind'], name='agent_porta_cycle_i_171a01_idx')],
            },
        ),
    ]
