# Generated by Django 5.2 on 2026-07-07 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0005_sourcereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionline',
            name='graphite_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionline',
            name='graphite_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='commissionline',
            name='graphite_status',
            field=models.CharField(blank=True, choices=[('ok', 'Confirmed in Graphite'), ('mismatch', 'Differs from Graphite'), ('not_found', 'Not found in Graphite'), ('unavailable', 'Graphite unavailable'), ('skipped', 'No policy number to check')], default='', max_length=12),
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lines_checked', models.PositiveIntegerField(default=0)),
                ('ok_count', models.PositiveIntegerField(default=0)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('not_found_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('unavailable', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='agent_portal.commissioncycle')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
