# Generated by Django 5.2 on 2026-07-27 09:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0006_commissionline_graphite_checked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='agent',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentPayslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('ex_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('annual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('not_paid', models.JSONField(blank=True, default=list)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_to', models.EmailField(blank=True, default='', max_length=254)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='agent_portal.agent')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='agent_portal.commissioncycle')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agent__name'],
                'abstract': False,
                'indexes': [models.Index(fields=['cycle', 'agent'], name='agent_porta_cycle_i_693a1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'agent'), name='uniq_payslip_cycle_agent')],
            },
        ),
    ]
